libxputty: xputty/header/b64_encode.h File Reference
b64_encode.h File Reference
Functions
void b64_encode (char *clrstr, char *b64dst)
b64_encode - encode a b64 based char
void b64_decode (char *b64src, char *clrdst)
b64_decode - decode to a b64 based char
Function Documentation
b64_decode()
void b64_decode (char * b64src, char * clrdst)
b64_decode - decode to a b64 based char
Parameters
*b64src - the char to decode
*clrdst - the decoded char
Definition at line 26 of file b64_encode.c.
{
    int c, phase, i;
    unsigned char in[4];
    char *p;
    clrdst[0] = '\0';
    phase = 0;
    i=0;
    while(b64src[i]) {
        c = (int) b64src[i];
        if(c == '=') {
            decodeblock(in, (unsigned char **) &clrdst);
            break;
        }
        p = strchr(b64, c);
        if(p) {
            in[phase] = p - b64;
            phase = (phase + 1) % 4;
            if(phase == 0) {
                decodeblock(in, (unsigned char **) &clrdst);
                in[0]=in[1]=in[2]=in[3]=0;
            }
        }
        i++;
    }
}
References b64, and decodeblock().
Referenced by widget_get_scaled_svg(), and widget_get_svg().
b64_encode()
void b64_encode (char * clrstr, char * b64dst)
b64_encode - encode a b64 based char
Parameters
*clrstr - the char to encode
*b64dst - the encoded char
Definition at line 66 of file b64_encode.c.
{
    unsigned char in[3];
    int i, len = 0;
    int j = 0;
    b64dst[0] = '\0';
    while(clrstr[j]) {
        len = 0;
        for(i=0; i<3; i++) {
            in[i] = (unsigned char) clrstr[j];
            if(clrstr[j]) {
                len++;
                j++;
            }
            else in[i] = 0;
        }
        if( len ) {
            encodeblock( in, b64dst, len );
        }
    }
}
References encodeblock().