libxputty: xputty/lv2_plugin/lv2_plugin.cc File Reference
lv2_plugin.cc File Reference
Functions
Widget_t * add_my_knob (Widget_t *w, PortIndex index, const char *label, X11_UI *ui, int x, int y, int width, int height)
Widget_t * add_my_image_knob (Widget_t *w, PortIndex index, const char *label, X11_UI *ui, int x, int y, int width, int height)
Widget_t * add_my_value_knob (Widget_t *w, PortIndex index, const char *label, X11_UI *ui, int x, int y, int width, int height)
Widget_t * add_my_switch_image (Widget_t *w, PortIndex index, const char *label, X11_UI *ui, int x, int y, int width, int height)
Widget_t * add_my_combobox (Widget_t *w, PortIndex index, const char *label, const char **items, size_t len, int active, X11_UI *ui, int x, int y, int width, int height)
LV2_SYMBOL_EXPORT const LV2UI_Descriptor * lv2ui_descriptor (uint32_t index)
Function Documentation
add_my_combobox()
Widget_t * add_my_combobox (Widget_t * w, PortIndex index, const char * label, const char ** items, size_t len, int active, X11_UI * ui, int x, int y, int width, int height)
Definition at line 267 of file lv2_plugin.cc.
{
    w = add_combobox(ui->win, label, x, y, width, height);
    size_t st = 0;
    for(; st < len; st++) {
        combobox_add_entry(w,items[st]);
    }
    w->parent_struct = ui;
    w->data = index;
    combobox_set_active_entry(w, active);
    w->func.value_changed_callback = value_changed;
    return w;
}
References add_combobox(), combobox_add_entry(), combobox_set_active_entry(), Widget_t::data, Widget_t::func, Widget_t::parent_struct, Func_t::value_changed_callback, and X11_UI::win.
add_my_image_knob()
Widget_t * add_my_image_knob (Widget_t * w, PortIndex index, const char * label, X11_UI * ui, int x, int y, int width, int height)
Definition at line 237 of file lv2_plugin.cc.
{
    w = add_image_knob(ui->win, label, x, y, width, height);
    w->parent_struct = ui;
    w->data = index;
    w->func.value_changed_callback = value_changed;
    return w;
}
References add_image_knob(), Widget_t::data, Widget_t::func, Widget_t::parent_struct, Func_t::value_changed_callback, and X11_UI::win.
add_my_knob()
Widget_t * add_my_knob (Widget_t * w, PortIndex index, const char * label, X11_UI * ui, int x, int y, int width, int height)
Definition at line 226 of file lv2_plugin.cc.
{
    w = add_knob(ui->win, label, x, y, width, height);
    w->func.expose_callback = draw_my_knob;
    w->parent_struct = ui;
    w->data = index;
    w->func.value_changed_callback = value_changed;
    return w;
}
References add_knob(), Widget_t::data, Func_t::expose_callback, Widget_t::func, Widget_t::parent_struct, Func_t::value_changed_callback, and X11_UI::win.
add_my_switch_image()
Widget_t * add_my_switch_image (Widget_t * w, PortIndex index, const char * label, X11_UI * ui, int x, int y, int width, int height)
Definition at line 257 of file lv2_plugin.cc.
{
    w = add_switch_image_button(ui->win, label, x, y, width, height);
    w->parent_struct = ui;
    w->data = index;
    w->func.value_changed_callback = value_changed;
    return w;
}
References add_switch_image_button(), Widget_t::data, Widget_t::func, Widget_t::parent_struct, Func_t::value_changed_callback, and X11_UI::win.
add_my_value_knob()
Widget_t * add_my_value_knob (Widget_t * w, PortIndex index, const char * label, X11_UI * ui, int x, int y, int width, int height)
Definition at line 247 of file lv2_plugin.cc.
{
    w = add_knob(ui->win, label, x, y, width, height);
    w->parent_struct = ui;
    w->data = index;
    w->func.value_changed_callback = value_changed;
    return w;
}
References add_knob(), Widget_t::data, Widget_t::func, Widget_t::parent_struct, Func_t::value_changed_callback, and X11_UI::win.
lv2ui_descriptor()
LV2_SYMBOL_EXPORT const LV2UI_Descriptor * lv2ui_descriptor (uint32_t index)
Definition at line 427 of file lv2_plugin.cc.
{
    if (index >= sizeof(descriptors) / sizeof(descriptors[0])) {
        return NULL;
    }
    return descriptors + index;
}