libxputty: xputty/lv2_plugin/lv2_plugin.h File Reference
lv2_plugin.h File Reference
Data Structures
struct KnobColors
struct X11_UI
Functions
void plugin_value_changed (X11_UI *ui, Widget_t *w, PortIndex index)
void plugin_set_window_size (int *w, int *h, const char *plugin_uri)
const char * plugin_set_name ()
void plugin_create_controller_widgets (X11_UI *ui, const char *plugin_uri)
Widget_t * add_my_knob (Widget_t *w, PortIndex index, const char *label, X11_UI *ui, int x, int y, int width, int height)
Widget_t * add_my_image_knob (Widget_t *w, PortIndex index, const char *label, X11_UI *ui, int x, int y, int width, int height)
Widget_t * add_my_value_knob (Widget_t *w, PortIndex index, const char *label, X11_UI *ui, int x, int y, int width, int height)
Widget_t * add_my_switch_image (Widget_t *w, PortIndex index, const char *label, X11_UI *ui, int x, int y, int width, int height)
Widget_t * add_my_combobox (Widget_t *w, PortIndex index, const char *label, const char **items, size_t len, int active, X11_UI *ui, int x, int y, int width, int height)
void plugin_cleanup (X11_UI *ui)
void plugin_port_event (LV2UI_Handle handle, uint32_t port_index, uint32_t buffer_size, uint32_t format, const void *buffer)
Function Documentation
add_my_combobox()
Widget_t * add_my_combobox (Widget_t * w, PortIndex index, const char * label, const char ** items, size_t len, int active, X11_UI * ui, int x, int y, int width, int height)
Definition at line 267 of file lv2_plugin.cc.
{
    w = add_combobox(ui->win, label, x, y, width, height);
    size_t st = 0;
    for(; st < len; st++) {
        combobox_add_entry(w,items[st]);
    }
    w->parent_struct = ui;
    w->data = index;
    combobox_set_active_entry(w, active);
    w->func.value_changed_callback = value_changed;
    return w;
}
References add_combobox(), combobox_add_entry(), combobox_set_active_entry(), Widget_t::data, Widget_t::func, Widget_t::parent_struct, Func_t::value_changed_callback, and X11_UI::win.
add_my_image_knob()
Widget_t * add_my_image_knob (Widget_t * w, PortIndex index, const char * label, X11_UI * ui, int x, int y, int width, int height)
Definition at line 237 of file lv2_plugin.cc.
{
    w = add_image_knob(ui->win, label, x, y, width, height);
    w->parent_struct = ui;
    w->data = index;
    w->func.value_changed_callback = value_changed;
    return w;
}
References add_image_knob(), Widget_t::data, Widget_t::func, Widget_t::parent_struct, Func_t::value_changed_callback, and X11_UI::win.
add_my_knob()
Widget_t * add_my_knob (Widget_t * w, PortIndex index, const char * label, X11_UI * ui, int x, int y, int width, int height)
Definition at line 226 of file lv2_plugin.cc.
{
    w = add_knob(ui->win, label, x, y, width, height);
    w->func.expose_callback = draw_my_knob;
    w->parent_struct = ui;
    w->data = index;
    w->func.value_changed_callback = value_changed;
    return w;
}
References add_knob(), Widget_t::data, Func_t::expose_callback, Widget_t::func, Widget_t::parent_struct, Func_t::value_changed_callback, and X11_UI::win.
add_my_switch_image()
Widget_t * add_my_switch_image (Widget_t * w, PortIndex index, const char * label, X11_UI * ui, int x, int y, int width, int height)
Definition at line 257 of file lv2_plugin.cc.
{
    w = add_switch_image_button(ui->win, label, x, y, width, height);
    w->parent_struct = ui;
    w->data = index;
    w->func.value_changed_callback = value_changed;
    return w;
}
References add_switch_image_button(), Widget_t::data, Widget_t::func, Widget_t::parent_struct, Func_t::value_changed_callback, and X11_UI::win.
add_my_value_knob()
Widget_t * add_my_value_knob (Widget_t * w, PortIndex index, const char * label, X11_UI * ui, int x, int y, int width, int height)
Definition at line 247 of file lv2_plugin.cc.
{
    w = add_knob(ui->win, label, x, y, width, height);
    w->parent_struct = ui;
    w->data = index;
    w->func.value_changed_callback = value_changed;
    return w;
}
References add_knob(), Widget_t::data, Widget_t::func, Widget_t::parent_struct, Func_t::value_changed_callback, and X11_UI::win.
plugin_cleanup()
void plugin_cleanup (X11_UI * ui)
Definition at line 71 of file lv2_plugname_ui.c.
{
    // clean up used sources when needed
}
plugin_create_controller_widgets()
void plugin_create_controller_widgets (X11_UI * ui, const char * plugin_uri)
Definition at line 65 of file lv2_plugname_ui.c.
{
    // create all controllers needed
    // ui->widget[0] = add_my_knob(ui->widget[0], PORT,"NAME", ui, x, y, w, h);
    // set_adjustment(ui->widget[0]->adj,0.5, 0.5, 0.0, 1.0, 0.01, CL_CONTINUOS);
}
plugin_port_event()
void plugin_port_event (LV2UI_Handle handle, uint32_t port_index, uint32_t buffer_size, uint32_t format, const void * buffer)
Definition at line 75 of file lv2_plugname_ui.c.
{
    // port value change message from host
    // do special stuff when needed
}
plugin_set_name()
const char * plugin_set_name ()
Definition at line 61 of file lv2_plugname_ui.c.
{
    return "NAME"; //set plugin name to display on UI
}
plugin_set_window_size()
void plugin_set_window_size (int * w, int * h, const char * plugin_uri)
Definition at line 56 of file lv2_plugname_ui.c.
{
    (*w) = 1; //set initial widht of main window
    (*h) = 1; //set initial heigth of main window
}
plugin_value_changed()
void plugin_value_changed (X11_UI * ui, Widget_t * w, PortIndex index)
Definition at line 52 of file lv2_plugname_ui.c.
{
    // do special stuff when needed
}