libxputty: xputty/header/nanosvg.h File Reference
nanosvg.h File Reference
NanoSVG is a simple stupid single-header-file SVG parse. The output of the parser is a list of cubic bezier shapes.
Data Structures
struct NSVGgradientStop
struct NSVGgradient
struct NSVGpaint
struct NSVGpath
struct NSVGshape
struct NSVGimage
struct NSVGcoordinate
struct NSVGlinearData
struct NSVGradialData
struct NSVGgradientData
struct NSVGattrib
struct NSVGparser
struct NSVGNamedColor
Typedefs
typedef struct NSVGgradientStop NSVGgradientStop
typedef struct NSVGgradient NSVGgradient
typedef struct NSVGpaint NSVGpaint
typedef struct NSVGpath NSVGpath
typedef struct NSVGshape NSVGshape
typedef struct NSVGimage NSVGimage
typedef struct NSVGcoordinate NSVGcoordinate
typedef struct NSVGlinearData NSVGlinearData
typedef struct NSVGradialData NSVGradialData
typedef struct NSVGgradientData NSVGgradientData
typedef struct NSVGattrib NSVGattrib
typedef struct NSVGparser NSVGparser
typedef struct NSVGNamedColor NSVGNamedColor
Enumerations
enum NSVGpaintType { NSVG_PAINT_NONE = 0 , NSVG_PAINT_COLOR = 1 , NSVG_PAINT_LINEAR_GRADIENT = 2 , NSVG_PAINT_RADIAL_GRADIENT = 3 }
enum NSVGspreadType { NSVG_SPREAD_PAD = 0 , NSVG_SPREAD_REFLECT = 1 , NSVG_SPREAD_REPEAT = 2 }
enum NSVGlineJoin { NSVG_JOIN_MITER = 0 , NSVG_JOIN_ROUND = 1 , NSVG_JOIN_BEVEL = 2 }
enum NSVGlineCap { NSVG_CAP_BUTT = 0 , NSVG_CAP_ROUND = 1 , NSVG_CAP_SQUARE = 2 }
enum NSVGfillRule { NSVG_FILLRULE_NONZERO = 0 , NSVG_FILLRULE_EVENODD = 1 }
enum NSVGflags { NSVG_FLAGS_VISIBLE = 0x01 }
enum NSVGgradientUnits { NSVG_USER_SPACE = 0 , NSVG_OBJECT_SPACE = 1 }
enum NSVGunits {
NSVG_UNITS_USER , NSVG_UNITS_PX , NSVG_UNITS_PT , NSVG_UNITS_PC ,
NSVG_UNITS_MM , NSVG_UNITS_CM , NSVG_UNITS_IN , NSVG_UNITS_PERCENT ,
NSVG_UNITS_EM , NSVG_UNITS_EX
}
Functions
NSVGimage * nsvgParseFromFile (const char *filename, const char *units, float dpi)
NSVGimage * nsvgParse (char *input, const char *units, float dpi)
NSVGpath * nsvgDuplicatePath (NSVGpath *p)
void nsvgDelete (NSVGimage *image)
int nsvg__parseXML (char *input, void(*startelCb)(void *ud, const char *el, const char **attr), void(*endelCb)(void *ud, const char *el), void(*contentCb)(void *ud, const char *s), void *ud)
Variables
NSVGNamedColor nsvg__colors []
Detailed Description
NanoSVG is a simple stupid single-header-file SVG parse. The output of the parser is a list of cubic bezier shapes.
The library suits well for anything from rendering scalable icons in your editor application to prototyping a game.
NanoSVG supports a wide range of SVG features, but something may be missing, feel free to create a pull request!
The shapes in the SVG images are transformed by the viewBox and converted to specified units. That is, you should get the same looking data as your designed in your favorite app.
NanoSVG can return the paths in few different units. For example if you want to render an image, you may choose to get the paths in pixels, or if you are feeding the data into a CNC-cutter, you may want to use millimeters.
The units passed to NanoSVG should be one of: 'px', 'pt', 'pc' 'mm', 'cm', or 'in'. DPI (dots-per-inch) controls how the unit conversion is done.
If you don't know or care about the units stuff, "px" and 96 should get you going.
Definition in file nanosvg.h.
Typedef Documentation
NSVGattrib
typedef struct NSVGattrib NSVGattrib
NSVGcoordinate
typedef struct NSVGcoordinate NSVGcoordinate
NSVGgradient
typedef struct NSVGgradient NSVGgradient
NSVGgradientData
typedef struct NSVGgradientData NSVGgradientData
NSVGgradientStop
typedef struct NSVGgradientStop NSVGgradientStop
NSVGimage
typedef struct NSVGimage NSVGimage
NSVGlinearData
typedef struct NSVGlinearData NSVGlinearData
NSVGNamedColor
typedef struct NSVGNamedColor NSVGNamedColor
NSVGpaint
typedef struct NSVGpaint NSVGpaint
NSVGparser
typedef struct NSVGparser NSVGparser
NSVGpath
typedef struct NSVGpath NSVGpath
NSVGradialData
typedef struct NSVGradialData NSVGradialData
NSVGshape
typedef struct NSVGshape NSVGshape
Enumeration Type Documentation
NSVGfillRule
enum NSVGfillRule
Enumerator
NSVG_FILLRULE_NONZERO
NSVG_FILLRULE_EVENODD
Definition at line 100 of file nanosvg.h.
                  {
    NSVG_FILLRULE_NONZERO = 0,
    NSVG_FILLRULE_EVENODD = 1
};
NSVGflags
enum NSVGflags
Enumerator
NSVG_FLAGS_VISIBLE
Definition at line 105 of file nanosvg.h.
               {
    NSVG_FLAGS_VISIBLE = 0x01
};
NSVGgradientUnits
enum NSVGgradientUnits
Enumerator
NSVG_USER_SPACE
NSVG_OBJECT_SPACE
Definition at line 362 of file nanosvg.h.
                       {
    NSVG_USER_SPACE = 0,
    NSVG_OBJECT_SPACE = 1
};
NSVGlineCap
enum NSVGlineCap
Enumerator
NSVG_CAP_BUTT
NSVG_CAP_ROUND
NSVG_CAP_SQUARE
Definition at line 94 of file nanosvg.h.
                 {
    NSVG_CAP_BUTT = 0,
    NSVG_CAP_ROUND = 1,
    NSVG_CAP_SQUARE = 2
};
NSVGlineJoin
enum NSVGlineJoin
Enumerator
NSVG_JOIN_MITER
NSVG_JOIN_ROUND
NSVG_JOIN_BEVEL
Definition at line 88 of file nanosvg.h.
                  {
    NSVG_JOIN_MITER = 0,
    NSVG_JOIN_ROUND = 1,
    NSVG_JOIN_BEVEL = 2
};
NSVGpaintType
enum NSVGpaintType
Enumerator
NSVG_PAINT_NONE
NSVG_PAINT_COLOR
NSVG_PAINT_LINEAR_GRADIENT
NSVG_PAINT_RADIAL_GRADIENT
Definition at line 75 of file nanosvg.h.
                   {
    NSVG_PAINT_NONE = 0,
    NSVG_PAINT_COLOR = 1,
    NSVG_PAINT_LINEAR_GRADIENT = 2,
    NSVG_PAINT_RADIAL_GRADIENT = 3
};
NSVGspreadType
enum NSVGspreadType
Enumerator
NSVG_SPREAD_PAD
NSVG_SPREAD_REFLECT
NSVG_SPREAD_REPEAT
Definition at line 82 of file nanosvg.h.
                    {
    NSVG_SPREAD_PAD = 0,
    NSVG_SPREAD_REFLECT = 1,
    NSVG_SPREAD_REPEAT = 2
};
NSVGunits
enum NSVGunits
Enumerator
NSVG_UNITS_USER
NSVG_UNITS_PX
NSVG_UNITS_PT
NSVG_UNITS_PC
NSVG_UNITS_MM
NSVG_UNITS_CM
NSVG_UNITS_IN
NSVG_UNITS_PERCENT
NSVG_UNITS_EM
NSVG_UNITS_EX
Definition at line 369 of file nanosvg.h.
               {
    NSVG_UNITS_USER,
    NSVG_UNITS_PX,
    NSVG_UNITS_PT,
    NSVG_UNITS_PC,
    NSVG_UNITS_MM,
    NSVG_UNITS_CM,
    NSVG_UNITS_IN,
    NSVG_UNITS_PERCENT,
    NSVG_UNITS_EM,
    NSVG_UNITS_EX
};
Function Documentation
nsvg__parseXML()
int nsvg__parseXML (char * input, void(*)(void *ud, const char *el, const char **attr) startelCb, void(*)(void *ud, const char *el) endelCb, void(*)(void *ud, const char *s) contentCb, void * ud)
Definition at line 327 of file nanosvg.h.
{
    char* s = input;
    char* mark = s;
    int state = NSVG_XML_CONTENT;
    while (*s) {
        if (*s == '<' && state == NSVG_XML_CONTENT) {
            // Start of a tag
            *s++ = '\0';
            nsvg__parseContent(mark, contentCb, ud);
            mark = s;
            state = NSVG_XML_TAG;
        } else if (*s == '>' && state == NSVG_XML_TAG) {
            // Start of a content or new tag.
            *s++ = '\0';
            nsvg__parseElement(mark, startelCb, endelCb, ud);
            mark = s;
            state = NSVG_XML_CONTENT;
        } else {
            s++;
        }
    }
    return 1;
}
Referenced by nsvgParse().
nsvgDelete()
void nsvgDelete (NSVGimage * image)
Definition at line 2993 of file nanosvg.h.
{
    NSVGshape *snext, *shape;
    if (image == NULL) return;
    shape = image->shapes;
    while (shape != NULL) {
        snext = shape->next;
        nsvg__deletePaths(shape->paths);
        nsvg__deletePaint(&shape->fill);
        nsvg__deletePaint(&shape->stroke);
        free(shape);
        shape = snext;
    }
    free(image);
}
References NSVGshape::fill, NSVGshape::next, NSVGshape::paths, NSVGimage::shapes, and NSVGshape::stroke.
Referenced by cairo_image_surface_create_from_svg(), nsvgParseFromFile(), widget_get_scaled_svg(), widget_get_scaled_svg_from_file(), widget_get_svg(), and widget_get_svg_from_file().
nsvgDuplicatePath()
NSVGpath * nsvgDuplicatePath (NSVGpath * p)
Definition at line 2963 of file nanosvg.h.
{
    NSVGpath* res = NULL;
    if (p == NULL)
        return NULL;
    res = (NSVGpath*)malloc(sizeof(NSVGpath));
    if (res == NULL) goto error;
    memset(res, 0, sizeof(NSVGpath));
    res->pts = (float*)malloc(p->npts*2*sizeof(float));
    if (res->pts == NULL) goto error;
    memcpy(res->pts, p->pts, p->npts * sizeof(float) * 2);
    res->npts = p->npts;
    memcpy(res->bounds, p->bounds, sizeof(p->bounds));
    res->closed = p->closed;
    return res;
error:
    if (res != NULL) {
        free(res->pts);
        free(res);
    }
    return NULL;
}
References NSVGpath::bounds, NSVGpath::closed, NSVGpath::npts, and NSVGpath::pts.
nsvgParse()
NSVGimage * nsvgParse (char * input, const char * units, float dpi)
Definition at line 2910 of file nanosvg.h.
{
    NSVGparser* p;
    NSVGimage* ret = 0;
    p = nsvg__createParser();
    if (p == NULL) {
        return NULL;
    }
    p->dpi = dpi;
    nsvg__parseXML(input, nsvg__startElement, nsvg__endElement, nsvg__content, p);
    // Scale to viewBox
    nsvg__scaleToViewbox(p, units);
    ret = p->image;
    p->image = NULL;
    nsvg__deleteParser(p);
    return ret;
}
References NSVGparser::dpi, NSVGparser::image, and nsvg__parseXML().
Referenced by nsvgParseFromFile(), widget_get_scaled_svg(), and widget_get_svg().
nsvgParseFromFile()
NSVGimage * nsvgParseFromFile (const char * filename, const char * units, float dpi)
Definition at line 2934 of file nanosvg.h.
{
    FILE* fp = NULL;
    size_t size;
    char* data = NULL;
    NSVGimage* image = NULL;
    fp = fopen(filename, "rb");
    if (!fp) goto error;
    fseek(fp, 0, SEEK_END);
    size = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    data = (char*)malloc(size+1);
    if (data == NULL) goto error;
    if (fread(data, 1, size, fp) != size) goto error;
    data[size] = '\0';  // Must be null terminated.
    fclose(fp);
    image = nsvgParse(data, units, dpi);
    free(data);
    return image;
error:
    if (fp) fclose(fp);
    if (data) free(data);
    if (image) nsvgDelete(image);
    return NULL;
}
References nsvgDelete(), and nsvgParse().
Referenced by cairo_image_surface_create_from_svg(), widget_get_scaled_svg_from_file(), and widget_get_svg_from_file().
Variable Documentation
nsvg__colors
NSVGNamedColor nsvg__colors[]
Definition at line 1242 of file nanosvg.h.
{
    { "red", NSVG_RGB(255, 0, 0) },
    { "green", NSVG_RGB( 0, 128, 0) },
    { "blue", NSVG_RGB( 0, 0, 255) },
    { "yellow", NSVG_RGB(255, 255, 0) },
    { "cyan", NSVG_RGB( 0, 255, 255) },
    { "magenta", NSVG_RGB(255, 0, 255) },
    { "black", NSVG_RGB( 0, 0, 0) },
    { "grey", NSVG_RGB(128, 128, 128) },
    { "gray", NSVG_RGB(128, 128, 128) },
    { "white", NSVG_RGB(255, 255, 255) },
#ifdef NANOSVG_ALL_COLOR_KEYWORDS
    { "aliceblue", NSVG_RGB(240, 248, 255) },
    { "antiquewhite", NSVG_RGB(250, 235, 215) },
    { "aqua", NSVG_RGB( 0, 255, 255) },
    { "aquamarine", NSVG_RGB(127, 255, 212) },
    { "azure", NSVG_RGB(240, 255, 255) },
    { "beige", NSVG_RGB(245, 245, 220) },
    { "bisque", NSVG_RGB(255, 228, 196) },
    { "blanchedalmond", NSVG_RGB(255, 235, 205) },
    { "blueviolet", NSVG_RGB(138, 43, 226) },
    { "brown", NSVG_RGB(165, 42, 42) },
    { "burlywood", NSVG_RGB(222, 184, 135) },
    { "cadetblue", NSVG_RGB( 95, 158, 160) },
    { "chartreuse", NSVG_RGB(127, 255, 0) },
    { "chocolate", NSVG_RGB(210, 105, 30) },
    { "coral", NSVG_RGB(255, 127, 80) },
    { "cornflowerblue", NSVG_RGB(100, 149, 237) },
    { "cornsilk", NSVG_RGB(255, 248, 220) },
    { "crimson", NSVG_RGB(220, 20, 60) },
    { "darkblue", NSVG_RGB( 0, 0, 139) },
    { "darkcyan", NSVG_RGB( 0, 139, 139) },
    { "darkgoldenrod", NSVG_RGB(184, 134, 11) },
    { "darkgray", NSVG_RGB(169, 169, 169) },
    { "darkgreen", NSVG_RGB( 0, 100, 0) },
    { "darkgrey", NSVG_RGB(169, 169, 169) },
    { "darkkhaki", NSVG_RGB(189, 183, 107) },
    { "darkmagenta", NSVG_RGB(139, 0, 139) },
    { "darkolivegreen", NSVG_RGB( 85, 107, 47) },
    { "darkorange", NSVG_RGB(255, 140, 0) },
    { "darkorchid", NSVG_RGB(153, 50, 204) },
    { "darkred", NSVG_RGB(139, 0, 0) },
    { "darksalmon", NSVG_RGB(233, 150, 122) },
    { "darkseagreen", NSVG_RGB(143, 188, 143) },
    { "darkslateblue", NSVG_RGB( 72, 61, 139) },
    { "darkslategray", NSVG_RGB( 47, 79, 79) },
    { "darkslategrey", NSVG_RGB( 47, 79, 79) },
    { "darkturquoise", NSVG_RGB( 0, 206, 209) },
    { "darkviolet", NSVG_RGB(148, 0, 211) },
    { "deeppink", NSVG_RGB(255, 20, 147) },
    { "deepskyblue", NSVG_RGB( 0, 191, 255) },
    { "dimgray", NSVG_RGB(105, 105, 105) },
    { "dimgrey", NSVG_RGB(105, 105, 105) },
    { "dodgerblue", NSVG_RGB( 30, 144, 255) },
    { "firebrick", NSVG_RGB(178, 34, 34) },
    { "floralwhite", NSVG_RGB(255, 250, 240) },
    { "forestgreen", NSVG_RGB( 34, 139, 34) },
    { "fuchsia", NSVG_RGB(255, 0, 255) },
    { "gainsboro", NSVG_RGB(220, 220, 220) },
    { "ghostwhite", NSVG_RGB(248, 248, 255) },
    { "gold", NSVG_RGB(255, 215, 0) },
    { "goldenrod", NSVG_RGB(218, 165, 32) },
    { "greenyellow", NSVG_RGB(173, 255, 47) },
    { "honeydew", NSVG_RGB(240, 255, 240) },
    { "hotpink", NSVG_RGB(255, 105, 180) },
    { "indianred", NSVG_RGB(205, 92, 92) },
    { "indigo", NSVG_RGB( 75, 0, 130) },
    { "ivory", NSVG_RGB(255, 255, 240) },
    { "khaki", NSVG_RGB(240, 230, 140) },
    { "lavender", NSVG_RGB(230, 230, 250) },
    { "lavenderblush", NSVG_RGB(255, 240, 245) },
    { "lawngreen", NSVG_RGB(124, 252, 0) },
    { "lemonchiffon", NSVG_RGB(255, 250, 205) },
    { "lightblue", NSVG_RGB(173, 216, 230) },
    { "lightcoral", NSVG_RGB(240, 128, 128) },
    { "lightcyan", NSVG_RGB(224, 255, 255) },
    { "lightgoldenrodyellow", NSVG_RGB(250, 250, 210) },
    { "lightgray", NSVG_RGB(211, 211, 211) },
    { "lightgreen", NSVG_RGB(144, 238, 144) },
    { "lightgrey", NSVG_RGB(211, 211, 211) },
    { "lightpink", NSVG_RGB(255, 182, 193) },
    { "lightsalmon", NSVG_RGB(255, 160, 122) },
    { "lightseagreen", NSVG_RGB( 32, 178, 170) },
    { "lightskyblue", NSVG_RGB(135, 206, 250) },
    { "lightslategray", NSVG_RGB(119, 136, 153) },
    { "lightslategrey", NSVG_RGB(119, 136, 153) },
    { "lightsteelblue", NSVG_RGB(176, 196, 222) },
    { "lightyellow", NSVG_RGB(255, 255, 224) },
    { "lime", NSVG_RGB( 0, 255, 0) },
    { "limegreen", NSVG_RGB( 50, 205, 50) },
    { "linen", NSVG_RGB(250, 240, 230) },
    { "maroon", NSVG_RGB(128, 0, 0) },
    { "mediumaquamarine", NSVG_RGB(102, 205, 170) },
    { "mediumblue", NSVG_RGB( 0, 0, 205) },
    { "mediumorchid", NSVG_RGB(186, 85, 211) },
    { "mediumpurple", NSVG_RGB(147, 112, 219) },
    { "mediumseagreen", NSVG_RGB( 60, 179, 113) },
    { "mediumslateblue", NSVG_RGB(123, 104, 238) },
    { "mediumspringgreen", NSVG_RGB( 0, 250, 154) },
    { "mediumturquoise", NSVG_RGB( 72, 209, 204) },
    { "mediumvioletred", NSVG_RGB(199, 21, 133) },
    { "midnightblue", NSVG_RGB( 25, 25, 112) },
    { "mintcream", NSVG_RGB(245, 255, 250) },
    { "mistyrose", NSVG_RGB(255, 228, 225) },
    { "moccasin", NSVG_RGB(255, 228, 181) },
    { "navajowhite", NSVG_RGB(255, 222, 173) },
    { "navy", NSVG_RGB( 0, 0, 128) },
    { "oldlace", NSVG_RGB(253, 245, 230) },
    { "olive", NSVG_RGB(128, 128, 0) },
    { "olivedrab", NSVG_RGB(107, 142, 35) },
    { "orange", NSVG_RGB(255, 165, 0) },
    { "orangered", NSVG_RGB(255, 69, 0) },
    { "orchid", NSVG_RGB(218, 112, 214) },
    { "palegoldenrod", NSVG_RGB(238, 232, 170) },
    { "palegreen", NSVG_RGB(152, 251, 152) },
    { "paleturquoise", NSVG_RGB(175, 238, 238) },
    { "palevioletred", NSVG_RGB(219, 112, 147) },
    { "papayawhip", NSVG_RGB(255, 239, 213) },
    { "peachpuff", NSVG_RGB(255, 218, 185) },
    { "peru", NSVG_RGB(205, 133, 63) },
    { "pink", NSVG_RGB(255, 192, 203) },
    { "plum", NSVG_RGB(221, 160, 221) },
    { "powderblue", NSVG_RGB(176, 224, 230) },
    { "purple", NSVG_RGB(128, 0, 128) },
    { "rosybrown", NSVG_RGB(188, 143, 143) },
    { "royalblue", NSVG_RGB( 65, 105, 225) },
    { "saddlebrown", NSVG_RGB(139, 69, 19) },
    { "salmon", NSVG_RGB(250, 128, 114) },
    { "sandybrown", NSVG_RGB(244, 164, 96) },
    { "seagreen", NSVG_RGB( 46, 139, 87) },
    { "seashell", NSVG_RGB(255, 245, 238) },
    { "sienna", NSVG_RGB(160, 82, 45) },
    { "silver", NSVG_RGB(192, 192, 192) },
    { "skyblue", NSVG_RGB(135, 206, 235) },
    { "slateblue", NSVG_RGB(106, 90, 205) },
    { "slategray", NSVG_RGB(112, 128, 144) },
    { "slategrey", NSVG_RGB(112, 128, 144) },
    { "snow", NSVG_RGB(255, 250, 250) },
    { "springgreen", NSVG_RGB( 0, 255, 127) },
    { "steelblue", NSVG_RGB( 70, 130, 180) },
    { "tan", NSVG_RGB(210, 180, 140) },
    { "teal", NSVG_RGB( 0, 128, 128) },
    { "thistle", NSVG_RGB(216, 191, 216) },
    { "tomato", NSVG_RGB(255, 99, 71) },
    { "turquoise", NSVG_RGB( 64, 224, 208) },
    { "violet", NSVG_RGB(238, 130, 238) },
    { "wheat", NSVG_RGB(245, 222, 179) },
    { "whitesmoke", NSVG_RGB(245, 245, 245) },
    { "yellowgreen", NSVG_RGB(154, 205, 50) },
#endif
};