libxputty: xputty/xadjustment.c File Reference
xadjustment.c File Reference
Functions
Adjustment_t * add_adjustment (Widget_t *w, float std_value, float value, float min_value, float max_value, float step, CL_type type)
*add_adjustment - adding a adjustment to a Widget_t
void set_adjustment (Adjustment_t *adj, float std_value, float value, float min_value, float max_value, float step, CL_type type)
*set_adjustment - set a new range to a existing Adjustment_t it will be created if it not exsits yet
void * delete_adjustment (Adjustment_t *adj)
delete_adjustment - freeing the memory of the Adjustment_t You usually don't need to call this, as it get handled by main_quit() -> destroy_widget()
void adj_set_state (Adjustment_t *adj, float state)
adj_set_state - set the current state of the Adjustment_t
float adj_get_state (Adjustment_t *adj)
adj_get_state - get the current state of the Adjustment_t
float adj_get_value (Adjustment_t *adj)
adj_get_value - get the current value of the Adjustment_t
float adj_get_std_value (Adjustment_t *adj)
adj_get_std_value - get the standart value of the Adjustment_t
float adj_get_min_value (Adjustment_t *adj)
adj_get_min_value - get the minimal value of the Adjustment_t
float adj_get_max_value (Adjustment_t *adj)
adj_get_max_value - get the maximal value of the Adjustment_t
void adj_set_value (Adjustment_t *adj, float v)
adj_set_value - set the current value to the Adjustment_t
void adj_set_min_value (Adjustment_t *adj, float v)
adj_set_min_value - set the minimal value to the Adjustment_t
void adj_set_max_value (Adjustment_t *adj, float v)
adj_set_max_value - set the maximal value to the Adjustment_t
void adj_set_std_value (Adjustment_t *adj, float v)
adj_set_std_value - set the standart value to the Adjustment_t
void adj_set_start_value (void *w)
adj_set_start_value - internal use to store the value when pointer movment starts
void adj_set_scale (Adjustment_t *adj, float value)
adj_set_scale - internal use to scale the pointer movement (0.1 -1.0)
void adj_set_log_scale (Adjustment_t *adj, float value)
adj_set_log_scale - internal use to set the logarithmic scale
void adj_set_motion_state (void *w, float x, float y)
adj_set_motion_state - internal use to set value and state of the Adjustment_t on mouse pointer movment
void check_value_changed (Adjustment_t *adj, float *value)
check_value_changed - check if Adjustment_t value have changed and send value_changed_callback (VALUE_CHANGED) and adj_callback (ADJ_INTERN) if so
Function Documentation
add_adjustment()
Adjustment_t * add_adjustment (Widget_t * w, float std_value, float value, float min_value, float max_value, float step, CL_type type)
*add_adjustment - adding a adjustment to a Widget_t
Parameters
*w - pointer to the Widget_t request a Adjustment_t
std_value - standard value of the Adjustment_t
value - current value of the Adjustment_t
min_value - minimum value of the Adjustment_t
max_value - maximal value of the Adjustment_t
step - step to increase/decrease the Adjustment_t
type - set CL_type of Adjustment_t
Returns
*adj - pointer to the Adjustment_t
Definition at line 25 of file xadjustment.c.
{
    Adjustment_t *adj = (Adjustment_t*)malloc(sizeof(Adjustment_t));
    assert(adj);
    adj->log_scale = 20.0;
    switch(type) {
        case (CL_LOGSCALE) :
        *(adj) = (Adjustment_t) {
            .w           = w,
            .std_value   = powf(10,(std_value/adj->log_scale)),
            .value       = powf(10,(value/adj->log_scale)),
            .min_value   = powf(10,(min_value/adj->log_scale)),
            .max_value   = powf(10,(max_value/adj->log_scale)),
            .step        = step,
            .start_value = powf(10,(value/adj->log_scale)),
            .scale       = 1.0,
            .type        = type,
            .log_scale   = adj->log_scale
        };
        break;
        case (CL_LOGARITHMIC) :
        *(adj) = (Adjustment_t) {
            .w           = w,
            .std_value   = log10(std_value),
            .value       = log10(value),
            .min_value   = log10(min_value),
            .max_value   = log10(max_value),
            .step        = step,
            .start_value = log10(value),
            .scale       = 1.0,
            .type        = type,
            .log_scale   = adj->log_scale
        };
        break;
        default:
        *(adj) = (Adjustment_t) {
            .w           = w,
            .std_value   = std_value,
            .value       = value,
            .min_value   = min_value,
            .max_value   = max_value,
            .step        = step,
            .start_value = value,
            .scale       = 1.0,
            .type        = type,
            .log_scale   = adj->log_scale
        };
        break;
    }
    debug_print("Widget_t add adjustment\n");
    return adj;
}
References CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, and Widget_t::scale.
Referenced by add_button(), add_check_box(), add_check_button(), add_combobox(), add_hmeter(), add_hslider(), add_image_button(), add_image_knob(), add_image_toggle_button(), add_knob(), add_listbox(), add_listview(), add_menu(), add_multi_listview(), add_on_off_button(), add_playhead(), add_switch_image_button(), add_tabbox(), add_toggle_button(), add_tuner(), add_valuedisplay(), add_vmeter(), add_vslider(), cmenu_add_submenu(), create_combobox_viewport(), create_listbox_viewport(), create_listview_viewport(), create_multi_listview_viewport(), create_viewport(), menu_add_check_item(), menu_add_submenu(), menu_add_value_entry(), and menu_add_value_item().
adj_get_max_value()
float adj_get_max_value (Adjustment_t * adj)
adj_get_max_value - get the maximal value of the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
Returns
float - return the Adjustment_t value
Definition at line 181 of file xadjustment.c.
{
    if (!adj) return 0.0;
    if (adj->type == CL_LOGSCALE)
        return log10(adj->max_value)*adj->log_scale;
    else if (adj->type == CL_LOGARITHMIC)
        return powf(10,adj->max_value);
    return (adj->max_value);
}
References CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, Adjustment_t::max_value, and Adjustment_t::type.
adj_get_min_value()
float adj_get_min_value (Adjustment_t * adj)
adj_get_min_value - get the minimal value of the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
Returns
float - return the Adjustment_t value
Definition at line 172 of file xadjustment.c.
{
    if (!adj) return 0.0;
    if (adj->type == CL_LOGSCALE)
        return log10(adj->min_value)*adj->log_scale;
    else if (adj->type == CL_LOGARITHMIC)
        return powf(10,adj->min_value);
    return (adj->min_value);
}
References CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, Adjustment_t::min_value, and Adjustment_t::type.
adj_get_state()
float adj_get_state (Adjustment_t * adj)
adj_get_state - get the current state of the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
Returns
float - return the Adjustment_t state mapped to (0<->1)
Definition at line 148 of file xadjustment.c.
{
    if (!adj) return 0.0;
    return (adj->value - adj->min_value) /
       (adj->max_value - adj->min_value);
}
References Adjustment_t::max_value, Adjustment_t::min_value, and Adjustment_t::value.
Referenced by _draw_combobox_menu_slider(), _draw_hslider(), _draw_image_button(), _draw_image_button_with_label(), _draw_image_knob(), _draw_image_slider(), _draw_knob(), _draw_listbox_viewslider(), _draw_listviewslider(), _draw_menu_slider(), _draw_multi_listviewslider(), _draw_playhead(), _draw_vslider(), _reconfigure_combobox_viewport(), _reconfigure_listbox_viewport(), _reconfigure_listview_viewport(), _set_combobox_menu_viewport(), _set_combobox_viewpoint(), _set_entry(), _set_listview_viewpoint(), _set_listviewport(), _set_menu_viewpoint(), _set_multi_listview_viewpoint(), _set_multi_listviewport(), _set_viewpoint(), and mk_draw_knob().
adj_get_std_value()
float adj_get_std_value (Adjustment_t * adj)
adj_get_std_value - get the standart value of the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
Returns
float - return the Adjustment_t value
Definition at line 163 of file xadjustment.c.
{
    if (!adj) return 0.0;
    if (adj->type == CL_LOGSCALE)
        return log10(adj->std_value)*adj->log_scale;
    else if (adj->type == CL_LOGARITHMIC)
        return powf(10,adj->std_value);
    return (adj->std_value);
}
References CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, Adjustment_t::std_value, and Adjustment_t::type.
adj_get_value()
float adj_get_value (Adjustment_t * adj)
adj_get_value - get the current value of the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
Returns
float - return the Adjustment_t value
Definition at line 154 of file xadjustment.c.
{
    if (!adj) return 0.0;
    if (adj->type == CL_LOGSCALE)
        return log10(adj->value)*adj->log_scale;
    else if (adj->type == CL_LOGARITHMIC)
        return powf(10,adj->value);
    return (adj->value);
}
References CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, Adjustment_t::type, and Adjustment_t::value.
Referenced by _buttons_released(), _combobox_entry_released(), _combobox_key_pressed(), _combobox_motion(), _draw_check_box(), _draw_combobox(), _draw_combobox_entrys(), _draw_h_meter(), _draw_hslider(), _draw_image_button_with_label(), _draw_knob(), _draw_list(), _draw_multi_list(), _draw_spinbox(), _draw_tabbox(), _draw_tuner(), _draw_v_meter(), _draw_value_item(), _draw_valuedisplay(), _draw_vslider(), _list_entry_double_clicked(), _list_entry_released(), _list_key_pressed(), _list_motion(), _menu_entry_released(), _multi_list_entry_double_clicked(), _multi_list_entry_released(), _multi_list_key_pressed(), _multi_list_motion(), _reconfigure_multi_listview_viewport(), _set_entry(), _set_listbox_viewpoint(), _set_viewpoint(), _update_list_view(), _update_view(), mk_open_midi_keyboard(), and set_active_radio_entry().
adj_set_log_scale()
void adj_set_log_scale (Adjustment_t * adj, float value)
adj_set_log_scale - internal use to set the logarithmic scale
Parameters
*adj - pointer to the Adjustment_t
value - value to set the scaleing factor to
Definition at line 237 of file xadjustment.c.
{
    adj->log_scale = value;
}
References Adjustment_t::log_scale.
adj_set_max_value()
void adj_set_max_value (Adjustment_t * adj, float value)
adj_set_max_value - set the maximal value to the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
value - value to set the Adjustment_t to
Definition at line 209 of file xadjustment.c.
{
    if (!adj) return;
    if (adj->type == CL_LOGSCALE)
        v = powf(10,(v/adj->log_scale));
    else if (adj->type == CL_LOGARITHMIC)
        v = log10(v);
    adj->max_value = v;
}
References CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, Adjustment_t::max_value, and Adjustment_t::type.
adj_set_min_value()
void adj_set_min_value (Adjustment_t * adj, float value)
adj_set_min_value - set the minimal value to the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
value - value to set the Adjustment_t to
Definition at line 200 of file xadjustment.c.
{
    if (!adj) return;
    if (adj->type == CL_LOGSCALE)
        v = powf(10,(v/adj->log_scale));
    else if (adj->type == CL_LOGARITHMIC)
        v = log10(v);
    adj->min_value = v;
}
References CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, Adjustment_t::min_value, and Adjustment_t::type.
adj_set_motion_state()
void adj_set_motion_state (void * w, float x, float y)
adj_set_motion_state - internal use to set value and state of the Adjustment_t on mouse pointer movment
Parameters
*w - pointer to Widget_t containing Adjustment_t
x - movment on the x-axis
y - movement on the y-axis
Definition at line 241 of file xadjustment.c.
{
    Widget_t * wid = (Widget_t*)w;
    if(wid->adj_x) {
        float value= wid->adj_x->value;
        switch(wid->adj_x->type) {
            case (CL_LOGSCALE):
            case (CL_LOGARITHMIC):
            case (CL_CONTINUOS):
            {
                float state = (wid->adj_x->start_value - wid->adj_x->min_value) /
                    (wid->adj_x->max_value - wid->adj_x->min_value);
                float nsteps = wid->adj_x->step / (wid->adj_x->max_value - wid->adj_x->min_value);
                float nvalue = min(1.0,max(0.0,state + ((float)(x - wid->pos_x)*wid->adj_x->scale *nsteps)));
                float prevalue = nvalue * (wid->adj_x->max_value - wid->adj_x->min_value) + wid->adj_x->min_value;
                float mulscale = round(prevalue/wid->adj_x->step);
                value = min(wid->adj_x->max_value,max(wid->adj_x->min_value,mulscale*wid->adj_x->step));
            }
            break;
            case (CL_VIEWPORTSLIDER):
            {
                float state = (wid->adj_x->start_value - wid->adj_x->min_value) /
                    (wid->adj_x->max_value - wid->adj_x->min_value);
                float nsteps = wid->adj_x->step / (wid->adj_x->max_value - wid->adj_x->min_value);
                float nvalue = min(1.0,max(0.0,state - ((float)(x - wid->pos_x)*wid->adj_x->scale *nsteps)));
                float prevalue = nvalue * (wid->adj_x->max_value - wid->adj_x->min_value) + wid->adj_x->min_value;
                float mulscale = round(prevalue/wid->adj_x->step);
                value = min(wid->adj_x->max_value,max(wid->adj_x->min_value,mulscale*wid->adj_x->step));
            }
            break;
            case (CL_TOGGLE):
                // dont toggle on motion!
                // value = wid->adj_x->value ? 0.0 : 1.0;
            break;
            default:
            break;
        }
        check_value_changed(wid->adj_x, &value);
    }
    if(wid->adj_y) {
        float value = wid->adj_y->value;
        switch(wid->adj_y->type) {
            case (CL_LOGSCALE):
            case (CL_LOGARITHMIC):
            case (CL_CONTINUOS):
            {
                float state = (wid->adj_y->start_value - wid->adj_y->min_value) /
                    (wid->adj_y->max_value - wid->adj_y->min_value);
                float nsteps = wid->adj_y->step / (wid->adj_y->max_value - wid->adj_y->min_value);
                float nvalue = min(1.0,max(0.0,state + ((float)(wid->pos_y - y)*wid->adj_y->scale *nsteps)));
                float prevalue = nvalue * (wid->adj_y->max_value - wid->adj_y->min_value) + wid->adj_y->min_value;
                float mulscale = round(prevalue/wid->adj_y->step);
                value = min(wid->adj_y->max_value,max(wid->adj_y->min_value,mulscale*wid->adj_y->step));
            }
            break;
            case (CL_VIEWPORTSLIDER):
            {
                float state = (wid->adj_y->start_value - wid->adj_y->min_value) /
                    (wid->adj_y->max_value - wid->adj_y->min_value);
                float nsteps = wid->adj_y->step / (wid->adj_y->max_value - wid->adj_y->min_value);
                float nvalue = min(1.0,max(0.0,state - ((float)(wid->pos_y - y)*wid->adj_y->scale *nsteps)));
                float prevalue = nvalue * (wid->adj_y->max_value - wid->adj_y->min_value) + wid->adj_y->min_value;
                float mulscale = round(prevalue/wid->adj_y->step);
                value = min(wid->adj_y->max_value,max(wid->adj_y->min_value,mulscale*wid->adj_y->step));
            }
            break;
            case (CL_TOGGLE):
                // dont toggle on motion!
                // value = wid->adj_y->value ? 0.0 : 1.0;
            break;
            default:
            break;
        }
        check_value_changed(wid->adj_y, &value);
    }
}
References Widget_t::adj_x, Widget_t::adj_y, check_value_changed(), CL_CONTINUOS, CL_LOGARITHMIC, CL_LOGSCALE, CL_TOGGLE, CL_VIEWPORTSLIDER, Adjustment_t::max_value, Adjustment_t::min_value, Widget_t::pos_x, Widget_t::pos_y, Adjustment_t::scale, Adjustment_t::start_value, Adjustment_t::step, Adjustment_t::type, and Adjustment_t::value.
Referenced by os_widget_event_loop(), and WndProc().
adj_set_scale()
void adj_set_scale (Adjustment_t * adj, float value)
adj_set_scale - internal use to scale the pointer movement (0.1 -1.0)
Parameters
*adj - pointer to the Adjustment_t
value - value to set the scaleing factor to
Definition at line 233 of file xadjustment.c.
{
    adj->scale = value;
}
References Adjustment_t::scale.
Referenced by _configure_listview(), _configure_menu(), _reconfigure_combobox_viewport(), _reconfigure_multi_listview_viewport(), and mk_open_midi_keyboard().
adj_set_start_value()
void adj_set_start_value (void * w)
adj_set_start_value - internal use to store the value when pointer movment starts
Parameters
*w - pointer to Widget_t containing the Adjustment_t
Definition at line 227 of file xadjustment.c.
{
    Widget_t * wid = (Widget_t*)w;
    if(wid->adj_x)wid->adj_x->start_value = wid->adj_x->value;
    if(wid->adj_y)wid->adj_y->start_value = wid->adj_y->value;
}
References Widget_t::adj_x, Widget_t::adj_y, Adjustment_t::start_value, and Adjustment_t::value.
Referenced by _toggle_event().
adj_set_state()
void adj_set_state (Adjustment_t * adj, float state)
adj_set_state - set the current state of the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
state - set the Adjustment_t state mapped to (0<->1)
Definition at line 141 of file xadjustment.c.
{
    if (!adj) return;
    float nvalue = min(1.0,max(0.0,state));
    float value = nvalue * (adj->max_value - adj->min_value) + adj->min_value;
    check_value_changed(adj, &value);
}
References check_value_changed(), Adjustment_t::max_value, and Adjustment_t::min_value.
Referenced by _reconfigure_combobox_viewport(), _reconfigure_listbox_viewport(), _reconfigure_listview_viewport(), _set_combobox_menu_viewport(), _set_combobox_viewpoint(), _set_entry(), _set_listview_viewpoint(), _set_listviewport(), _set_menu_viewpoint(), _set_multi_listview_viewpoint(), _set_multi_listviewport(), and _set_viewpoint().
adj_set_std_value()
void adj_set_std_value (Adjustment_t * adj, float value)
adj_set_std_value - set the standart value to the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
value - value to set the Adjustment_t to
Definition at line 218 of file xadjustment.c.
{
    if (!adj) return;
    if (adj->type == CL_LOGSCALE)
        v = powf(10,(v/adj->log_scale));
    else if (adj->type == CL_LOGARITHMIC)
        v = log10(v);
    adj->std_value = v;
}
References CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, Adjustment_t::std_value, and Adjustment_t::type.
adj_set_value()
void adj_set_value (Adjustment_t * adj, float value)
adj_set_value - set the current value to the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
value - value to set the Adjustment_t to
Definition at line 190 of file xadjustment.c.
{
    if (!adj) return;
    if (adj->type == CL_LOGSCALE)
        v = powf(10,(v/adj->log_scale));
    else if (adj->type == CL_LOGARITHMIC)
        v = log10(v);
    v = min(adj->max_value,max(adj->min_value, v));
    check_value_changed(adj, &v);
}
References check_value_changed(), CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, Adjustment_t::max_value, Adjustment_t::min_value, and Adjustment_t::type.
Referenced by _button_combobox_released(), _button_pressed(), _button_released(), _buttons_released(), _check_item_button_pressed(), _combobox_entry_released(), _list_entry_released(), _menu_entry_released(), _multi_list_entry_released(), _reconfigure_multi_listview_viewport(), _set_entry(), _tab_button_released(), _toggle_button_released(), add_keyboard(), combobox_set_active_entry(), listbox_set_active_entry(), listview_remove_list(), listview_set_active_entry(), multi_listview_remove_list(), multi_listview_set_active_entry(), radio_box_set_active(), radio_item_set_active(), set_active_radio_entry(), and tabbox_add_tab().
check_value_changed()
void check_value_changed (Adjustment_t * adj, float * value)
check_value_changed - check if Adjustment_t value have changed and send value_changed_callback (VALUE_CHANGED) and adj_callback (ADJ_INTERN) if so
Parameters
*adj - pointer to the Adjustment_t
value - value to check
Definition at line 317 of file xadjustment.c.
{
    debug_print("Adjustment_t check_value_changed %f\n", *(value));
    if(fabs(*(value) - adj->value)>=0.00001) {
        adj->value = *(value);
        adj->w->func.adj_callback(adj->w, NULL);
        adj->w->func.value_changed_callback(adj->w, value);
    }
}
References Func_t::adj_callback, Widget_t::func, Adjustment_t::value, Func_t::value_changed_callback, and Adjustment_t::w.
Referenced by _check_enum(), _listbox_entry_released(), _scroll_event(), _set_adj_value(), adj_set_motion_state(), adj_set_state(), and adj_set_value().
delete_adjustment()
void * delete_adjustment (Adjustment_t * adj)
delete_adjustment - freeing the memory of the Adjustment_t You usually don't need to call this, as it get handled by main_quit() -> destroy_widget()
Parameters
*adj - pointer to the Adjustment to free
Definition at line 133 of file xadjustment.c.
{
    if(adj) {
        free(adj);
        debug_print("Widget_t delete adjustment\n");
    }
    return NULL;
}
Referenced by destroy_widget().
set_adjustment()
void set_adjustment (Adjustment_t * adj, float std_value, float value, float min_value, float max_value, float step, CL_type type)
*set_adjustment - set a new range to a existing Adjustment_t it will be created if it not exsits yet
Parameters
*w - pointer to the Widget_t request a Adjustment_t
std_value - standard value of the Adjustment_t
value - current value of the Adjustment_t
min_value - minimum value of the Adjustment_t
max_value - maximal value of the Adjustment_t
step - step to increase/decrease the Adjustment_t
type - set CL_type of Adjustment_t
Definition at line 80 of file xadjustment.c.
{
    if (!adj) adj = (Adjustment_t*)malloc(sizeof(Adjustment_t));
    assert(adj);
    switch(type) {
        case (CL_LOGSCALE) :
        *(adj) = (Adjustment_t) {
            .w           = adj->w,
            .std_value   = powf(10,(std_value/adj->log_scale)),
            .value       = powf(10,(value/adj->log_scale)),
            .min_value   = powf(10,(min_value/adj->log_scale)),
            .max_value   = powf(10,(max_value/adj->log_scale)),
            .step        = step,
            .start_value = powf(10,(value/adj->log_scale)),
            .scale       = 1.0,
            .type        = type,
            .log_scale   = adj->log_scale
        };
        break;
        case (CL_LOGARITHMIC) :
        *(adj) = (Adjustment_t) {
            .w           = adj->w,
            .std_value   = log10(std_value),
            .value       = log10(value),
            .min_value   = log10(min_value),
            .max_value   = log10(max_value),
            .step        = step,
            .start_value = log10(value),
            .scale       = 1.0,
            .type        = type,
            .log_scale   = adj->log_scale
        };
        break;
        default:
        *(adj) = (Adjustment_t) {
            .w           = adj->w,
            .std_value   = std_value,
            .value       = value,
            .min_value   = min_value,
            .max_value   = max_value,
            .step        = step,
            .start_value = value,
            .scale       = 1.0,
            .type        = type,
            .log_scale   = adj->log_scale
        };
        break;
    }
    debug_print("Widget_t set adjustment\n");
}
References CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, Widget_t::scale, and Adjustment_t::w.
Referenced by _configure_combobox_menu(), _configure_menu(), _reconfigure_combobox_viewport(), add_keyboard(), add_keyboard_knob(), cmenu_add_submenu(), combobox_add_entry(), combobox_delete_entrys(), create_combobox_menu(), create_menu(), listbox_add_entry(), listview_remove_list(), listview_set_list(), menu_add_accel_check_entry(), menu_add_check_entry(), menu_add_entry(), menu_add_item(), menu_add_numeric_items(), menu_add_radio_entry(), menu_add_submenu(), menu_add_value_entry(), menu_remove_item(), mk_open_midi_keyboard(), multi_listview_remove_list(), multi_listview_set_list(), open_file_dialog(), tabbox_add_tab(), and tabbox_remove_tab().