libxputty: xputty/xasprintf.c File Reference
xasprintf.c File Reference
Functions
int _vscprintf_so (const char *format, va_list pargs)
int vasprintf (char **strp, const char *fmt, va_list ap)
int asprintf (char *strp[], const char *fmt,...)
Function Documentation
_vscprintf_so()
int _vscprintf_so (const char * format, va_list pargs)
Definition at line 16 of file xasprintf.c.
{
    int retval;
    va_list argcopy;
    va_copy(argcopy, pargs);
    retval = vsnprintf(NULL, 0, format, argcopy);
    va_end(argcopy);
    return retval;
}
Referenced by vasprintf().
asprintf()
int asprintf (char * strp[], const char * fmt, ...)
Definition at line 36 of file xasprintf.c.
{
    va_list ap;
    va_start(ap, fmt);
    int r = vasprintf(strp, fmt, ap);
    va_end(ap);
    return r;
}
References vasprintf().
Referenced by add_root_directory(), combobox_add_entry(), combobox_rename_entry(), fp_get_files(), fp_init(), hyperlink_pressed(), locale_from_utf8(), os_get_home_dir(), and utf8_from_locale().
vasprintf()
int vasprintf (char ** strp, const char * fmt, va_list ap)
Definition at line 25 of file xasprintf.c.
{
    int len = _vscprintf_so(fmt, ap);
    if (len == -1) return -1;
    char *str = malloc((size_t) len + 1);
    if (!str) return -1;
    int r = vsnprintf(str, len + 1, fmt, ap);
    if (r == -1) return free(str), -1;
    *strp = str;
    return r;
}
References _vscprintf_so().
Referenced by asprintf().