libxputty: xputty/widgets/xbutton.c File Reference
xbutton.c File Reference
Functions
Widget_t * add_button (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_button - add a button to a Widget_t connect to func.value_changed_callback to implement your actions
Widget_t * add_image_button (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_image_button - add a image button to a Widget_t connect to func.value_changed_callback to implement your actions
Widget_t * add_on_off_button (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_on_off_button - add a button with default on/off label to a Widget_t connect to func.value_changed_callback to implement your actions
Widget_t * add_toggle_button (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_toggle_button - add a button to a Widget_t connect to func.value_changed_callback to implement your actions
Widget_t * add_image_toggle_button (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_image_toggle_button - add a button to a Widget_t connect to func.value_changed_callback to implement your actions
Widget_t * add_switch_image_button (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_switch_image_button - add a button to a Widget_t connect to func.value_changed_callback to implement your actions
Widget_t * add_check_button (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_check_button - add a button to a Widget_t connect to func.value_changed_callback to implement your actions
int get_width (const char *label)
Widget_t * add_check_box (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_check_box - add a check box to a Widget_t connect to func.value_changed_callback to implement your actions
Function Documentation
add_button()
Widget_t * add_button (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_button - add a button to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the button
*label - Label to show on the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 26 of file xbutton.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,1.0, CL_TOGGLE);
    wid->adj = wid->adj_y;
    wid->scale.gravity = CENTER;
    wid->func.expose_callback = _draw_base_button;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_press_callback = _button_pressed;
    wid->func.button_release_callback = _button_released;
    return wid;
}
References _button_pressed(), _button_released(), _draw_base_button(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, CL_TOGGLE, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
Referenced by add_combobox(), open_directory_dialog(), open_file_dialog(), open_message_dialog(), and save_file_dialog().
add_check_box()
Widget_t * add_check_box (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_check_box - add a check box to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the button
*label - Label to show on the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 141 of file xbutton.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, get_width(label), height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,1.0, CL_TOGGLE);
    wid->adj = wid->adj_y;
    wid->scale.gravity = CENTER;
    wid->func.expose_callback = _draw_check_box;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_press_callback = _toggle_button_pressed;
    wid->func.button_release_callback = _toggle_button_released;
    return wid;
}
References _draw_check_box(), _toggle_button_pressed(), _toggle_button_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, CL_TOGGLE, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, get_width(), Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
add_check_button()
Widget_t * add_check_button (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_check_button - add a button to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the button
*label - Label to show on the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 121 of file xbutton.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,1.0, CL_TOGGLE);
    wid->adj = wid->adj_y;
    wid->scale.gravity = CENTER;
    wid->func.expose_callback = _draw_check_button;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_press_callback = _toggle_button_pressed;
    wid->func.button_release_callback = _toggle_button_released;
    return wid;
}
References _draw_check_button(), _toggle_button_pressed(), _toggle_button_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, CL_TOGGLE, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
Referenced by open_directory_dialog(), open_file_dialog(), and save_file_dialog().
add_image_button()
Widget_t * add_image_button (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_image_button - add a image button to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the button
*label - Label to show on the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 42 of file xbutton.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,1.0, CL_TOGGLE);
    wid->adj = wid->adj_y;
    wid->scale.gravity = CENTER;
    wid->func.expose_callback = _draw_button;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_press_callback = _button_pressed;
    wid->func.button_release_callback = _button_released;
    return wid;
}
References _button_pressed(), _button_released(), _draw_button(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, CL_TOGGLE, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
add_image_toggle_button()
Widget_t * add_image_toggle_button (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_image_toggle_button - add a button to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the button
*label - Label to show on the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 89 of file xbutton.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,1.0, CL_TOGGLE);
    wid->adj = wid->adj_y;
    wid->scale.gravity = CENTER;
    wid->func.expose_callback = _draw_ti_button;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_press_callback = _toggle_button_pressed;
    wid->func.button_release_callback = _toggle_button_released;
    return wid;
}
References _draw_ti_button(), _toggle_button_pressed(), _toggle_button_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, CL_TOGGLE, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
Referenced by add_directory_button(), add_file_button(), and add_save_file_button().
add_on_off_button()
Widget_t * add_on_off_button (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_on_off_button - add a button with default on/off label to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the button
*label - Label (ignored)
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 58 of file xbutton.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,1.0, CL_TOGGLE);
    wid->adj = wid->adj_y;
    wid->scale.gravity = CENTER;
    wid->func.expose_callback = _draw_on_off_button;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_press_callback = _toggle_button_pressed;
    wid->func.button_release_callback = _toggle_button_released;
    return wid;
}
References _draw_on_off_button(), _toggle_button_pressed(), _toggle_button_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, CL_TOGGLE, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
add_switch_image_button()
Widget_t * add_switch_image_button (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_switch_image_button - add a button to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the button
*label - Label to show on the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 105 of file xbutton.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,1.0, CL_TOGGLE);
    wid->adj = wid->adj_y;
    wid->scale.gravity = ASPECT;
    wid->func.expose_callback = _draw_switch_image_button;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_press_callback = _toggle_button_pressed;
    wid->func.button_release_callback = _toggle_button_released;
    return wid;
}
References _draw_switch_image_button(), _toggle_button_pressed(), _toggle_button_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, ASPECT, Func_t::button_press_callback, Func_t::button_release_callback, CL_TOGGLE, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
Referenced by add_my_switch_image().
add_toggle_button()
Widget_t * add_toggle_button (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_toggle_button - add a button to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the button
*label - Label to show on the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 73 of file xbutton.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,1.0, CL_TOGGLE);
    wid->adj = wid->adj_y;
    wid->scale.gravity = CENTER;
    wid->func.expose_callback = _draw_base_button;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_press_callback = _toggle_button_pressed;
    wid->func.button_release_callback = _toggle_button_released;
    return wid;
}
References _draw_base_button(), _toggle_button_pressed(), _toggle_button_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, CL_TOGGLE, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
get_width()
int get_width (const char * label)
Definition at line 137 of file xbutton.c.
{
    return max(1, strlen(label)*12);
}
Referenced by add_check_box().