libxputty: xputty/widgets/xbutton_private.c File Reference
xbutton_private.c File Reference
Functions
void _rounded_rectangle (cairo_t *cr, float x, float y, float width, float height)
_rounded_rectangle - internal draw a rounded button
void _pattern_out (Widget_t *w, Color_state st, int height)
_pattern_in - a little pattern to make press state more visible
void _pattern_in (Widget_t *w, Color_state st, int height)
_pattern_in - a little pattern to make press state more visible
void _draw_image_button (Widget_t *w, int width_t, int height_t, float offset)
void _draw_image_button_with_label (Widget_t *w, int width_t, int height_t)
void _draw_switch_image_button (void *w_, void *user_data)
draw switch_image_button - internal draw the button to the buffer
void _draw_button_base (Widget_t *w, int width, int height)
int _remove_low_dash (char *str)
void _draw_button (void *w_, void *user_data)
_draw_button - internal draw the button to the buffer
void _draw_base_button (void *w_, void *user_data)
_draw_base_button - internal draw the button with base to the buffer
void _draw_on_off_button (void *w_, void *user_data)
_draw_on_off_button - internal draw the on/off button to the buffer
void _draw_ti_button (void *w_, void *user_data)
_draw_ti_button - internal draw the button to the buffer
void _draw_check_button (void *w_, void *user_data)
_draw_check_button - internal draw the button to the buffer
void _draw_check_box (void *w_, void *user_data)
_draw_check_box - internal draw the check box to the buffer
void _button_pressed (void *w_, void *button, void *user_data)
_button_pressed - redraw the button and send state via user_callback
void _button_released (void *w_, void *button_, void *user_data)
_button_released - redraw the button and send state via user_callback
void _toggle_button_pressed (void *w_, void *button, void *user_data)
_toggle_button_pressed - redraw the button and send state via user_callback
void _toggle_button_released (void *w_, void *button_, void *user_data)
_toggle_button_released - redraw the button and send state via user_callback
Function Documentation
_button_pressed()
void _button_pressed (void * w_, void * button_, void * user_data)
_button_pressed - redraw the button and send state via user_callback
Parameters
*w_ - void pointer to the Widget_t button
*button_ - void pointer to XEvent.xbutton struct
*user_data - void pointer to attached user_data
Definition at line 420 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    adj_set_value(w->adj_y, 1.0);
}
References adj_set_value(), and Widget_t::adj_y.
Referenced by add_button(), and add_image_button().
_button_released()
void _button_released (void * w_, void * button_, void * user_data)
_button_released - redraw the button and send state via user_callback
Parameters
*w_ - void pointer to the Widget_t button
*button_ - void pointer to XEvent.xbutton struct
*user_data - void pointer to attached user_data
Definition at line 425 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (w->flags & HAS_POINTER) w->state=1;
    adj_set_value(w->adj_y, 0.0);
}
References adj_set_value(), Widget_t::adj_y, Widget_t::flags, HAS_POINTER, and Widget_t::state.
Referenced by add_button(), and add_image_button().
_draw_base_button()
void _draw_base_button (void * w_, void * user_data)
_draw_base_button - internal draw the button with base to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Definition at line 220 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    _draw_button_base(w, width, height);
    float offset = 0.0;
    if(w->state==1 && ! (int)w->adj_y->value) {
        offset = 1.0;
    } else if(w->state==1) {
        offset = 2.0;
    } else if(w->state==2) {
        offset = 2.0;
    } else if(w->state==3) {
        offset = 1.0;
    }
    if (w->image) {
        if(strlen(w->label)) {
            _draw_image_button_with_label(w, width, height);
        } else {
            _draw_image_button(w, width, height,offset);
        }
    } else {
        cairo_text_extents_t extents;
        use_text_color_scheme(w, get_color_state(w));
        cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
        if (strstr(w->label, "_")) {
            cairo_text_extents(w->crb, "--", &extents);
            double underline = extents.width;
            strncpy(w->input_label,w->label, sizeof(w->input_label)-1);
            int pos = _remove_low_dash(w->input_label);
            int len = strlen(w->input_label);
            cairo_text_extents(w->crb,w->input_label , &extents);
            int set_line = (extents.width/len) * pos;
            cairo_move_to (w->crb, (width-extents.width)*0.5 +offset, (height+extents.height)*0.5 +offset);
            cairo_show_text(w->crb, w->input_label);
            cairo_set_line_width(w->crb, 1.0);
            cairo_move_to (w->crb, (width-extents.width)*0.5 +offset + set_line, (height+extents.height)*0.55 +offset);
            cairo_line_to(w->crb,(width-extents.width)*0.5 +offset + set_line + underline, (height+extents.height)*0.55 +offset);
            cairo_stroke(w->crb);
        } else {
            cairo_text_extents(w->crb,w->label , &extents);
            cairo_move_to (w->crb, (width-extents.width)*0.5 +offset, (height+extents.height)*0.5 +offset);
            cairo_show_text(w->crb, w->label);
        }
    }
}
References _draw_button_base(), _draw_image_button(), _draw_image_button_with_label(), _remove_low_dash(), Widget_t::adj_y, Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::image, Widget_t::input_label, Widget_t::label, Xputty::normal_font, os_get_window_metrics(), Widget_t::scale, Widget_t::state, use_text_color_scheme(), Adjustment_t::value, Metrics_t::visible, and Metrics_t::width.
Referenced by add_button(), and add_toggle_button().
_draw_button()
void _draw_button (void * w_, void * user_data)
_draw_button - internal draw the button to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Definition at line 191 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    float offset = 0.0;
    if(w->state==1 && ! (int)w->adj_y->value) {
        offset = 1.0;
    } else if(w->state==1) {
        offset = 2.0;
    } else if(w->state==2) {
        offset = 2.0;
    } else if(w->state==3) {
        offset = 1.0;
    }
    if (w->image) {
        if(strlen(w->label)) {
            _draw_image_button_with_label(w, width, height);
        } else {
            _draw_image_button(w, width, height,offset);
        }
    }
}
References _draw_image_button(), _draw_image_button_with_label(), Widget_t::adj_y, Metrics_t::height, Widget_t::image, Widget_t::label, os_get_window_metrics(), Widget_t::state, Adjustment_t::value, Metrics_t::visible, and Metrics_t::width.
Referenced by add_image_button().
_draw_button_base()
void _draw_button_base (Widget_t * w, int width, int height)
Definition at line 129 of file xbutton_private.c.
{
    if (!w->state && (int)w->adj_y->value) {
        w->state = 3;
    } else if (w->state == 3 && !(int)w->adj_y->value) {
        w->state = 0;
    }
    _rounded_rectangle(w->crb,2.0, 2.0, width, height);
    if(w->state==0) {
        cairo_set_line_width(w->crb, 1.0);
        _pattern_out(w, NORMAL_, height);
        cairo_fill_preserve(w->crb);
        use_frame_color_scheme(w, PRELIGHT_);
    } else if(w->state==1) {
        _pattern_out(w, PRELIGHT_, height);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.5);
        use_frame_color_scheme(w, PRELIGHT_);
    } else if(w->state==2) {
        _pattern_in(w, SELECTED_, height);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, PRELIGHT_);
    } else if(w->state==3) {
        _pattern_in(w, ACTIVE_, height);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, PRELIGHT_);
    }
    cairo_stroke(w->crb);
    if(w->state==2) {
        _rounded_rectangle(w->crb,4.0, 4.0, width, height);
        cairo_stroke(w->crb);
        _rounded_rectangle(w->crb,3.0, 3.0, width, height);
        cairo_stroke(w->crb);
    } else if (w->state==3) {
        _rounded_rectangle(w->crb,3.0, 3.0, width, height);
        cairo_stroke(w->crb);
    }
}
References _pattern_in(), _pattern_out(), _rounded_rectangle(), ACTIVE_, Widget_t::adj_y, Widget_t::crb, NORMAL_, PRELIGHT_, SELECTED_, Widget_t::state, use_frame_color_scheme(), and Adjustment_t::value.
Referenced by _draw_base_button(), _draw_check_box(), _draw_check_button(), _draw_on_off_button(), and _draw_ti_button().
_draw_check_box()
void _draw_check_box (void * w_, void * user_data)
_draw_check_box - internal draw the check box to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Definition at line 374 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int height = metrics.height-2;
    if (!metrics.visible) return;
    if (w->image) {
        _draw_image_button(w, height, height,0.0);
    } else {
        _draw_button_base(w, height, height);
        if(adj_get_value(w->adj)) {
            use_fg_color_scheme(w, get_color_state(w));
            float offset = 1.0;
            int wa = height/1.3;
            int h = height/2.2;
            int wa1 = height/2.2;
            int h1 = height/1.3;
            int wa2 = height/2.8;
            cairo_set_line_width(w->crb, 2.5);
            cairo_move_to(w->crb, wa+offset, h+offset);
            cairo_line_to(w->crb, wa1+offset, h1+offset);
            cairo_line_to(w->crb, wa2+offset, h+offset);
            cairo_stroke(w->crb);
        }
        cairo_new_path (w->crb);
        cairo_text_extents_t extents;
        use_text_color_scheme(w, get_color_state(w));
        cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
        cairo_text_extents(w->crb,w->label , &extents);
        cairo_move_to (w->crb, height+5 , (height+extents.height)*0.5 );
        cairo_show_text(w->crb, w->label);
        cairo_new_path (w->crb);
    }
}
References _draw_button_base(), _draw_image_button(), Widget_t::adj, adj_get_value(), Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::image, Widget_t::label, Xputty::normal_font, os_get_window_metrics(), Widget_t::scale, use_fg_color_scheme(), use_text_color_scheme(), and Metrics_t::visible.
Referenced by add_check_box().
_draw_check_button()
void _draw_check_button (void * w_, void * user_data)
_draw_check_button - internal draw the button to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Definition at line 341 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    if (w->image) {
        _draw_image_button(w, width, height,0.0);
    } else {
        _draw_button_base(w, width, height);
        if(w->state==3) {
            use_fg_color_scheme(w, get_color_state(w));
            float offset = 1.0;
            int wa = width/1.3;
            int h = height/2.2;
            int wa1 = width/2.2;
            int h1 = height/1.3;
            int wa2 = width/2.8;
            cairo_set_line_width(w->crb, 2.5);
            cairo_move_to(w->crb, wa+offset, h+offset);
            cairo_line_to(w->crb, wa1+offset, h1+offset);
            cairo_line_to(w->crb, wa2+offset, h+offset);
            cairo_stroke(w->crb);
        }
        cairo_new_path (w->crb);
    }
}
References _draw_button_base(), _draw_image_button(), Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::image, os_get_window_metrics(), Widget_t::state, use_fg_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by add_check_button().
_draw_image_button()
void _draw_image_button (Widget_t * w, int width_t, int height_t, float offset)
Definition at line 57 of file xbutton_private.c.
{
    int width, height;
    os_get_surface_size(w->image, &width, &height);
    double half_width = (width/height >=2) ? width*0.5 : width;
    double x = (double)width_t/(double)(half_width);
    double y = (double)height_t/(double)height;
    double x1 = (double)height/(double)height_t;
    double y1 = (double)(half_width)/(double)width_t;
    double off_set = offset*x1;
    double buttonstate = adj_get_state(w->adj);
    int findex = (int)(((width/height)-1) * buttonstate) * (width/height >=2);
    cairo_scale(w->crb, x,y);
    cairo_set_source_surface (w->crb, w->image, -height*findex+off_set, off_set);
    cairo_rectangle(w->crb,0, 0, height, height);
    cairo_fill(w->crb);
    cairo_scale(w->crb, x1,y1);
}
References Widget_t::adj, adj_get_state(), Widget_t::crb, Widget_t::image, and os_get_surface_size().
Referenced by _draw_base_button(), _draw_button(), _draw_check_box(), _draw_check_button(), _draw_switch_image_button(), and _draw_ti_button().
_draw_image_button_with_label()
void _draw_image_button_with_label (Widget_t * w, int width_t, int height_t)
Definition at line 75 of file xbutton_private.c.
{
    int width, height;
    os_get_surface_size(w->image, &width, &height);
    double x = (double)width_t/(double)height;
    double y = (double)height/(double)width_t;
    double buttonstate = adj_get_state(w->adj);
    int findex = (int)(((width/height)-1) * buttonstate);
    cairo_scale(w->crb, x,x);
    cairo_set_source_surface (w->crb, w->image, -height*findex, 0);
    cairo_rectangle(w->crb,0, 0, height, height);
    cairo_fill(w->crb);
    cairo_scale(w->crb, y,y);
    cairo_text_extents_t extents;
    if(w->state==0) {
        use_fg_color_scheme(w, NORMAL_);
    } else if(w->state==1 && ! (int)w->adj_y->value) {
        use_fg_color_scheme(w, PRELIGHT_);
    } else if(w->state==1) {
        use_fg_color_scheme(w, ACTIVE_);
    } else if(w->state==2) {
        use_fg_color_scheme(w, SELECTED_);
    } else if(w->state==3) {
        use_fg_color_scheme(w, ACTIVE_);
    }
    use_text_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb,w->app->normal_font/w->scale.ascale);
    if ((int)adj_get_value(w->adj) && strlen(w->input_label)) {
        cairo_text_extents(w->crb,w->input_label , &extents);
        cairo_move_to (w->crb, (width_t*0.5)-(extents.width/2), height_t-(extents.height/4));
        cairo_show_text(w->crb, w->input_label);
    } else {
        cairo_text_extents(w->crb,w->label , &extents);
        cairo_move_to (w->crb, (width_t*0.5)-(extents.width/2), height_t-(extents.height/4));
        cairo_show_text(w->crb, w->label);
    }
    cairo_new_path (w->crb);
}
References ACTIVE_, Widget_t::adj, adj_get_state(), adj_get_value(), Widget_t::adj_y, Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Widget_t::image, Widget_t::input_label, Widget_t::label, NORMAL_, Xputty::normal_font, os_get_surface_size(), PRELIGHT_, Widget_t::scale, SELECTED_, Widget_t::state, use_fg_color_scheme(), use_text_color_scheme(), and Adjustment_t::value.
Referenced by _draw_base_button(), _draw_button(), and _draw_switch_image_button().
_draw_on_off_button()
void _draw_on_off_button (void * w_, void * user_data)
_draw_on_off_button - internal draw the on/off button to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Definition at line 274 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    _draw_button_base(w, width, height);
    float offset = 0.0;
    cairo_text_extents_t extents;
    if(w->state==1 && ! (int)w->adj_y->value) {
        offset = 1.0;
    } else if(w->state==1) {
        offset = 2.0;
    } else if(w->state==2) {
        offset = 2.0;
    } else if(w->state==3) {
        offset = 1.0;
    }
    if((int)w->adj_y->value) {
        w->label = "On";
    } else {
        w->label = "Off";
    }
    use_text_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    cairo_text_extents(w->crb,w->label , &extents);
    if(IS_UTF8(w->label[0])) {
        cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
        cairo_text_extents(w->crb,w->label , &extents);
    }
    cairo_move_to (w->crb, (width-extents.width)*0.5 +offset, (height+extents.height)*0.5 +offset);
    cairo_show_text(w->crb, w->label);
    cairo_new_path (w->crb);
}
References _draw_button_base(), Widget_t::adj_y, Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::label, Xputty::normal_font, os_get_window_metrics(), Widget_t::scale, Widget_t::state, use_text_color_scheme(), Adjustment_t::value, Metrics_t::visible, and Metrics_t::width.
Referenced by add_on_off_button().
_draw_switch_image_button()
void _draw_switch_image_button (void * w_, void * user_data)
draw switch_image_button - internal draw the button to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Definition at line 114 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    if(strlen(w->label)) {
        _draw_image_button_with_label(w, width, height);
    } else {
        _draw_image_button(w, width, height,0.0);
    }
}
References _draw_image_button(), _draw_image_button_with_label(), Metrics_t::height, Widget_t::label, os_get_window_metrics(), Metrics_t::visible, and Metrics_t::width.
Referenced by add_switch_image_button().
_draw_ti_button()
void _draw_ti_button (void * w_, void * user_data)
_draw_ti_button - internal draw the button to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Definition at line 316 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    _draw_button_base(w, width, height);
    if (w->image) {
        float offset = 0.0;
        if(w->state==1 && ! (int)w->adj_y->value) {
            offset = 1.0;
        } else if(w->state==1) {
            offset = 2.0;
        } else if(w->state==2) {
            offset = 2.0;
        } else if(w->state==3) {
            offset = 1.0;
        }
       _draw_image_button(w, width, height,offset);
   }
}
References _draw_button_base(), _draw_image_button(), Widget_t::adj_y, Metrics_t::height, Widget_t::image, os_get_window_metrics(), Widget_t::state, Adjustment_t::value, Metrics_t::visible, and Metrics_t::width.
Referenced by add_image_toggle_button().
_pattern_in()
void _pattern_in (Widget_t * w, Color_state st, int height)
_pattern_in - a little pattern to make press state more visible
Parameters
*w - void pointer to the Widget_t button
st - the color state to use
height - the button height
Definition at line 46 of file xbutton_private.c.
{
    Colors *c = get_color_scheme(w,st);
    if (!c) return;
    cairo_pattern_t *pat = cairo_pattern_create_linear (2, 2, 2, height);
    cairo_pattern_add_color_stop_rgba(pat, 0.0, 0.0, 0.0, 0.0, 0.0);
    cairo_pattern_add_color_stop_rgba(pat, 0.5, c->light[0],  c->light[1], c->light[2],  c->light[3]);
    cairo_pattern_add_color_stop_rgba(pat, 1.0, 0.0, 0.0, 0.0, 0.0);
    cairo_set_source(w->crb, pat);
    cairo_pattern_destroy (pat);
}
References Widget_t::crb, get_color_scheme(), and Colors::light.
Referenced by _draw_button_base(), and _draw_combobox_button().
_pattern_out()
void _pattern_out (Widget_t * w, Color_state st, int height)
_pattern_in - a little pattern to make press state more visible
Parameters
*w - void pointer to the Widget_t button
st - the color state to use
height - the button height
Definition at line 35 of file xbutton_private.c.
{
    Colors *c = get_color_scheme(w,st);
    if (!c) return;
    cairo_pattern_t *pat = cairo_pattern_create_linear (2, 2, 2, height);
    cairo_pattern_add_color_stop_rgba(pat, 0.0, c->light[0],  c->light[1], c->light[2],  c->light[3]);
    cairo_pattern_add_color_stop_rgba(pat, 0.5, 0.0, 0.0, 0.0, 0.0);
    cairo_pattern_add_color_stop_rgba(pat, 1.0, c->light[0],  c->light[1], c->light[2],  c->light[3]);
    cairo_set_source(w->crb, pat);
    cairo_pattern_destroy (pat);
}
References Widget_t::crb, get_color_scheme(), and Colors::light.
Referenced by _draw_button_base(), and _draw_combobox_button().
_remove_low_dash()
int _remove_low_dash (char * str)
Definition at line 172 of file xbutton_private.c.
{
    char *src;
    char *dst;
    int i = 0;
    int r = 0;
    for (src = dst = str; *src != '\0'; src++) {
        *dst = *src;
        if (*dst != '_') {
            dst++;
        } else {
            r = i;
        }
        i++;
    }
    *dst = '\0';
    return r;
}
Referenced by _draw_base_button().
_rounded_rectangle()
void _rounded_rectangle (cairo_t * cr, float x, float y, float width, float height)
_rounded_rectangle - internal draw a rounded button
Parameters
*cr - the cairo_t context to draw to
x - point on x axis
y - point on y axis
width - the button width
height - the button height
Definition at line 25 of file xbutton_private.c.
{
    cairo_new_path (cr);
    cairo_move_to  (cr, x, (y + height)/2);
    cairo_curve_to (cr, x ,y, x, y, (x + width)/2, y);
    cairo_curve_to (cr, width, y, width, y, width, (y + height)/2);
    cairo_curve_to (cr, width, height, width, height, (width + x)/2, height);
    cairo_curve_to (cr, x, height, x, height, x, (y + height)/2);
    cairo_close_path (cr);
}
Referenced by _draw_button_base().
_toggle_button_pressed()
void _toggle_button_pressed (void * w_, void * button_, void * user_data)
_toggle_button_pressed - redraw the button and send state via user_callback
Parameters
*w_ - void pointer to the Widget_t button
*button_ - void pointer to XEvent.xbutton struct
*user_data - void pointer to attached user_data
Definition at line 437 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    expose_widget(w);
}
References expose_widget().
Referenced by add_check_box(), add_check_button(), add_image_toggle_button(), add_on_off_button(), add_switch_image_button(), and add_toggle_button().
_toggle_button_released()
void _toggle_button_released (void * w_, void * button_, void * user_data)
_toggle_button_released - redraw the button and send state via user_callback
Parameters
*w_ - void pointer to the Widget_t button
*button_ - void pointer to XEvent.xbutton struct
*user_data - void pointer to attached user_data
Definition at line 442 of file xbutton_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    XButtonEvent *xbutton = (XButtonEvent*)button_;
    if (w->flags & HAS_POINTER) {
        float value = w->adj->value;
        if (xbutton->button == Button1) value = value ?
                w->adj->min_value : w->adj->max_value;
        if (xbutton->button == Button4) value = w->adj->max_value;
        if (xbutton->button == Button5) value = w->adj->min_value;
        adj_set_value(w->adj, value);
        w->state = (int) w->adj->value ? 3 : 1;
    } else {
        w->state = (int) w->adj->value ? 3 : 0;
    }
    expose_widget(w);
}
References Widget_t::adj, adj_set_value(), XEvent::button, expose_widget(), Widget_t::flags, HAS_POINTER, Adjustment_t::max_value, Adjustment_t::min_value, Widget_t::state, and Adjustment_t::value.
Referenced by add_check_box(), add_check_button(), add_image_toggle_button(), add_on_off_button(), add_switch_image_button(), and add_toggle_button().