libxputty: xputty/header/xchildlist.h File Reference
xchildlist.h File Reference
Data Structures
struct Childlist_t
Childlist_t - struct to hold a Widget_t child list
Xputty main holds a list of any Widget_t created in relation to main
Any Event is only propagate to Widget_t's found in this list
Every Widget_t holds a list of Child Widget_t's they contain
When a Widget_t get destroy_widget() call, all of it's childs receive a destroy_widget() call before the Widget_t itself get destroyed
the expose_callback() (EXPOSE) and the configure_callback() (CONFIGURE) will be propagate to all childs in a Childlist_t.
Functions
void childlist_init (Childlist_t *childlist)
childlist_init - internal use to allocate the array to min size
You usually didn't need to call this
void childlist_destroy (Childlist_t *childlist)
childlist_destroy - internal use to free the Childlist_t
You usually didn't need to call this
void childlist_add_child (Childlist_t *childlist, Widget_t *child)
childlist_add_child - internal use to add a child to the Childlist_t
You usually didn't need to call this
void childlist_remove_child (Childlist_t *childlist, Widget_t *child)
childlist_remove_child - internal use to remove a child from the childlist
You usually didn't need to call this
int childlist_find_child (Childlist_t *childlist, Widget_t *child)
childlist_find_child - find a child in a the Childlist_t this could be sued to check if a Widget_t is a child of a other Widget_t
int childlist_find_widget (Childlist_t *childlist, Window child_window)
childlist_find_widget - find a child Widget_t in a the childlist by given the Window id
int childlist_has_child (Childlist_t *childlist)
childlist_has_child - check if a Widget_t Childlist_t contain a child
Function Documentation
childlist_add_child()
void childlist_add_child (Childlist_t * childlist, Widget_t * child)
childlist_add_child - internal use to add a child to the Childlist_t
You usually didn't need to call this
Parameters
*childlist - pointer to the Childlist_t
*child - pointer to the child to add
Returns
void
Definition at line 42 of file xchildlist.c.
{
    if(!childlist) childlist_init(childlist);
    if (childlist->cap < childlist->elem+2) {
         _childlist_add_elem(childlist);
     }
    childlist->childs[childlist->elem] = child;
    debug_print("Childlist_t  add_child\n");
    if (child->flags & IS_WINDOW) {
        os_register_wm_delete_window(child);
    }
    childlist->elem +=1;
}
References _childlist_add_elem(), Childlist_t::cap, childlist_init(), Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_WINDOW, and os_register_wm_delete_window().
Referenced by add_popup_spinbox(), create_combobox_menu(), create_menu(), create_tooltip(), create_widget(), create_window(), os_create_main_window_and_surface(), and os_create_widget_window_and_surface().
childlist_destroy()
void childlist_destroy (Childlist_t * childlist)
childlist_destroy - internal use to free the Childlist_t
You usually didn't need to call this
Parameters
*childlist - pointer to the Childlist_t
Returns
void
Definition at line 38 of file xchildlist.c.
{
    if(childlist) free(childlist->childs);
}
References Childlist_t::childs.
Referenced by destroy_widget(), and main_quit().
childlist_find_child()
int childlist_find_child (Childlist_t * childlist, Widget_t * child)
childlist_find_child - find a child in a the Childlist_t this could be sued to check if a Widget_t is a child of a other Widget_t
Parameters
*childlist - pointer to the Childlist_t
*child - pointer to the child to find
Returns
int - return position in childlist or -1 when not found
Definition at line 69 of file xchildlist.c.
{
    int i = 0;
    for(;i<childlist->elem;i++) {
        if(childlist->childs[i] == child) {
            return i;
        }
    }
    return -1;
}
References Childlist_t::childs, and Childlist_t::elem.
Referenced by childlist_remove_child(), and destroy_widget().
childlist_find_widget()
int childlist_find_widget (Childlist_t * childlist, Window child_window)
childlist_find_widget - find a child Widget_t in a the childlist by given the Window id
Parameters
*childlist - pointer to the Childlist_t
child_window - the Window to find the Widget_t for
Returns
int - return position in childlist or -1 when not found
Definition at line 79 of file xchildlist.c.
{
    int i = childlist->elem-1;
    for(;i>-1;i--) {
        if(childlist->childs[i]->widget == child_window) {
            return i;
        }
    }
    return -1;
}
References Childlist_t::childs, Childlist_t::elem, and Widget_t::widget.
Referenced by os_main_run(), os_run_embedded(), and WndProc().
childlist_has_child()
int childlist_has_child (Childlist_t * childlist)
childlist_has_child - check if a Widget_t Childlist_t contain a child
Parameters
*childlist - pointer to the Childlist_t
Returns
int - return element counter value 0 when Widget_t Childlist_t didn't contain a child
Definition at line 89 of file xchildlist.c.
{
    return childlist->elem;
}
References Childlist_t::elem.
Referenced by _button_press(), _check_grab(), _check_menu_state(), _configure_listbox(), _enter_submenu(), _leave_submenu(), _propagate_child_expose(), _reconfigure_listbox_viewport(), _resize_childs(), cmenu_add_submenu(), destroy_widget(), listbox_add_entry(), menu_add_item(), menu_add_numeric_items(), menu_add_submenu(), menu_add_value_entry(), os_main_run(), os_run_embedded(), os_widget_event_loop(), pop_combobox_menu_show(), pop_menu_show(), pop_submenu_show(), set_active_radio_entry(), and WndProc().
childlist_init()
void childlist_init (Childlist_t * childlist)
childlist_init - internal use to allocate the array to min size
You usually didn't need to call this
Parameters
*childlist - pointer to the Childlist_t
Returns
void
Definition at line 25 of file xchildlist.c.
{
    childlist->childs = (Widget_t**)malloc(sizeof(Widget_t*) * 4);
    assert(childlist->childs != NULL);
    memset(childlist->childs, 0, 4 * sizeof(Widget_t*));
    childlist->cap =4;
    childlist->size = sizeof(childlist);
    childlist->elem = 0;
    int i = 0;
    for(;i<childlist->cap;i++) {
        childlist->childs[i] = NULL;
    }
}
References Childlist_t::cap, Childlist_t::childs, Childlist_t::elem, and Childlist_t::size.
Referenced by childlist_add_child(), create_widget(), create_window(), and main_init().
childlist_remove_child()
void childlist_remove_child (Childlist_t * childlist, Widget_t * child)
childlist_remove_child - internal use to remove a child from the childlist
You usually didn't need to call this
Parameters
*childlist - pointer to the Childlist_t
*child - pointer to the child to remove
Returns
void
Definition at line 55 of file xchildlist.c.
{
    if (!childlist) return;
    int it = childlist_find_child(childlist, child);
    if(it >= 0){
        childlist->childs[it] = NULL;
        childlist->elem--;
        int i = it;
        for(;i<childlist->elem;i++) {
            childlist->childs[i] = childlist->childs[i+1];
        }
        childlist->childs[childlist->elem+1] = NULL;
    }
}
References childlist_find_child(), Childlist_t::childs, and Childlist_t::elem.
Referenced by destroy_widget().