libxputty: xputty/header/xcolor.h File Reference
xcolor.h File Reference
Data Structures
struct Colors
Color_t - struct used to set cairo color for Widget_t.
struct XColor_t
XColor_t - the Widget_t Color struct
XColor_t could be used for theming you Widget_t set.
struct SystrayColor_t
SystrayColor - the Systray Color struct
SystrayColor could be used for the backgroung color of the SystrayIcon.
Enumerations
enum Color_state {
NORMAL_ , PRELIGHT_ , SELECTED_ , ACTIVE_ ,
INSENSITIVE_
}
Color_state - select color mode to use on Widget_t.
enum Color_mod {
FORGROUND_ , BACKGROUND_ , BASE_ , TEXT_ ,
SHADOW_ , FRAME_ , LIGHT_
}
Color_set - select color set to use on draw.
Functions
void set_dark_theme (Xputty *main)
set_dark_theme - init the XColor_t struct to the default dark theme
void set_light_theme (Xputty *main)
set_light_theme - init the XColor_t struct to the default light theme
void color_scheme_to_childs (Widget_t *wid)
color_scheme_to_childs - copy a colorscheme to all childs light theme
void set_widget_color (Widget_t *w, Color_state st, Color_mod mod, double r, double g, double b, double a)
set_widget_color - set a individual Widget_t color
void widget_set_color (double *c, double r, double g, double b, double a)
widget_set_color - set a individual Widget_t color
Colors * get_color_scheme (Widget_t *wid, Color_state st)
get_color_scheme - get pointer to the Colors struct to use in relation to the Color_state
Color_state get_color_state (Widget_t *wid)
get_color_state - get the Color_state to use in relation to the Widget_t state
void use_fg_color_scheme (Widget_t *w, Color_state st)
use_fg_color_scheme - use forground Colors to paint on Widget_t
void use_bg_color_scheme (Widget_t *w, Color_state st)
use_bg_color_scheme - use background Colors to paint on Widget_t
void use_base_color_scheme (Widget_t *w, Color_state st)
use_base_color_scheme - use base Colors to paint on Widget_t
void use_text_color_scheme (Widget_t *w, Color_state st)
use_text_color_scheme - use text Colors to paint on Widget_t
void use_shadow_color_scheme (Widget_t *w, Color_state st)
use_shadow_color_scheme - use shadow Colors to paint on Widget_t
void use_frame_color_scheme (Widget_t *w, Color_state st)
use_frame_color_scheme - use frame Colors to paint on Widget_t
void use_light_color_scheme (Widget_t *w, Color_state st)
use_light_color_scheme - use light Colors to paint on Widget_t
void use_systray_color (Widget_t *w)
use_systray_color - use systray Colors to paint on Widget_t
void set_systray_color (Xputty *main, double r, double g, double b, double a)
set_systray_color - set the systray background color
void set_pattern (Widget_t *w, Colors *from, Colors *to, Color_mod mod)
set_pattern - set pattern for the selected Colors
Enumeration Type Documentation
Color_mod
enum Color_mod
Color_set - select color set to use on draw.
Enumerator
FORGROUND_
BACKGROUND_
BASE_
TEXT_
SHADOW_
FRAME_
LIGHT_
Definition at line 51 of file xcolor.h.
             {
    FORGROUND_,
    BACKGROUND_,
    BASE_,
    TEXT_,
    SHADOW_,
    FRAME_,
    LIGHT_,
} Color_mod;
Color_state
enum Color_state
Color_state - select color mode to use on Widget_t.
Enumerator
NORMAL_
PRELIGHT_
SELECTED_
ACTIVE_
INSENSITIVE_
Definition at line 38 of file xcolor.h.
             {
    NORMAL_,
    PRELIGHT_,
    SELECTED_,
    ACTIVE_,
    INSENSITIVE_,
} Color_state;
Function Documentation
color_scheme_to_childs()
void color_scheme_to_childs (Widget_t * wid)
color_scheme_to_childs - copy a colorscheme to all childs light theme
Parameters
*wid - pointer to the Widget_t take the colorscheme from
Definition at line 130 of file xcolor.c.
{
    int i=0;
    for(;i<wid->childlist->elem;i++) {
        Widget_t* w = wid->childlist->childs[i];
        memcpy(w->color_scheme, wid->color_scheme, sizeof (struct XColor_t));
        color_scheme_to_childs(w);
    }
}
References Widget_t::childlist, Childlist_t::childs, Widget_t::color_scheme, color_scheme_to_childs(), and Childlist_t::elem.
Referenced by color_scheme_to_childs().
get_color_scheme()
Colors * get_color_scheme (Widget_t * wid, Color_state st)
get_color_scheme - get pointer to the Colors struct to use in relation to the Color_state
Parameters
*st - the Color state to use
Definition at line 197 of file xcolor.c.
{
    switch(st) {
        case NORMAL_:
            return &wid->color_scheme->normal;
        break;
        case PRELIGHT_:
            return &wid->color_scheme->prelight;
        break;
        case SELECTED_:
            return &wid->color_scheme->selected;
        break;
        case ACTIVE_:
            return &wid->color_scheme->active;
        break;
        case INSENSITIVE_:
            return &wid->color_scheme->insensitive;
        break;
        default:
            return &wid->color_scheme->normal;
        break;
    }
    return NULL;
}
References XColor_t::active, ACTIVE_, Widget_t::color_scheme, XColor_t::insensitive, INSENSITIVE_, XColor_t::normal, NORMAL_, XColor_t::prelight, PRELIGHT_, XColor_t::selected, and SELECTED_.
Referenced by _create_playhead_image(), _pattern_hslider(), _pattern_in(), _pattern_out(), _pattern_vslider(), set_widget_color(), use_base_color_scheme(), use_bg_color_scheme(), use_fg_color_scheme(), use_frame_color_scheme(), use_light_color_scheme(), use_shadow_color_scheme(), and use_text_color_scheme().
get_color_state()
Color_state get_color_state (Widget_t * wid)
get_color_state - get the Color_state to use in relation to the Widget_t state
Parameters
*wid - pointer to the Widget_t
Returns
Color_state - the Color_state related to the Widget_t state
Examples
simple-example.c.
Definition at line 222 of file xcolor.c.
{
    switch(wid->state) {
        case 0:
            return NORMAL_;
        break;
        case 1:
            return PRELIGHT_;
        break;
        case 2:
            return SELECTED_;
        break;
        case 3:
            return ACTIVE_;
        break;
        case 4:
            return INSENSITIVE_;
        break;
        default:
            return NORMAL_;
        break;
    }
}
References ACTIVE_, INSENSITIVE_, NORMAL_, PRELIGHT_, SELECTED_, and Widget_t::state.
Referenced by _draw_accel_check_item(), _draw_accel_item(), _draw_base_button(), _draw_buttons(), _draw_check_box(), _draw_check_button(), _draw_check_item(), _draw_combobox(), _draw_combobox_button(), _draw_combobox_menu_slider(), _draw_frame(), _draw_hslider(), _draw_image(), _draw_image_button_with_label(), _draw_item(), _draw_knob(), _draw_label(), _draw_listbox_item(), _draw_listviewslider(), _draw_menu(), _draw_menu_label(), _draw_menu_slider(), _draw_multi_listviewslider(), _draw_on_off_button(), _draw_spinbox(), _draw_submenu(), _draw_tabbox(), _draw_tooltip(), _draw_value_item(), _draw_valuedisplay(), _draw_vslider(), _draw_waveview(), draw_hyperlink(), and mk_draw_knob().
set_dark_theme()
void set_dark_theme (Xputty * main)
set_dark_theme - init the XColor_t struct to the default dark theme
Parameters
*main - pointer to the main Xputty struct
Definition at line 24 of file xcolor.c.
{
    main->color_scheme->normal = (Colors) {
         /* cairo    / r  / g  / b  / a  /  */
        .fg =       { 0.85, 0.85, 0.85, 1.0},
        .bg =       { 0.1, 0.1, 0.1, 1.0},
        .base =     { 0.0, 0.0, 0.0, 1.0},
        .text =     { 0.9, 0.9, 0.9, 1.0},
        .shadow =   { 0.0, 0.0, 0.0, 0.2},
        .frame =    { 0.0, 0.0, 0.0, 1.0},
        .light =    { 0.1, 0.1, 0.1, 1.0}
    };
    main->color_scheme->prelight = (Colors) {
        .fg =       { 1.0, 0.0, 1.0, 1.0},
        .bg =       { 0.25, 0.25, 0.25, 1.0},
        .base =     { 0.3, 0.3, 0.3, 1.0},
        .text =     { 1.0, 1.0, 1.0, 1.0},
        .shadow =   { 0.1, 0.1, 0.1, 0.4},
        .frame =    { 0.3, 0.3, 0.3, 1.0},
        .light =    { 0.3, 0.3, 0.3, 1.0}
    };
    main->color_scheme->selected = (Colors) {
        .fg =       { 0.9, 0.9, 0.9, 1.0},
        .bg =       { 0.2, 0.2, 0.2, 1.0},
        .base =     { 0.5, 0.18, 0.18, 1.0},
        .text =     { 1.0, 1.0, 1.0, 1.0},
        .shadow =   { 0.8, 0.18, 0.18, 0.2},
        .frame =    { 0.5, 0.18, 0.18, 1.0},
        .light =    { 0.5, 0.18, 0.18, 1.0}
    };
    main->color_scheme->active = (Colors) {
        .fg =       { 0.0, 1.0, 1.0, 1.0},
        .bg =       { 0.0, 0.0, 0.0, 1.0},
        .base =     { 0.18, 0.38, 0.38, 1.0},
        .text =     { 0.75, 0.75, 0.75, 1.0},
        .shadow =   { 0.18, 0.38, 0.38, 0.5},
        .frame =    { 0.18, 0.38, 0.38, 1.0},
        .light =    { 0.18, 0.38, 0.38, 1.0}
    };
    main->color_scheme->insensitive = (Colors) {
        .fg =       { 0.85, 0.85, 0.85, 0.5},
        .bg =       { 0.1, 0.1, 0.1, 0.5},
        .base =     { 0.0, 0.0, 0.0, 0.5},
        .text =     { 0.9, 0.9, 0.9, 0.5},
        .shadow =   { 0.0, 0.0, 0.0, 0.1},
        .frame =    { 0.0, 0.0, 0.0, 0.5},
        .light =    { 0.1, 0.1, 0.1, 0.5}
    };
}
References XColor_t::active, Xputty::color_scheme, Colors::fg, XColor_t::insensitive, XColor_t::normal, XColor_t::prelight, and XColor_t::selected.
Referenced by main_init().
set_light_theme()
void set_light_theme (Xputty * main)
set_light_theme - init the XColor_t struct to the default light theme
Parameters
*main - pointer to the main Xputty struct
Definition at line 77 of file xcolor.c.
{
    main->color_scheme->normal = (Colors) {
         /* cairo    / r  / g  / b  / a  /  */
        .fg =       { 0.15, 0.15, 0.15, 1.0},
        .bg =       { 0.85, 0.85, 0.85, 1.0},
        .base =     { 0.9, 0.9, 0.9, 1.0},
        .text =     { 0.25, 0.25, 0.25, 1.0},
        .shadow =   { 0.0, 0.0, 0.0, 0.2},
        .frame =    { 0.2, 0.2, 0.2, 1.0},
        .light =    { 0.9, 0.9, 0.9, 1.0}
    };
    main->color_scheme->prelight = (Colors) {
        .fg =       { 0.25, 0.25, 0.25, 1.0},
        .bg =       { 1.0, 1.0, 1.0, 1.0},
        .base =     { 0.75, 0.75, 0.75, 1.0},
        .text =     { 0.15, 0.15, 0.15, 1.0},
        .shadow =   { 0.1, 0.1, 0.1, 0.4},
        .frame =    { 0.3, 0.3, 0.3, 1.0},
        .light =    { 0.75, 0.75, 0.75, 1.0}
    };
    main->color_scheme->selected = (Colors) {
        .fg =       { 0.2, 0.2, 0.2, 1.0},
        .bg =       { 0.9, 0.9, 0.9, 1.0},
        .base =     { 0.0, 0.5, 0.65, 1.0},
        .text =     { 0.8, 0.8, 0.8, 1.0},
        .shadow =   { 0.8, 0.18, 0.18, 0.2},
        .frame =    { 0.5, 0.18, 0.18, 1.0},
        .light =    { 0.5, 0.5, 0.5, 1.0}
    };
    main->color_scheme->active = (Colors) {
        .fg =       { 0.0, 0.0, 0.0, 1.0},
        .bg =       { 1.0, 1.0, 1.0, 1.0},
        .base =     { 0.0, 0.3, 0.65, 1.0},
        .text =     { 0.8, 0.8, 0.8, 1.0},
        .shadow =   { 0.18, 0.38, 0.38, 0.5},
        .frame =    { 0.18, 0.38, 0.38, 1.0},
        .light =    { 0.3, 0.3, 0.3, 1.0}
    };
    main->color_scheme->insensitive = (Colors) {
        .fg =       { 0.15, 0.15, 0.15, 0.5},
        .bg =       { 0.85, 0.85, 0.85, 0.5},
        .base =     { 0.9, 0.9, 0.9, 0.5},
        .text =     { 0.25, 0.25, 0.25, 0.5},
        .shadow =   { 0.0, 0.0, 0.0, 0.1},
        .frame =    { 0.2, 0.2, 0.2, 0.5},
        .light =    { 0.9, 0.9, 0.9, 0.5}
    };
}
References XColor_t::active, Xputty::color_scheme, Colors::fg, XColor_t::insensitive, XColor_t::normal, XColor_t::prelight, and XColor_t::selected.
set_pattern()
void set_pattern (Widget_t * w, Colors * from, Colors * to, Color_mod mod)
set_pattern - set pattern for the selected Colors
Parameters
*w_ - pointer to the Widget_t to set the pattern
*from - the Colors set to pattern from (0)
*to - the Colors set to pattern to (1)
mod - the Color_mod to use
Definition at line 308 of file xcolor.c.
{
    double *col_from = NULL;
    double *col_to = NULL;
    switch (mod) {
        case FORGROUND_:
            col_from = from->fg;
            col_to = to->fg;
        break;
        case BACKGROUND_:
            col_from = from->bg;
            col_to = to->bg;
        break;
        case BASE_:
            col_from = from->base;
            col_to = to->base;
        break;
        case TEXT_:
            col_from = from->text;
            col_to = to->text;
        break;
        case SHADOW_:
            col_from = from->shadow;
            col_to = to->shadow;
        break;
        case FRAME_:
            col_from = from->frame;
            col_to = to->frame;
        break;
        case LIGHT_:
            col_from = from->light;
            col_to = to->light;
        break;
   }
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    cairo_pattern_t *pat = cairo_pattern_create_linear (0, 0, width, height);
    cairo_pattern_add_color_stop_rgba(pat, 0.0, col_from[0], col_from[1], col_from[2], col_from[3]);
    cairo_pattern_add_color_stop_rgba(pat, 1.0, col_to[0], col_to[1], col_to[2], col_to[3]);
    cairo_set_source(w->crb, pat);
    cairo_set_source(w->cr, pat);
    cairo_pattern_destroy (pat);
}
References BACKGROUND_, Colors::base, BASE_, Colors::bg, Widget_t::cr, Widget_t::crb, Colors::fg, FORGROUND_, Colors::frame, FRAME_, Metrics_t::height, Colors::light, LIGHT_, os_get_window_metrics(), Colors::shadow, SHADOW_, Colors::text, TEXT_, and Metrics_t::width.
Referenced by _draw_combobox_menu(), _draw_listview(), and _draw_multi_listview().
set_systray_color()
void set_systray_color (Xputty * main, double r, double g, double b, double a)
set_systray_color - set the systray background color
Parameters
main - pointer to the main Xputty struct
r - the red Color to use
g - the green Color to use
b - the blue Color to use
a - the alpha Cannel to use
Definition at line 300 of file xcolor.c.
{
    SystrayColor_t *c = main->systray_color;
    c->r = r;
    c->g = g;
    c->b = b;
    c->a = a;
}
References SystrayColor_t::a, SystrayColor_t::b, SystrayColor_t::g, SystrayColor_t::r, and Xputty::systray_color.
Referenced by main_init(), and os_send_systray_message().
set_widget_color()
void set_widget_color (Widget_t * w, Color_state st, Color_mod mod, double r, double g, double b, double a)
set_widget_color - set a individual Widget_t color
Parameters
*w - the Widget_t the color belong to
st - the state the color belong to
*mod - the Color mod to set
r - the red color
g - the green color
b - the blue color
a - the alpha channel
Definition at line 146 of file xcolor.c.
{
    Colors *c = get_color_scheme(w, st);
    switch(mod) {
        case FORGROUND_:
           c->fg[0] = r;
           c->fg[1] = g;
           c->fg[2] = b;
           c->fg[3] = a;
        break;
        case BACKGROUND_:
           c->bg[0] = r;
           c->bg[1] = g;
           c->bg[2] = b;
           c->bg[3] = a;
        break;
        case BASE_:
           c->base[0] = r;
           c->base[1] = g;
           c->base[2] = b;
           c->base[3] = a;
        break;
        case TEXT_:
           c->text[0] = r;
           c->text[1] = g;
           c->text[2] = b;
           c->text[3] = a;
        break;
        case SHADOW_:
           c->shadow[0] = r;
           c->shadow[1] = g;
           c->shadow[2] = b;
           c->shadow[3] = a;
        break;
        case FRAME_:
           c->frame[0] = r;
           c->frame[1] = g;
           c->frame[2] = b;
           c->frame[3] = a;
        break;
        case LIGHT_:
           c->light[0] = r;
           c->light[1] = g;
           c->light[2] = b;
           c->light[3] = a;
        break;
        default:
        break;
    }
}
References BACKGROUND_, Colors::base, BASE_, Colors::bg, Colors::fg, FORGROUND_, Colors::frame, FRAME_, get_color_scheme(), Colors::light, LIGHT_, Colors::shadow, SHADOW_, Colors::text, and TEXT_.
use_base_color_scheme()
void use_base_color_scheme (Widget_t * w, Color_state st)
use_base_color_scheme - use base Colors to paint on Widget_t
Parameters
w - the Widget_t to set the Colors
st - the Color_state to use
Definition at line 259 of file xcolor.c.
{
    Colors *c = get_color_scheme(w, st);
    if (!c) return;
    cairo_set_source_rgba(w->cr, c->base[0],  c->base[1], c->base[2],  c->base[3]);
    cairo_set_source_rgba(w->crb, c->base[0],  c->base[1], c->base[2],  c->base[3]);
}
References Colors::base, Widget_t::cr, Widget_t::crb, and get_color_scheme().
Referenced by _draw_accel_item(), _draw_combobox_entrys(), _draw_image(), _draw_item(), _draw_list(), _draw_listbox_item(), _draw_listbox_viewslider(), _draw_multi_list(), _draw_submenu(), _draw_value_item(), _update_list_view(), and _update_view().
use_bg_color_scheme()
void use_bg_color_scheme (Widget_t * w, Color_state st)
use_bg_color_scheme - use background Colors to paint on Widget_t
Parameters
w - the Widget_t to set the Colors
st - the Color_state to use
Examples
simple-example.c.
Definition at line 252 of file xcolor.c.
{
    Colors *c = get_color_scheme(w, st);
    if (!c) return;
    cairo_set_source_rgba(w->cr, c->bg[0],  c->bg[1], c->bg[2],  c->bg[3]);
    cairo_set_source_rgba(w->crb, c->bg[0],  c->bg[1], c->bg[2],  c->bg[3]);
}
References Colors::bg, Widget_t::cr, Widget_t::crb, and get_color_scheme().
Referenced by _draw_buttons(), _draw_combobox_menu_slider(), _draw_hslider(), _draw_knob(), _draw_listbox(), _draw_listbox_viewslider(), _draw_listviewslider(), _draw_menu(), _draw_menu_slider(), _draw_multi_listviewslider(), _draw_spinbox(), _draw_tabbox(), _draw_tooltip(), _draw_tuner(), _draw_vslider(), and _draw_waveview().
use_fg_color_scheme()
void use_fg_color_scheme (Widget_t * w, Color_state st)
use_fg_color_scheme - use forground Colors to paint on Widget_t
Parameters
*w - the Widget_t to set the Colors
st - the Color_state to use
Definition at line 245 of file xcolor.c.
{
    Colors *c = get_color_scheme(w, st);
    if (!c) return;
    cairo_set_source_rgba(w->cr, c->fg[0],  c->fg[1], c->fg[2],  c->fg[3]);
    cairo_set_source_rgba(w->crb, c->fg[0],  c->fg[1], c->fg[2],  c->fg[3]);
}
References Widget_t::cr, Widget_t::crb, Colors::fg, and get_color_scheme().
Referenced by _draw_accel_check_item(), _draw_check_box(), _draw_check_button(), _draw_check_item(), _draw_combobox_button(), _draw_hslider(), _draw_image_button_with_label(), _draw_knob(), _draw_listbox_viewslider(), _draw_vslider(), _draw_waveview(), and draw_hyperlink().
use_frame_color_scheme()
void use_frame_color_scheme (Widget_t * w, Color_state st)
use_frame_color_scheme - use frame Colors to paint on Widget_t
Parameters
w - the Widget_t to set the Colors
st - the Color_state to use
Definition at line 280 of file xcolor.c.
{
    Colors *c = get_color_scheme(w, st);
    if (!c) return;
    cairo_set_source_rgba(w->cr, c->frame[0],  c->frame[1], c->frame[2],  c->frame[3]);
    cairo_set_source_rgba(w->crb, c->frame[0],  c->frame[1], c->frame[2],  c->frame[3]);
}
References Widget_t::cr, Widget_t::crb, Colors::frame, and get_color_scheme().
Referenced by _draw_accel_item(), _draw_button_base(), _draw_combobox(), _draw_combobox_button(), _draw_combobox_entrys(), _draw_combobox_menu_slider(), _draw_frame(), _draw_item(), _draw_list(), _draw_listbox_item(), _draw_submenu(), _draw_tabbox(), _draw_value_item(), _draw_valuedisplay(), _draw_waveview(), and _update_list_view().
use_light_color_scheme()
void use_light_color_scheme (Widget_t * w, Color_state st)
use_light_color_scheme - use light Colors to paint on Widget_t
Parameters
w - the Widget_t to set the Colors
st - the Color_state to use
Definition at line 287 of file xcolor.c.
{
    Colors *c = get_color_scheme(w, st);
    if (!c) return;
    cairo_set_source_rgba(w->cr, c->light[0],  c->light[1], c->light[2],  c->light[3]);
    cairo_set_source_rgba(w->crb, c->light[0],  c->light[1], c->light[2],  c->light[3]);
}
References Widget_t::cr, Widget_t::crb, get_color_scheme(), and Colors::light.
Referenced by _draw_waveview().
use_shadow_color_scheme()
void use_shadow_color_scheme (Widget_t * w, Color_state st)
use_shadow_color_scheme - use shadow Colors to paint on Widget_t
Parameters
w - the Widget_t to set the Colors
st - the Color_state to use
Definition at line 273 of file xcolor.c.
{
    Colors *c = get_color_scheme(w, st);
    if (!c) return;
    cairo_set_source_rgba(w->cr, c->shadow[0],  c->shadow[1], c->shadow[2],  c->shadow[3]);
    cairo_set_source_rgba(w->crb, c->shadow[0],  c->shadow[1], c->shadow[2],  c->shadow[3]);
}
References Widget_t::cr, Widget_t::crb, get_color_scheme(), and Colors::shadow.
Referenced by _create_horizontal_meter_image(), _create_vertical_meter_image(), _draw_accel_check_item(), _draw_check_item(), _draw_combobox(), _draw_combobox_menu_slider(), _draw_hslider(), _draw_knob(), _draw_listviewslider(), _draw_menu_slider(), _draw_multi_listviewslider(), _draw_valuedisplay(), and _draw_vslider().
use_systray_color()
void use_systray_color (Widget_t * w)
use_systray_color - use systray Colors to paint on Widget_t
Parameters
w - the Widget_t to set the Colors
Definition at line 294 of file xcolor.c.
{
    SystrayColor_t *c = w->app->systray_color;
    cairo_set_source_rgba(w->cr, c->r,  c->g, c->b,  c->a);
    cairo_set_source_rgba(w->crb, c->r,  c->g, c->b,  c->a);
}
References SystrayColor_t::a, Widget_t::app, SystrayColor_t::b, Widget_t::cr, Widget_t::crb, SystrayColor_t::g, SystrayColor_t::r, and Xputty::systray_color.
use_text_color_scheme()
void use_text_color_scheme (Widget_t * w, Color_state st)
use_text_color_scheme - use text Colors to paint on Widget_t
Parameters
w - the Widget_t to set the Colors
st - the Color_state to use
Definition at line 266 of file xcolor.c.
{
    Colors *c = get_color_scheme(w, st);
    if (!c) return;
    cairo_set_source_rgba(w->cr, c->text[0],  c->text[1], c->text[2],  c->text[3]);
    cairo_set_source_rgba(w->crb, c->text[0],  c->text[1], c->text[2],  c->text[3]);
}
References Widget_t::cr, Widget_t::crb, get_color_scheme(), and Colors::text.
Referenced by _draw_accel_item(), _draw_base_button(), _draw_buttons(), _draw_check_box(), _draw_combobox(), _draw_combobox_button(), _draw_combobox_entrys(), _draw_frame(), _draw_hslider(), _draw_image_button_with_label(), _draw_item(), _draw_knob(), _draw_label(), _draw_list(), _draw_listbox_item(), _draw_menu_label(), _draw_multi_list(), _draw_on_off_button(), _draw_spinbox(), _draw_submenu(), _draw_tabbox(), _draw_tooltip(), _draw_tuner(), _draw_value_item(), _draw_valuedisplay(), _draw_vslider(), _draw_waveview(), _update_list_view(), _update_view(), and mk_draw_knob().
widget_set_color()
void widget_set_color (double * c, double r, double g, double b, double a)
widget_set_color - set a individual Widget_t color
Parameters
*c - direct pointer to the color array
r - the red color
g - the green color
b - the blue color
a - the alpha channel
Definition at line 139 of file xcolor.c.
{
    c[0] = r;
    c[1] = g;
    c[2] = b;
    c[3] = a;
}