libxputty: xputty/widgets/xcombobox.c File Reference
xcombobox.c File Reference
Functions
void combobox_set_active_entry (Widget_t *w, int active)
combobox_set_active_entry - set the active combobox entry
void combobox_rename_entry (Widget_t *w, int active, const char *label)
combobox_rename_entry - rename a entry in the combobox
void combobox_mem_free (void *w_, void *user_data)
combobox_mem_free - release additional used memory when destroy the Widget_t
void combobox_set_menu_size (Widget_t *combobox, int v)
combobox_set_menu_size - set the number of entrys shown in the pop menu
void combobox_delete_entrys (Widget_t *combobox)
combobox_delete_entrys - free the list hold the combobox entrys
void pop_combobox_menu_show (Widget_t *parent, Widget_t *menu, bool above)
Widget_t * create_combobox_viewport (Widget_t *parent, int elem, int width, int height)
Widget_t * create_combobox_menu (Widget_t *parent, int height)
Widget_t * add_combobox (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_combobox - add a combobox
void combobox_add_entry (Widget_t *wid, const char *label)
combobox_add_entry - add a entry to the combobox
void combobox_add_numeric_entrys (Widget_t *wid, int imin, int imax)
combobox_add_numeric_items - add numeric items from imin to imax to wid
Function Documentation
add_combobox()
Widget_t * add_combobox (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_combobox - add a combobox
Parameters
*parent - pointer to the Widget_t request the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 152 of file xcombobox.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->scale.gravity = CENTER;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_ENUM);
    wid->adj = wid->adj_y;
    wid->func.adj_callback = _set_entry;
    wid->func.expose_callback = _draw_combobox;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_release_callback = _combobox_button_released;
    Widget_t* button = add_button(wid, "", width-20, 0, 20, height);
    button->func.expose_callback = _draw_combobox_button;
    button->func.button_release_callback = _button_combobox_released;
    Widget_t* menu = create_combobox_menu(wid, 25);
    menu->func.button_release_callback = _entry_released;
    return wid;
}
References _button_combobox_released(), _combobox_button_released(), _draw_combobox(), _draw_combobox_button(), _entry_released(), _set_entry(), add_adjustment(), add_button(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, Func_t::button_release_callback, CENTER, CL_ENUM, create_combobox_menu(), create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
Referenced by add_my_combobox(), mk_open_midi_keyboard(), open_directory_dialog(), open_file_dialog(), and save_file_dialog().
combobox_add_entry()
void combobox_add_entry (Widget_t * wid, const char * label)
combobox_add_entry - add a entry to the combobox
Parameters
*wid - pointer to the Widget_t combobox
*label - Label to show on the menu
Returns
void
Definition at line 175 of file xcombobox.c.
{
    Widget_t *menu = wid->childlist->childs[1];
    Widget_t* view_port =  menu->childlist->childs[0];
    ComboBox_t *comboboxlist = (ComboBox_t*)view_port->parent_struct;
    comboboxlist->list_size++;
    comboboxlist->list_names = (char **)realloc(comboboxlist->list_names,
      comboboxlist->list_size * sizeof(char *));
    asprintf(&comboboxlist->list_names[comboboxlist->list_size-1],"%s",label);
    assert(comboboxlist->list_names != NULL);
    float max_value = wid->adj->max_value+1.0;
    set_adjustment(wid->adj,0.0, max_value, 0.0, max_value,1.0, CL_ENUM);
}
References Widget_t::adj, asprintf(), Widget_t::childlist, Childlist_t::childs, CL_ENUM, ComboBox_t::list_names, ComboBox_t::list_size, Adjustment_t::max_value, Widget_t::parent_struct, and set_adjustment().
Referenced by add_my_combobox(), combobox_add_numeric_entrys(), mk_open_midi_keyboard(), open_file_dialog(), and save_file_dialog().
combobox_add_numeric_entrys()
void combobox_add_numeric_entrys (Widget_t * wid, int imin, int imax)
combobox_add_numeric_items - add numeric items from imin to imax to wid
Parameters
*wid - pointer to the Widget_t combobox
*imin - the low number of the numeric items
*imax - the high number of the numeric items
Returns
void
Definition at line 189 of file xcombobox.c.
{
    int i = imin;
    int o = imax+1;
    for (;i<o;i++) {
        char s[32];
        snprintf(s, 31, "%i",i);
        combobox_add_entry(wid, s);
    }
}
References combobox_add_entry().
combobox_delete_entrys()
void combobox_delete_entrys (Widget_t * combobox)
combobox_delete_entrys - free the list hold the combobox entrys
Parameters
*combobox - void pointer to the Widget_t combobox
Returns
void
Definition at line 67 of file xcombobox.c.
{
    Widget_t * menu = combobox->childlist->childs[1];
    Widget_t* view_port =  menu->childlist->childs[0];
    ComboBox_t *comboboxlist = (ComboBox_t*)view_port->parent_struct;
    unsigned int j = 0;
    for(; j<comboboxlist->list_size;j++) {
        free(comboboxlist->list_names[j]);
        comboboxlist->list_names[j] = NULL;
    }
    comboboxlist->list_size = 0;
    set_adjustment(combobox->adj,0.0, 0.0, 0.0, -1.0,1.0, CL_ENUM);
    set_adjustment(view_port->adj,0.0, 0.0, 0.0, -6.0,1.0, CL_ENUM);
    set_adjustment(comboboxlist->slider->adj,0.0, 0.0, 0.0, 1.0,0.0085, CL_VIEWPORTSLIDER);
}
References Widget_t::adj, Widget_t::childlist, Childlist_t::childs, CL_ENUM, CL_VIEWPORTSLIDER, ComboBox_t::list_names, ComboBox_t::list_size, Widget_t::parent_struct, set_adjustment(), and ComboBox_t::slider.
combobox_mem_free()
void combobox_mem_free (void * w_, void * user_data)
combobox_mem_free - release additional used memory when destroy the Widget_t
Parameters
*w_ - void pointer to the Widget_t
*user_data - void pointer to attached user_data
Returns
void
Definition at line 47 of file xcombobox.c.
{
    Widget_t *w = (Widget_t*)w_;
    ComboBox_t *comboboxlist = (ComboBox_t*)w->parent_struct;
    unsigned int j = 0;
    for(; j<comboboxlist->list_size;j++) {
        free(comboboxlist->list_names[j]);
        comboboxlist->list_names[j] = NULL;
    }
    free(comboboxlist->list_names);
    free(comboboxlist);
}
References ComboBox_t::list_names, ComboBox_t::list_size, and Widget_t::parent_struct.
Referenced by create_combobox_viewport().
combobox_rename_entry()
void combobox_rename_entry (Widget_t * wid, int active, const char * label)
combobox_rename_entry - rename a entry in the combobox
Parameters
*wid - pointer to the Widget_t combobox
active - the entry to rename (int)
*label - new Label to show on the menu
Returns
void
Definition at line 34 of file xcombobox.c.
{
    float value = (float)active;
    if ((value>w->adj->max_value) || (value<w->adj->min_value)) return;
    Widget_t * menu = w->childlist->childs[1];
    Widget_t* view_port =  menu->childlist->childs[0];
    ComboBox_t *comboboxlist = (ComboBox_t*)view_port->parent_struct;
    //fprintf(stderr,"%s %s\n", comboboxlist->list_names[active], label);
    free(comboboxlist->list_names[active]);
    comboboxlist->list_names[active] = NULL;
    asprintf(&comboboxlist->list_names[active],"%s",label);
    assert(comboboxlist->list_names != NULL);
}
References Widget_t::adj, asprintf(), Widget_t::childlist, Childlist_t::childs, ComboBox_t::list_names, Adjustment_t::max_value, Adjustment_t::min_value, and Widget_t::parent_struct.
combobox_set_active_entry()
void combobox_set_active_entry (Widget_t * w, int active)
combobox_set_active_entry - set the active combobox entry
Parameters
*w_ - void pointer to the Widget_t combobox
active - the active entry (int)
Returns
void
Definition at line 27 of file xcombobox.c.
{
    float value = (float)active;
    if (value>w->adj->max_value) value = w->adj->max_value;
    else if (value<w->adj->min_value) value = w->adj->min_value;
    adj_set_value(w->adj, value);
}
References Widget_t::adj, adj_set_value(), Adjustment_t::max_value, and Adjustment_t::min_value.
Referenced by add_my_combobox(), mk_open_midi_keyboard(), open_directory_dialog(), open_file_dialog(), and save_file_dialog().
combobox_set_menu_size()
void combobox_set_menu_size (Widget_t * combobox, int v)
combobox_set_menu_size - set the number of entrys shown in the pop menu
Parameters
*combobox - pointer to the Widget_t combobox
v - the max entry count (int)
Returns
void
Definition at line 59 of file xcombobox.c.
{
    Widget_t * menu = combobox->childlist->childs[1];
    Widget_t* view_port =  menu->childlist->childs[0];
    ComboBox_t *comboboxlist = (ComboBox_t*)view_port->parent_struct;
    comboboxlist->show_items = v;
    _configure_combobox_menu(combobox, menu, comboboxlist->show_items, true);
}
References _configure_combobox_menu(), Widget_t::childlist, Childlist_t::childs, Widget_t::parent_struct, and ComboBox_t::show_items.
create_combobox_menu()
Widget_t * create_combobox_menu (Widget_t * parent, int height)
Definition at line 123 of file xcombobox.c.
{
    int x1, y1;
    os_translate_coords( parent, parent->widget, os_get_root_window(parent->app, IS_WIDGET), 0, 0, &x1, &y1);
    Widget_t *wid = create_window(parent->app, os_get_root_window(parent->app, IS_WIDGET), x1, y1, 10, height);
    Widget_t *viewport = create_combobox_viewport(wid, 6, 10, 5*height);
    ComboBox_t *comboboxlist = (ComboBox_t*)viewport->parent_struct;
    comboboxlist->combobox = parent;
    os_set_window_attrb(wid);
    os_set_transient_for_hint(parent, wid);
    wid->func.expose_callback = _draw_combobox_menu;
    wid->flags |= IS_POPUP;
    wid->scale.gravity = NONE;
    childlist_add_child(parent->childlist, wid);
    comboboxlist->slider = add_vslider(wid, "", 0, 0, 10, height);
    comboboxlist->slider->func.expose_callback = _draw_combobox_menu_slider;
    set_adjustment(comboboxlist->slider->adj_y,0.0, 0.0, 0.0, 1.0,0.0085, CL_VIEWPORTSLIDER);
    comboboxlist->slider->adj = comboboxlist->slider->adj_y;
    comboboxlist->slider->func.value_changed_callback = _set_combobox_menu_viewport;
    comboboxlist->slider->scale.gravity = NORTHWEST;
    comboboxlist->slider->flags &= ~USE_TRANSPARENCY;
    comboboxlist->slider->flags |= NO_AUTOREPEAT | NO_PROPAGATE;
    comboboxlist->slider->parent_struct = viewport;
    return wid;
}
References _draw_combobox_menu(), _draw_combobox_menu_slider(), _set_combobox_menu_viewport(), add_vslider(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Widget_t::childlist, childlist_add_child(), CL_VIEWPORTSLIDER, ComboBox_t::combobox, create_combobox_viewport(), create_window(), Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, IS_POPUP, IS_WIDGET, NO_AUTOREPEAT, NO_PROPAGATE, NONE, NORTHWEST, os_get_root_window(), os_set_transient_for_hint(), os_set_window_attrb(), os_translate_coords(), Widget_t::parent_struct, Widget_t::scale, set_adjustment(), ComboBox_t::slider, Func_t::value_changed_callback, and Widget_t::widget.
Referenced by add_combobox().
create_combobox_viewport()
Widget_t * create_combobox_viewport (Widget_t * parent, int elem, int width, int height)
Definition at line 96 of file xcombobox.c.
{
    Widget_t *wid = create_widget(parent->app, parent, 0, 0, width, height);
    os_set_input_mask(wid);
    wid->scale.gravity = CENTER;
    ComboBox_t *comboboxlist;
    comboboxlist = (ComboBox_t*)malloc(sizeof(ComboBox_t));
    comboboxlist->show_items = elem;
    comboboxlist->prelight_item = 0;
    comboboxlist->active_item = 0;
    comboboxlist->list_names = NULL;
    comboboxlist->list_size = 0;
    wid->flags |= HAS_MEM;
    wid->parent_struct = comboboxlist;
    float max_value = -elem;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
    wid->adj = wid->adj_y;
    wid->func.adj_callback = _set_combobox_viewpoint;
    wid->func.motion_callback = _combobox_motion;
    wid->func.leave_callback = _leave_combobox;
    wid->func.button_release_callback = _combobox_entry_released;
    wid->func.key_press_callback = _combobox_key_pressed;
    wid->func.expose_callback = _draw_combobox_entrys;
    wid->func.configure_notify_callback = _reconfigure_combobox_viewport;
    wid->func.mem_free_callback = combobox_mem_free;
    return wid;
}
References _combobox_entry_released(), _combobox_key_pressed(), _combobox_motion(), _draw_combobox_entrys(), _leave_combobox(), _reconfigure_combobox_viewport(), _set_combobox_viewpoint(), ComboBox_t::active_item, add_adjustment(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, Func_t::button_release_callback, CENTER, CL_VIEWPORT, combobox_mem_free(), Func_t::configure_notify_callback, create_widget(), Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, Func_t::key_press_callback, Func_t::leave_callback, ComboBox_t::list_names, ComboBox_t::list_size, Func_t::mem_free_callback, Func_t::motion_callback, os_set_input_mask(), Widget_t::parent_struct, ComboBox_t::prelight_item, Widget_t::scale, and ComboBox_t::show_items.
Referenced by create_combobox_menu().
pop_combobox_menu_show()
void pop_combobox_menu_show (Widget_t * parent, Widget_t * menu, bool above)
Definition at line 82 of file xcombobox.c.
{
    if (!childlist_has_child(menu->childlist)) return;
    Widget_t* view_port =  menu->childlist->childs[0];
    ComboBox_t *comboboxlist = (ComboBox_t*)view_port->parent_struct;
    if (!comboboxlist->list_size) return;
    _configure_combobox_menu(parent, menu, comboboxlist->show_items, above);
    pop_widget_show_all(menu);
    int err = os_grab_pointer(menu);
    menu->app->hold_grab = menu;
    if (err) debug_print("Error grap pointer\n");
}
References _configure_combobox_menu(), Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Xputty::hold_grab, ComboBox_t::list_size, os_grab_pointer(), Widget_t::parent_struct, pop_widget_show_all(), and ComboBox_t::show_items.
Referenced by _button_combobox_released(), and _combobox_button_released().