libxputty: xputty/header/widgets/xcombobox_private.h File Reference
xcombobox_private.h File Reference
Functions
void _draw_combobox_button (void *w_, void *user_data)
_draw_combobox_button - internal draw the combobox button to the buffer
void _draw_combobox (void *w_, void *user_data)
_draw_combobox - internal draw the combobox to the buffer
void _draw_combobox_menu (void *w_, void *user_data)
_draw_combobox_menu - internal draw the combobox menu to the buffer
void _draw_combobox_entrys (void *w_, void *user_data)
_draw_combobox_entrys - internal draw the combobox entrys to the buffer
void _combobox_motion (void *w_, void *xmotion_, void *user_data)
_combobox_motion - mouse pointer move in viewport
void _combobox_key_pressed (void *w_, void *xkey_, void *user_data)
_combobox_key_released - viewport entry released key
void _combobox_entry_released (void *w_, void *button_, void *user_data)
_combobox_entry_released - viewport entry released mouse button
void _leave_combobox (void *w_, void *user_data)
_leave_combobox - mouse pointer leave the combobox
void _reconfigure_combobox_viewport (void *w_, void *user_data)
_reconfigure_combobox_viewport - set slider scale and step to match viewport entrys
void _set_combobox_viewpoint (void *w_, void *user_data)
_set_combobox_viewpoint - set the slider state from viewport position
void _draw_combobox_menu_slider (void *w_, void *user_data)
_draw_combobox_menu_slider - internal draw the combobox menu slider
void _set_combobox_menu_viewport (void *w_, void *user_data)
_set_combobox_menu_viewport - set the viewport position from slider state
void _combobox_button_released (void *w_, void *button_, void *user_data)
_combobox_button_released - popup menu on right click
void _button_combobox_released (void *w_, void *button_, void *user_data)
_button_combobox_released - popup the combobox menu
void _entry_released (void *w_, void *item_, void *user_data)
_entry_released - the combobox menu release func
void _set_entry (void *w_, void *user_data)
_set_entry - set the active combobox entry on adjustment change
void _configure_combobox_menu (Widget_t *parent, Widget_t *menu, int elem, bool above)
_configure_combobox_menu - set final size and position of menu to a Widget_t
Function Documentation
_button_combobox_released()
void _button_combobox_released (void * w_, void * button_, void * user_data)
_button_combobox_released - popup the combobox menu
Parameters
*w_ - void pointer to the Widget_t button
*button - void pointer to XEvent.xbutton struct
*user_data - void pointer to attached user_data
Returns
void
Definition at line 382 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    XButtonEvent *xbutton = (XButtonEvent*)button_;
    if (w->flags & HAS_POINTER && xbutton->button == Button1) {
        Widget_t *parent = (Widget_t*)w->parent;
        w->state=1;
        pop_combobox_menu_show(parent, parent->childlist->childs[1], true);
    }
    adj_set_value(w->adj, 0.0);
}
References Widget_t::adj, adj_set_value(), XEvent::button, Widget_t::childlist, Childlist_t::childs, Widget_t::flags, HAS_POINTER, Widget_t::parent, pop_combobox_menu_show(), and Widget_t::state.
Referenced by add_combobox().
_combobox_button_released()
void _combobox_button_released (void * w_, void * button_, void * user_data)
_combobox_button_released - popup menu on right click
Parameters
*w_ - void pointer to the Widget_t button
*button - void pointer to XEvent.xbutton struct
*user_data - void pointer to attached user_data
Returns
void
Definition at line 371 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (w->flags & HAS_POINTER){
        XButtonEvent *xbutton = (XButtonEvent*)button_;
        if (xbutton->button == Button3) {
            w->state=1;
            pop_combobox_menu_show(w, w->childlist->childs[1], true);
        }
    }
}
References XEvent::button, Widget_t::childlist, Childlist_t::childs, Widget_t::flags, HAS_POINTER, pop_combobox_menu_show(), and Widget_t::state.
Referenced by add_combobox().
_combobox_entry_released()
void _combobox_entry_released (void * w_, void * button_, void * user_data)
_combobox_entry_released - viewport entry released mouse button
Parameters
*w_ - void pointer to the Widget_t viewport
*button - void pointer to XEvent.xbutton struct
*user_data - void pointer to attached user_data
Returns
void
Definition at line 278 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (w->flags & HAS_POINTER) {
        ComboBox_t *comboboxlist = (ComboBox_t*)w->parent_struct;
        XButtonEvent *xbutton = (XButtonEvent*)button_;
        Metrics_t metrics;
        os_get_window_metrics(w, &metrics);
        int height = metrics.height-2;
        int _items = height/(height/25);
        int prelight_item = xbutton->y/_items  + (int)max(0,adj_get_value(w->adj));
        if(xbutton->button == Button4) {
            if(prelight_item != comboboxlist->prelight_item) {
                comboboxlist->prelight_item = prelight_item;
            }
        } else if (xbutton->button == Button5) {
            if(prelight_item != comboboxlist->prelight_item) {
                comboboxlist->prelight_item = prelight_item;
            }
        } else if(xbutton->button == Button1) {
            Widget_t* combobox = (Widget_t*) w->parent;
            comboboxlist->active_item = comboboxlist->prelight_item;
            adj_set_value(combobox->adj,comboboxlist->active_item);
            adj_set_value(comboboxlist->combobox->adj,comboboxlist->active_item +
                                        comboboxlist->combobox->adj->min_value);
            combobox->func.button_release_callback(combobox,NULL,NULL);
        }
    }
}
References ComboBox_t::active_item, Widget_t::adj, adj_get_value(), adj_set_value(), XEvent::button, Func_t::button_release_callback, ComboBox_t::combobox, Widget_t::flags, Widget_t::func, HAS_POINTER, Metrics_t::height, Adjustment_t::min_value, os_get_window_metrics(), Widget_t::parent, Widget_t::parent_struct, ComboBox_t::prelight_item, and XEvent::y.
Referenced by create_combobox_viewport().
_combobox_key_pressed()
void _combobox_key_pressed (void * w_, void * xkey_, void * user_data)
_combobox_key_released - viewport entry released key
Parameters
*w_ - void pointer to the Widget_t viewport
*xkey - void pointer to XEvent.xkey struct
*user_data - void pointer to attached user_data
Returns
void
Definition at line 255 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    XKeyEvent *xkey = (XKeyEvent*)xkey_;
    ComboBox_t *comboboxlist = (ComboBox_t*)w->parent_struct;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int height = metrics.height-2;
    int _items = height/(height/25);
    comboboxlist->prelight_item = xkey->y/_items  + (int)max(0,adj_get_value(w->adj));
    int nk = key_mapping(w->app->dpy, xkey);
    if (nk) {
        switch (nk) {
            case 3:
            case 4:
            case 5:
            case 6: comboboxlist->prelight_item = xkey->y/_items  + (int)max(0,adj_get_value(w->adj));
            break;
            default:
            break;
        }
    }
}
References Widget_t::adj, adj_get_value(), Widget_t::app, Xputty::dpy, Metrics_t::height, key_mapping(), os_get_window_metrics(), Widget_t::parent_struct, ComboBox_t::prelight_item, and XEvent::y.
Referenced by create_combobox_viewport().
_combobox_motion()
void _combobox_motion (void * w_, void * xmotion_, void * user_data)
_combobox_motion - mouse pointer move in viewport
Parameters
*w_ - void pointer to the Widget_t viewport
*xmotion - void pointer to XEvent.xmotion struct
*user_data - void pointer to attached user_data
Returns
void
Definition at line 240 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    ComboBox_t *comboboxlist = (ComboBox_t*)w->parent_struct;
    XMotionEvent *xmotion = (XMotionEvent*)xmotion_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int height = metrics.height-2;
    int _items = height/(height/25);
    int prelight_item = (xmotion->y/_items)  + (int)max(0,adj_get_value(w->adj));
    if(prelight_item != comboboxlist->prelight_item) {
        comboboxlist->prelight_item = prelight_item;
    }
    expose_widget(w);
}
References Widget_t::adj, adj_get_value(), expose_widget(), Metrics_t::height, os_get_window_metrics(), Widget_t::parent_struct, ComboBox_t::prelight_item, and XEvent::y.
Referenced by create_combobox_viewport().
_configure_combobox_menu()
void _configure_combobox_menu (Widget_t * parent, Widget_t * menu, int elem, bool above)
_configure_combobox_menu - set final size and position of menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
*menu - the menu to show
elem - how many entrys to show
above - show menu below (0) or beside (1) the combobox
Returns
void
Definition at line 415 of file xcombobox_private.c.
{
    Widget_t* view_port =  menu->childlist->childs[0];
    ComboBox_t *comboboxlist = (ComboBox_t*)view_port->parent_struct;
    Widget_t *slider =  menu->childlist->childs[1];
    if (!comboboxlist->list_size) return;
    int height = 25;
    int x1, y1;
    int posy = (above) ? parent->height : 0;
    os_translate_coords(parent, parent->widget, os_get_root_window(parent->app, IS_WIDGET), 0, posy, &x1, &y1);
    int item_width = 1.0;
    cairo_text_extents_t extents;
    int i = comboboxlist->list_size-1;
    float m = view_port->adj->min_value;
    set_adjustment(view_port->adj,0.0, view_port->adj->value, m, i-(elem-1)+m,1.0, CL_VIEWPORT);
    bool is_not_scrolable = false;
    if(comboboxlist->list_size <= elem) {
        elem = comboboxlist->list_size;
        is_not_scrolable = true;
    }
    cairo_set_font_size (view_port->crb, height/2);
    for(;i>-1;i--) {
        cairo_text_extents(view_port->crb,comboboxlist->list_names[i] , &extents);
        item_width = max(item_width, (int)extents.width+40);
        if(is_not_scrolable) view_port->scale.gravity = NORTHEAST;
    }
    if(above) {
        if(item_width<parent->width)item_width = parent->width;
    }
    int screen_height = os_get_screen_height(parent);
    if (y1+(height*elem) > screen_height) y1 = y1-((height*elem)+parent->height);
    os_resize_window (menu->app->dpy, menu, item_width, height*elem);
    os_resize_window (view_port->app->dpy, view_port, item_width, height*elem);
    os_move_window(menu->app->dpy,slider,item_width-15, 0);
    os_resize_window(menu->app->dpy,slider,15,height*elem);
    os_move_window(menu->app->dpy,menu,x1, y1);
}
References Widget_t::adj, Widget_t::app, Widget_t::childlist, Childlist_t::childs, CL_VIEWPORT, Widget_t::crb, Xputty::dpy, Resize_t::gravity, Widget_t::height, IS_WIDGET, ComboBox_t::list_names, ComboBox_t::list_size, Adjustment_t::min_value, NORTHEAST, os_get_root_window(), os_get_screen_height(), os_move_window(), os_resize_window(), os_translate_coords(), Widget_t::parent_struct, Widget_t::scale, set_adjustment(), Adjustment_t::value, Widget_t::widget, and Widget_t::width.
Referenced by combobox_set_menu_size(), and pop_combobox_menu_show().
_draw_combobox()
void _draw_combobox (void * w_, void * user_data)
_draw_combobox - internal draw the combobox to the buffer
Parameters
*w_ - void pointer to the Widget_t combobox
*user_data - void pointer to attached user_data
Returns
void
Definition at line 100 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    int v = (int)adj_get_value(w->adj);
    int vl = v - (int) w->adj->min_value;
   // if (v<0) return;
    Widget_t * menu = w->childlist->childs[1];
    Widget_t* view_port =  menu->childlist->childs[0];
    ComboBox_t *comboboxlist = (ComboBox_t*)view_port->parent_struct;
    cairo_rectangle(w->crb,2.0, 2.0, width, height);
    if(w->state==0) {
        cairo_set_line_width(w->crb, 1.0);
        use_shadow_color_scheme(w, NORMAL_);
        cairo_fill_preserve(w->crb);
        use_frame_color_scheme(w, NORMAL_);
    } else if(w->state==1) {
        use_shadow_color_scheme(w, PRELIGHT_);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.5);
        use_frame_color_scheme(w, NORMAL_);
    } else if(w->state==2) {
        use_shadow_color_scheme(w, SELECTED_);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, SELECTED_);
    } else if(w->state==3) {
        use_shadow_color_scheme(w, ACTIVE_);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, ACTIVE_);
    } else if(w->state==4) {
        use_shadow_color_scheme(w, INSENSITIVE_);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, INSENSITIVE_);
    }
    cairo_stroke(w->crb);
    cairo_rectangle(w->crb,4.0, 4.0, width, height);
    cairo_stroke(w->crb);
    cairo_rectangle(w->crb,3.0, 3.0, width, height);
    cairo_stroke(w->crb);
    if (comboboxlist->list_size<1) return;
    if (vl<0) return;
    cairo_text_extents_t extents;
    use_text_color_scheme(w, get_color_state(w));
    float font_size = w->app->normal_font/w->scale.ascale;
    cairo_set_font_size (w->crb, font_size);
    cairo_text_extents(w->crb,"Ay", &extents);
    double h = extents.height;
    cairo_move_to (w->crb, 15, (height+h)*0.55);
    cairo_show_text(w->crb, comboboxlist->list_names[vl]);
    cairo_new_path (w->crb);
    if (extents.width > (float)width-20) {
        tooltip_set_text(w,comboboxlist->list_names[vl]);
        w->flags |= HAS_TOOLTIP;
    } else {
        w->flags &= ~HAS_TOOLTIP;
    }
}
References ACTIVE_, Widget_t::adj, adj_get_value(), Widget_t::app, Resize_t::ascale, Widget_t::childlist, Childlist_t::childs, Widget_t::crb, Widget_t::flags, get_color_state(), HAS_TOOLTIP, Metrics_t::height, INSENSITIVE_, ComboBox_t::list_names, ComboBox_t::list_size, Adjustment_t::min_value, NORMAL_, Xputty::normal_font, os_get_window_metrics(), Widget_t::parent_struct, PRELIGHT_, Widget_t::scale, SELECTED_, Widget_t::state, tooltip_set_text(), use_frame_color_scheme(), use_shadow_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by add_combobox().
_draw_combobox_button()
void _draw_combobox_button (void * w_, void * user_data)
_draw_combobox_button - internal draw the combobox button to the buffer
Parameters
*w_ - void pointer to the Widget_t combobox button
*user_data - void pointer to attached user_data
Returns
void
Definition at line 26 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    if (!w->state && (int)w->adj_y->value)
        w->state = 3;
    cairo_rectangle(w->crb,2.0, 4.0, width, height);
    if(w->state==0) {
        cairo_set_line_width(w->crb, 1.0);
        _pattern_out(w, NORMAL_, height);
        cairo_fill_preserve(w->crb);
        use_frame_color_scheme(w, PRELIGHT_);
    } else if(w->state==1) {
        _pattern_out(w, PRELIGHT_, height);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.5);
        use_frame_color_scheme(w, PRELIGHT_);
    } else if(w->state==2) {
        _pattern_in(w, SELECTED_, height);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, PRELIGHT_);
    } else if(w->state==3) {
        _pattern_in(w, ACTIVE_, height);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, PRELIGHT_);
    }
    cairo_stroke(w->crb);
    if(w->state==2) {
        cairo_rectangle(w->crb,4.0, 6.0, width, height);
        cairo_stroke(w->crb);
        cairo_rectangle(w->crb,3.0, 4.0, width, height);
        cairo_stroke(w->crb);
    } else if (w->state==3) {
        cairo_rectangle(w->crb,3.0, 4.0, width, height);
        cairo_stroke(w->crb);
    }
    float offset = 0.0;
    if(w->state==0) {
        use_fg_color_scheme(w, NORMAL_);
    } else if(w->state==1) {
        use_fg_color_scheme(w, PRELIGHT_);
        offset = 1.0;
    } else if(w->state==2) {
        use_fg_color_scheme(w, SELECTED_);
        offset = 2.0;
    } else if(w->state==3) {
        use_fg_color_scheme(w, ACTIVE_);
        offset = 1.0;
    }
    use_text_color_scheme(w, get_color_state(w));
    int wa = width/1.1;
    int h = height/2.2;
    int wa1 = width/1.55;
    int h1 = height/1.3;
    int wa2 = width/2.8;
    cairo_move_to(w->crb, wa+offset, h+offset);
    cairo_line_to(w->crb, wa1+offset, h1+offset);
    cairo_line_to(w->crb, wa2+offset, h+offset);
    cairo_line_to(w->crb, wa+offset, h+offset);
    cairo_fill(w->crb);
}
References _pattern_in(), _pattern_out(), ACTIVE_, Widget_t::adj_y, Widget_t::crb, get_color_state(), Metrics_t::height, NORMAL_, os_get_window_metrics(), PRELIGHT_, SELECTED_, Widget_t::state, use_fg_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), Adjustment_t::value, Metrics_t::visible, and Metrics_t::width.
Referenced by add_combobox().
_draw_combobox_entrys()
void _draw_combobox_entrys (void * w_, void * user_data)
_draw_combobox_entrys - internal draw the combobox entrys to the buffer
Parameters
*w_ - void pointer to the Widget_t combobox
*user_data - void pointer to attached user_data
Returns
void
show label
Definition at line 178 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    ComboBox_t *comboboxlist = (ComboBox_t*)w->parent_struct;
    use_base_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, 0, 0, width, height);
    cairo_fill (w->crb);
    int i = (int)max(0,adj_get_value(w->adj));
    int a = 0;
    int j = comboboxlist->list_size<comboboxlist->show_items+i+1 ?
      comboboxlist->list_size : comboboxlist->show_items+i+1;
    for(;i<j;i++) {
        if(i == comboboxlist->prelight_item && i == comboboxlist->active_item)
            use_base_color_scheme(w, ACTIVE_);
        else if(i == comboboxlist->prelight_item)
            use_base_color_scheme(w, PRELIGHT_);
        else if (i == comboboxlist->active_item)
            use_base_color_scheme(w, SELECTED_);
        else
            use_base_color_scheme(w,NORMAL_ );
        cairo_rectangle(w->crb, 0, a*25, width, 25);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, PRELIGHT_);
        cairo_stroke(w->crb);
        cairo_text_extents_t extents;
        if(i == comboboxlist->prelight_item && i == comboboxlist->active_item)
            use_text_color_scheme(w, ACTIVE_);
        else if(i == comboboxlist->prelight_item)
            use_text_color_scheme(w, PRELIGHT_);
        else if (i == comboboxlist->active_item)
            use_text_color_scheme(w, SELECTED_);
        else
            use_text_color_scheme(w,NORMAL_ );
        cairo_set_font_size (w->crb, 12);
        cairo_text_extents(w->crb,"Ay", &extents);
        double h = extents.height;
        cairo_text_extents(w->crb,comboboxlist->list_names[i] , &extents);
        cairo_move_to (w->crb, 15, (25*(a+1)) - h +2);
        cairo_show_text(w->crb, comboboxlist->list_names[i]);
        cairo_new_path (w->crb);
        if (i == comboboxlist->prelight_item && extents.width > (float)width-20) {
            tooltip_set_text(w,comboboxlist->list_names[i]);
            w->flags |= HAS_TOOLTIP;
            show_tooltip(w);
        } else if (i == comboboxlist->prelight_item && extents.width < (float)width-20) {
            w->flags &= ~HAS_TOOLTIP;
            hide_tooltip(w);
        }
        a++;
    }
}
References ACTIVE_, ComboBox_t::active_item, Widget_t::adj, adj_get_value(), Widget_t::crb, Widget_t::flags, HAS_TOOLTIP, Metrics_t::height, hide_tooltip(), ComboBox_t::list_names, ComboBox_t::list_size, NORMAL_, os_get_window_metrics(), Widget_t::parent_struct, PRELIGHT_, ComboBox_t::prelight_item, SELECTED_, ComboBox_t::show_items, show_tooltip(), tooltip_set_text(), use_base_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by create_combobox_viewport().
_draw_combobox_menu()
void _draw_combobox_menu (void * w_, void * user_data)
_draw_combobox_menu - internal draw the combobox menu to the buffer
Parameters
*w_ - void pointer to the Widget_t combobox
*user_data - void pointer to attached user_data
Returns
void
Definition at line 171 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    set_pattern(w,&w->color_scheme->normal,&w->color_scheme->active,BACKGROUND_);
    cairo_paint (w->cr);
}
References XColor_t::active, BACKGROUND_, Widget_t::color_scheme, Widget_t::cr, XColor_t::normal, and set_pattern().
Referenced by create_combobox_menu().
_draw_combobox_menu_slider()
void _draw_combobox_menu_slider (void * w_, void * user_data)
_draw_combobox_menu_slider - internal draw the combobox menu slider
Parameters
*w_ - void pointer to the Widget_t combobox
*user_data - void pointer to attached user_data
Returns
void
Definition at line 337 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t* view_port = (Widget_t*)w->parent_struct;
    ComboBox_t *comboboxlist = (ComboBox_t*)view_port->parent_struct;
    int v = (int)w->adj->max_value;
    if (!v) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    int show_items = height/25;
    float slidersize = 1.0;
    if (comboboxlist->list_size > show_items)
        slidersize = (float)((float)show_items/(float)comboboxlist->list_size);
    float sliderstate = adj_get_state(w->adj);
    use_frame_color_scheme(w, PRELIGHT_);
    cairo_rectangle(w->crb, 0,0,width,height);
    cairo_fill_preserve(w->crb);
    use_shadow_color_scheme(w, get_color_state(w));
    cairo_fill(w->crb);
    use_bg_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, 0,((float)height-
        ((float)height*slidersize))*sliderstate,width,((float)height*slidersize));
    cairo_fill(w->crb);
}
References Widget_t::adj, adj_get_state(), Widget_t::crb, get_color_state(), Metrics_t::height, ComboBox_t::list_size, Adjustment_t::max_value, NORMAL_, os_get_window_metrics(), Widget_t::parent_struct, PRELIGHT_, use_bg_color_scheme(), use_frame_color_scheme(), use_shadow_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by create_combobox_menu().
_entry_released()
void _entry_released (void * w_, void * item_, void * user_data)
_entry_released - the combobox menu release func
Parameters
*w_ - void pointer to the Widget_t menu
*item - void pointer to the selected item *(int*)
*user_data - void pointer to the item label *(const char**)
Returns
void
Definition at line 393 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t* view_port =  w->childlist->childs[0];
    ComboBox_t *comboboxlist = (ComboBox_t*)view_port->parent_struct;
    _set_entry(comboboxlist->combobox, NULL);
}
References _set_entry(), Widget_t::childlist, Childlist_t::childs, ComboBox_t::combobox, and Widget_t::parent_struct.
Referenced by add_combobox().
_leave_combobox()
void _leave_combobox (void * w_, void * user_data)
_leave_combobox - mouse pointer leave the combobox
Parameters
*w_ - void pointer to the Widget_t combobox
*user_data - void pointer to attached user_data
Returns
void
Definition at line 307 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    ComboBox_t *comboboxlist = (ComboBox_t*)w->parent_struct;
    comboboxlist->prelight_item = -1;
    expose_widget(w);
}
References expose_widget(), Widget_t::parent_struct, and ComboBox_t::prelight_item.
Referenced by create_combobox_viewport().
_reconfigure_combobox_viewport()
void _reconfigure_combobox_viewport (void * w_, void * user_data)
_reconfigure_combobox_viewport - set slider scale and step to match viewport entrys
Parameters
*w_ - void pointer to the Widget_t combobox
*user_data - void pointer to attached user_data
Returns
void
Definition at line 314 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    float st = adj_get_state(w->adj);
    Widget_t* combobox = (Widget_t*) w->parent;
    ComboBox_t *comboboxlist = (ComboBox_t*)w->parent_struct;
    Metrics_t metrics;
    os_get_window_metrics(combobox, &metrics);
    int height = metrics.height;
    comboboxlist->show_items = height/25;
    set_adjustment(comboboxlist->slider->adj,0.0, 0.0, 0.0,
        (float)(comboboxlist->list_size-(comboboxlist->show_items-1)),1.0, CL_VIEWPORTSLIDER);
    adj_set_scale(comboboxlist->slider->adj,
        ((float)(comboboxlist->list_size)/(float)comboboxlist->show_items)/25.0);
    adj_set_state(w->adj,st);
}
References Widget_t::adj, adj_get_state(), adj_set_scale(), adj_set_state(), CL_VIEWPORTSLIDER, Metrics_t::height, ComboBox_t::list_size, os_get_window_metrics(), Widget_t::parent, Widget_t::parent_struct, set_adjustment(), ComboBox_t::show_items, and ComboBox_t::slider.
Referenced by create_combobox_viewport().
_set_combobox_menu_viewport()
void _set_combobox_menu_viewport (void * w_, void * user_data)
_set_combobox_menu_viewport - set the viewport position from slider state
Parameters
*w_ - void pointer to the Widget_t combobox
*user_data - void pointer to attached user_data
Returns
void
Definition at line 364 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t *viewport = (Widget_t*)w->parent_struct;
    adj_set_state(viewport->adj, adj_get_state(w->adj));
    expose_widget(w);
}
References Widget_t::adj, adj_get_state(), adj_set_state(), expose_widget(), and Widget_t::parent_struct.
Referenced by create_combobox_menu().
_set_combobox_viewpoint()
void _set_combobox_viewpoint (void * w_, void * user_data)
_set_combobox_viewpoint - set the slider state from viewport position
Parameters
*w_ - void pointer to the Widget_t combobox
*user_data - void pointer to attached user_data
Returns
void
Definition at line 330 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    ComboBox_t *comboboxlist = (ComboBox_t*)w->parent_struct;
    adj_set_state(comboboxlist->slider->adj,adj_get_state(w->adj));
    expose_widget(w);
}
References Widget_t::adj, adj_get_state(), adj_set_state(), expose_widget(), Widget_t::parent_struct, and ComboBox_t::slider.
Referenced by create_combobox_viewport().
_set_entry()
void _set_entry (void * w_, void * user_data)
_set_entry - set the active combobox entry on adjustment change
Parameters
*w_ - void pointer to the Widget_t combobox
*user_data - void pointer to the item label *(const char**)
Returns
void
Definition at line 400 of file xcombobox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    int v = (int)adj_get_value(w->adj)-w->adj->min_value;
    Widget_t * menu = w->childlist->childs[1];
    Widget_t* view_port =  menu->childlist->childs[0];
    ComboBox_t *comboboxlist = (ComboBox_t*)view_port->parent_struct;
    if(v>=0 && comboboxlist->list_size) {
        w->label = comboboxlist->list_names[v];
        comboboxlist->active_item = v;
        adj_set_value(w->adj,comboboxlist->active_item + w->adj->min_value);
        adj_set_state(comboboxlist->slider->adj,adj_get_state(w->adj));
        os_transparent_draw(w, user_data);
    }
}
References ComboBox_t::active_item, Widget_t::adj, adj_get_state(), adj_get_value(), adj_set_state(), adj_set_value(), Widget_t::childlist, Childlist_t::childs, Widget_t::label, ComboBox_t::list_names, ComboBox_t::list_size, Adjustment_t::min_value, os_transparent_draw(), Widget_t::parent_struct, and ComboBox_t::slider.
Referenced by _entry_released(), and add_combobox().