libxputty: xputty/xdgmime/xdgmimealias.c File Reference
xdgmimealias.c File Reference
Data Structures
struct XdgAlias
struct XdgAliasList
Typedefs
typedef struct XdgAlias XdgAlias
Functions
XdgAliasList * _xdg_mime_alias_list_new (void)
void _xdg_mime_alias_list_free (XdgAliasList *list)
const char * _xdg_mime_alias_list_lookup (XdgAliasList *list, const char *alias)
void _xdg_mime_alias_read_from_file (XdgAliasList *list, const char *file_name)
void _xdg_mime_alias_list_dump (XdgAliasList *list)
Typedef Documentation
XdgAlias
typedef struct XdgAlias XdgAlias
Definition at line 48 of file xdgmimealias.c.
Function Documentation
_xdg_mime_alias_list_dump()
void _xdg_mime_alias_list_dump (XdgAliasList * list)
Definition at line 169 of file xdgmimealias.c.
{
  int i;
  if (list->aliases)
    {
      for (i = 0; i < list->n_aliases; i++)
    {
      printf ("%s %s\n",
          list->aliases[i].alias,
          list->aliases[i].mime_type);
    }
    }
}
References XdgAlias::alias, XdgAliasList::aliases, XdgAlias::mime_type, and XdgAliasList::n_aliases.
Referenced by xdg_mime_dump().
_xdg_mime_alias_list_free()
void _xdg_mime_alias_list_free (XdgAliasList * list)
Definition at line 76 of file xdgmimealias.c.
{
  int i;
  if (list->aliases)
    {
      for (i = 0; i < list->n_aliases; i++)
    {
      free (list->aliases[i].alias);
      free (list->aliases[i].mime_type);
    }
      free (list->aliases);
    }
  free (list);
}
References XdgAlias::alias, XdgAliasList::aliases, XdgAlias::mime_type, and XdgAliasList::n_aliases.
Referenced by xdg_mime_shutdown().
_xdg_mime_alias_list_lookup()
const char * _xdg_mime_alias_list_lookup (XdgAliasList * list, const char * alias)
Definition at line 99 of file xdgmimealias.c.
{
  XdgAlias *entry;
  XdgAlias key;
  if (list->n_aliases > 0)
    {
      key.alias = (char *)alias;
      key.mime_type = NULL;
      entry = bsearch (&key, list->aliases, list->n_aliases,
               sizeof (XdgAlias), alias_entry_cmp);
      if (entry)
        return entry->mime_type;
    }
  return NULL;
}
References XdgAlias::alias, XdgAliasList::aliases, XdgAlias::mime_type, and XdgAliasList::n_aliases.
Referenced by _xdg_mime_unalias_mime_type().
_xdg_mime_alias_list_new()
XdgAliasList * _xdg_mime_alias_list_new (void)
Definition at line 63 of file xdgmimealias.c.
{
  XdgAliasList *list;
  list = malloc (sizeof (XdgAliasList));
  list->aliases = NULL;
  list->n_aliases = 0;
  return list;
}
References XdgAliasList::aliases, and XdgAliasList::n_aliases.
_xdg_mime_alias_read_from_file()
void _xdg_mime_alias_read_from_file (XdgAliasList * list, const char * file_name)
Definition at line 120 of file xdgmimealias.c.
{
  FILE *file;
  char line[255];
  int alloc;
  file = fopen (file_name, "r");
  if (file == NULL)
    return;
  /* FIXME: Not UTF-8 safe.  Doesn't work if lines are greater than 255 chars.
   * Blah */
  alloc = list->n_aliases + 16;
  list->aliases = realloc (list->aliases, alloc * sizeof (XdgAlias));
  while (fgets (line, 255, file) != NULL)
    {
      char *sep;
      if (line[0] == '#')
    continue;
      sep = strchr (line, ' ');
      if (sep == NULL)
    continue;
      *(sep++) = '\000';
      sep[strlen (sep) -1] = '\000';
      if (list->n_aliases == alloc)
    {
      alloc <<= 1;
      list->aliases = realloc (list->aliases,
                   alloc * sizeof (XdgAlias));
    }
      list->aliases[list->n_aliases].alias = strdup (line);
      list->aliases[list->n_aliases].mime_type = strdup (sep);
      list->n_aliases++;
    }
  list->aliases = realloc (list->aliases,
               list->n_aliases * sizeof (XdgAlias));
  fclose (file);
  if (list->n_aliases > 1)
    qsort (list->aliases, list->n_aliases,
           sizeof (XdgAlias), alias_entry_cmp);
}
References XdgAlias::alias, XdgAliasList::aliases, XdgAlias::mime_type, and XdgAliasList::n_aliases.