libxputty: xputty/xdgmime/xdgmimeicon.c File Reference
xdgmimeicon.c File Reference
Data Structures
struct XdgIcon
struct XdgIconList
Typedefs
typedef struct XdgIcon XdgIcon
Functions
XdgIconList * _xdg_mime_icon_list_new (void)
void _xdg_mime_icon_list_free (XdgIconList *list)
const char * _xdg_mime_icon_list_lookup (XdgIconList *list, const char *mime_type)
void _xdg_mime_icon_read_from_file (XdgIconList *list, const char *file_name)
void _xdg_mime_icon_list_dump (XdgIconList *list)
Typedef Documentation
XdgIcon
typedef struct XdgIcon XdgIcon
Definition at line 47 of file xdgmimeicon.c.
Function Documentation
_xdg_mime_icon_list_dump()
void _xdg_mime_icon_list_dump (XdgIconList * list)
Definition at line 168 of file xdgmimeicon.c.
{
  int i;
  if (list->icons)
    {
      for (i = 0; i < list->n_icons; i++)
    {
      printf ("%s %s\n",
          list->icons[i].mime_type,
          list->icons[i].icon_name);
    }
    }
}
References XdgIcon::icon_name, XdgIconList::icons, XdgIcon::mime_type, and XdgIconList::n_icons.
_xdg_mime_icon_list_free()
void _xdg_mime_icon_list_free (XdgIconList * list)
Definition at line 75 of file xdgmimeicon.c.
{
  int i;
  if (list->icons)
    {
      for (i = 0; i < list->n_icons; i++)
    {
      free (list->icons[i].mime_type);
      free (list->icons[i].icon_name);
    }
      free (list->icons);
    }
  free (list);
}
References XdgIcon::icon_name, XdgIconList::icons, XdgIcon::mime_type, and XdgIconList::n_icons.
Referenced by xdg_mime_shutdown().
_xdg_mime_icon_list_lookup()
const char * _xdg_mime_icon_list_lookup (XdgIconList * list, const char * mime_type)
Definition at line 98 of file xdgmimeicon.c.
{
  XdgIcon *entry;
  XdgIcon key;
  if (list->n_icons > 0)
    {
      key.mime_type = (char *)mime_type;
      key.icon_name = NULL;
      entry = bsearch (&key, list->icons, list->n_icons,
               sizeof (XdgIcon), icon_entry_cmp);
      if (entry)
        return entry->icon_name;
    }
  return NULL;
}
References XdgIcon::icon_name, XdgIconList::icons, XdgIcon::mime_type, and XdgIconList::n_icons.
Referenced by xdg_mime_get_generic_icon(), and xdg_mime_get_icon().
_xdg_mime_icon_list_new()
XdgIconList * _xdg_mime_icon_list_new (void)
Definition at line 62 of file xdgmimeicon.c.
{
  XdgIconList *list;
  list = malloc (sizeof (XdgIconList));
  list->icons = NULL;
  list->n_icons = 0;
  return list;
}
References XdgIconList::icons, and XdgIconList::n_icons.
_xdg_mime_icon_read_from_file()
void _xdg_mime_icon_read_from_file (XdgIconList * list, const char * file_name)
Definition at line 119 of file xdgmimeicon.c.
{
  FILE *file;
  char line[255];
  int alloc;
  file = fopen (file_name, "r");
  if (file == NULL)
    return;
  /* FIXME: Not UTF-8 safe.  Doesn't work if lines are greater than 255 chars.
   * Blah */
  alloc = list->n_icons + 16;
  list->icons = realloc (list->icons, alloc * sizeof (XdgIcon));
  while (fgets (line, 255, file) != NULL)
    {
      char *sep;
      if (line[0] == '#')
    continue;
      sep = strchr (line, ':');
      if (sep == NULL)
    continue;
      *(sep++) = '\000';
      sep[strlen (sep) -1] = '\000';
      if (list->n_icons == alloc)
    {
      alloc <<= 1;
      list->icons = realloc (list->icons,
                   alloc * sizeof (XdgIcon));
    }
      list->icons[list->n_icons].mime_type = strdup (line);
      list->icons[list->n_icons].icon_name = strdup (sep);
      list->n_icons++;
    }
  list->icons = realloc (list->icons,
               list->n_icons * sizeof (XdgIcon));
  fclose (file);
  if (list->n_icons > 1)
    qsort (list->icons, list->n_icons,
           sizeof (XdgIcon), icon_entry_cmp);
}
References XdgIcon::icon_name, XdgIconList::icons, XdgIcon::mime_type, and XdgIconList::n_icons.