libxputty: xputty/xdgmime/xdgmimeint.c File Reference
xdgmimeint.c File Reference
Functions
xdg_unichar_t _xdg_utf8_to_ucs4 (const char *source)
xdg_unichar_t _xdg_ucs4_to_lower (xdg_unichar_t source)
int _xdg_utf8_validate (const char *source)
const char * _xdg_get_base_name (const char *file_name)
xdg_unichar_t * _xdg_convert_to_ucs4 (const char *source, int *len)
void _xdg_reverse_ucs4 (xdg_unichar_t *source, int len)
const char * _xdg_binary_or_text_fallback (const void *data, size_t len)
Variables
const char *const _xdg_utf8_skip = _xdg_utf8_skip_data
Function Documentation
_xdg_binary_or_text_fallback()
const char * _xdg_binary_or_text_fallback (const void * data, size_t len)
Definition at line 193 of file xdgmimeint.c.
{
  unsigned char *chardata;
  int i;
  chardata = (unsigned char *) data;
  for (i = 0; i < 128 && i < len; ++i)
    {
       if (chardata[i] < 32 && chardata[i] != 9 && chardata[i] != 10 && chardata[i] != 13)
         return XDG_MIME_TYPE_UNKNOWN; /* binary data */
    }
  return XDG_MIME_TYPE_TEXTPLAIN;
}
Referenced by _xdg_mime_cache_get_mime_type_for_file(), xdg_mime_get_mime_type_for_data(), and xdg_mime_get_mime_type_for_file().
_xdg_convert_to_ucs4()
xdg_unichar_t * _xdg_convert_to_ucs4 (const char * source, int * len)
Definition at line 157 of file xdgmimeint.c.
{
  xdg_unichar_t *out;
  int i;
  const char *p;
  out = malloc (sizeof (xdg_unichar_t) * (strlen (source) + 1));
  p = source;
  i = 0;
  while (*p)
    {
      out[i++] = _xdg_utf8_to_ucs4 (p);
      p = _xdg_utf8_next_char (p);
    }
  out[i] = 0;
  *len = i;
  return out;
}
References _xdg_utf8_to_ucs4().
_xdg_get_base_name()
const char * _xdg_get_base_name (const char * file_name)
Definition at line 141 of file xdgmimeint.c.
{
  const char *base_name;
  if (file_name == NULL)
    return NULL;
  base_name = strrchr (file_name, '/');
  if (base_name == NULL)
    return file_name;
  else
    return base_name + 1;
}
Referenced by _xdg_mime_cache_get_mime_type_for_file(), and xdg_mime_get_mime_type_for_file().
_xdg_reverse_ucs4()
void _xdg_reverse_ucs4 (xdg_unichar_t * source, int len)
Definition at line 179 of file xdgmimeint.c.
{
  xdg_unichar_t c;
  int i;
  for (i = 0; i < len - i - 1; i++)
    {
      c = source[i];
      source[i] = source[len - i - 1];
      source[len - i - 1] = c;
    }
}
_xdg_ucs4_to_lower()
xdg_unichar_t _xdg_ucs4_to_lower (xdg_unichar_t source)
Definition at line 124 of file xdgmimeint.c.
{
  /* FIXME: Do a real to_upper sometime */
  /* CaseFolding-3.2.0.txt has a table of rules. */
  if ((source & 0xFF) == source)
    return (xdg_unichar_t) tolower ((unsigned char) source);
  return source;
}
_xdg_utf8_to_ucs4()
xdg_unichar_t _xdg_utf8_to_ucs4 (const char * source)
Definition at line 61 of file xdgmimeint.c.
{
  xdg_unichar_t ucs32;
  if( ! ( *source & 0x80 ) )
    {
      ucs32 = *source;
    }
  else
    {
      int bytelength = 0;
      xdg_unichar_t result;
      if ( ! (*source & 0x40) )
    {
      ucs32 = *source;
    }
      else
    {
      if ( ! (*source & 0x20) )
        {
          result = *source++ & 0x1F;
          bytelength = 2;
        }
      else if ( ! (*source & 0x10) )
        {
          result = *source++ & 0x0F;
          bytelength = 3;
        }
      else if ( ! (*source & 0x08) )
        {
          result = *source++ & 0x07;
          bytelength = 4;
        }
      else if ( ! (*source & 0x04) )
        {
          result = *source++ & 0x03;
          bytelength = 5;
        }
      else if ( ! (*source & 0x02) )
        {
          result = *source++ & 0x01;
          bytelength = 6;
        }
      else
        {
          result = *source++;
          bytelength = 1;
        }
      for ( bytelength --; bytelength > 0; bytelength -- )
        {
          result <<= 6;
          result |= *source++ & 0x3F;
        }
      ucs32 = result;
    }
    }
  return ucs32;
}
Referenced by _xdg_convert_to_ucs4().
_xdg_utf8_validate()
int _xdg_utf8_validate (const char * source)
Definition at line 134 of file xdgmimeint.c.
{
  /* FIXME: actually write */
  return TRUE;
}
Referenced by _xdg_mime_cache_get_mime_type_for_file(), xdg_mime_get_mime_type_for_file(), and xdg_mime_is_valid_mime_type().
Variable Documentation
_xdg_utf8_skip
const char* const _xdg_utf8_skip = _xdg_utf8_skip_data
Definition at line 55 of file xdgmimeint.c.