libxputty: xputty/xdgmime/xdgmimemagic.c File Reference
xdgmimemagic.c File Reference
Data Structures
struct XdgMimeMagicMatch
struct XdgMimeMagicMatchlet
struct XdgMimeMagic
Typedefs
typedef struct XdgMimeMagicMatch XdgMimeMagicMatch
typedef struct XdgMimeMagicMatchlet XdgMimeMagicMatchlet
Enumerations
enum XdgMimeMagicState { XDG_MIME_MAGIC_SECTION , XDG_MIME_MAGIC_MAGIC , XDG_MIME_MAGIC_ERROR , XDG_MIME_MAGIC_EOF }
Functions
XdgMimeMagic * _xdg_mime_magic_new (void)
void _xdg_mime_magic_free (XdgMimeMagic *mime_magic)
int _xdg_mime_magic_get_buffer_extents (XdgMimeMagic *mime_magic)
const char * _xdg_mime_magic_lookup_data (XdgMimeMagic *mime_magic, const void *data, size_t len, int *result_prio, const char *mime_types[], int n_mime_types)
void _xdg_mime_magic_read_from_file (XdgMimeMagic *mime_magic, const char *file_name)
Typedef Documentation
XdgMimeMagicMatch
typedef struct XdgMimeMagicMatch XdgMimeMagicMatch
Definition at line 54 of file xdgmimemagic.c.
XdgMimeMagicMatchlet
typedef struct XdgMimeMagicMatchlet XdgMimeMagicMatchlet
Definition at line 55 of file xdgmimemagic.c.
Enumeration Type Documentation
XdgMimeMagicState
enum XdgMimeMagicState
Enumerator
XDG_MIME_MAGIC_SECTION
XDG_MIME_MAGIC_MAGIC
XDG_MIME_MAGIC_ERROR
XDG_MIME_MAGIC_EOF
Definition at line 57 of file xdgmimemagic.c.
{
  XDG_MIME_MAGIC_SECTION,
  XDG_MIME_MAGIC_MAGIC,
  XDG_MIME_MAGIC_ERROR,
  XDG_MIME_MAGIC_EOF
} XdgMimeMagicState;
Function Documentation
_xdg_mime_magic_free()
void _xdg_mime_magic_free (XdgMimeMagic * mime_magic)
Definition at line 644 of file xdgmimemagic.c.
{
  if (mime_magic) {
    _xdg_mime_magic_match_free (mime_magic->match_list);
    free (mime_magic);
  }
}
References XdgMimeMagic::match_list.
Referenced by xdg_mime_shutdown().
_xdg_mime_magic_get_buffer_extents()
int _xdg_mime_magic_get_buffer_extents (XdgMimeMagic * mime_magic)
Definition at line 653 of file xdgmimemagic.c.
{
  return mime_magic->max_extent;
}
References XdgMimeMagic::max_extent.
Referenced by xdg_mime_get_max_buffer_extents(), and xdg_mime_get_mime_type_for_file().
_xdg_mime_magic_lookup_data()
const char * _xdg_mime_magic_lookup_data (XdgMimeMagic * mime_magic, const void * data, size_t len, int * result_prio, const char * mime_types[], int n_mime_types)
Definition at line 659 of file xdgmimemagic.c.
{
  XdgMimeMagicMatch *match;
  const char *mime_type;
  int n;
  int prio;
  prio = 0;
  mime_type = NULL;
  for (match = mime_magic->match_list; match; match = match->next)
    {
      if (_xdg_mime_magic_match_compare_to_data (match, data, len))
    {
      prio = match->priority;
      mime_type = match->mime_type;
      break;
    }
      else
    {
      for (n = 0; n < n_mime_types; n++)
        {
          if (mime_types[n] &&
          _xdg_mime_mime_type_equal (mime_types[n], match->mime_type))
        mime_types[n] = NULL;
        }
    }
    }
  if (mime_type == NULL)
    {
      for (n = 0; n < n_mime_types; n++)
    {
      if (mime_types[n])
        mime_type = mime_types[n];
    }
    }
  if (result_prio)
    *result_prio = prio;
  return mime_type;
}
References _xdg_mime_mime_type_equal(), XdgMimeMagic::match_list, XdgMimeMagicMatch::mime_type, XdgMimeMagicMatch::next, and XdgMimeMagicMatch::priority.
Referenced by xdg_mime_get_mime_type_for_data(), and xdg_mime_get_mime_type_for_file().
_xdg_mime_magic_new()
XdgMimeMagic * _xdg_mime_magic_new (void)
Definition at line 638 of file xdgmimemagic.c.
{
  return calloc (1, sizeof (XdgMimeMagic));
}
_xdg_mime_magic_read_from_file()
void _xdg_mime_magic_read_from_file (XdgMimeMagic * mime_magic, const char * file_name)
Definition at line 798 of file xdgmimemagic.c.
{
  FILE *magic_file;
  char header[12];
  magic_file = fopen (file_name, "r");
  if (magic_file == NULL)
    return;
  if (fread (header, 1, 12, magic_file) == 12)
    {
      if (memcmp ("MIME-Magic\0\n", header, 12) == 0)
        _xdg_mime_magic_read_magic_file (mime_magic, magic_file);
    }
  fclose (magic_file);
}