libxputty: xputty/xdgmime/xdgmime.c File Reference
xdgmime.c File Reference
Data Structures
struct XdgDirTimeList
struct XdgCallbackList
Typedefs
typedef struct XdgDirTimeList XdgDirTimeList
typedef struct XdgCallbackList XdgCallbackList
typedef int(* XdgDirectoryFunc) (const char *directory, void *user_data)
Enumerations
enum { XDG_CHECKED_UNCHECKED , XDG_CHECKED_VALID , XDG_CHECKED_INVALID }
Functions
const char * xdg_mime_get_mime_type_for_data (const void *data, size_t len, int *result_prio)
const char * xdg_mime_get_mime_type_for_file (const char *file_name, struct stat *statbuf)
const char * xdg_mime_get_mime_type_from_file_name (const char *file_name)
int xdg_mime_get_mime_types_from_file_name (const char *file_name, const char *mime_types[], int n_mime_types)
int xdg_mime_is_valid_mime_type (const char *mime_type)
void xdg_mime_shutdown (void)
int xdg_mime_get_max_buffer_extents (void)
const char * _xdg_mime_unalias_mime_type (const char *mime_type)
const char * xdg_mime_unalias_mime_type (const char *mime_type)
int _xdg_mime_mime_type_equal (const char *mime_a, const char *mime_b)
int xdg_mime_mime_type_equal (const char *mime_a, const char *mime_b)
int xdg_mime_media_type_equal (const char *mime_a, const char *mime_b)
int _xdg_mime_mime_type_subclass (const char *mime, const char *base)
int xdg_mime_mime_type_subclass (const char *mime, const char *base)
char ** xdg_mime_list_mime_parents (const char *mime)
const char ** xdg_mime_get_mime_parents (const char *mime)
void xdg_mime_dump (void)
int xdg_mime_register_reload_callback (XdgMimeCallback callback, void *data, XdgMimeDestroy destroy)
void xdg_mime_remove_callback (int callback_id)
const char * xdg_mime_get_icon (const char *mime)
const char * xdg_mime_get_generic_icon (const char *mime)
Variables
XdgMimeCache ** _caches = NULL
const char xdg_mime_type_unknown [] = "application/octet-stream"
const char xdg_mime_type_empty [] = "application/x-zerosize"
const char xdg_mime_type_textplain [] = "text/plain"
Typedef Documentation
XdgCallbackList
typedef struct XdgCallbackList XdgCallbackList
Definition at line 49 of file xdgmime.c.
XdgDirectoryFunc
typedef int(* XdgDirectoryFunc) (const char *directory, void *user_data)
Definition at line 98 of file xdgmime.c.
XdgDirTimeList
typedef struct XdgDirTimeList XdgDirTimeList
Definition at line 48 of file xdgmime.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
XDG_CHECKED_UNCHECKED
XDG_CHECKED_VALID
XDG_CHECKED_INVALID
Definition at line 71 of file xdgmime.c.
{
  XDG_CHECKED_UNCHECKED,
  XDG_CHECKED_VALID,
  XDG_CHECKED_INVALID
};
Function Documentation
_xdg_mime_mime_type_equal()
int _xdg_mime_mime_type_equal (const char * mime_a, const char * mime_b)
Definition at line 706 of file xdgmime.c.
{
  const char *unalias_a, *unalias_b;
  unalias_a = _xdg_mime_unalias_mime_type (mime_a);
  unalias_b = _xdg_mime_unalias_mime_type (mime_b);
  if (strcmp (unalias_a, unalias_b) == 0)
    return 1;
  return 0;
}
References _xdg_mime_unalias_mime_type().
Referenced by _xdg_mime_magic_lookup_data(), and xdg_mime_mime_type_equal().
_xdg_mime_mime_type_subclass()
int _xdg_mime_mime_type_subclass (const char * mime, const char * base)
Definition at line 770 of file xdgmime.c.
{
  const char *umime, *ubase;
  const char **parents;
  if (_caches)
    return _xdg_mime_cache_mime_type_subclass (mime, base);
  umime = _xdg_mime_unalias_mime_type (mime);
  ubase = _xdg_mime_unalias_mime_type (base);
  if (strcmp (umime, ubase) == 0)
    return 1;
#if 1
  /* Handle supertypes */
  if (xdg_mime_is_super_type (ubase) &&
      xdg_mime_media_type_equal (umime, ubase))
    return 1;
#endif
  /*  Handle special cases text/plain and application/octet-stream */
  if (strcmp (ubase, "text/plain") == 0 &&
      strncmp (umime, "text/", 5) == 0)
    return 1;
  if (strcmp (ubase, "application/octet-stream") == 0 &&
      strncmp (umime, "inode/", 6) != 0)
    return 1;
  parents = _xdg_mime_parent_list_lookup (parent_list, umime);
  for (; parents && *parents; parents++)
    {
      if (_xdg_mime_mime_type_subclass (*parents, ubase))
    return 1;
    }
  return 0;
}
References _caches, _xdg_mime_cache_mime_type_subclass(), _xdg_mime_mime_type_subclass(), _xdg_mime_parent_list_lookup(), _xdg_mime_unalias_mime_type(), and xdg_mime_media_type_equal().
Referenced by _xdg_mime_mime_type_subclass(), and xdg_mime_mime_type_subclass().
_xdg_mime_unalias_mime_type()
const char * _xdg_mime_unalias_mime_type (const char * mime_type)
Definition at line 684 of file xdgmime.c.
{
  const char *lookup;
  if (_caches)
    return _xdg_mime_cache_unalias_mime_type (mime_type);
  if ((lookup = _xdg_mime_alias_list_lookup (alias_list, mime_type)) != NULL)
    return lookup;
  return mime_type;
}
References _caches, _xdg_mime_alias_list_lookup(), and _xdg_mime_cache_unalias_mime_type().
Referenced by _xdg_mime_mime_type_equal(), _xdg_mime_mime_type_subclass(), xdg_mime_get_mime_parents(), and xdg_mime_unalias_mime_type().
xdg_mime_dump()
void xdg_mime_dump (void)
Definition at line 857 of file xdgmime.c.
{
  xdg_mime_init();
  printf ("*** ALIASES ***\n\n");
  _xdg_mime_alias_list_dump (alias_list);
  printf ("\n*** PARENTS ***\n\n");
  _xdg_mime_parent_list_dump (parent_list);
  printf ("\n*** CACHE ***\n\n");
  _xdg_glob_hash_dump (global_hash);
  printf ("\n*** GLOBS ***\n\n");
  _xdg_glob_hash_dump (global_hash);
  printf ("\n*** GLOBS REVERSE TREE ***\n\n");
  _xdg_mime_cache_glob_dump ();
}
References _xdg_glob_hash_dump(), _xdg_mime_alias_list_dump(), _xdg_mime_cache_glob_dump(), and _xdg_mime_parent_list_dump().
xdg_mime_get_generic_icon()
const char * xdg_mime_get_generic_icon (const char * mime)
Definition at line 937 of file xdgmime.c.
{
  xdg_mime_init ();
  if (_caches)
    return _xdg_mime_cache_get_generic_icon (mime);
  return _xdg_mime_icon_list_lookup (generic_icon_list, mime);
}
References _caches, _xdg_mime_cache_get_generic_icon(), and _xdg_mime_icon_list_lookup().
xdg_mime_get_icon()
const char * xdg_mime_get_icon (const char * mime)
Definition at line 926 of file xdgmime.c.
{
  xdg_mime_init ();
  if (_caches)
    return _xdg_mime_cache_get_icon (mime);
  return _xdg_mime_icon_list_lookup (icon_list, mime);
}
References _caches, _xdg_mime_cache_get_icon(), and _xdg_mime_icon_list_lookup().
xdg_mime_get_max_buffer_extents()
int xdg_mime_get_max_buffer_extents (void)
Definition at line 673 of file xdgmime.c.
{
  xdg_mime_init ();
  if (_caches)
    return _xdg_mime_cache_get_max_buffer_extents ();
  return _xdg_mime_magic_get_buffer_extents (global_magic);
}
References _caches, _xdg_mime_cache_get_max_buffer_extents(), and _xdg_mime_magic_get_buffer_extents().
xdg_mime_get_mime_parents()
const char ** xdg_mime_get_mime_parents (const char * mime)
Definition at line 845 of file xdgmime.c.
{
  const char *umime;
  xdg_mime_init ();
  umime = _xdg_mime_unalias_mime_type (mime);
  return _xdg_mime_parent_list_lookup (parent_list, umime);
}
References _xdg_mime_parent_list_lookup(), and _xdg_mime_unalias_mime_type().
Referenced by xdg_mime_list_mime_parents().
xdg_mime_get_mime_type_for_data()
const char * xdg_mime_get_mime_type_for_data (const void * data, size_t len, int * result_prio)
Definition at line 466 of file xdgmime.c.
{
  const char *mime_type;
  if (len == 0)
    {
      if (result_prio != NULL)
        *result_prio = 100;
      return XDG_MIME_TYPE_EMPTY;
    }
  xdg_mime_init ();
  if (_caches)
    mime_type = _xdg_mime_cache_get_mime_type_for_data (data, len, result_prio);
  else
    mime_type = _xdg_mime_magic_lookup_data (global_magic, data, len, result_prio, NULL, 0);
  if (mime_type)
    return mime_type;
  return _xdg_binary_or_text_fallback(data, len);
}
References _caches, _xdg_binary_or_text_fallback(), _xdg_mime_cache_get_mime_type_for_data(), and _xdg_mime_magic_lookup_data().
xdg_mime_get_mime_type_for_file()
const char * xdg_mime_get_mime_type_for_file (const char * file_name, struct stat * statbuf)
Definition at line 493 of file xdgmime.c.
{
  const char *mime_type;
  /* currently, only a few globs occur twice, and none
   * more often, so 5 seems plenty.
   */
  const char *mime_types[5];
  FILE *file;
  unsigned char *data;
  int max_extent;
  int bytes_read;
  struct stat buf;
  const char *base_name;
  int n;
  if (file_name == NULL)
    return NULL;
  if (! _xdg_utf8_validate (file_name))
    return NULL;
  xdg_mime_init ();
  if (_caches)
    return _xdg_mime_cache_get_mime_type_for_file (file_name, statbuf);
  base_name = _xdg_get_base_name (file_name);
  n = _xdg_glob_hash_lookup_file_name (global_hash, base_name, mime_types, 5);
  if (n == 1)
    return mime_types[0];
  if (!statbuf)
    {
      if (stat (file_name, &buf) != 0)
    return XDG_MIME_TYPE_UNKNOWN;
      statbuf = &buf;
    }
  if (!S_ISREG (statbuf->st_mode))
    return XDG_MIME_TYPE_UNKNOWN;
  /* FIXME: Need to make sure that max_extent isn't totally broken.  This could
   * be large and need getting from a stream instead of just reading it all
   * in. */
  max_extent = _xdg_mime_magic_get_buffer_extents (global_magic);
  data = malloc (max_extent);
  if (data == NULL)
    return XDG_MIME_TYPE_UNKNOWN;
  file = fopen (file_name, "r");
  if (file == NULL)
    {
      free (data);
      return XDG_MIME_TYPE_UNKNOWN;
    }
  bytes_read = fread (data, 1, max_extent, file);
  if (ferror (file))
    {
      free (data);
      fclose (file);
      return XDG_MIME_TYPE_UNKNOWN;
    }
  mime_type = _xdg_mime_magic_lookup_data (global_magic, data, bytes_read, NULL,
                       mime_types, n);
  if (!mime_type)
    mime_type = _xdg_binary_or_text_fallback (data, bytes_read);
  free (data);
  fclose (file);
  return mime_type;
}
References _caches, _xdg_binary_or_text_fallback(), _xdg_get_base_name(), _xdg_glob_hash_lookup_file_name(), _xdg_mime_cache_get_mime_type_for_file(), _xdg_mime_magic_get_buffer_extents(), _xdg_mime_magic_lookup_data(), and _xdg_utf8_validate().
xdg_mime_get_mime_type_from_file_name()
const char * xdg_mime_get_mime_type_from_file_name (const char * file_name)
Definition at line 572 of file xdgmime.c.
{
  const char *mime_type;
  xdg_mime_init ();
  if (_caches)
    return _xdg_mime_cache_get_mime_type_from_file_name (file_name);
  if (_xdg_glob_hash_lookup_file_name (global_hash, file_name, &mime_type, 1))
    return mime_type;
  else
    return XDG_MIME_TYPE_UNKNOWN;
}
References _caches, _xdg_glob_hash_lookup_file_name(), and _xdg_mime_cache_get_mime_type_from_file_name().
xdg_mime_get_mime_types_from_file_name()
int xdg_mime_get_mime_types_from_file_name (const char * file_name, const char * mime_types[], int n_mime_types)
Definition at line 588 of file xdgmime.c.
{
  xdg_mime_init ();
  if (_caches)
    return _xdg_mime_cache_get_mime_types_from_file_name (file_name, mime_types, n_mime_types);
  return _xdg_glob_hash_lookup_file_name (global_hash, file_name, mime_types, n_mime_types);
}
References _caches, _xdg_glob_hash_lookup_file_name(), and _xdg_mime_cache_get_mime_types_from_file_name().
xdg_mime_is_valid_mime_type()
int xdg_mime_is_valid_mime_type (const char * mime_type)
Definition at line 601 of file xdgmime.c.
{
  /* FIXME: We should make this a better test
   */
  return _xdg_utf8_validate (mime_type);
}
References _xdg_utf8_validate().
xdg_mime_list_mime_parents()
char ** xdg_mime_list_mime_parents (const char * mime)
Definition at line 821 of file xdgmime.c.
{
  const char **parents;
  char **result;
  int i, n;
  if (_caches)
    return _xdg_mime_cache_list_mime_parents (mime);
  parents = xdg_mime_get_mime_parents (mime);
  if (!parents)
    return NULL;
  for (i = 0; parents[i]; i++) ;
  n = (i + 1) * sizeof (char *);
  result = (char **) malloc (n);
  memcpy (result, parents, n);
  return result;
}
References _caches, _xdg_mime_cache_list_mime_parents(), and xdg_mime_get_mime_parents().
xdg_mime_media_type_equal()
int xdg_mime_media_type_equal (const char * mime_a, const char * mime_b)
Definition at line 730 of file xdgmime.c.
{
  char *sep;
  sep = strchr (mime_a, '/');
  if (sep && strncmp (mime_a, mime_b, sep - mime_a + 1) == 0)
    return 1;
  return 0;
}
Referenced by _xdg_mime_cache_mime_type_subclass(), and _xdg_mime_mime_type_subclass().
xdg_mime_mime_type_equal()
int xdg_mime_mime_type_equal (const char * mime_a, const char * mime_b)
Definition at line 721 of file xdgmime.c.
{
  xdg_mime_init ();
  return _xdg_mime_mime_type_equal (mime_a, mime_b);
}
References _xdg_mime_mime_type_equal().
xdg_mime_mime_type_subclass()
int xdg_mime_mime_type_subclass (const char * mime, const char * base)
Definition at line 812 of file xdgmime.c.
{
  xdg_mime_init ();
  return _xdg_mime_mime_type_subclass (mime, base);
}
References _xdg_mime_mime_type_subclass().
xdg_mime_register_reload_callback()
int xdg_mime_register_reload_callback (XdgMimeCallback callback, void * data, XdgMimeDestroy destroy)
Definition at line 877 of file xdgmime.c.
{
  XdgCallbackList *list_el;
  static int callback_id = 1;
  /* Make a new list element */
  list_el = calloc (1, sizeof (XdgCallbackList));
  list_el->callback_id = callback_id;
  list_el->callback = callback;
  list_el->data = data;
  list_el->destroy = destroy;
  list_el->next = callback_list;
  if (list_el->next)
    list_el->next->prev = list_el;
  callback_list = list_el;
  callback_id ++;
  return callback_id - 1;
}
References XdgCallbackList::callback, XdgCallbackList::callback_id, XdgCallbackList::data, XdgCallbackList::destroy, XdgCallbackList::next, and XdgCallbackList::prev.
xdg_mime_remove_callback()
void xdg_mime_remove_callback (int callback_id)
Definition at line 901 of file xdgmime.c.
{
  XdgCallbackList *list;
  for (list = callback_list; list; list = list->next)
    {
      if (list->callback_id == callback_id)
    {
      if (list->next)
        list->next = list->prev;
      if (list->prev)
        list->prev->next = list->next;
      else
        callback_list = list->next;
      /* invoke the destroy handler */
      (list->destroy) (list->data);
      free (list);
      return;
    }
    }
}
References XdgCallbackList::callback_id, XdgCallbackList::data, XdgCallbackList::destroy, XdgCallbackList::next, and XdgCallbackList::prev.
xdg_mime_shutdown()
void xdg_mime_shutdown (void)
Definition at line 609 of file xdgmime.c.
{
  XdgCallbackList *list;
  /* FIXME: Need to make this (and the whole library) thread safe */
  if (dir_time_list)
    {
      xdg_dir_time_list_free (dir_time_list);
      dir_time_list = NULL;
    }
  if (global_hash)
    {
      _xdg_glob_hash_free (global_hash);
      global_hash = NULL;
    }
  if (global_magic)
    {
      _xdg_mime_magic_free (global_magic);
      global_magic = NULL;
    }
  if (alias_list)
    {
      _xdg_mime_alias_list_free (alias_list);
      alias_list = NULL;
    }
  if (parent_list)
    {
      _xdg_mime_parent_list_free (parent_list);
      parent_list = NULL;
    }
  if (icon_list)
    {
      _xdg_mime_icon_list_free (icon_list);
      icon_list = NULL;
    }
  if (generic_icon_list)
    {
      _xdg_mime_icon_list_free (generic_icon_list);
      generic_icon_list = NULL;
    }
  if (_caches)
    {
      int i;
      for (i = 0; i < n_caches; i++)
        _xdg_mime_cache_unref (_caches[i]);
      free (_caches);
      _caches = NULL;
      n_caches = 0;
    }
  for (list = callback_list; list; list = list->next)
    (list->callback) (list->data);
  need_reread = TRUE;
}
References _caches, _xdg_glob_hash_free(), _xdg_mime_alias_list_free(), _xdg_mime_cache_unref(), _xdg_mime_icon_list_free(), _xdg_mime_magic_free(), _xdg_mime_parent_list_free(), XdgCallbackList::callback, XdgCallbackList::data, and XdgCallbackList::next.
xdg_mime_unalias_mime_type()
const char * xdg_mime_unalias_mime_type (const char * mime_type)
Definition at line 698 of file xdgmime.c.
{
  xdg_mime_init ();
  return _xdg_mime_unalias_mime_type (mime_type);
}
References _xdg_mime_unalias_mime_type().
Referenced by _xdg_mime_cache_list_mime_parents().
Variable Documentation
_caches
XdgMimeCache** _caches = NULL
Definition at line 63 of file xdgmime.c.
Referenced by _xdg_mime_cache_get_max_buffer_extents(), _xdg_mime_cache_glob_dump(), _xdg_mime_cache_list_mime_parents(), _xdg_mime_cache_mime_type_subclass(), _xdg_mime_mime_type_subclass(), _xdg_mime_unalias_mime_type(), xdg_mime_get_generic_icon(), xdg_mime_get_icon(), xdg_mime_get_max_buffer_extents(), xdg_mime_get_mime_type_for_data(), xdg_mime_get_mime_type_for_file(), xdg_mime_get_mime_type_from_file_name(), xdg_mime_get_mime_types_from_file_name(), xdg_mime_list_mime_parents(), and xdg_mime_shutdown().
xdg_mime_type_empty
const char xdg_mime_type_empty[] = "application/x-zerosize"
Definition at line 67 of file xdgmime.c.
xdg_mime_type_textplain
const char xdg_mime_type_textplain[] = "text/plain"
Definition at line 68 of file xdgmime.c.
xdg_mime_type_unknown
const char xdg_mime_type_unknown[] = "application/octet-stream"
Definition at line 66 of file xdgmime.c.