libxputty: xputty/widgets/xdrawing_area_private.c File Reference
xdrawing_area_private.c File Reference
Functions
void _rounded_iframe (cairo_t *cr, float x, float y, float w, float h)
void _draw_image (void *w_, void *user_data)
_draw_image - internal draw the image to the buffer
Function Documentation
_draw_image()
void _draw_image (void * w_, void * user_data)
_draw_image - internal draw the image to the buffer
Parameters
*w_ - void pointer to the Widget_t image
*user_data - void pointer to attached user_data
Returns
void
Definition at line 39 of file xdrawing_area_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width_t = metrics.width;
    int height_t = metrics.height;
    if (!w->image) {
        cairo_text_extents_t extents;
        use_base_color_scheme(w, get_color_state(w));
        cairo_set_font_size (w->crb, w->app->big_font/w->scale.ascale);
        cairo_text_extents(w->crb,"Missing Image" , &extents);
        cairo_move_to (w->crb, (w->width -extents.width)*0.5, (w->height - extents.height)*0.5);
        cairo_show_text(w->crb, "Missing Image");
        cairo_new_path (w->crb);
        cairo_set_line_width(w->crb,3);
        _rounded_iframe(w->crb, 5, 5, width_t-10, height_t-10);
        cairo_stroke(w->crb);
    }
    if (w->image) {
        int width, height;
        os_get_surface_size(w->image, &width, &height);
        double x = (double)width_t/(double)(width);
        double y = (double)height_t/(double)height;
        double x1 = (double)(width)/(double)width_t;
        double y1 = (double)height/(double)height_t;
        cairo_scale(w->crb, x,y);
        cairo_set_source_surface (w->crb, w->image, 0, 0);
        cairo_paint (w->crb);
        cairo_scale(w->crb, x1,y1);
    }
}
References _rounded_iframe(), Widget_t::app, Resize_t::ascale, Xputty::big_font, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::height, Widget_t::image, os_get_surface_size(), os_get_window_metrics(), Widget_t::scale, use_base_color_scheme(), Metrics_t::width, and Widget_t::width.
Referenced by add_image().
_rounded_iframe()
void _rounded_iframe (cairo_t * cr, float x, float y, float w, float h)
Definition at line 25 of file xdrawing_area_private.c.
{
    cairo_new_path (cr);
    float r = 20.0;
    cairo_move_to(cr, x+r,y);
    cairo_line_to(cr, x+w-r,y);
    cairo_curve_to(cr, x+w,y,x+w,y,x+w,y+r);
    cairo_line_to(cr, x+w,y+h-r);
    cairo_curve_to(cr, x+w,y+h,x+w,y+h,x+w-r,y+h);
    cairo_line_to(cr, x+r,y+h);
    cairo_curve_to(cr, x,y+h,x,y+h,x,y+h-r);
    cairo_line_to(cr, x,y+r);
    cairo_curve_to(cr, x,y,x,y,x+r,y);
}
Referenced by _draw_image().