libxputty: xputty/xfilepicker.c File Reference
xfilepicker.c File Reference
Functions
bool is_root_directory (char *path)
void add_root_directory (FilePicker *filepicker, char *path)
bool is_file (DIR *dirp, struct dirent *dp)
bool is_directory (DIR *dirp, struct dirent *dp)
int fp_check_link (char *path, struct dirent *dp)
int fp_check_dir (char *path, struct dirent *dp)
int fp_is_link (struct dirent *dp)
int fp_get_files (FilePicker *filepicker, char *path, int get_dirs, int get_files)
fp_get_files - fill file_names and dir_names with the results from readdir path
void fp_free (FilePicker *filepicker)
fp_free - release all memory used by the filepicker
void fp_init (FilePicker *filepicker, const char *path)
fp_init - set default values used by the filepicker
Function Documentation
add_root_directory()
void add_root_directory (FilePicker * filepicker, char * path)
Definition at line 108 of file xfilepicker.c.
{
    DWORD drives = GetLogicalDrives();
    int i;
    for (i=0; i<='Z'-'A'; i++) {
      if ((drives & (1 << i)) != 0) {
        filepicker->dir_counter += 1;
        filepicker->dir_names = (char **)realloc(filepicker->dir_names,
          (filepicker->dir_counter) * sizeof(char *));
        asprintf(&filepicker->dir_names[filepicker->dir_counter-1], "%c:\\", 'A'+i);
      }
    }
   /* filepicker->dir_names = (char **)realloc(filepicker->dir_names,
      (filepicker->dir_counter + 1) * sizeof(char *));
    assert(filepicker->dir_names != NULL);
    asprintf(&filepicker->dir_names[filepicker->dir_counter++], "c:%s", PATH_SEPARATOR);
    assert(&filepicker->dir_names[filepicker->dir_counter] != NULL);*/
}
References asprintf(), FilePicker::dir_counter, and FilePicker::dir_names.
fp_check_dir()
int fp_check_dir (char * path, struct dirent * dp)
Definition at line 201 of file xfilepicker.c.
{
#ifdef __linux__ //not supported on win32
    if (dp->d_type == DT_UNKNOWN) {
        char s[256];
        snprintf(s, 256, (strcmp(path, PATH_SEPARATOR) != 0) ?
              "%s" PATH_SEPARATOR "%s" : "%s%s" , path,dp->d_name);
        struct stat sb;
        if (stat(s, &sb) == 0 && S_ISDIR(sb.st_mode)) {
            return 1;
        } else {
            return 2;
        }
    }
#endif
    return 0;
}
Referenced by fp_get_files().
fp_check_link()
int fp_check_link (char * path, struct dirent * dp)
Definition at line 186 of file xfilepicker.c.
{
#ifdef __linux__ //not supported on win32
    if(dp -> d_type == DT_LNK) {
        char s[256];
        snprintf(s, 256, (strcmp(path, PATH_SEPARATOR) != 0) ?
              "%s" PATH_SEPARATOR "%s" : "%s%s" , path,dp->d_name);
        struct stat sb;
        if (stat(s, &sb) == 0 && S_ISDIR(sb.st_mode)) {
            return 1;
        }
    }
#endif
    return 0;
}
Referenced by fp_get_files().
fp_free()
void fp_free (FilePicker * filepicker)
fp_free - release all memory used by the filepicker
Parameters
*filepicker - pointer to the struct to be released
Definition at line 275 of file xfilepicker.c.
{
    fp_clear_filebuffer(filepicker);
    fp_clear_dirbuffer(filepicker);
    free(filepicker->selected_file);
    free(filepicker->path);
    free(filepicker->filter);
}
References FilePicker::filter, FilePicker::path, and FilePicker::selected_file.
fp_get_files()
int fp_get_files (FilePicker * filepicker, char * path, int get_dirs, int get_files)
fp_get_files - fill file_names and dir_names with the results from readdir path
Parameters
*filepicker - pointer to the struct holding the list pointers
*path - the path to read from
get_dirs - 0 = only read files 1 = refill the directory buffer as well
get_files - 0 = only read directorys 1 = refill the file buffer as well
Returns
int - return the position of the given path in the directory list
Definition at line 226 of file xfilepicker.c.
{
    int ret = 0;
    fp_clear_filebuffer(filepicker);
    DIR *dirp;
    struct dirent *dp;
    if((dirp = opendir(path)) == NULL) {
        path =(char*)PATH_SEPARATOR;
        dirp = opendir(PATH_SEPARATOR);
        assert(dirp);
    }
    if(get_dirs) {
        fp_clear_dirbuffer(filepicker);
        ret = fp_prefill_dirbuffer(filepicker, path);
    }
    while ((dp = readdir(dirp)) != NULL) {
        if((get_files && (is_file(dirp, dp) || (fp_check_dir(path, dp) == 2)) && strlen(dp->d_name)!=0
          && strcmp(dp->d_name,"..")!=0 && fp_show_hidden_files(filepicker, dp->d_name)
          && fp_show_filter_files(filepicker, dp->d_name) && !fp_check_link(path, dp)) ) {
            filepicker->file_names = (char **)realloc(filepicker->file_names,
              (filepicker->file_counter + 1) * sizeof(char *));
            assert(filepicker->file_names != NULL);
            asprintf(&filepicker->file_names[filepicker->file_counter++],"%s",dp->d_name);
            assert(&filepicker->file_names[filepicker->file_counter-1] != NULL);
        } else if(get_dirs && (is_directory(dirp, dp) || fp_is_link(dp) || (fp_check_dir(path, dp) == 1))
          && strlen(dp->d_name)!=0 && strcmp(dp->d_name,"..")!=0 && fp_show_hidden_files(filepicker, dp->d_name)) {
            if (fp_is_link(dp)) {
                if (!fp_check_link(path, dp)) continue;
            }
            filepicker->file_names = (char **)realloc(filepicker->file_names,
              (filepicker->file_counter + 1) * sizeof(char *));
            assert(filepicker->file_names != NULL);
            asprintf(&filepicker->file_names[filepicker->file_counter++], (strcmp(path, PATH_SEPARATOR) != 0) ?
              "%s" PATH_SEPARATOR "%s" : "%s%s" , path,dp->d_name);
            //asprintf(&filepicker->file_names[filepicker->file_counter++],"%s%s" , path,dp->d_name);
            assert(&filepicker->dir_names[filepicker->file_counter-1] != NULL);
        }
    }
    closedir(dirp);
    fp_sort_buffers(filepicker, get_dirs);
    return ret;
}
References asprintf(), FilePicker::dir_names, FilePicker::file_counter, FilePicker::file_names, fp_check_dir(), fp_check_link(), fp_is_link(), is_directory(), and is_file().
Referenced by open_directory_dialog(), open_file_dialog(), and save_file_dialog().
fp_init()
void fp_init (FilePicker * filepicker, const char * path)
fp_init - set default values used by the filepicker
Parameters
*filepicker - pointer to the struct to alocate
*path - the path to read from
Definition at line 283 of file xfilepicker.c.
{
    filepicker->file_counter=0;
    filepicker->dir_counter=0;
    filepicker->use_filter = 0;
    filepicker->show_hidden = false;
    filepicker->file_names = NULL;
    filepicker->dir_names = NULL;
    filepicker->selected_file = NULL;
    filepicker->path = NULL;
    filepicker->filter = NULL;
#ifdef _WIN32 //file/drive functions
    asprintf(&filepicker->path, "%s", "C:\\");
#else
    asprintf(&filepicker->path, "%s", path);
#endif
    assert(filepicker->path != NULL);
}
References asprintf(), FilePicker::dir_counter, FilePicker::dir_names, FilePicker::file_counter, FilePicker::file_names, FilePicker::filter, FilePicker::path, FilePicker::selected_file, FilePicker::show_hidden, and FilePicker::use_filter.
Referenced by open_directory_dialog(), open_file_dialog(), and save_file_dialog().
fp_is_link()
int fp_is_link (struct dirent * dp)
Definition at line 218 of file xfilepicker.c.
{
#ifdef _WIN32 //not supported on win32
    return 0;
#else
    return dp -> d_type == DT_LNK;
#endif
}
Referenced by fp_get_files().
is_directory()
bool is_directory (DIR * dirp, struct dirent * dp)
Definition at line 131 of file xfilepicker.c.
{
    return ((dirp->dd_dta.attrib & _A_SUBDIR) != 0);
}
Referenced by fp_get_files().
is_file()
bool is_file (DIR * dirp, struct dirent * dp)
Definition at line 127 of file xfilepicker.c.
{
    return ((dirp->dd_dta.attrib & _A_SUBDIR)==0);
}
Referenced by fp_get_files().
is_root_directory()
bool is_root_directory (char * path)
Definition at line 103 of file xfilepicker.c.
{
   return (((strlen(path)==3) && path[1] == ':' && path[2] == '\\')
          ||((strlen(path)==1) && path[0] == '\\'));
}