libxputty: xputty/widgets/xframe_private.c File Reference
xframe_private.c File Reference
Functions
void _rounded_frame (cairo_t *cr, float x, float y, float w, float h, float lsize)
void _draw_frame (void *w_, void *user_data)
_draw_frame - internal draw the frame to the buffer
Function Documentation
_draw_frame()
void _draw_frame (void * w_, void * user_data)
_draw_frame - internal draw the frame to the buffer
Parameters
*w_ - void pointer to the Widget_t frame
*user_data - void pointer to attached user_data
Returns
void
Definition at line 39 of file xframe_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width_t = metrics.width;
    int height_t = metrics.height;
    if (w->image) {
        int width, height;
        os_get_surface_size(w->image, &width, &height);
        double x = (double)width_t/(double)(width);
        double y = (double)height_t/(double)height;
        double x1 = (double)(width)/(double)width_t;
        double y1 = (double)height/(double)height_t;
        cairo_scale(w->crb, x,y);
        cairo_set_source_surface (w->crb, w->image, 0, 0);
        _rounded_frame(w->crb, 5/x, 5/y, (width_t-10)/x, (height_t-10)/y, 0);
        cairo_close_path (w->crb);
        cairo_fill (w->crb);
        cairo_scale(w->crb, x1,y1);
    }
    cairo_text_extents_t extents;
    use_text_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    cairo_text_extents(w->crb,w->label , &extents);
    cairo_move_to (w->crb, 30, extents.height);
    cairo_show_text(w->crb, w->label);
    cairo_new_path (w->crb);
    cairo_set_line_width(w->crb,3);
    use_frame_color_scheme(w, INSENSITIVE_);
    _rounded_frame(w->crb, 5, 5, width_t-10, height_t-10, extents.width+10);
    cairo_stroke(w->crb);
}
References _rounded_frame(), Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::image, INSENSITIVE_, Widget_t::label, Xputty::normal_font, os_get_surface_size(), os_get_window_metrics(), Widget_t::scale, use_frame_color_scheme(), use_text_color_scheme(), and Metrics_t::width.
Referenced by add_frame().
_rounded_frame()
void _rounded_frame (cairo_t * cr, float x, float y, float w, float h, float lsize)
Definition at line 25 of file xframe_private.c.
{
    cairo_new_path (cr);
    float r = 20.0;
    cairo_move_to(cr, x+lsize+r,y);
    cairo_line_to(cr, x+w-r,y);
    cairo_curve_to(cr, x+w,y,x+w,y,x+w,y+r);
    cairo_line_to(cr, x+w,y+h-r);
    cairo_curve_to(cr, x+w,y+h,x+w,y+h,x+w-r,y+h);
    cairo_line_to(cr, x+r,y+h);
    cairo_curve_to(cr, x,y+h,x,y+h,x,y+h-r);
    cairo_line_to(cr, x,y+r);
    cairo_curve_to(cr, x,y,x,y,x+r,y);
}
Referenced by _draw_frame().