libxputty: xputty/header/widgets/xkeyboard.h File Reference
xkeyboard.h File Reference
Data Structures
struct MidiKeyboard
Typedefs
typedef void(* midikeyfunc) (Widget_t *w, const int *key, const int on_off)
typedef void(* midiwheelfunc) (Widget_t *w, const int *value)
Functions
void keysym_azerty_to_midi_key (long inkey, float *midi_key)
void keysym_azerty_fr_to_midi_key (long inkey, float *midi_key)
void keysym_azerty_be_to_midi_key (long inkey, float *midi_key)
void keysym_azerty_afnor_to_midi_key (long inkey, float *midi_key)
void keysym_qwertz_to_midi_key (long inkey, float *midi_key)
void keysym_qwerty_to_midi_key (unsigned int inkey, float *midi_key)
void custom_to_midi_key (long custom_keys[128][2], long inkey, float *midi_key)
void read_keymap (const char *keymapfile, long keys[128][2])
void set_key_in_matrix (unsigned long *key_matrix, int key, bool set)
bool is_key_in_matrix (unsigned long *key_matrix, int key)
bool have_key_in_matrix (unsigned long *key_matrix)
void clear_key_matrix (unsigned long *key_matrix)
void add_keyboard (Widget_t *wid, const char *label)
Widget_t * open_midi_keyboard (Widget_t *w, const char *label)
Widget_t * add_midi_keyboard (Widget_t *parent, const char *label, int x, int y, int width, int height)
bool need_redraw (MidiKeyboard *keys)
Typedef Documentation
midikeyfunc
typedef void(* midikeyfunc) (Widget_t *w, const int *key, const int on_off)
Definition at line 33 of file xkeyboard.h.
midiwheelfunc
typedef void(* midiwheelfunc) (Widget_t *w, const int *value)
Definition at line 34 of file xkeyboard.h.
Function Documentation
add_keyboard()
void add_keyboard (Widget_t * wid, const char * label)
Definition at line 923 of file xkeyboard.c.
{
    MidiKeyboard *keys = (MidiKeyboard*)malloc(sizeof(MidiKeyboard));
    wid->private_struct = keys;
    wid->flags |= HAS_MEM | NO_AUTOREPEAT;
    wid->scale.gravity = EASTSOUTH;
    keys->prelight_key = -1;
    keys->active_key = -1;
    keys->new_prelight_key = -1;
    keys->new_active_key = -1;
    keys->last_active_key = -1;
    keys->in_motion = 0;
    keys->send_key = -1;
    keys->octave = 12*2;
    keys->layout = 0;
    keys->channel = 0;
    keys->velocity = 64;
    keys->key_size = 20;
    keys->key_offset = 15;
    keys->keyboard = wid;
    memset(keys->custom_keys, 0, 128*2*sizeof keys->custom_keys[0][0]);
    int j = 0;
    for(;j<4;j++) {
        keys->key_matrix[j] = 0;
    }
    int i = 0;
    for(;i<16;i++) {
        j = 0;
        for(;j<4;j++) {
            keys->in_key_matrix[i][j] = 0;
        }
    }
    read_keymap(label, keys->custom_keys);
    wid->func.expose_callback = draw_keyboard;
    wid->func.motion_callback = keyboard_motion;
    wid->func.leave_callback = leave_keyboard;
    wid->func.button_press_callback = button_pressed_keyboard;
    wid->func.button_release_callback = button_released_keyboard;
    wid->func.double_click_callback = button_released_keyboard;
    wid->func.key_press_callback = key_press;
    wid->func.key_release_callback = key_release;
    wid->func.mem_free_callback = keyboard_mem_free;
    keys->mk_send_note = key_dummy;
    keys->mk_send_all_sound_off = wheel_dummy;
    keys->context_menu = create_menu(wid,25);
    Widget_t* keymap = cmenu_add_submenu(keys->context_menu,_("Keyboard"));
    keymap->private_struct = keys;
    menu_add_radio_entry(keymap,_("qwertz"));
    menu_add_radio_entry(keymap,_("qwerty"));
    menu_add_radio_entry(keymap,_("azerty (fr)"));
    menu_add_radio_entry(keymap,_("azerty (be)"));
    set_active_radio_entry_num(keymap, keys->layout);
    keymap->func.value_changed_callback = layout_callback;
    Widget_t* octavemap = cmenu_add_submenu(keys->context_menu,_("Octave"));
    octavemap->private_struct = keys;
    menu_add_radio_entry(octavemap,_("C 0"));
    menu_add_radio_entry(octavemap,_("C 1"));
    menu_add_radio_entry(octavemap,_("C 2"));
    menu_add_radio_entry(octavemap,_("C 3"));
    menu_add_radio_entry(octavemap,_("C 4"));
    set_active_radio_entry_num(octavemap, keys->octave/12);
    octavemap->func.value_changed_callback = octave_callback;
    Widget_t* velocity = cmenu_add_submenu(keys->context_menu,_("Velocity"));
    velocity->private_struct = keys;
    Widget_t* vel = menu_add_value_entry(velocity, "128");
    vel->private_struct = keys;
    set_adjustment(vel->adj, 0.0, 0.0, 0.0, 127.0, 1.0, CL_CONTINUOS);
    adj_set_value(vel->adj, keys->velocity);
    vel->func.value_changed_callback = velocity_changed;
    keys->grab_keyboard = menu_add_check_item(keys->context_menu,_("Grab Keyboard"));
    keys->grab_keyboard->private_struct = keys;
    keys->grab_keyboard->func.value_changed_callback = grab_callback;
}
References MidiKeyboard::active_key, Widget_t::adj, adj_set_value(), Func_t::button_press_callback, Func_t::button_release_callback, MidiKeyboard::channel, CL_CONTINUOS, cmenu_add_submenu(), MidiKeyboard::context_menu, create_menu(), MidiKeyboard::custom_keys, Func_t::double_click_callback, EASTSOUTH, Func_t::expose_callback, Widget_t::flags, Widget_t::func, MidiKeyboard::grab_keyboard, Resize_t::gravity, HAS_MEM, MidiKeyboard::in_key_matrix, MidiKeyboard::in_motion, MidiKeyboard::key_matrix, MidiKeyboard::key_offset, Func_t::key_press_callback, Func_t::key_release_callback, MidiKeyboard::key_size, MidiKeyboard::keyboard, MidiKeyboard::last_active_key, MidiKeyboard::layout, Func_t::leave_callback, Func_t::mem_free_callback, menu_add_check_item(), menu_add_radio_entry(), menu_add_value_entry(), MidiKeyboard::mk_send_all_sound_off, MidiKeyboard::mk_send_note, Func_t::motion_callback, MidiKeyboard::new_active_key, MidiKeyboard::new_prelight_key, NO_AUTOREPEAT, MidiKeyboard::octave, MidiKeyboard::prelight_key, Widget_t::private_struct, read_keymap(), Widget_t::scale, MidiKeyboard::send_key, set_active_radio_entry_num(), set_adjustment(), Func_t::value_changed_callback, and MidiKeyboard::velocity.
Referenced by add_midi_keyboard(), and open_midi_keyboard().
add_midi_keyboard()
Widget_t * add_midi_keyboard (Widget_t * parent, const char * label, int x, int y, int width, int height)
Definition at line 906 of file xkeyboard.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    os_set_input_mask(wid);
    add_keyboard(wid, label);
    return wid;
}
References add_keyboard(), Widget_t::app, create_widget(), Widget_t::label, and os_set_input_mask().
clear_key_matrix()
void clear_key_matrix (unsigned long * key_matrix)
Definition at line 353 of file xkeyboard.c.
{
    int i = 0;
    int j = 0;
    for(;j<4;j++) {
        for(;i<32;i++) {
            key_matrix[j] &= (~(1 << i));
        }
        i = 0;
    }
}
custom_to_midi_key()
void custom_to_midi_key (long custom_keys[128][2], long inkey, float * midi_key)
Definition at line 272 of file xkeyboard.c.
{
    int i = 0;
    for(;i<129;i++) {
        int j = 0;
        for(;j<2;j++) {
            if (inkey == custom_keys[i][j]) {
                (*midi_key) = (float)i;
                return;
            }
        }
    }
}
have_key_in_matrix()
bool have_key_in_matrix (unsigned long * key_matrix)
Definition at line 336 of file xkeyboard.c.
{
    bool ret = false;
    int i = 0;
    int j = 0;
    for(;j<4;j++) {
        for(;i<32;i++) {
            if(key_matrix[j] & (1<<i)) {
                ret = true;
                break;
            }
        }
        i = 0;
    }
    return ret;
}
Referenced by need_redraw().
is_key_in_matrix()
bool is_key_in_matrix (unsigned long * key_matrix, int key)
Definition at line 305 of file xkeyboard.c.
{
    unsigned long *use_matrix = &key_matrix[0];
    if(key>94) {
        use_matrix = &key_matrix[3];
        key -=94;
    } else if(key>62) {
        use_matrix = &key_matrix[2];
        key -=62;
    } else if(key>31) {
        use_matrix = &key_matrix[1];
        key -= 31;
    }
    bool ret = false;
    if((*use_matrix) & (1<<key)) {
        ret = true;
    }
    return ret;
}
Referenced by is_key_in_in_matrix().
keysym_azerty_afnor_to_midi_key()
void keysym_azerty_afnor_to_midi_key (long inkey, float * midi_key)
Definition at line 158 of file xkeyboard.c.
{
    /* probably a future standard for azerty keyboards */
    switch(inkey) {
        case(XK_less) : (*midi_key) = 11.0; /* "<" = B-1 */
        break;
        case(XK_KP_Decimal) : (*midi_key) = 23.0; /* . */
        break;
        case(XK_semicolon) : (*midi_key) = 24.0; /* ; = C1 */
        break;
        case(XK_eacute) : (*midi_key) = 25.0; /*  */
        break;
        case(XK_colon) : (*midi_key) = 26.0; /* : */
        break;
        case(XK_quotedbl) : (*midi_key) = 27.0; /* " */
        break;
        case(XK_exclam) : (*midi_key) = 28.0; /* ! */
        break;
        case(XK_ugrave) : (*midi_key) = 29.0; /*  = F1 */
        break;
        case(XK_asterisk) : (*midi_key) = 30.0; /* * */
        break;
        case(XK_parenleft) : (*midi_key) = 30.0; /* ( */
        break;
        case(XK_minus) : (*midi_key) = 32.0; /* - */
        break;
        case(XK_egrave) : (*midi_key) = 34.0; /*  */
        break;
        case(XK_ccedilla) : (*midi_key) = 37.0; /*  */
        break;
        case(XK_agrave) : (*midi_key) = 39.0; /*  */
        break;
        case (XK_parenright) : (*midi_key) = 41.0; /* ) = F2 */
        break;
        case (XK_equal) : (*midi_key) = 42.0; /* = */
        break;
        case (XK_dollar) : (*midi_key) = 43.0; /* $ */
        break;
        default: keysym_azerty_to_midi_key(inkey, midi_key);
    }
}
References keysym_azerty_to_midi_key().
keysym_azerty_be_to_midi_key()
void keysym_azerty_be_to_midi_key (long inkey, float * midi_key)
Definition at line 117 of file xkeyboard.c.
{
    /* common azerty keyboards sell in Belgium (Wallonia) */
    switch(inkey) {
        case(XK_less) : (*midi_key) = 11.0; /* "<" = B-1 */
        break;
        case(XK_comma) : (*midi_key) = 23.0; /* , */
        break;
        case(XK_semicolon) : (*midi_key) = 24.0; /* ; = C1 */
        break;
        case(XK_eacute) : (*midi_key) = 25.0; /*  */
        break;
        case(XK_colon) : (*midi_key) = 26.0; /* : */
        break;
        case(XK_quotedbl) : (*midi_key) = 27.0; /* " */
        break;
        case(XK_equal) : (*midi_key) = 28.0; /* = */
        break;
        case(XK_ugrave) : (*midi_key) = 29.0; /*  = F1 */
        break;
        case(XK_mu) : (*midi_key) = 30.0; /*  */
        break;
        case(XK_parenleft) : (*midi_key) = 30.0; /* ( */
        break;
        case(XK_section) : (*midi_key) = 32.0; /*  */
        break;
        case(XK_egrave) : (*midi_key) = 34.0; /*  */
        break;
        case(XK_ccedilla) : (*midi_key) = 37.0; /*  */
        break;
        case(XK_agrave) : (*midi_key) = 39.0; /*  */
        break;
        case (XK_parenright) : (*midi_key) = 41.0; /* ) = F2 */
        break;
        case (XK_minus) : (*midi_key) = 42.0; /* - */
        break;
        case (XK_dollar) : (*midi_key) = 43.0; /* $ */
        break;
        default: keysym_azerty_to_midi_key(inkey, midi_key);
    }
}
References keysym_azerty_to_midi_key().
keysym_azerty_fr_to_midi_key()
void keysym_azerty_fr_to_midi_key (long inkey, float * midi_key)
Definition at line 76 of file xkeyboard.c.
{
    /* common azerty keyboards sell in France */
    switch(inkey) {
        case(XK_less) : (*midi_key) = 11.0; /* "<" = B-1 */
        break;
        case(XK_comma) : (*midi_key) = 23.0; /* , */
        break;
        case(XK_semicolon) : (*midi_key) = 24.0; /* ; = C1 */
        break;
        case(XK_eacute) : (*midi_key) = 25.0; /*  */
        break;
        case(XK_colon) : (*midi_key) = 26.0; /* : */
        break;
        case(XK_quotedbl) : (*midi_key) = 27.0; /* " */
        break;
        case(XK_exclam) : (*midi_key) = 28.0; /* ! */
        break;
        case(XK_ugrave) : (*midi_key) = 29.0; /*  = F1 */
        break;
        case(XK_asterisk) : (*midi_key) = 30.0; /* * */
        break;
        case(XK_parenleft) : (*midi_key) = 30.0; /* ( */
        break;
        case(XK_minus) : (*midi_key) = 32.0; /* - */
        break;
        case(XK_egrave) : (*midi_key) = 34.0; /*  */
        break;
        case(XK_ccedilla) : (*midi_key) = 37.0; /*  */
        break;
        case(XK_agrave) : (*midi_key) = 39.0; /*  */
        break;
        case (XK_parenright) : (*midi_key) = 41.0; /* ) = F2 */
        break;
        case (XK_equal) : (*midi_key) = 42.0; /* = */
        break;
        case (XK_dollar) : (*midi_key) = 43.0; /* $ */
        break;
        default: keysym_azerty_to_midi_key(inkey, midi_key);
    }
}
References keysym_azerty_to_midi_key().
keysym_azerty_to_midi_key()
void keysym_azerty_to_midi_key (long inkey, float * midi_key)
Definition at line 24 of file xkeyboard.c.
{
    /* these keys are common to all types of azerty keyboards */
    switch(inkey) {
        case(XK_w) : (*midi_key) = 12.0; /* w = C0 */
        break;
        case(XK_s) : (*midi_key) = 13.0; /* s */
        break;
        case(XK_x) : (*midi_key) = 14.0; /* x */
        break;
        case(XK_d) : (*midi_key) = 15.0; /* d */
        break;
        case(XK_c) : (*midi_key) = 16.0; /* c */
        break;
        case(XK_v) : (*midi_key) = 17.0; /* v */
        break;
        case(XK_g) : (*midi_key) = 18.0; /* g */
        break;
        case(XK_b) : (*midi_key) = 19.0; /* b */
        break;
        case(XK_h) : (*midi_key) = 20.0; /* h */
        break;
        case(XK_n) : (*midi_key) = 21.0; /* n */
        break;
        case(XK_j) : (*midi_key) = 22.0; /* j */
        break;
        case(XK_a) : (*midi_key) = 24.0; /* a = C1 */
        break;
        case(XK_l) : (*midi_key) = 25.0; /* l */
        break;
        case(XK_z) : (*midi_key) = 26.0; /* z */
        break;
        case(XK_m) : (*midi_key) = 27.0; /* m */
        break;
        case(XK_e) : (*midi_key) = 28.0; /* e */
        break;
        case(XK_r) : (*midi_key) = 29.0; /* r */
        break;
        case(XK_t) : (*midi_key) = 31.0; /* t */
        break;
        case(XK_y) : (*midi_key) = 33.0; /* y */
        break;
        case(XK_u) : (*midi_key) = 35.0; /* u */
        break;
        case(XK_i) : (*midi_key) = 36.0; /* i */
        break;
        case(XK_o) : (*midi_key) = 38.0; /* o */
        break;
        case(XK_p) : (*midi_key) = 40.0; /* p */
        break;
    }
}
Referenced by keysym_azerty_afnor_to_midi_key(), keysym_azerty_be_to_midi_key(), and keysym_azerty_fr_to_midi_key().
keysym_qwerty_to_midi_key()
void keysym_qwerty_to_midi_key (unsigned int inkey, float * midi_key)
Definition at line 266 of file xkeyboard.c.
{
    keysym_qwertz_to_midi_key(inkey,midi_key);
    if ((*midi_key) == 12) (*midi_key) = 33;
    else if ((*midi_key) == 33) (*midi_key) = 12;
}
References keysym_qwertz_to_midi_key().
keysym_qwertz_to_midi_key()
void keysym_qwertz_to_midi_key (long inkey, float * midi_key)
Definition at line 199 of file xkeyboard.c.
{
    switch(inkey) {
        case(XK_y) : (*midi_key) = 12.0; /* y = C0 */
        break;
        case(XK_s) : (*midi_key) = 13.0; /* s */
        break;
        case(XK_x) : (*midi_key) = 14.0; /* x */
        break;
        case(XK_d) : (*midi_key) = 15.0; /* d */
        break;
        case(XK_c) : (*midi_key) = 16.0; /* c */
        break;
        case(XK_v) : (*midi_key) = 17.0; /* v */
        break;
        case(XK_g) : (*midi_key) = 18.0; /* g */
        break;
        case(XK_b) : (*midi_key) = 19.0; /* b */
        break;
        case(XK_h) : (*midi_key) = 20.0; /* h */
        break;
        case(XK_n) : (*midi_key) = 21.0; /* n */
        break;
        case(XK_j) : (*midi_key) = 22.0; /* j */
        break;
        case(XK_m) : (*midi_key) = 23.0; /* m */
        break;
        case(XK_q) : (*midi_key) = 24.0; /* q */
        break;
        case(XK_2) : (*midi_key) = 25.0; /* 2 */
        break;
        case(XK_w) : (*midi_key) = 26.0; /* w */
        break;
        case(XK_3) : (*midi_key) = 27.0; /* 3 */
        break;
        case(XK_e) : (*midi_key) = 28.0; /* e */
        break;
        case(XK_r) : (*midi_key) = 29.0; /* r */
        break;
        case(XK_5) : (*midi_key) = 30.0; /* 5 */
        break;
        case(XK_t) : (*midi_key) = 31.0; /* t */
        break;
        case(XK_6) : (*midi_key) = 32.0; /* 6 */
        break;
        case(XK_z) : (*midi_key) = 33.0; /* z */
        break;
        case(XK_7) : (*midi_key) = 34.0; /* 7 */
        break;
        case(XK_u) : (*midi_key) = 35.0; /* u */
        break;
        case(XK_i) : (*midi_key) = 36.0; /* i */
        break;
        case(XK_9) : (*midi_key) = 37.0; /* 9 */
        break;
        case(XK_o) : (*midi_key) = 38.0; /* o */
        break;
        case(XK_0) : (*midi_key) = 39.0; /* 0 */
        break;
        case(XK_p) : (*midi_key) = 40.0; /* p */
        break;
        case(XK_udiaeresis) : (*midi_key) = 41.0; /*  */
        break;
        case(XK_plus) : (*midi_key) = 42.0; /* + */
        break;
    }
}
Referenced by keysym_qwerty_to_midi_key().
need_redraw()
bool need_redraw (MidiKeyboard * keys)
Definition at line 830 of file xkeyboard.c.
{
    bool have = false;
    int i = 0;
    for(;i<16;i++) {
        if (have_key_in_matrix(keys->in_key_matrix[i])) {
            have = true;
            break;
        }
    }
    return (keys->active_key > 0 ? 1 : 0) |
    (keys->prelight_key  > 0 ? 1 : 0)  |
    have_key_in_matrix(keys->key_matrix) |
    have;
}
References MidiKeyboard::active_key, have_key_in_matrix(), MidiKeyboard::in_key_matrix, MidiKeyboard::key_matrix, and MidiKeyboard::prelight_key.
open_midi_keyboard()
Widget_t * open_midi_keyboard (Widget_t * w, const char * label)
Definition at line 915 of file xkeyboard.c.
{
    Widget_t *wid = create_window(w->app, os_get_root_window(w->app, IS_WINDOW), 0, 0, 700, 200);
    os_set_input_mask(wid);
    add_keyboard(wid, label);
    wid->parent = w;
    return wid;
}
References add_keyboard(), Widget_t::app, create_window(), IS_WINDOW, os_get_root_window(), os_set_input_mask(), and Widget_t::parent.
read_keymap()
void read_keymap (const char * keymapfile, long keys[128][2])
Definition at line 878 of file xkeyboard.c.
{
    if( access(keymapfile, F_OK ) != -1 ) {
        FILE *fp;
        if((fp=fopen(keymapfile, "rb"))==NULL) {
            fprintf(stderr,"Cannot open file.\n");
        }
        if(fread(keys, sizeof(long), 128*2, fp) != 128*2) {
            if(feof(fp))
            fprintf(stderr,"Premature end of file.");
            else
            fprintf(stderr,"File read error.");
        }
        fclose(fp);
    }
}
Referenced by add_keyboard().
set_key_in_matrix()
void set_key_in_matrix (unsigned long * key_matrix, int key, bool set)
Definition at line 285 of file xkeyboard.c.
{
    unsigned long *use_matrix = &key_matrix[0];
    if(key>94) {
        use_matrix = &key_matrix[3];
        key -=94;
    } else if(key>62) {
        use_matrix = &key_matrix[2];
        key -=62;
    } else if(key>31) {
        use_matrix = &key_matrix[1];
        key -= 31;
    }
    if (set) {
        (*use_matrix) |= (1 << key);
    }else {
        (*use_matrix) &= (~(1 << key));
    }
}