libxputty: xputty/header/widgets/xknob_private.h File Reference
xknob_private.h File Reference
Functions
void _draw_image_knob (Widget_t *w, int width_t, int height_t)
_draw_image_knob - internal draw the knob from image to the buffer
void _draw_knob_image (void *w_, void *user_data)
_draw_knob_image - internal draw the knob to the buffer
void _draw_knob (void *w_, void *user_data)
_draw_knob - internal draw the knob to the buffer
void _knob_released (void *w_, void *button_, void *user_data)
_knob_released - redraw the slider when buttob released
Function Documentation
_draw_image_knob()
void _draw_image_knob (Widget_t * w, int width_t, int height_t)
_draw_image_knob - internal draw the knob from image to the buffer
Parameters
*w - pointer to the Widget_t knob
Returns
void
Definition at line 35 of file xknob_private.c.
{
    int width, height;
    os_get_surface_size(w->image, &width, &height);
    double x = (double)width_t/(double)height;
    double y = (double)height/(double)width_t;
    double knobstate = adj_get_state(w->adj_y);
    int findex = (int)(((width/height)-1) * knobstate);
    int posx = 0;
    int posy = (height_t/2 - ((height*x)/2));
    if (width_t > height_t) {
        x = (double)height_t/(double)height;
        y = (double)height/(double)height_t;
        posx = (width_t/2 -((height*x)/2));
        posy = 0;
    }
    cairo_save(w->crb);
    cairo_scale(w->crb, x,x);
    cairo_translate(w->crb, posx * ((1-x)/x), posy * ((1-x)/x));
    cairo_set_source_surface (w->crb, w->image, -height*findex + posx, posy);
    cairo_rectangle(w->crb, posx, posy, height, height);
    cairo_fill(w->crb);
    cairo_scale(w->crb, y,y);
    cairo_restore(w->crb);
}
References adj_get_state(), Widget_t::adj_y, Widget_t::crb, Widget_t::image, and os_get_surface_size().
Referenced by _draw_knob(), and _draw_knob_image().
_draw_knob()
void _draw_knob (void * w_, void * user_data)
_draw_knob - internal draw the knob to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Returns
void
get values for the knob
create a rotating pointer on the kob
show value on the kob
Definition at line 66 of file xknob_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    const double scale_zero = 20 * (M_PI/180); // defines "dead zone" for knobs
    int arc_offset = 0;
    int knob_x = 0;
    int knob_y = 0;
    int grow = (width > height) ? height:width;
    knob_x = grow-1;
    knob_y = grow-1;
    int knobx = (width - knob_x) * 0.5;
    int knobx1 = width* 0.5;
    int knoby = (height - knob_y) * 0.5;
    int knoby1 = height * 0.5;
    if (w->image) {
        _draw_image_knob(w, width, height);
    } else {
        double knobstate = adj_get_state(w->adj_y);
        double angle = scale_zero + knobstate * 2 * (M_PI - scale_zero);
        double pointer_off =knob_x/6;
        double radius = min(knob_x-pointer_off, knob_y-pointer_off) / 2;
        double lengh_x = (knobx+radius+pointer_off/2) - radius * sin(angle);
        double lengh_y = (knoby+radius+pointer_off/2) + radius * cos(angle);
        double radius_x = (knobx+radius+pointer_off/2) - radius/ 1.24 * sin(angle);
        double radius_y = (knoby+radius+pointer_off/2) + radius/ 1.24 * cos(angle);
        cairo_arc(w->crb,knobx1+arc_offset, knoby1+arc_offset, knob_x/2.1, 0, 2 * M_PI );
        use_shadow_color_scheme(w, get_color_state(w));
        cairo_fill (w->crb);
        cairo_new_path (w->crb);
        use_bg_color_scheme(w, get_color_state(w));
        cairo_arc(w->crb,knobx1+arc_offset, knoby1+arc_offset, knob_x/3.1, 0, 2 * M_PI );
        cairo_fill_preserve(w->crb);
        use_fg_color_scheme(w, NORMAL_);
        cairo_set_line_width(w->crb, min(3.0, knobx1/15));
        cairo_stroke(w->crb);
        cairo_new_path (w->crb);
        cairo_set_line_cap(w->crb, CAIRO_LINE_CAP_ROUND);
        cairo_set_line_join(w->crb, CAIRO_LINE_JOIN_BEVEL);
        cairo_move_to(w->crb, radius_x, radius_y);
        cairo_line_to(w->crb,lengh_x,lengh_y);
        cairo_set_line_width(w->crb,min(6.0, knobx1/7));
        use_fg_color_scheme(w, NORMAL_);
        cairo_stroke(w->crb);
        cairo_new_path (w->crb);
    }
    use_text_color_scheme(w, get_color_state(w));
    cairo_text_extents_t extents;
    if (w->state) {
        char s[64];
        const char* format[] = {"%.1f", "%.2f", "%.3f"};
        float value = adj_get_value(w->adj);
        if (fabs(w->adj->step)>0.99) {
            snprintf(s, 63,"%d",  (int) value);
        } else if (fabs(w->adj->step)>0.09) {
            snprintf(s, 63, format[1-1], value);
        } else {
            snprintf(s, 63, format[2-1], value);
        }
        cairo_set_font_size (w->crb, w->app->small_font/w->scale.ascale);
        cairo_text_extents(w->crb, s, &extents);
        cairo_move_to (w->crb, knobx1-extents.width/2, knoby1+extents.height/2);
        cairo_show_text(w->crb, s);
        cairo_new_path (w->crb);
    }
    _show_label(w, width, height);
}
References _draw_image_knob(), Widget_t::adj, adj_get_state(), adj_get_value(), Widget_t::adj_y, Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::image, NORMAL_, os_get_window_metrics(), Widget_t::scale, Xputty::small_font, Widget_t::state, Adjustment_t::step, use_bg_color_scheme(), use_fg_color_scheme(), use_shadow_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by add_knob().
_draw_knob_image()
void _draw_knob_image (void * w_, void * user_data)
_draw_knob_image - internal draw the knob to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Returns
void
Definition at line 60 of file xknob_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    _draw_image_knob(w, w->width, w->height);
    _show_label(w, w->width-2, w->height-2);
}
References _draw_image_knob(), Widget_t::height, and Widget_t::width.
Referenced by add_image_knob().
_knob_released()
void _knob_released (void * w_, void * button_, void * user_data)
_knob_released - redraw the slider when buttob released
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Returns
void
Definition at line 151 of file xknob_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (w->flags & HAS_POINTER) w->state= 1;
    expose_widget(w);
}
References expose_widget(), Widget_t::flags, HAS_POINTER, and Widget_t::state.
Referenced by add_image_knob(), and add_knob().