libxputty: xputty/header/widgets/xknob.h File Reference
xknob.h File Reference
Functions
Widget_t * add_knob (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_knob - add a knob to a Widget_t connect to func.value_changed_callback to implement your actions use set_adjustment(w->adj_y, . .) to set the range you need
Widget_t * add_image_knob (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_image_knob - add a knob from image to a Widget_t without value display on the knob connect to func.value_changed_callback to implement your actions use set_adjustment(w->adj_y, . .) to set the range you need
Function Documentation
add_image_knob()
Widget_t * add_image_knob (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_image_knob - add a knob from image to a Widget_t without value display on the knob connect to func.value_changed_callback to implement your actions use set_adjustment(w->adj_y, . .) to set the range you need
Parameters
*parent - pointer to the Widget_t request the button
*label - Label to show on the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 41 of file xknob.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,0.01, CL_CONTINUOS);
    wid->adj = wid->adj_y;
    wid->scale.gravity = ASPECT;
    wid->func.expose_callback = _draw_knob_image;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_release_callback = _knob_released;
    return wid;
}
References _draw_knob_image(), _knob_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, ASPECT, Func_t::button_release_callback, CL_CONTINUOS, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
Referenced by add_my_image_knob().
add_knob()
Widget_t * add_knob (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_knob - add a knob to a Widget_t connect to func.value_changed_callback to implement your actions use set_adjustment(w->adj_y, . .) to set the range you need
Parameters
*parent - pointer to the Widget_t request the button
*label - Label to show on the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 26 of file xknob.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,0.01, CL_CONTINUOS);
    wid->adj = wid->adj_y;
    wid->scale.gravity = ASPECT;
    wid->func.expose_callback = _draw_knob;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_release_callback = _knob_released;
    return wid;
}
References _draw_knob(), _knob_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, ASPECT, Func_t::button_release_callback, CL_CONTINUOS, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.
Referenced by add_keyboard_knob(), add_my_knob(), and add_my_value_knob().