libxputty: xputty/widgets/xlabel_private.c File Reference
xlabel_private.c File Reference
Functions
void _draw_label (void *w_, void *user_data)
_draw_label - internal draw the label to the buffer
Function Documentation
_draw_label()
void _draw_label (void * w_, void * user_data)
_draw_label - internal draw the label to the buffer
Parameters
*w_ - void pointer to the Widget_t label
*user_data - void pointer to attached user_data
Returns
void
Definition at line 25 of file xlabel_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    cairo_text_extents_t extents;
    use_text_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    cairo_text_extents(w->crb,w->label , &extents);
    cairo_move_to (w->crb, (width*0.5)-(extents.width/2), height-(extents.height/4));
    cairo_show_text(w->crb, w->label);
    cairo_new_path (w->crb);
}
References Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::label, Xputty::normal_font, os_get_window_metrics(), Widget_t::scale, use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by add_label().