libxputty: xputty/header/widgets/xlistview.h File Reference
xlistview.h File Reference
Data Structures
struct ViewList_t
ViewList_t - struct to hold information for the listview.
Functions
void listview_set_active_entry (Widget_t *w, int active)
listview_set_active_entry - set the active listview entry
void listview_unset_active_entry (Widget_t *w)
listview_unset_active_entry - unset the active listview entry
Widget_t * create_listview_viewport (Widget_t *parent, int elem, int width, int height)
create_listview_viewport - create a viewport on a listview to a Widget_t
Widget_t * add_listview (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_label - add a listview to a Widget_t
void listview_mem_free (void *w_, void *user_data)
listview_mem_free - release additional used memory when destroy the Widget_t
void listview_remove_list (Widget_t *listview)
listview_remove_list - remove the list from a listview Widget_t
void listview_set_list (Widget_t *listview, char **list, int list_size)
listview_set_list - set a list to a listview Widget_t
void listview_set_check_dir (Widget_t *listview, int set)
listview_set_check_dir - set optional check if list item is a directory
Function Documentation
add_listview()
Widget_t * add_listview (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_label - add a listview to a Widget_t
Parameters
*parent - pointer to the Widget_t request the label
*label - Label to show on the button
x,y,width,height - the position/geometry to create the label
Returns
Widget_t* - pointer to the Widget_t label struct
Definition at line 72 of file xlistview.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->scale.gravity = CENTER;
    wid->flags &= ~USE_TRANSPARENCY;
    wid->func.expose_callback = _draw_listview;
    int elem = height/25;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_NONE);
    wid->adj = wid->adj_y;
    Widget_t *viewport = create_listview_viewport(wid, elem, width-10, height);
    ViewList_t *filelist = (ViewList_t*)viewport->parent_struct;
    filelist->folder = surface_get_png(wid, filelist->folder, LDVAR(directory_png));
    filelist->file = surface_get_png(wid, filelist->file, LDVAR(file_png));
    filelist->slider = add_vslider(wid, "", width-10, 0, 10, height);
    filelist->slider->func.expose_callback = _draw_listviewslider;
    filelist->slider->adj_y = add_adjustment(filelist->slider,0.0, 0.0, 0.0, 1.0,0.0085, CL_VIEWPORTSLIDER);
    filelist->slider->adj = filelist->slider->adj_y;
    filelist->slider->func.value_changed_callback = _set_listviewport;
    filelist->slider->scale.gravity = WESTSOUTH;
    filelist->slider->flags &= ~USE_TRANSPARENCY;
    filelist->slider->flags |= NO_AUTOREPEAT | NO_PROPAGATE;
    filelist->slider->parent_struct = viewport;
    return wid;
}
References _draw_listview(), _draw_listviewslider(), _set_listviewport(), add_adjustment(), add_vslider(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, CENTER, CL_NONE, CL_VIEWPORTSLIDER, create_listview_viewport(), create_widget(), Func_t::expose_callback, ViewList_t::file, Widget_t::flags, ViewList_t::folder, Widget_t::func, Resize_t::gravity, Widget_t::label, NO_AUTOREPEAT, NO_PROPAGATE, Widget_t::parent_struct, Widget_t::scale, ViewList_t::slider, surface_get_png(), Func_t::value_changed_callback, and WESTSOUTH.
Referenced by open_directory_dialog(), and save_file_dialog().
create_listview_viewport()
Widget_t * create_listview_viewport (Widget_t * parent, int elem, int width, int height)
create_listview_viewport - create a viewport on a listview to a Widget_t
Parameters
*parent - pointer to the Widget_t the listview should pop over
width - define the width of the viewport
height - define the height of the viewport
Returns
Widget_t* - pointer to the Widget_t viewport
Definition at line 46 of file xlistview.c.
{
    Widget_t *wid = create_widget(parent->app, parent, 0, 0, width, height);
    os_set_input_mask(wid);
    wid->scale.gravity = NORTHWEST;
    ViewList_t *filelist;
    filelist = (ViewList_t*)malloc(sizeof(ViewList_t));
    filelist->show_items = elem;
    filelist->check_dir = 0;
    wid->flags |= HAS_MEM;
    wid->parent_struct = filelist;
    float max_value = -elem;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
    wid->adj = wid->adj_y;
    wid->func.adj_callback = _set_listview_viewpoint;
    wid->func.motion_callback = _list_motion;
    wid->func.leave_callback = _leave_list;
    wid->func.button_release_callback = _list_entry_released;
    wid->func.double_click_callback = _list_entry_double_clicked;
    wid->func.key_press_callback = _list_key_pressed;
    wid->func.expose_callback = _draw_list;
    wid->func.configure_notify_callback = _reconfigure_listview_viewport;
    wid->func.map_notify_callback = _configure_listview;
    wid->func.mem_free_callback = listview_mem_free;
    return wid;
}
References _configure_listview(), _draw_list(), _leave_list(), _list_entry_double_clicked(), _list_entry_released(), _list_key_pressed(), _list_motion(), _reconfigure_listview_viewport(), _set_listview_viewpoint(), add_adjustment(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, Func_t::button_release_callback, ViewList_t::check_dir, CL_VIEWPORT, Func_t::configure_notify_callback, create_widget(), Func_t::double_click_callback, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, Func_t::key_press_callback, Func_t::leave_callback, listview_mem_free(), Func_t::map_notify_callback, Func_t::mem_free_callback, Func_t::motion_callback, NORTHWEST, os_set_input_mask(), Widget_t::parent_struct, Widget_t::scale, and ViewList_t::show_items.
Referenced by add_listview().
listview_mem_free()
void listview_mem_free (void * w_, void * user_data)
listview_mem_free - release additional used memory when destroy the Widget_t
Parameters
*w_ - void pointer to the Widget_t
*user_data - void pointer to attached user_data
Returns
void
Definition at line 101 of file xlistview.c.
{
    Widget_t *w = (Widget_t*)w_;
    ViewList_t *filelist = (ViewList_t*)w->parent_struct;
    cairo_surface_destroy(filelist->folder);
    cairo_surface_destroy(filelist->file);
    free(filelist);
}
References ViewList_t::file, ViewList_t::folder, and Widget_t::parent_struct.
Referenced by create_listview_viewport().
listview_remove_list()
void listview_remove_list (Widget_t * listview)
listview_remove_list - remove the list from a listview Widget_t
Parameters
*listview - pointer to the Widget_t listview which should show the list
Returns
void
Definition at line 109 of file xlistview.c.
{
    Widget_t* view_port =  listview->childlist->childs[0];
    ViewList_t *filelist = (ViewList_t*)view_port->parent_struct;
    filelist->list_names = NULL;
    filelist->list_size = 0;
    Metrics_t metrics;
    os_get_window_metrics(listview, &metrics);
    int height = metrics.height;
    float elem = height/25;
    set_adjustment(listview->adj,0.0, 0.0, 0.0, -1.0,1.0, CL_NONE);
    set_adjustment(view_port->adj,0.0, 0.0, 0.0, -elem,1.0, CL_VIEWPORT);
    adj_set_value(filelist->slider->adj,0.0);
}
References Widget_t::adj, adj_set_value(), Widget_t::childlist, Childlist_t::childs, CL_NONE, CL_VIEWPORT, Metrics_t::height, ViewList_t::list_names, ViewList_t::list_size, os_get_window_metrics(), Widget_t::parent_struct, set_adjustment(), and ViewList_t::slider.
listview_set_active_entry()
void listview_set_active_entry (Widget_t * w, int active)
listview_set_active_entry - set the active listview entry
Parameters
*w_ - void pointer to the Widget_t listview
active - the active entry (int)
Returns
void
Definition at line 28 of file xlistview.c.
{
    if(active<0) return;
    Widget_t* view_port =  w->childlist->childs[0];
    ViewList_t *filelist = (ViewList_t*)view_port->parent_struct;
    float value = (float)active;
    if (value>w->adj->max_value) value = w->adj->max_value;
    else if (value<w->adj->min_value) value = w->adj->min_value;
    filelist->active_item = (int)value;
    adj_set_value(w->adj,filelist->active_item);
}
References ViewList_t::active_item, Widget_t::adj, adj_set_value(), Widget_t::childlist, Childlist_t::childs, Adjustment_t::max_value, Adjustment_t::min_value, and Widget_t::parent_struct.
Referenced by open_directory_dialog(), and save_file_dialog().
listview_set_check_dir()
void listview_set_check_dir (Widget_t * listview, int set)
listview_set_check_dir - set optional check if list item is a directory
Parameters
*listview - pointer to the Widget_t listview which should show the list
set - 0 = no check (default); 1 = check
Returns
void
Definition at line 134 of file xlistview.c.
{
    Widget_t* view_port =  listview->childlist->childs[0];
    ViewList_t *filelist = (ViewList_t*)view_port->parent_struct;
    filelist->check_dir = set;
}
References ViewList_t::check_dir, Widget_t::childlist, Childlist_t::childs, and Widget_t::parent_struct.
Referenced by save_file_dialog().
listview_set_list()
void listview_set_list (Widget_t * listview, char ** list, int list_size)
listview_set_list - set a list to a listview Widget_t
Parameters
*listview - pointer to the Widget_t listview which should show the list
**list - pointer to the list
list_size - how many items contain the list
Returns
void
Definition at line 123 of file xlistview.c.
{
    Widget_t* view_port =  listview->childlist->childs[0];
    ViewList_t *filelist = (ViewList_t*)view_port->parent_struct;
    filelist->list_names = list;
    filelist->list_size = list_size;
    set_adjustment(listview->adj,0.0, 0.0, 0.0, (float)(list_size-1.0),1.0, CL_NONE);
    float max_value = view_port->adj->max_value+ (float)list_size;
    set_adjustment(view_port->adj,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
    _configure_listview(view_port, NULL);
}
References _configure_listview(), Widget_t::adj, Widget_t::childlist, Childlist_t::childs, CL_NONE, CL_VIEWPORT, ViewList_t::list_names, ViewList_t::list_size, Adjustment_t::max_value, Widget_t::parent_struct, and set_adjustment().
listview_unset_active_entry()
void listview_unset_active_entry (Widget_t * w)
listview_unset_active_entry - unset the active listview entry
Parameters
*w_ - void pointer to the Widget_t listview
Returns
void
Definition at line 39 of file xlistview.c.
{
    Widget_t* view_port =  w->childlist->childs[0];
    ViewList_t *filelist = (ViewList_t*)view_port->parent_struct;
    filelist->active_item = -1;
    filelist->prelight_item = -1;
}
References ViewList_t::active_item, Widget_t::childlist, Childlist_t::childs, Widget_t::parent_struct, and ViewList_t::prelight_item.
Referenced by save_file_dialog().