libxputty: xputty/widgets/xlistbox_private.c File Reference
xlistbox_private.c File Reference
Functions
void _draw_listbox (void *w_, void *user_data)
_draw_listbox - draw listbox on expose call
void _draw_listbox_item (void *w_, void *user_data)
_draw_listbox_item - draw item on expose call
void _reconfigure_listbox_viewport (void *w_, void *user_data)
_reconfigure_listbox_viewport - reconfigure the viewport adjustment on size changes
void _configure_listbox (void *w_, void *user_data)
_configure_listbox - configure the viewport on mapping
void _draw_listbox_viewslider (void *w_, void *user_data)
_draw_listbox_viewslider - draw a slider on the viewport to indicate the view point
void _set_listbox_viewpoint (void *w_, void *user_data)
_set_listbox_viewpoint - move the view_port to position
void _listbox_entry_released (void *w_, void *button_, void *user_data)
_listbox_entry_released - redraw the slider when buttob released
Function Documentation
_configure_listbox()
void _configure_listbox (void * w_, void * user_data)
_configure_listbox - configure the viewport on mapping
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 90 of file xlistbox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    int si = max(1,childlist_has_child(w->childlist));
    Widget_t* listbox = (Widget_t*)w->parent;
    Metrics_t metrics;
    os_get_window_metrics(listbox, &metrics);
    int width = metrics.width;
    os_resize_window (w->app->dpy, w, width, 25*(si));
}
References Widget_t::app, Widget_t::childlist, childlist_has_child(), Xputty::dpy, os_get_window_metrics(), os_resize_window(), Widget_t::parent, and Metrics_t::width.
Referenced by create_listbox_viewport().
_draw_listbox()
void _draw_listbox (void * w_, void * user_data)
_draw_listbox - draw listbox on expose call
Parameters
*w_ - the listbox to draw
*user_data - attached user_data
Returns
void
Definition at line 26 of file xlistbox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    use_bg_color_scheme(w, NORMAL_);
    cairo_paint (w->crb);
}
References Widget_t::crb, NORMAL_, and use_bg_color_scheme().
Referenced by add_listbox().
_draw_listbox_item()
void _draw_listbox_item (void * w_, void * user_data)
_draw_listbox_item - draw item on expose call
Parameters
*w_ - the item to draw
*user_data - attached user_data
Returns
void
show label
Definition at line 33 of file xlistbox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    Widget_t* view_port = (Widget_t*)w->parent;
    Widget_t* listbox =  (Widget_t*)view_port->parent;
    int j = (int)listbox->adj->value;
    if(w == view_port->childlist->childs[j])
      w->state = (w->state == 1) ? 1 : 3;
    use_base_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, 0, 0, width , height);
    if(w->state==1) {
        use_base_color_scheme(w, PRELIGHT_);
    } else if(w->state==2) {
        use_base_color_scheme(w, SELECTED_);
    } else if(w->state==3) {
        use_base_color_scheme(w, ACTIVE_);
    }
    cairo_fill_preserve(w->crb);
    cairo_set_line_width(w->crb, 1.0);
    use_frame_color_scheme(w, PRELIGHT_);
    cairo_stroke(w->crb);
    cairo_text_extents_t extents;
    use_text_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb, height/2);
    cairo_text_extents(w->crb,w->label , &extents);
    cairo_move_to (w->crb, (width-extents.width)/2., height - extents.height );
    cairo_show_text(w->crb, w->label);
    cairo_new_path (w->crb);
    if (extents.width > (float)width) {
        tooltip_set_text(w,w->label);
        w->flags |= HAS_TOOLTIP;
    } else {
        w->flags &= ~HAS_TOOLTIP;
    }
}
References ACTIVE_, Widget_t::adj, Widget_t::childlist, Childlist_t::childs, Widget_t::crb, Widget_t::flags, get_color_state(), HAS_TOOLTIP, Metrics_t::height, Widget_t::label, NORMAL_, os_get_window_metrics(), Widget_t::parent, PRELIGHT_, SELECTED_, Widget_t::state, tooltip_set_text(), use_base_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), Adjustment_t::value, Metrics_t::visible, and Metrics_t::width.
Referenced by listbox_add_entry().
_draw_listbox_viewslider()
void _draw_listbox_viewslider (void * w_, void * user_data)
_draw_listbox_viewslider - draw a slider on the viewport to indicate the view point
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 100 of file xlistbox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    int v = (int)w->adj->max_value;
    if (!v) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    if (!metrics.visible) return;
    float sliderstate = adj_get_state(w->adj);
    use_bg_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, width-5,0,5,height);
    cairo_fill_preserve(w->crb);
    use_base_color_scheme(w, NORMAL_);
    cairo_fill(w->crb);
    use_bg_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, width-5,(height-10)*sliderstate,5,10);
    cairo_fill_preserve(w->crb);
    use_fg_color_scheme(w, NORMAL_);
    cairo_set_line_width(w->crb,1);
    cairo_stroke(w->crb);
}
References Widget_t::adj, adj_get_state(), Widget_t::crb, Metrics_t::height, Adjustment_t::max_value, NORMAL_, os_get_window_metrics(), use_base_color_scheme(), use_bg_color_scheme(), use_fg_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by create_listbox_viewport().
_listbox_entry_released()
void _listbox_entry_released (void * w_, void * button_, void * user_data)
_listbox_entry_released - redraw the slider when buttob released
Parameters
*w_ - void pointer to the Widget_t entry
*button_ - void pointer to the XButtonEvent
*user_data - void pointer to attached user_data
Returns
void
Definition at line 132 of file xlistbox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t* view_port = (Widget_t*)w->parent;
    int direction = 0 ;
    if (w->flags & HAS_POINTER) {
        XButtonEvent *xbutton = (XButtonEvent*)button_;
        if(xbutton->button == Button1) {
            Widget_t* listbox =  (Widget_t*)view_port->parent;
            int i = view_port->childlist->elem-1;
            int old_value = (int) listbox->adj->value;
            for(;i>-1;i--) {
                Widget_t *wid = view_port->childlist->childs[i];
                if (xbutton->window == wid->widget) {
                    const char *l = view_port->childlist->childs[i]->label;
                    float value = (float)i;
                    check_value_changed(listbox->adj, &value);
                    wid->state= 3;
                    listbox->func.button_release_callback(listbox, &i, &l);
                }
                wid->state= 0;
            }
            expose_widget(view_port->childlist->childs[old_value]);
            expose_widget(w);
        } else if(xbutton->button == Button4) {
            direction = 1;
        } else if(xbutton->button == Button5) {
            direction = -1;
        }
        if (direction !=0) {
            float value = view_port->adj->value + (view_port->adj->step * -direction);
            if (value>view_port->adj->max_value) value = view_port->adj->max_value;
            if (value<view_port->adj->min_value) value = view_port->adj->min_value;
            check_value_changed(view_port->adj, &value);
        }
    }
}
References Widget_t::adj, XEvent::button, Func_t::button_release_callback, check_value_changed(), Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, expose_widget(), Widget_t::flags, Widget_t::func, HAS_POINTER, Widget_t::label, Adjustment_t::max_value, Adjustment_t::min_value, Widget_t::parent, Widget_t::state, Adjustment_t::step, Adjustment_t::value, Widget_t::widget, and XEvent::window.
Referenced by listbox_add_entry().
_reconfigure_listbox_viewport()
void _reconfigure_listbox_viewport (void * w_, void * user_data)
_reconfigure_listbox_viewport - reconfigure the viewport adjustment on size changes
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 77 of file xlistbox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    float st = adj_get_state(w->adj);
    Widget_t* listbox = (Widget_t*)w->parent;
    Metrics_t metrics;
    os_get_window_metrics(listbox, &metrics);
    int height = metrics.height-2;
    int elem = height/25;
    int si = childlist_has_child(w->childlist);
    w->adj->max_value = si-elem;
    adj_set_state(w->adj,st);
}
References Widget_t::adj, adj_get_state(), adj_set_state(), Widget_t::childlist, childlist_has_child(), Metrics_t::height, Adjustment_t::max_value, os_get_window_metrics(), and Widget_t::parent.
Referenced by create_listbox_viewport().
_set_listbox_viewpoint()
void _set_listbox_viewpoint (void * w_, void * user_data)
_set_listbox_viewpoint - move the view_port to position
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 123 of file xlistbox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    int v = (int)adj_get_value(w->adj);
    Metrics_t metrics;
    os_get_window_metrics(w->childlist->childs[0], &metrics);
    int height = metrics.height;
    os_move_window(w->app->dpy,w,0, -height*v);
}
References Widget_t::adj, adj_get_value(), Widget_t::app, Widget_t::childlist, Childlist_t::childs, Xputty::dpy, Metrics_t::height, os_get_window_metrics(), and os_move_window().
Referenced by create_listbox_viewport().