libxputty: xputty/widgets/xlistview_private.c File Reference
xlistview_private.c File Reference
Functions
void _draw_listview (void *w_, void *user_data)
_draw_listview - draw listview on expose call
void _draw_list (void *w_, void *user_data)
_draw_list - draw list on expose call
void _update_list_view (void *w_)
void _list_motion (void *w_, void *xmotion_, void *user_data)
_list_motion - follow mouse pointer to set prelight item
void _list_key_pressed (void *w_, void *xkey_, void *user_data)
_list_key_pressed - move listview or set active entry
void _list_entry_released (void *w_, void *button_, void *user_data)
_list_entry_released - move listview or set active entry
void _list_entry_double_clicked (void *w_, void *button_, void *user_data)
_list_entry_double_clicke - forward double click from list entry to list view
void _leave_list (void *w_, void *user_data)
_leave_list - draw list on pointer leave
void _reconfigure_listview_viewport (void *w_, void *user_data)
_reconfigure_listview_viewport - reconfigure the viewport adjustment on size changes
void _configure_listview (void *w_, void *user_data)
_configure_listview - configure the viewport on mapping
void _set_listview_viewpoint (void *w_, void *user_data)
_set_listview_viewpoint - move the view_port to position
void _draw_listviewslider (void *w_, void *user_data)
_draw_listviewslider - draw a slider on the viewport to indicate the view point
void _set_listviewport (void *w_, void *user_data)
_set_listviewport - move the view_port to position by listviewslider state
Function Documentation
_configure_listview()
void _configure_listview (void * w_, void * user_data)
_configure_listview - configure the viewport on mapping
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 306 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t* listview = (Widget_t*) w->parent;
    ViewList_t *filelist = (ViewList_t*)w->parent_struct;
    Metrics_t metrics;
    os_get_window_metrics(listview, &metrics);
    int height = metrics.height;
    int width = metrics.width;
    filelist->show_items = height/25;
    filelist->slider->adj->step = max(0.0,1.0/(filelist->list_size-filelist->show_items));
    adj_set_scale(filelist->slider->adj, ((float)filelist->list_size/(float)filelist->show_items)/25.0);
    os_resize_window (w->app->dpy, w, width, height);
}
References Widget_t::adj, adj_set_scale(), Widget_t::app, Xputty::dpy, Metrics_t::height, ViewList_t::list_size, os_get_window_metrics(), os_resize_window(), Widget_t::parent, Widget_t::parent_struct, ViewList_t::show_items, ViewList_t::slider, Adjustment_t::step, and Metrics_t::width.
Referenced by create_listview_viewport(), and listview_set_list().
_draw_list()
void _draw_list (void * w_, void * user_data)
_draw_list - draw list on expose call
Parameters
*w_ - the Widget_t to draw
*user_data - attached user_data
Returns
void
show label
Definition at line 34 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    if (!metrics.visible) return;
    ViewList_t *filelist = (ViewList_t*)w->parent_struct;
    use_base_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, 0, 0, width, height);
    cairo_fill (w->crb);
    cairo_set_font_size (w->crb, min(w->app->big_font ,w->app->normal_font/w->scale.ascale));
    cairo_text_extents_t extents;
    cairo_text_extents(w->crb,"Ay", &extents);
    double h = extents.height;
    int i = (int)max(0,adj_get_value(w->adj));
    int a = 0;
    int j = filelist->list_size<filelist->show_items+i+1 ?
      filelist->list_size : filelist->show_items+i+1;
    for(;i<j;i++) {
        if(i == filelist->prelight_item && i == filelist->active_item)
            use_base_color_scheme(w, ACTIVE_);
        else if(i == filelist->prelight_item)
            use_base_color_scheme(w, PRELIGHT_);
        else if (i == filelist->active_item)
            use_base_color_scheme(w, SELECTED_);
        else
            use_base_color_scheme(w,NORMAL_ );
        cairo_rectangle(w->crb, 0, a*25, width, 25);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, PRELIGHT_);
        cairo_stroke(w->crb);
        if(i == filelist->prelight_item && i == filelist->active_item)
            use_text_color_scheme(w, ACTIVE_);
        else if(i == filelist->prelight_item)
            use_text_color_scheme(w, PRELIGHT_);
        else if (i == filelist->active_item)
            use_text_color_scheme(w, SELECTED_);
        else
            use_text_color_scheme(w,NORMAL_ );
        if (filelist->check_dir) {
            if (os_is_directory(filelist->list_names[i])) {
                cairo_scale(w->crb,0.08, 0.08);
                cairo_set_source_surface (w->crb, filelist->folder,1.0*12.5,((double)a+0.1)*25.0*12.5);
                cairo_paint (w->crb);
                cairo_scale(w->crb,12.5, 12.5);
                use_text_color_scheme(w, INSENSITIVE_);
            } else {
                cairo_scale(w->crb,0.08, 0.08);
                cairo_set_source_surface (w->crb, filelist->file,1.0*12.5,((double)a+0.1)*25.0*12.5);
                cairo_paint (w->crb);
                cairo_scale(w->crb,12.5, 12.5);
                use_text_color_scheme(w,NORMAL_ );
            }
        }
        cairo_text_extents(w->crb,filelist->list_names[i] , &extents);
        cairo_move_to (w->crb, 20, (25.0*((double)a+1.0))+3.0 - (h*max(0.71,w->scale.ascale)));
        cairo_show_text(w->crb, filelist->list_names[i]);
        cairo_new_path (w->crb);
        if (i == filelist->prelight_item && extents.width > (float)width-20) {
            tooltip_set_text(w,filelist->list_names[i]);
            w->flags |= HAS_TOOLTIP;
            show_tooltip(w);
        } else if (i == filelist->prelight_item && extents.width < (float)width-20){
            w->flags &= ~HAS_TOOLTIP;
            hide_tooltip(w);
        }
        a++;
    }
}
References ACTIVE_, ViewList_t::active_item, Widget_t::adj, adj_get_value(), Widget_t::app, Resize_t::ascale, Xputty::big_font, ViewList_t::check_dir, Widget_t::crb, ViewList_t::file, Widget_t::flags, ViewList_t::folder, HAS_TOOLTIP, Metrics_t::height, hide_tooltip(), INSENSITIVE_, ViewList_t::list_names, ViewList_t::list_size, NORMAL_, Xputty::normal_font, os_get_window_metrics(), os_is_directory(), Widget_t::parent_struct, PRELIGHT_, ViewList_t::prelight_item, Widget_t::scale, SELECTED_, ViewList_t::show_items, show_tooltip(), tooltip_set_text(), use_base_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by create_listview_viewport().
_draw_listview()
void _draw_listview (void * w_, void * user_data)
_draw_listview - draw listview on expose call
Parameters
*w_ - the listview to draw
*user_data - attached user_data
Returns
void
Definition at line 27 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    set_pattern(w,&w->color_scheme->normal,&w->color_scheme->active,BACKGROUND_);
    cairo_paint (w->cr);
}
References XColor_t::active, BACKGROUND_, Widget_t::color_scheme, Widget_t::cr, XColor_t::normal, and set_pattern().
Referenced by add_listview().
_draw_listviewslider()
void _draw_listviewslider (void * w_, void * user_data)
_draw_listviewslider - draw a slider on the viewport to indicate the view point
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 327 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t* view_port = (Widget_t*)w->parent_struct;
    ViewList_t *filelist = (ViewList_t*)view_port->parent_struct;
    int v = (int)w->adj->max_value;
    if (!v) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    if (!metrics.visible) return;
    int show_items = height/25;
    float slidersize = 1.0;
    if (filelist->list_size > show_items)
        slidersize = (float)((float)show_items/(float)filelist->list_size);
    float sliderstate = adj_get_state(w->adj);
    use_bg_color_scheme(w, get_color_state(w));
    cairo_rectangle(w->crb, 0,0,width,height);
    cairo_fill_preserve(w->crb);
    use_shadow_color_scheme(w, NORMAL_);
    cairo_fill(w->crb);
    use_bg_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, 0,((float)height-
        ((float)height*slidersize))*sliderstate,width,((float)height*slidersize));
    cairo_fill(w->crb);
}
References Widget_t::adj, adj_get_state(), Widget_t::crb, get_color_state(), Metrics_t::height, ViewList_t::list_size, Adjustment_t::max_value, NORMAL_, os_get_window_metrics(), Widget_t::parent_struct, use_bg_color_scheme(), use_shadow_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by add_listview().
_leave_list()
void _leave_list (void * w_, void * user_data)
_leave_list - draw list on pointer leave
Parameters
*w_ - the Widget_t to draw
*user_data - attached user_data
Returns
void
Definition at line 286 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    ViewList_t *filelist = (ViewList_t*)w->parent_struct;
    filelist->prelight_item = -1;
    expose_widget(w);
}
References expose_widget(), Widget_t::parent_struct, and ViewList_t::prelight_item.
Referenced by create_listview_viewport().
_list_entry_double_clicked()
void _list_entry_double_clicked (void * w_, void * button_, void * user_data)
_list_entry_double_clicke - forward double click from list entry to list view
Parameters
*w_ - void pointer to the Widget_t listview
*button_ - void pointer to the XButtonEvent
*user_data - void pointer to attached user_data
Returns
void
Definition at line 272 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t* listview = (Widget_t*) w->parent;
    ViewList_t *filelist = (ViewList_t*)w->parent_struct;
    XButtonEvent *xbutton = (XButtonEvent*)button_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int height = metrics.height;
    int _items = height/(height/25);
    int prelight_item = xbutton->y/_items  + (int)max(0,adj_get_value(w->adj));
    if (prelight_item > filelist->list_size-1) return;
    listview->func.double_click_callback(listview,button_,NULL);
}
References Widget_t::adj, adj_get_value(), Func_t::double_click_callback, Widget_t::func, Metrics_t::height, ViewList_t::list_size, os_get_window_metrics(), Widget_t::parent, Widget_t::parent_struct, and XEvent::y.
Referenced by create_listview_viewport().
_list_entry_released()
void _list_entry_released (void * w_, void * button_, void * user_data)
_list_entry_released - move listview or set active entry
Parameters
*w_ - void pointer to the Widget_t listview
*button_ - void pointer to the XButtonEvent
*user_data - void pointer to attached user_data
Returns
void
Definition at line 244 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (w->flags & HAS_POINTER) {
        ViewList_t *filelist = (ViewList_t*)w->parent_struct;
        XButtonEvent *xbutton = (XButtonEvent*)button_;
        Metrics_t metrics;
        os_get_window_metrics(w, &metrics);
        int height = metrics.height;
        int _items = height/(height/25);
        int prelight_item = xbutton->y/_items  + (int)max(0,adj_get_value(w->adj));
        if (prelight_item > filelist->list_size-1) return;
        if(xbutton->button == Button4) {
            if(prelight_item != filelist->prelight_item) {
                filelist->prelight_item = prelight_item;
            }
        } else if (xbutton->button == Button5) {
            if(prelight_item != filelist->prelight_item) {
                filelist->prelight_item = prelight_item;
            }
        } else if(xbutton->button == Button1) {
            Widget_t* listview = (Widget_t*) w->parent;
            filelist->active_item = filelist->prelight_item;
            adj_set_value(listview->adj,filelist->active_item);
            listview->func.button_release_callback(listview,xbutton,user_data);
        }
    }
}
References ViewList_t::active_item, Widget_t::adj, adj_get_value(), adj_set_value(), XEvent::button, Func_t::button_release_callback, Widget_t::flags, Widget_t::func, HAS_POINTER, Metrics_t::height, ViewList_t::list_size, os_get_window_metrics(), Widget_t::parent, Widget_t::parent_struct, ViewList_t::prelight_item, and XEvent::y.
Referenced by create_listview_viewport().
_list_key_pressed()
void _list_key_pressed (void * w_, void * xkey_, void * user_data)
_list_key_pressed - move listview or set active entry
Parameters
*w_ - void pointer to the Widget_t listview
*button_ - void pointer to the XButtonEvent
*user_data - void pointer to attached user_data
Returns
void
Definition at line 219 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t* listview = (Widget_t*) w->parent;
    XKeyEvent *xkey = (XKeyEvent*)xkey_;
    ViewList_t *filelist = (ViewList_t*)w->parent_struct;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int height = metrics.height;
    int _items = height/(height/25);
    filelist->prelight_item = xkey->y/_items  + (int)max(0,adj_get_value(w->adj));
    int nk = key_mapping(w->app->dpy, xkey);
    if (nk) {
        switch (nk) {
            case 3:
            case 4:
            case 5:
            case 6: filelist->prelight_item = xkey->y/_items  + (int)max(0,adj_get_value(w->adj));
            break;
            default:
            break;
        }
    }
    listview->func.key_press_callback(listview, xkey_, user_data);
}
References Widget_t::adj, adj_get_value(), Widget_t::app, Xputty::dpy, Widget_t::func, Metrics_t::height, key_mapping(), Func_t::key_press_callback, os_get_window_metrics(), Widget_t::parent, Widget_t::parent_struct, ViewList_t::prelight_item, and XEvent::y.
Referenced by create_listview_viewport().
_list_motion()
void _list_motion (void * w_, void * xmotion_, void * user_data)
_list_motion - follow mouse pointer to set prelight item
Parameters
*w_ - void pointer to the Widget_t listview
*xmotion_ - void pointer to the XMotionEvent
*user_data - void pointer to attached user_data
Returns
void
Definition at line 202 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    ViewList_t *filelist = (ViewList_t*)w->parent_struct;
    XMotionEvent *xmotion = (XMotionEvent*)xmotion_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int height = metrics.height;
    int _items = height/(height/25);
    int prelight_item = (xmotion->y/_items)  + (int)max(0,adj_get_value(w->adj));
    if(prelight_item != filelist->prelight_item) {
        filelist->prev_prelight_item = filelist->prelight_item;
        filelist->prelight_item = prelight_item;
        hide_tooltip(w);
        _update_list_view(w);
    }
}
References _update_list_view(), Widget_t::adj, adj_get_value(), Metrics_t::height, hide_tooltip(), os_get_window_metrics(), Widget_t::parent_struct, ViewList_t::prelight_item, ViewList_t::prev_prelight_item, and XEvent::y.
Referenced by create_listview_viewport().
_reconfigure_listview_viewport()
void _reconfigure_listview_viewport (void * w_, void * user_data)
_reconfigure_listview_viewport - reconfigure the viewport adjustment on size changes
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 293 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    float st = adj_get_state(w->adj);
    Widget_t* listview = (Widget_t*) w->parent;
    ViewList_t *filelist = (ViewList_t*)w->parent_struct;
    Metrics_t metrics;
    os_get_window_metrics(listview, &metrics);
    int height = metrics.height;
    filelist->show_items = height/25;
    w->adj->max_value = filelist->list_size-filelist->show_items;
    adj_set_state(w->adj,st);
}
References Widget_t::adj, adj_get_state(), adj_set_state(), Metrics_t::height, ViewList_t::list_size, Adjustment_t::max_value, os_get_window_metrics(), Widget_t::parent, Widget_t::parent_struct, and ViewList_t::show_items.
Referenced by create_listview_viewport().
_set_listview_viewpoint()
void _set_listview_viewpoint (void * w_, void * user_data)
_set_listview_viewpoint - move the view_port to position
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 320 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    ViewList_t *filelist = (ViewList_t*)w->parent_struct;
    adj_set_state(filelist->slider->adj,adj_get_state(w->adj));
    expose_widget(w);
}
References Widget_t::adj, adj_get_state(), adj_set_state(), expose_widget(), Widget_t::parent_struct, and ViewList_t::slider.
Referenced by create_listview_viewport().
_set_listviewport()
void _set_listviewport (void * w_, void * user_data)
_set_listviewport - move the view_port to position by listviewslider state
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 354 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t *viewport = (Widget_t*)w->parent_struct;
    adj_set_state(viewport->adj, adj_get_state(w->adj));
    expose_widget(w);
}
References Widget_t::adj, adj_get_state(), adj_set_state(), expose_widget(), and Widget_t::parent_struct.
Referenced by add_listview().
_update_list_view()
void _update_list_view (void * w_)
show label
Definition at line 112 of file xlistview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    ViewList_t *filelist = (ViewList_t*)w->parent_struct;
    cairo_push_group (w->crb);
    use_base_color_scheme(w, NORMAL_);
    cairo_set_font_size (w->crb, min(w->app->big_font ,w->app->normal_font/w->scale.ascale));
    cairo_text_extents_t extents;
    cairo_text_extents(w->crb,"Ay", &extents);
    double h = extents.height;
    int i = (int)max(0,adj_get_value(w->adj));
    int a = 0;
    int j = filelist->list_size<filelist->show_items+i+1 ?
      filelist->list_size : filelist->show_items+i+1;
    for(;i<j;i++) {
        if (i != filelist->prelight_item && i != filelist->prev_prelight_item) {
            if (i<j-1) {
                a++;
            }
            continue;
        }
        if(i == filelist->prelight_item && i == filelist->active_item)
            use_base_color_scheme(w, ACTIVE_);
        else if(i == filelist->prelight_item)
            use_base_color_scheme(w, PRELIGHT_);
        else if (i == filelist->active_item)
            use_base_color_scheme(w, SELECTED_);
        else
            use_base_color_scheme(w,NORMAL_ );
        cairo_rectangle(w->crb, 0, a*25, width, 25);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, PRELIGHT_);
        cairo_stroke(w->crb);
        if(i == filelist->prelight_item && i == filelist->active_item)
            use_text_color_scheme(w, ACTIVE_);
        else if(i == filelist->prelight_item)
            use_text_color_scheme(w, PRELIGHT_);
        else if (i == filelist->active_item)
            use_text_color_scheme(w, SELECTED_);
        else
            use_text_color_scheme(w,NORMAL_ );
        if (filelist->check_dir) {
            struct stat sb;
            if (stat(filelist->list_names[i], &sb) == 0 && S_ISDIR(sb.st_mode)) {
                cairo_scale(w->crb,0.08, 0.08);
                cairo_set_source_surface (w->crb, filelist->folder,1.0*12.5,((double)a+0.1)*25.0*12.5);
                cairo_paint (w->crb);
                cairo_scale(w->crb,12.5, 12.5);
                use_text_color_scheme(w, INSENSITIVE_);
            } else {
                cairo_scale(w->crb,0.08, 0.08);
                cairo_set_source_surface (w->crb, filelist->file,1.0*12.5,((double)a+0.1)*25.0*12.5);
                cairo_paint (w->crb);
                cairo_scale(w->crb,12.5, 12.5);
                use_text_color_scheme(w,NORMAL_ );
            }
        }
        cairo_text_extents(w->crb,filelist->list_names[i] , &extents);
        cairo_move_to (w->crb, 20, (25.0*((double)a+1.0))+3.0 - (h*max(0.71,w->scale.ascale)));
        cairo_show_text(w->crb, filelist->list_names[i]);
        cairo_new_path (w->crb);
        if (i == filelist->prelight_item && extents.width > (float)width-20) {
            tooltip_set_text(w,filelist->list_names[i]);
            w->flags |= HAS_TOOLTIP;
            show_tooltip(w);
        } else if (i == filelist->prelight_item && extents.width < (float)width-20){
            w->flags &= ~HAS_TOOLTIP;
            hide_tooltip(w);
        }
        a++;
    }
    cairo_pop_group_to_source (w->crb);
    cairo_paint (w->crb);
    cairo_push_group (w->cr);
    cairo_set_source_surface (w->cr, w->buffer,0,0);
    cairo_paint (w->cr);
    cairo_pop_group_to_source (w->cr);
    cairo_paint (w->cr);
}
References ACTIVE_, ViewList_t::active_item, Widget_t::adj, adj_get_value(), Widget_t::app, Resize_t::ascale, Xputty::big_font, Widget_t::buffer, ViewList_t::check_dir, Widget_t::cr, Widget_t::crb, ViewList_t::file, Widget_t::flags, ViewList_t::folder, HAS_TOOLTIP, hide_tooltip(), INSENSITIVE_, ViewList_t::list_names, ViewList_t::list_size, NORMAL_, Xputty::normal_font, os_get_window_metrics(), Widget_t::parent_struct, PRELIGHT_, ViewList_t::prelight_item, ViewList_t::prev_prelight_item, Widget_t::scale, SELECTED_, ViewList_t::show_items, show_tooltip(), tooltip_set_text(), use_base_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), and Metrics_t::width.
Referenced by _list_motion().