libxputty: xputty/header/widgets/xmenu.h File Reference
xmenu.h File Reference
Functions
void pop_menu_show (Widget_t *parent, Widget_t *menu, int elem, bool above)
pop_menu_show - pop up a menu to a Widget_t
void pop_submenu_show (Widget_t *parent, Widget_t *menu, int elem, bool above)
pop_submenu_show - pop up a submenu to a Widget_t
Widget_t * create_viewport (Widget_t *parent, int width, int height)
create_viewport - create a viewport on a menu to a Widget_t
Widget_t * add_menu (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_menu - add a menu to a Widget_t
Widget_t * add_menubar (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_menubar - add a menubar to a Widget_t
Widget_t * menubar_add_menu (Widget_t *parent, const char *label)
menubar_add_menu - add a menu to a menubar
Widget_t * menu_add_entry (Widget_t *wid, const char *label)
menu_add_entry - add a entry to menu
Widget_t * menu_add_radio_entry (Widget_t *wid, const char *label)
menu_add_radio_entry- add a radio entry to menu
Widget_t * menu_add_check_entry (Widget_t *wid, const char *label)
menu_add_check_entry- add a check entry to menu
Widget_t * menu_add_accel_check_entry (Widget_t *wid, const char *label)
menu_add_accel_check_entry- add a check entry with accel to menu
Widget_t * menu_add_value_entry (Widget_t *wid, const char *label)
menu_add_value_entry- add a value entry to menu
Widget_t * menu_add_submenu (Widget_t *wid, const char *label)
menu_add_submenu - add a submenu to a Widget_t
Widget_t * cmenu_add_submenu (Widget_t *wid, const char *label)
cmenu_add_submenu - add a submenu to a cmenu
Widget_t * create_menu (Widget_t *parent, int height)
create_menu - create a menu to a Widget_t
Widget_t * menu_add_item (Widget_t *menu, const char *label)
menu_add_item - add a item to menu
void menu_remove_item (Widget_t *menu, Widget_t *item)
menu_remove_item - remove a item from menu
Widget_t * menu_add_accel_item (Widget_t *menu, const char *label)
menu_add_accel_item - add a accel item to menu
Widget_t * menu_add_check_item (Widget_t *menu, const char *label)
menu_add_check_item - add a item to menu
Widget_t * menu_add_value_item (Widget_t *menu, const char *label)
menu_add_value_item - add a item to menu
void radio_item_set_active (Widget_t *w)
radio_item_set_active - activate selected radio item
void set_active_radio_entry_num (Widget_t *w, int active)
set_active_radio_item - activate selected radio item by number
Widget_t * menu_add_radio_item (Widget_t *menu, const char *label)
menu_add_radio_item - add a radio item to menu
void menu_add_numeric_items (Widget_t *menu, int *imin, int *imax)
menu_add_numeric_items - add numeric items from imin to imax to menu
Function Documentation
add_menu()
Widget_t * add_menu (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_menu - add a menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
*label - the label of the menu
x,y,width,height - the position/geometry to create the menu
Returns
Widget_t* - pointer to the Widget_t menu struct
Definition at line 86 of file xmenu.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_NONE);
    wid->adj = wid->adj_y;
    wid->scale.gravity = NONE;
    wid->state = 0;
    wid->func.adj_callback = set_active_radio_entry;
    wid->func.expose_callback = _draw_menu_label;
    wid->func.enter_callback = _check_menu_state;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.button_release_callback = _menu_released;
    Widget_t *menu = create_menu(wid, 25);
    menu->func.button_release_callback = _menu_entry_released;
    return wid;
}
References _check_menu_state(), _draw_menu_label(), _menu_entry_released(), _menu_released(), add_adjustment(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, Func_t::button_release_callback, CL_NONE, create_menu(), create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, NONE, os_transparent_draw(), Widget_t::scale, set_active_radio_entry(), and Widget_t::state.
Referenced by menubar_add_menu().
add_menubar()
Widget_t * add_menubar (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_menubar - add a menubar to a Widget_t
Parameters
*parent - pointer to the Widget_t hold the menubar
*label - unused
x,y,width,height - the position/geometry to create the menubar
Returns
Widget_t* - pointer to the Widget_t menu struct
Definition at line 106 of file xmenu.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->scale.gravity = NORTHEAST;
    wid->flags |= NO_AUTOREPEAT | NO_PROPAGATE;
    return wid;
}
References Widget_t::app, create_widget(), Widget_t::flags, Resize_t::gravity, NO_AUTOREPEAT, NO_PROPAGATE, NORTHEAST, and Widget_t::scale.
cmenu_add_submenu()
Widget_t * cmenu_add_submenu (Widget_t * wid, const char * label)
cmenu_add_submenu - add a submenu to a cmenu
Parameters
*wid - pointer to the Widget_t the submenu belongs to
*label - the label of the menu
Returns
Widget_t* - pointer to the Widget_t submenu struct
Definition at line 226 of file xmenu.c.
{
    Widget_t *menu = w;
    Widget_t* view_port =  menu->childlist->childs[0];
    Metrics_t metrics;
    os_get_window_metrics(menu, &metrics);
    int width = metrics.width;
    int height = menu->scale.init_height;
    int si = childlist_has_child(view_port->childlist);
    Widget_t *wid = create_widget(menu->app, view_port, 0, height*si, width, height);
    float max_value1 = view_port->adj->max_value+1.0;
    set_adjustment(view_port->adj,0.0, 0.0, 0.0, max_value1,1.0, CL_VIEWPORT);
    wid->scale.gravity = MENUITEM;
    wid->flags &= ~USE_TRANSPARENCY;
    wid->flags |= FAST_REDRAW;
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_NONE);
    wid->adj = wid->adj_y;
    float max_value = wid->adj->max_value+1.0;
    set_adjustment(wid->adj,0.0, max_value, 0.0, max_value,1.0, CL_NONE);
    wid->func.adj_callback = set_active_radio_entry;
    wid->func.expose_callback = _draw_submenu;
    wid->func.enter_callback = _enter_submenu;
    wid->func.leave_callback = _leave_submenu;
    Widget_t* submenu = create_menu(wid, 25);
    submenu->flags |= IS_SUBMENU;
    submenu->func.button_release_callback = _menu_entry_released;
    return wid;
}
References _draw_submenu(), _enter_submenu(), _leave_submenu(), _menu_entry_released(), add_adjustment(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, Func_t::button_release_callback, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, CL_NONE, CL_VIEWPORT, create_menu(), create_widget(), Func_t::enter_callback, Func_t::expose_callback, FAST_REDRAW, Widget_t::flags, Widget_t::func, Resize_t::gravity, Resize_t::init_height, IS_SUBMENU, Widget_t::label, Func_t::leave_callback, Adjustment_t::max_value, MENUITEM, os_get_window_metrics(), Widget_t::scale, set_active_radio_entry(), set_adjustment(), and Metrics_t::width.
Referenced by add_keyboard().
create_menu()
Widget_t * create_menu (Widget_t * parent, int height)
create_menu - create a menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
height - define the height of a single menu item
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 256 of file xmenu.c.
{
    int x1, y1;
    os_translate_coords(parent, parent->widget, os_get_root_window(parent->app, IS_WIDGET), 0, 0, &x1, &y1);
    Widget_t *wid = create_window(parent->app, os_get_root_window(parent->app, IS_WIDGET), x1, y1, 10, height);
    memcpy(wid->color_scheme, parent->color_scheme, sizeof (struct XColor_t));
    create_viewport(wid, 10, 5*height);
    os_set_window_attrb(wid);
    os_set_transient_for_hint(parent, wid);
    wid->func.expose_callback = _draw_menu;
    wid->flags |= IS_POPUP;
    wid->scale.gravity = NONE;
    childlist_add_child(parent->childlist, wid);
    Widget_t *slider = add_vslider(wid, "", 0, 0, 10, height);
    slider->func.expose_callback = _draw_menu_slider;
    set_adjustment(slider->adj_y,0.0, 0.0, 0.0, 1.0,0.0085, CL_VIEWPORTSLIDER);
    slider->adj = slider->adj_y;
    slider->func.value_changed_callback = _set_menu_viewpoint;
    slider->scale.gravity = NORTHWEST;
    slider->flags &= ~USE_TRANSPARENCY;
    slider->flags |= NO_AUTOREPEAT | NO_PROPAGATE;
    return wid;
}
References _draw_menu(), _draw_menu_slider(), _set_menu_viewpoint(), add_vslider(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Widget_t::childlist, childlist_add_child(), CL_VIEWPORTSLIDER, Widget_t::color_scheme, create_viewport(), create_window(), Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, IS_POPUP, IS_WIDGET, NO_AUTOREPEAT, NO_PROPAGATE, NONE, NORTHWEST, os_get_root_window(), os_set_transient_for_hint(), os_set_window_attrb(), os_translate_coords(), Widget_t::scale, set_adjustment(), Func_t::value_changed_callback, and Widget_t::widget.
Referenced by add_keyboard(), add_menu(), cmenu_add_submenu(), and menu_add_submenu().
create_viewport()
Widget_t * create_viewport (Widget_t * parent, int width, int height)
create_viewport - create a viewport on a menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
width - define the width of the viewport
height - define the height of the viewport
Returns
Widget_t* - pointer to the Widget_t viewport
Definition at line 50 of file xmenu.c.
{
    Widget_t *wid = create_widget(parent->app, parent, 0, 0, width, height);
    wid->scale.gravity = NONE;
    wid->flags &= ~USE_TRANSPARENCY;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_VIEWPORT);
    wid->adj = wid->adj_y;
    wid->func.adj_callback = _set_viewpoint;
    return wid;
}
References _set_viewpoint(), add_adjustment(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, CL_VIEWPORT, create_widget(), Widget_t::flags, Widget_t::func, Resize_t::gravity, NONE, and Widget_t::scale.
Referenced by create_menu().
menu_add_accel_check_entry()
Widget_t * menu_add_accel_check_entry (Widget_t * wid, const char * label)
menu_add_accel_check_entry- add a check entry with accel to menu
Parameters
*wid - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 159 of file xmenu.c.
{
    Widget_t *menu = wid->childlist->childs[0];
    Widget_t *item = menu_add_check_item(menu,label);
    item->func.expose_callback = _draw_accel_check_item;
    float max_value = wid->adj->max_value+1.0;
    set_adjustment(wid->adj,0.0, max_value, 0.0, max_value,1.0, CL_NONE);
    return item;
}
References _draw_accel_check_item(), Widget_t::adj, Widget_t::childlist, Childlist_t::childs, CL_NONE, Func_t::expose_callback, Widget_t::func, Adjustment_t::max_value, menu_add_check_item(), and set_adjustment().
menu_add_accel_item()
Widget_t * menu_add_accel_item (Widget_t * menu, const char * label)
menu_add_accel_item - add a accel item to menu
Parameters
*menu - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 311 of file xmenu.c.
{
    Widget_t *wid = menu_add_item(menu, label);
    wid->func.expose_callback = _draw_accel_item;
    return wid;
}
References _draw_accel_item(), Func_t::expose_callback, Widget_t::func, and menu_add_item().
Referenced by menu_add_entry().
menu_add_check_entry()
Widget_t * menu_add_check_entry (Widget_t * wid, const char * label)
menu_add_check_entry- add a check entry to menu
Parameters
*wid - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 150 of file xmenu.c.
{
    Widget_t *menu = wid->childlist->childs[0];
    Widget_t *item = menu_add_check_item(menu,label);
    float max_value = wid->adj->max_value+1.0;
    set_adjustment(wid->adj,0.0, max_value, 0.0, max_value,1.0, CL_NONE);
    return item;
}
References Widget_t::adj, Widget_t::childlist, Childlist_t::childs, CL_NONE, Adjustment_t::max_value, menu_add_check_item(), and set_adjustment().
menu_add_check_item()
Widget_t * menu_add_check_item (Widget_t * menu, const char * label)
menu_add_check_item - add a item to menu
Parameters
*menu - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 317 of file xmenu.c.
{
    Widget_t *wid = menu_add_item(menu, label);
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,1.0, CL_TOGGLE);
    wid->adj = wid->adj_y;
    wid->func.expose_callback = _draw_check_item;
    wid->func.button_press_callback = _check_item_button_pressed;
    return wid;
}
References _check_item_button_pressed(), _draw_check_item(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Func_t::button_press_callback, CL_TOGGLE, Func_t::expose_callback, Widget_t::func, and menu_add_item().
Referenced by add_keyboard(), menu_add_accel_check_entry(), menu_add_check_entry(), and menu_add_radio_item().
menu_add_entry()
Widget_t * menu_add_entry (Widget_t * wid, const char * label)
menu_add_entry - add a entry to menu
Parameters
*wid - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 132 of file xmenu.c.
{
    Widget_t *menu = wid->childlist->childs[0];
    Widget_t *item = menu_add_accel_item(menu,label);
    float max_value = wid->adj->max_value+1.0;
    set_adjustment(wid->adj,0.0, max_value, 0.0, max_value,1.0, CL_NONE);
    return item;
}
References Widget_t::adj, Widget_t::childlist, Childlist_t::childs, CL_NONE, Adjustment_t::max_value, menu_add_accel_item(), and set_adjustment().
menu_add_item()
Widget_t * menu_add_item (Widget_t * menu, const char * label)
menu_add_item - add a item to menu
Parameters
*menu - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 283 of file xmenu.c.
{
    Widget_t* view_port =  menu->childlist->childs[0];
    Metrics_t metrics;
    os_get_window_metrics(menu, &metrics);
    int width = metrics.width;
    int height = menu->scale.init_height;
    int si = childlist_has_child(view_port->childlist);
    Widget_t *wid = create_widget(menu->app, view_port, 0, height*si, width, height);
    float max_value = view_port->adj->max_value+1.0;
    set_adjustment(view_port->adj,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
    wid->scale.gravity = MENUITEM;
    wid->flags &= ~USE_TRANSPARENCY;
    wid->flags |= FAST_REDRAW;
    wid->label = label;
    wid->func.expose_callback = _draw_item;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    return wid;
}
References _draw_item(), Widget_t::adj, Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, CL_VIEWPORT, create_widget(), Func_t::enter_callback, Func_t::expose_callback, FAST_REDRAW, Widget_t::flags, Widget_t::func, Resize_t::gravity, Resize_t::init_height, Widget_t::label, Func_t::leave_callback, Adjustment_t::max_value, MENUITEM, os_get_window_metrics(), os_transparent_draw(), Widget_t::scale, set_adjustment(), and Metrics_t::width.
Referenced by menu_add_accel_item(), menu_add_check_item(), and menu_add_value_item().
menu_add_numeric_items()
void menu_add_numeric_items (Widget_t * menu, int * imin, int * imax)
menu_add_numeric_items - add numeric items from imin to imax to menu
Parameters
*menu - pointer to the Widget_t menu
*imin - the low number of the numeric items
*imax - the high number of the numeric items
Definition at line 360 of file xmenu.c.
{
    Widget_t* view_port =  menu->childlist->childs[0];
    Metrics_t metrics;
    os_get_window_metrics(menu, &metrics);
    int width = metrics.width;
    int height = menu->scale.init_height;
    int si = childlist_has_child(view_port->childlist);
    float max_value = view_port->adj->max_value;
    Widget_t *wid;
    int i = (*imin);
    int o = (*imax)+1;
    for (;i<o;i++) {
        si = childlist_has_child(view_port->childlist);
        wid = create_widget(menu->app, view_port, 0, height*si, width, height);
        max_value += 1.0;
        set_adjustment(view_port->adj,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
        wid->scale.gravity = MENUITEM;
        wid->flags &= ~USE_TRANSPARENCY;
        wid->flags |= FAST_REDRAW;
        snprintf(wid->input_label, 31, "%i",i);
        wid->label = wid->input_label;
        wid->func.expose_callback = _draw_item;
        wid->func.enter_callback = os_transparent_draw;
        wid->func.leave_callback = os_transparent_draw;
    }
}
References _draw_item(), Widget_t::adj, Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, CL_VIEWPORT, create_widget(), Func_t::enter_callback, Func_t::expose_callback, FAST_REDRAW, Widget_t::flags, Widget_t::func, Resize_t::gravity, Resize_t::init_height, Widget_t::input_label, Widget_t::label, Func_t::leave_callback, Adjustment_t::max_value, MENUITEM, os_get_window_metrics(), os_transparent_draw(), Widget_t::scale, set_adjustment(), and Metrics_t::width.
menu_add_radio_entry()
Widget_t * menu_add_radio_entry (Widget_t * wid, const char * label)
menu_add_radio_entry- add a radio entry to menu
Parameters
*wid - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 141 of file xmenu.c.
{
    Widget_t *menu = wid->childlist->childs[0];
    Widget_t *item = menu_add_radio_item(menu,label);
    float max_value = wid->adj->max_value+1.0;
    set_adjustment(wid->adj,0.0, max_value, 0.0, max_value,1.0, CL_NONE);
    return item;
}
References Widget_t::adj, Widget_t::childlist, Childlist_t::childs, CL_NONE, Adjustment_t::max_value, menu_add_radio_item(), and set_adjustment().
Referenced by add_keyboard().
menu_add_radio_item()
Widget_t * menu_add_radio_item (Widget_t * menu, const char * label)
menu_add_radio_item - add a radio item to menu
Parameters
*menu - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 342 of file xmenu.c.
{
    Widget_t *wid = menu_add_check_item(menu, label);
    wid->flags |= IS_RADIO;
    wid->func.expose_callback = _draw_check_item;
    wid->func.button_press_callback = _radio_item_button_pressed;
    //radio_item_set_active(wid);
    return wid;
}
References _draw_check_item(), _radio_item_button_pressed(), Func_t::button_press_callback, Func_t::expose_callback, Widget_t::flags, Widget_t::func, IS_RADIO, and menu_add_check_item().
Referenced by menu_add_radio_entry().
menu_add_submenu()
Widget_t * menu_add_submenu (Widget_t * wid, const char * label)
menu_add_submenu - add a submenu to a Widget_t
Parameters
*wid - pointer to the Widget_t the submenu belongs to
*label - the label of the menu
Returns
Widget_t* - pointer to the Widget_t submenu struct
Definition at line 194 of file xmenu.c.
{
    float max_value2 = w->adj->max_value+1.0;
    set_adjustment(w->adj,0.0, max_value2, 0.0, max_value2,1.0, CL_NONE);
    Widget_t *menu = w->childlist->childs[0];
    Widget_t* view_port =  menu->childlist->childs[0];
    Metrics_t metrics;
    os_get_window_metrics(menu, &metrics);
    int width = metrics.width;
    int height = menu->scale.init_height;
    int si = childlist_has_child(view_port->childlist);
    Widget_t *wid = create_widget(menu->app, view_port, 0, height*si, width, height);
    float max_value1 = view_port->adj->max_value+1.0;
    set_adjustment(view_port->adj,0.0, 0.0, 0.0, max_value1,1.0, CL_VIEWPORT);
    wid->scale.gravity = MENUITEM;
    wid->flags &= ~USE_TRANSPARENCY;
    wid->flags |= FAST_REDRAW;
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_NONE);
    wid->adj = wid->adj_y;
    float max_value = wid->adj->max_value+1.0;
    set_adjustment(wid->adj,0.0, max_value, 0.0, max_value,1.0, CL_NONE);
    wid->func.adj_callback = set_active_radio_entry;
    wid->func.expose_callback = _draw_submenu;
    wid->func.enter_callback = _enter_submenu;
    wid->func.leave_callback = _leave_submenu;
    Widget_t* submenu = create_menu(wid, 25);
    submenu->flags |= IS_SUBMENU;
    submenu->func.button_release_callback = _menu_entry_released;
    return wid;
}
References _draw_submenu(), _enter_submenu(), _leave_submenu(), _menu_entry_released(), add_adjustment(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, Func_t::button_release_callback, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, CL_NONE, CL_VIEWPORT, create_menu(), create_widget(), Func_t::enter_callback, Func_t::expose_callback, FAST_REDRAW, Widget_t::flags, Widget_t::func, Resize_t::gravity, Resize_t::init_height, IS_SUBMENU, Widget_t::label, Func_t::leave_callback, Adjustment_t::max_value, MENUITEM, os_get_window_metrics(), Widget_t::scale, set_active_radio_entry(), set_adjustment(), and Metrics_t::width.
menu_add_value_entry()
Widget_t * menu_add_value_entry (Widget_t * wid, const char * label)
menu_add_value_entry- add a value entry to menu
Parameters
*wid - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 169 of file xmenu.c.
{
    Widget_t *menu = wid->childlist->childs[0];
    Widget_t* view_port =  menu->childlist->childs[0];
    Metrics_t metrics;
    os_get_window_metrics(menu, &metrics);
    int width = metrics.width;
    int height = 40;
    int si = childlist_has_child(view_port->childlist);
    Widget_t *item = create_widget(menu->app, view_port, 0, height*si, width, height);
    float max_value = view_port->adj->max_value+1.0;
    set_adjustment(view_port->adj,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
    item->scale.gravity = MENUITEM;
    item->flags &= ~USE_TRANSPARENCY;
    item->flags |= FAST_REDRAW;
    item->label = label;
    item->func.expose_callback = _draw_item;
    item->func.enter_callback = os_transparent_draw;
    item->func.leave_callback = os_transparent_draw;
    item->adj_y = add_adjustment(item,0.0, 0.0, 0.0, 1.0,0.01, CL_CONTINUOS);
    item->adj = item->adj_y;
    item->func.expose_callback = _draw_value_item;
    item->func.button_release_callback = _value_item_released;
    return item;
}
References _draw_item(), _draw_value_item(), _value_item_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Func_t::button_release_callback, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, CL_CONTINUOS, CL_VIEWPORT, create_widget(), Func_t::enter_callback, Func_t::expose_callback, FAST_REDRAW, Widget_t::flags, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, Adjustment_t::max_value, MENUITEM, os_get_window_metrics(), os_transparent_draw(), Widget_t::scale, set_adjustment(), and Metrics_t::width.
Referenced by add_keyboard().
menu_add_value_item()
Widget_t * menu_add_value_item (Widget_t * menu, const char * label)
menu_add_value_item - add a item to menu
Parameters
*menu - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 351 of file xmenu.c.
{
    Widget_t *wid = menu_add_item(menu, label);
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,0.01, CL_CONTINUOS);
    wid->adj = wid->adj_y;
    wid->func.expose_callback = _draw_value_item;
    wid->func.button_release_callback = _value_item_released;
    return wid;
}
References _draw_value_item(), _value_item_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Func_t::button_release_callback, CL_CONTINUOS, Func_t::expose_callback, Widget_t::func, and menu_add_item().
menu_remove_item()
void menu_remove_item (Widget_t * menu, Widget_t * item)
menu_remove_item - remove a item from menu
Parameters
*menu - pointer to the Widget_t menu
*item - pointer to the Widget_t item to be removed
Definition at line 303 of file xmenu.c.
{
    Widget_t* view_port =  menu->childlist->childs[0];
    float max_value = view_port->adj->max_value-1.0;
    destroy_widget(item,menu->app);
    set_adjustment(view_port->adj,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
    os_move_window(menu->app->dpy,view_port,0.0, 0.0);
}
References Widget_t::adj, Widget_t::app, Widget_t::childlist, Childlist_t::childs, CL_VIEWPORT, destroy_widget(), Xputty::dpy, Adjustment_t::max_value, os_move_window(), and set_adjustment().
menubar_add_menu()
Widget_t * menubar_add_menu (Widget_t * parent, const char * label)
menubar_add_menu - add a menu to a menubar
Parameters
*parent - pointer to the parent Widget_t (menubar)
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 114 of file xmenu.c.
{
    cairo_text_extents_t extents;
    cairo_text_extents(parent->crb,label , &extents);
    int width = (int)extents.width+20;
    Metrics_t metrics;
    os_get_window_metrics(parent, &metrics);
    int height = metrics.height;
    int x = 0;
    int i = parent->childlist->elem-1;
    for(;i>-1;i--) {
        Widget_t *w = parent->childlist->childs[i];
        os_get_window_metrics(w, &metrics);
        x += metrics.width;
    }
    Widget_t *wid = add_menu(parent, label, x, 0, width, height);
    return wid;
}
References add_menu(), Widget_t::childlist, Childlist_t::childs, Widget_t::crb, Childlist_t::elem, Metrics_t::height, os_get_window_metrics(), and Metrics_t::width.
pop_menu_show()
void pop_menu_show (Widget_t * parent, Widget_t * menu, int elem, bool above)
pop_menu_show - pop up a menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
*menu - the menu to show
elem - how many entries to show (max value)
above - show menu above or below the parent Widget_t
Definition at line 27 of file xmenu.c.
{
    if (!childlist_has_child(menu->childlist)) return;
    Widget_t* view_port =  menu->childlist->childs[0];
    if (!view_port->childlist->elem) return;
    _configure_menu(parent, menu, elem, above);
    pop_widget_show_all(menu);
    if (view_port->childlist->elem <= elem)
        widget_hide(menu->childlist->childs[1]);
    int err = os_grab_pointer(menu);
    menu->app->hold_grab = menu;
    if (err) debug_print("Error grap pointer\n");
}
References _configure_menu(), Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Childlist_t::elem, Xputty::hold_grab, os_grab_pointer(), pop_widget_show_all(), and widget_hide().
Referenced by _check_menu_state(), and _menu_released().
pop_submenu_show()
void pop_submenu_show (Widget_t * parent, Widget_t * menu, int elem, bool above)
pop_submenu_show - pop up a submenu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
*menu - the menu to show
elem - how many entries to show (max value)
above - show menu above or below the parent Widget_t
Definition at line 41 of file xmenu.c.
{
    if (!childlist_has_child(menu->childlist)) return;
    Widget_t* view_port =  menu->childlist->childs[0];
    if (!view_port->childlist->elem) return;
    _configure_menu(parent, menu, elem, above);
    submenu_widget_show_all(menu);
    menu->app->submenu = menu;
}
References _configure_menu(), Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Childlist_t::elem, Xputty::submenu, and submenu_widget_show_all().
Referenced by _enter_submenu().
radio_item_set_active()
void radio_item_set_active (Widget_t * w)
radio_item_set_active - activate selected radio item
Parameters
*w - the Widget_t to activate
Definition at line 326 of file xmenu.c.
{
    Widget_t * p = (Widget_t*) w->parent;
    int i = p->childlist->elem-1;
    for(;i>-1;i--) {
        Widget_t *wid = p->childlist->childs[i];
        if (wid->adj && wid->flags & IS_RADIO) {
            if (wid == w) {
                adj_set_value(wid->adj_y, 1.0);
            } else {
                adj_set_value(wid->adj_y, 0.0);
            }
            wid->state=0;
        }
    }
}
References Widget_t::adj, adj_set_value(), Widget_t::adj_y, Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_RADIO, Widget_t::parent, and Widget_t::state.
Referenced by _radio_item_button_pressed(), and set_active_radio_entry_num().
set_active_radio_entry_num()
void set_active_radio_entry_num (Widget_t * w, int active)
set_active_radio_item - activate selected radio item by number
Parameters
*w - the Widget_t hold the menu
active - the menu entry to activate
Definition at line 78 of file xmenu.c.
{
    Widget_t *menu = w->childlist->childs[0];
    Widget_t *view_port =  menu->childlist->childs[0];
    Widget_t *wid = view_port->childlist->childs[active];
    if (wid->adj && wid->flags & IS_RADIO)
        radio_item_set_active(wid);
}
References Widget_t::adj, Widget_t::childlist, Childlist_t::childs, Widget_t::flags, IS_RADIO, and radio_item_set_active().
Referenced by add_keyboard().