libxputty: xputty/widgets/xmenu_private.c File Reference
xmenu_private.c File Reference
Functions
int _menu_remove_low_dash (char *str)
void _draw_menu_label (void *w_, void *user_data)
_draw_menu_label - draw the menu label on expose call
void _check_menu_state (void *w_, void *user_data)
_check_menu_state - follow the mouse pointer when a menu is active
void _menu_released (void *w_, void *button_, void *user_data)
_menu_released - popup the menu on click
void _menu_entry_released (void *w_, void *item_, void *user_data)
_menu_entry_released - the menu release func
void _draw_menu_slider (void *w_, void *user_data)
_draw_menu_slider - draw the menu slider on expose call
void _draw_menu (void *w_, void *user_data)
_draw_menu - draw menu on expose call
void _draw_submenu (void *w_, void *user_data)
_draw_submenu - draw submenu on expose call
void _enter_submenu (void *w_, void *user_data)
_enter_submenu - enter submenu
void _leave_submenu (void *w_, void *user_data)
_leave_submenu - leave submenu
void _draw_item (void *w_, void *user_data)
_draw_item - draw item on expose call
void _draw_value_item (void *w_, void *user_data)
_draw_value_item - draw item on expose call
void _draw_accel_item (void *w_, void *user_data)
_draw_accel_item - draw accel item on expose call
void _draw_accel_check_item (void *w_, void *user_data)
_accel_draw_check_item - draw item on expose call
void _draw_check_item (void *w_, void *user_data)
_draw_check_item - draw item on expose call
void _set_viewpoint (void *w_, void *user_data)
_set_viewpoint - move the view_port to position
void _set_menu_viewpoint (void *w_, void *user_data)
_set_menu_viewpoint - move the view_port to position by slider
void _check_item_button_pressed (void *w_, void *button_, void *user_data)
_check_item_button_pressed - redraw item on button press
void _radio_item_button_pressed (void *w_, void *button_, void *user_data)
_radio_item_button_pressed - redraw item on button press
void _value_item_released (void *w_, void *button_, void *user_data)
_value_item_released - redraw item on button released
void _configure_menu (Widget_t *parent, Widget_t *menu, int elem, bool above)
_configure_menu - set final size and position of menu to a Widget_t
Function Documentation
_check_item_button_pressed()
void _check_item_button_pressed (void * w_, void * button_, void * user_data)
_check_item_button_pressed - redraw item on button press
Parameters
*w_ - void pointer to view_port
*button - the xbutton which is pressed
*user_data - attached user_data
Returns
void
Definition at line 458 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (w->flags & HAS_FOCUS) {
        float value = w->adj_y->value ? 0.0 : 1.0;
        adj_set_value(w->adj_y, value);
    }
}
References adj_set_value(), Widget_t::adj_y, Widget_t::flags, HAS_FOCUS, and Adjustment_t::value.
Referenced by menu_add_check_item().
_check_menu_state()
void _check_menu_state (void * w_, void * user_data)
_check_menu_state - follow the mouse pointer when a menu is active
Parameters
*w_ - the menu to check
*user_data - attached user_data
Returns
void
Definition at line 79 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t *parent = w->parent;
    int i = parent->childlist->elem-1;
    for(;i>-1;i--) {
        Widget_t *wid = parent->childlist->childs[i];
        if (childlist_has_child(wid->childlist)) {
            if ((wid->childlist->childs[0] == w->app->hold_grab) && (wid !=w)) {
#ifdef _WIN32   //SetCaptureDisabled//XUngrabPointer
                //ReleaseCapture(); // SetCapture() is currently disabled in pop_menu_show()
#else
                XUngrabPointer(w->app->dpy,CurrentTime);
#endif
                widget_hide(w->app->hold_grab);
                w->app->hold_grab = NULL;
                if (w->app->submenu) {
                    widget_hide(w->app->submenu);
                    w->app->submenu = NULL;
                }
                pop_menu_show(w, w->childlist->childs[0], 6, true);
                break;
            }
        }
    }
    os_transparent_draw(w_, user_data);
}
References Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Xputty::dpy, Childlist_t::elem, Xputty::hold_grab, os_transparent_draw(), Widget_t::parent, pop_menu_show(), Xputty::submenu, and widget_hide().
Referenced by add_menu().
_configure_menu()
void _configure_menu (Widget_t * parent, Widget_t * menu, int elem, bool above)
_configure_menu - set final size and position of menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
*menu - the menu to show
Returns
void
Definition at line 478 of file xmenu_private.c.
{
    Widget_t* view_port =  menu->childlist->childs[0];
    Widget_t *slider =  menu->childlist->childs[1];
    if (!view_port->childlist->elem) return;
    Metrics_t metrics;
    os_get_window_metrics(view_port->childlist->childs[0], &metrics);
    int height = metrics.height;
    int x1, y1;
    int posy = (above) ? parent->height : 0;
    int posx = (above) ? 0 : parent->width ;
    os_translate_coords(parent, parent->widget, os_get_root_window(parent->app, IS_WIDGET), posx, posy, &x1, &y1);
    int item_width = 1.0;
    cairo_text_extents_t extents;
    int i = view_port->childlist->elem-1;
    set_adjustment(view_port->adj,0.0, view_port->adj->value, 0.0, i-(elem-1),1.0, CL_VIEWPORT);
    bool is_not_scrolable = false;
    if(view_port->childlist->elem <= elem) {
        elem = view_port->childlist->elem;
        is_not_scrolable = true;
    }
    for(;i>-1;i--) {
        Widget_t *w = view_port->childlist->childs[i];
        cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
        cairo_text_extents(w->crb,w->label , &extents);
        item_width = max(item_width, (int)extents.width+40);
        if(is_not_scrolable) w->scale.gravity = NORTHEAST;
    }
    if(above) {
        if(item_width<parent->width)item_width = parent->width;
    }
    slider->adj->step = max(0.0,1.0/(view_port->childlist->elem-elem));
    adj_set_scale(slider->adj, ((float)view_port->childlist->elem/(float)elem)/25.0);
    int screen_height = os_get_screen_height(parent);
    if (y1+(height*elem) > screen_height) y1 = y1-((height*elem)+parent->height);
    os_resize_window (menu->app->dpy, menu, item_width, height*elem);
    os_resize_window (view_port->app->dpy, view_port, item_width, height*view_port->childlist->elem);
    os_move_window(menu->app->dpy,slider,item_width-10, 0);
    os_resize_window(menu->app->dpy,slider,10,height*elem);
    os_move_window(menu->app->dpy,menu,x1, y1);
}
References Widget_t::adj, adj_set_scale(), Widget_t::app, Resize_t::ascale, Widget_t::childlist, Childlist_t::childs, CL_VIEWPORT, Widget_t::crb, Xputty::dpy, Childlist_t::elem, Resize_t::gravity, Metrics_t::height, Widget_t::height, IS_WIDGET, Widget_t::label, Xputty::normal_font, NORTHEAST, os_get_root_window(), os_get_screen_height(), os_get_window_metrics(), os_move_window(), os_resize_window(), os_translate_coords(), Widget_t::scale, set_adjustment(), Adjustment_t::step, Adjustment_t::value, Widget_t::widget, and Widget_t::width.
Referenced by pop_menu_show(), and pop_submenu_show().
_draw_accel_check_item()
void _draw_accel_check_item (void * w_, void * user_data)
_accel_draw_check_item - draw item on expose call
Parameters
*w_ - the item to draw
*user_data - attached user_data
Returns
void
Definition at line 391 of file xmenu_private.c.
{
    _draw_accel_item(w_, user_data);
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int height = metrics.height;
    if (w->flags & IS_RADIO) {
        cairo_arc(w->crb, height/3, height/2, height/6, 0, 2 * M_PI );
    } else {
        cairo_rectangle(w->crb, height/6, height/3, height/3 , height/3);
    }
    use_shadow_color_scheme(w, get_color_state(w));
    cairo_fill(w->crb);
    if ((int) w->adj_y->value) {
        if (w->flags & IS_RADIO) {
            cairo_arc(w->crb, height/3, height/2, height/6-2, 0, 2 * M_PI );
        } else {
            cairo_rectangle(w->crb, height/6+1, height/3+1, height/3-2 , height/3-2);
        }
        use_fg_color_scheme(w, ACTIVE_);
        cairo_fill(w->crb);
    }
}
References _draw_accel_item(), ACTIVE_, Widget_t::adj_y, Widget_t::crb, Widget_t::flags, get_color_state(), Metrics_t::height, IS_RADIO, os_get_window_metrics(), use_fg_color_scheme(), use_shadow_color_scheme(), and Adjustment_t::value.
Referenced by menu_add_accel_check_entry().
_draw_accel_item()
void _draw_accel_item (void * w_, void * user_data)
_draw_accel_item - draw accel item on expose call
Parameters
*w_ - the item to draw
*user_data - attached user_data
Returns
void
show label
Definition at line 341 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    if (!metrics.visible) return;
    use_base_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, 0, 0, width , height);
    if(w->state==1) {
        use_base_color_scheme(w, PRELIGHT_);
    } else if(w->state==2) {
        use_base_color_scheme(w, SELECTED_);
    } else if(w->state==3) {
        use_base_color_scheme(w, ACTIVE_);
    }
    cairo_fill_preserve(w->crb);
    cairo_set_line_width(w->crb, 1.0);
    use_frame_color_scheme(w, PRELIGHT_);
    cairo_stroke(w->crb);
    cairo_text_extents_t extents;
    use_text_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    if (strstr(w->label, "_")) {
        cairo_text_extents(w->crb, "--", &extents);
        double underline = extents.width;
        strncpy(w->input_label,w->label, sizeof(w->input_label)-1);
        int pos = _menu_remove_low_dash(w->input_label);
        int len = strlen(w->input_label);
        cairo_text_extents(w->crb,w->input_label , &extents);
        int set_line = (extents.width/len) * pos;
        cairo_move_to (w->crb, 20, (height+extents.height)*0.5);
        cairo_show_text(w->crb, w->input_label);
        cairo_set_line_width(w->crb, 1.0);
        cairo_move_to (w->crb, 20 + set_line, (height+extents.height)*0.55);
        cairo_line_to(w->crb,20 + set_line + underline, (height+extents.height)*0.55);
        cairo_stroke(w->crb);
    } else {
        cairo_text_extents(w->crb,w->label , &extents);
        cairo_move_to (w->crb, 20, (height+extents.height)*0.5);
        cairo_show_text(w->crb, w->label);
    }
    cairo_new_path (w->crb);
}
References _menu_remove_low_dash(), ACTIVE_, Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::input_label, Widget_t::label, NORMAL_, Xputty::normal_font, os_get_window_metrics(), PRELIGHT_, Widget_t::scale, SELECTED_, Widget_t::state, use_base_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by _draw_accel_check_item(), and menu_add_accel_item().
_draw_check_item()
void _draw_check_item (void * w_, void * user_data)
_draw_check_item - draw item on expose call
Parameters
*w_ - the item to draw
*user_data - attached user_data
Returns
void
Definition at line 415 of file xmenu_private.c.
{
    _draw_item(w_, user_data);
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int height = metrics.height;
    if (w->flags & IS_RADIO) {
        cairo_arc(w->crb, height/3, height/2, height/6, 0, 2 * M_PI );
    } else {
        cairo_rectangle(w->crb, height/6, height/3, height/3 , height/3);
    }
    use_shadow_color_scheme(w, get_color_state(w));
    cairo_fill(w->crb);
    if ((int) w->adj_y->value) {
        if (w->flags & IS_RADIO) {
            cairo_arc(w->crb, height/3, height/2, height/6-2, 0, 2 * M_PI );
        } else {
            cairo_rectangle(w->crb, height/6+1, height/3+1, height/3-2 , height/3-2);
        }
        use_fg_color_scheme(w, ACTIVE_);
        cairo_fill(w->crb);
    }
}
References _draw_item(), ACTIVE_, Widget_t::adj_y, Widget_t::crb, Widget_t::flags, get_color_state(), Metrics_t::height, IS_RADIO, os_get_window_metrics(), use_fg_color_scheme(), use_shadow_color_scheme(), and Adjustment_t::value.
Referenced by menu_add_check_item(), and menu_add_radio_item().
_draw_item()
void _draw_item (void * w_, void * user_data)
_draw_item - draw item on expose call
Parameters
*w_ - the item to draw
*user_data - attached user_data
Returns
void
show label
Definition at line 266 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    if (!metrics.visible) return;
    use_base_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, 0, 0, width , height);
    if(w->state==1) {
        use_base_color_scheme(w, PRELIGHT_);
    } else if(w->state==2) {
        use_base_color_scheme(w, SELECTED_);
    } else if(w->state==3) {
        use_base_color_scheme(w, ACTIVE_);
    }
    cairo_fill_preserve(w->crb);
    cairo_set_line_width(w->crb, 1.0);
    use_frame_color_scheme(w, PRELIGHT_);
    cairo_stroke(w->crb);
    cairo_text_extents_t extents;
    use_text_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    cairo_text_extents(w->crb,w->label , &extents);
    cairo_move_to (w->crb, 20, (height+extents.height)*0.5);
    cairo_show_text(w->crb, w->label);
    cairo_new_path (w->crb);
}
References ACTIVE_, Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::label, NORMAL_, Xputty::normal_font, os_get_window_metrics(), PRELIGHT_, Widget_t::scale, SELECTED_, Widget_t::state, use_base_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by _draw_check_item(), menu_add_item(), menu_add_numeric_items(), and menu_add_value_entry().
_draw_menu()
void _draw_menu (void * w_, void * user_data)
_draw_menu - draw menu on expose call
Parameters
*w_ - the menu to draw
*user_data - attached user_data
Returns
void
Definition at line 152 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    use_bg_color_scheme(w, get_color_state(w));
    cairo_paint (w->crb);
}
References Widget_t::crb, get_color_state(), and use_bg_color_scheme().
Referenced by create_menu().
_draw_menu_label()
void _draw_menu_label (void * w_, void * user_data)
_draw_menu_label - draw the menu label on expose call
Parameters
*w_ - the menu to draw
*user_data - attached user_data
Returns
void
Definition at line 44 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int height = metrics.height;
    cairo_text_extents_t extents;
    use_text_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    cairo_text_extents(w->crb, "A", &extents);
    double lh = extents.height;
    if (strstr(w->label, "_")) {
        cairo_text_extents(w->crb, "--", &extents);
        double underline = extents.width;
        strncpy(w->input_label,w->label, sizeof(w->input_label)-1);
        int pos = _menu_remove_low_dash(w->input_label);
        int len = strlen(w->input_label);
        cairo_text_extents(w->crb,w->input_label , &extents);
        int set_line = (extents.width/len) * pos;
        cairo_move_to (w->crb, 10, (height+lh)*0.5);
        cairo_show_text(w->crb, w->input_label);
        cairo_set_line_width(w->crb, 1.0);
        cairo_move_to (w->crb, 10 + set_line, (height+lh)*0.55);
        cairo_line_to(w->crb,10 + set_line + underline, (height+lh)*0.55);
        cairo_stroke(w->crb);
    } else {
        cairo_text_extents(w->crb,w->label , &extents);
        cairo_move_to (w->crb, 10, (height+lh)*0.5);
        cairo_show_text(w->crb, w->label);
    }
    cairo_new_path (w->crb);
}
References _menu_remove_low_dash(), Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::input_label, Widget_t::label, Xputty::normal_font, os_get_window_metrics(), Widget_t::scale, and use_text_color_scheme().
Referenced by add_menu().
_draw_menu_slider()
void _draw_menu_slider (void * w_, void * user_data)
_draw_menu_slider - draw the menu slider on expose call
Parameters
*w_ - the menu to draw
*user_data - attached user_data
Returns
void
Definition at line 132 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    int v = (int)w->adj->max_value;
    if (!v) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    if (!metrics.visible) return;
    float sliderstate = adj_get_state(w->adj);
    use_bg_color_scheme(w, get_color_state(w));
    cairo_rectangle(w->crb, 0,0,width,height);
    cairo_fill_preserve(w->crb);
    use_shadow_color_scheme(w, NORMAL_);
    cairo_fill(w->crb);
    use_bg_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, 0,(height-10)*sliderstate,width,10);
    cairo_fill(w->crb);
}
References Widget_t::adj, adj_get_state(), Widget_t::crb, get_color_state(), Metrics_t::height, Adjustment_t::max_value, NORMAL_, os_get_window_metrics(), use_bg_color_scheme(), use_shadow_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by create_menu().
_draw_submenu()
void _draw_submenu (void * w_, void * user_data)
_draw_submenu - draw submenu on expose call
Parameters
*w_ - the menu to draw
*user_data - attached user_data
Returns
void
show label
Definition at line 159 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    if (!metrics.visible) return;
    use_base_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, 0, 0, width , height);
    if(w->state==1) {
        use_base_color_scheme(w, PRELIGHT_);
    } else if(w->state==2) {
        use_base_color_scheme(w, SELECTED_);
    } else if(w->state==3) {
        use_base_color_scheme(w, ACTIVE_);
    }
    cairo_fill_preserve(w->crb);
    cairo_set_line_width(w->crb, 1.0);
    use_frame_color_scheme(w, PRELIGHT_);
    cairo_stroke(w->crb);
    cairo_text_extents_t extents;
    use_text_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    if (strstr(w->label, "_")) {
        cairo_text_extents(w->crb, "--", &extents);
        double underline = extents.width;
        strncpy(w->input_label,w->label, sizeof(w->input_label)-1);
        int pos = _menu_remove_low_dash(w->input_label);
        int len = strlen(w->input_label);
        cairo_text_extents(w->crb,w->input_label , &extents);
        int set_line = (extents.width/len) * pos;
        cairo_move_to (w->crb, 20, (height+extents.height)*0.5);
        cairo_show_text(w->crb, w->input_label);
        cairo_set_line_width(w->crb, 1.0);
        cairo_move_to (w->crb, 20 + set_line, (height+extents.height)*0.55);
        cairo_line_to(w->crb,20 + set_line + underline, (height+extents.height)*0.55);
        cairo_stroke(w->crb);
    } else {
        cairo_text_extents(w->crb,w->label , &extents);
        cairo_move_to (w->crb, 20, (height+extents.height)*0.5);
        cairo_show_text(w->crb, w->label);
    }
    cairo_move_to (w->crb, (width-15), (height+extents.height)*0.5);
    cairo_show_text(w->crb, ">");
    cairo_new_path (w->crb);
}
References _menu_remove_low_dash(), ACTIVE_, Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::input_label, Widget_t::label, NORMAL_, Xputty::normal_font, os_get_window_metrics(), PRELIGHT_, Widget_t::scale, SELECTED_, Widget_t::state, use_base_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by cmenu_add_submenu(), and menu_add_submenu().
_draw_value_item()
void _draw_value_item (void * w_, void * user_data)
_draw_value_item - draw item on expose call
Parameters
*w_ - the item to draw
*user_data - attached user_data
Returns
void
show value on the item
Definition at line 299 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    use_base_color_scheme(w, NORMAL_);
    cairo_rectangle(w->crb, 0, 0, width , height);
    if(w->state==1) {
        use_base_color_scheme(w, PRELIGHT_);
    } else if(w->state==2) {
        use_base_color_scheme(w, SELECTED_);
    } else if(w->state==3) {
        use_base_color_scheme(w, ACTIVE_);
    }
    cairo_fill_preserve(w->crb);
    cairo_set_line_width(w->crb, 1.0);
    use_frame_color_scheme(w, PRELIGHT_);
    cairo_stroke(w->crb);
    use_text_color_scheme(w, get_color_state(w));
    cairo_text_extents_t extents;
    char s[64];
    const char* format[] = {"%.1f", "%.2f", "%.3f"};
    float value = adj_get_value(w->adj);
    if (fabs(w->adj->step)>0.99) {
        snprintf(s, 63,"%d",  (int) value);
    } else if (fabs(w->adj->step)>0.09) {
        snprintf(s, 63, format[1-1], value);
    } else {
        snprintf(s, 63, format[2-1], value);
    }
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    cairo_text_extents(w->crb, s, &extents);
    cairo_move_to (w->crb, 20, (height+extents.height)*0.5);
    cairo_show_text(w->crb, s);
    cairo_new_path (w->crb);
}
References ACTIVE_, Widget_t::adj, adj_get_value(), Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, NORMAL_, Xputty::normal_font, os_get_window_metrics(), PRELIGHT_, Widget_t::scale, SELECTED_, Widget_t::state, Adjustment_t::step, use_base_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by menu_add_value_entry(), and menu_add_value_item().
_enter_submenu()
void _enter_submenu (void * w_, void * user_data)
_enter_submenu - enter submenu
Parameters
*w_ - the submenu entered
*user_data - attached user_data
Returns
void
Definition at line 211 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    if (!metrics.visible) return;
    if (childlist_has_child(w->childlist)) {
        if (w->app->submenu) {
            if (w->app->submenu != w->childlist->childs[0]) {
                widget_hide(w->app->submenu);
                w->app->submenu = NULL;
            }
        }
        pop_submenu_show(w, w->childlist->childs[0], 6, false);
    }
    os_transparent_draw(w_, user_data);
}
References Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, os_get_window_metrics(), os_transparent_draw(), pop_submenu_show(), Xputty::submenu, Metrics_t::visible, and widget_hide().
Referenced by cmenu_add_submenu(), and menu_add_submenu().
_leave_submenu()
void _leave_submenu (void * w_, void * user_data)
_leave_submenu - leave submenu
Parameters
*w_ - the submenu leaved
*user_data - attached user_data
Returns
void
Definition at line 228 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w->data) {
#ifdef __linux__
        XCrossingEvent notify;
        memset(&notify, 0, sizeof(notify));
        notify.type = LeaveNotify;
        notify.display = w->app->dpy;
        notify.send_event = True;
        notify.subwindow = w->widget;
        notify.window = w->widget;
        notify.x = 1;
        notify.y = 1;
        notify.same_screen = True;
        notify.focus = False;
        XSendEvent(w->app->dpy, w->widget,True,LeaveWindowMask, (XEvent*)&notify);
#endif
        w->data = 1;
        return;
    }
    w->data = 0;
    if (childlist_has_child(w->childlist)) {
        Widget_t *parent = (Widget_t*) w->parent;
        int i=0;
        for(;i<parent->childlist->elem;i++) {
            if (parent->childlist->childs[i]->flags & HAS_FOCUS) {
                widget_hide(w->childlist->childs[0]);
                if (w->app->submenu == w->childlist->childs[0])
                    w->app->submenu = NULL;
                break;
            }
        }
    }
    os_transparent_draw(w_, user_data);
}
References Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Widget_t::data, Xputty::dpy, Childlist_t::elem, Widget_t::flags, HAS_FOCUS, os_transparent_draw(), Widget_t::parent, Xputty::submenu, Widget_t::widget, and widget_hide().
Referenced by cmenu_add_submenu(), and menu_add_submenu().
_menu_entry_released()
void _menu_entry_released (void * w_, void * item_, void * user_data)
_menu_entry_released - the menu release func
Parameters
*w_ - void pointer to the Widget_t menu
*item - void pointer to the selected item *(int*)
*user_data - void pointer to the item label *(const char**)
Returns
void
Definition at line 114 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t * bar = NULL;
    int i = w->app->childlist->elem-1;
    for(;i>-1;i--) {
        Widget_t *wid = w->app->childlist->childs[i];
        if (wid == w) {
            bar = w->app->childlist->childs[i-1];
            int old_value = (int)adj_get_value(bar->adj);
            adj_set_value(bar->adj, (float)*(int*)item_);
            if (old_value == *(int*)item_) {
                bar->func.value_changed_callback(bar, NULL);
            }
            break;
        }
    }
}
References Widget_t::adj, adj_get_value(), adj_set_value(), Widget_t::app, Xputty::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::func, and Func_t::value_changed_callback.
Referenced by add_menu(), cmenu_add_submenu(), and menu_add_submenu().
_menu_released()
void _menu_released (void * w_, void * button_, void * user_data)
_menu_released - popup the menu on click
Parameters
*w_ - void pointer to the Widget_t button
*button - void pointer to XEvent.xbutton struct
*user_data - void pointer to attached user_data
Returns
void
Definition at line 106 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    XButtonEvent *xbutton = (XButtonEvent*)button_;
    if (w->flags & HAS_POINTER && xbutton->button == Button1) {
        pop_menu_show(w, w->childlist->childs[0], 6, true);
    }
}
References XEvent::button, Widget_t::childlist, Childlist_t::childs, Widget_t::flags, HAS_POINTER, and pop_menu_show().
Referenced by add_menu().
_menu_remove_low_dash()
int _menu_remove_low_dash (char * str)
Definition at line 25 of file xmenu_private.c.
{
    char *src;
    char *dst;
    int i = 0;
    int r = 0;
    for (src = dst = str; *src != '\0'; src++) {
        *dst = *src;
        if (*dst != '_') {
            dst++;
        } else {
            r = i;
        }
        i++;
    }
    *dst = '\0';
    return r;
}
Referenced by _draw_accel_item(), _draw_menu_label(), and _draw_submenu().
_radio_item_button_pressed()
void _radio_item_button_pressed (void * w_, void * button_, void * user_data)
_radio_item_button_pressed - redraw item on button press
Parameters
*w_ - void pointer to view_port
*button - the xbutton which is pressed
*user_data - attached user_data
Returns
void
Definition at line 466 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (w->flags & HAS_FOCUS) {
        radio_item_set_active(w);
    }
}
References Widget_t::flags, HAS_FOCUS, and radio_item_set_active().
Referenced by menu_add_radio_item().
_set_menu_viewpoint()
void _set_menu_viewpoint (void * w_, void * user_data)
_set_menu_viewpoint - move the view_port to position by slider
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 451 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t *menu = (Widget_t*)w->parent;
    Widget_t*view_port =  menu->childlist->childs[0];
    adj_set_state(view_port->adj,adj_get_state(w->adj));
}
References Widget_t::adj, adj_get_state(), adj_set_state(), Widget_t::childlist, Childlist_t::childs, and Widget_t::parent.
Referenced by create_menu().
_set_viewpoint()
void _set_viewpoint (void * w_, void * user_data)
_set_viewpoint - move the view_port to position
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 439 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t *menu = (Widget_t*)w->parent;
    Widget_t* slider =  menu->childlist->childs[1];
    int v = (int)max(0,adj_get_value(w->adj));
    Metrics_t metrics;
    os_get_window_metrics(w->childlist->childs[0], &metrics);
    int height = metrics.height;
    os_move_window(w->app->dpy,w,0, -height*v);
    adj_set_state(slider->adj,adj_get_state(w->adj));
}
References Widget_t::adj, adj_get_state(), adj_get_value(), adj_set_state(), Widget_t::app, Widget_t::childlist, Childlist_t::childs, Xputty::dpy, Metrics_t::height, os_get_window_metrics(), os_move_window(), and Widget_t::parent.
Referenced by create_viewport().
_value_item_released()
void _value_item_released (void * w_, void * button_, void * user_data)
_value_item_released - redraw item on button released
Parameters
*w_ - void pointer to view_port
*button - the xbutton which is pressed
*user_data - attached user_data
Returns
void
Definition at line 473 of file xmenu_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    expose_widget(w);
}
References expose_widget().
Referenced by menu_add_value_entry(), and menu_add_value_item().