libxputty: xputty/header/dialogs/xmessage-dialog.h File Reference
xmessage-dialog.h File Reference
Data Structures
struct MessageDialog
Enumerations
enum {
INFO_BOX , WARNING_BOX , ERROR_BOX , QUESTION_BOX ,
SELECTION_BOX , ENTRY_BOX
}
Functions
Widget_t * open_message_dialog (Widget_t *w, int style, const char *title, const char *message, const char *choices)
open_message_dialog - open a non blocking dialog window, lines in message chould be separated by the character "|" choices for the SELECTION_BOX should be separated as well with the character "|". message and/or choices could be NULL when not needed. To fetch the response of a dialog, connect to the dialog_callback supported "styles" been
INFO_BOX - a message dialog display a info text
WARNING_BOX - a message dialog display a warning
ERROR_BOX - a message dialog display a error message
QUESTION_BOX - a no/yes dialog message
SELECTION_BOX - a dialog to select between multiple options
ENTRY_BOX - a dialog to get text input
void radio_box_set_active (Widget_t *w)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
INFO_BOX
WARNING_BOX
ERROR_BOX
QUESTION_BOX
SELECTION_BOX
ENTRY_BOX
Definition at line 32 of file xmessage-dialog.h.
     {
    INFO_BOX,
    WARNING_BOX,
    ERROR_BOX,
    QUESTION_BOX,
    SELECTION_BOX,
    ENTRY_BOX,
};
Function Documentation
open_message_dialog()
Widget_t * open_message_dialog (Widget_t * w, int style, const char * title, const char * message, const char * choices)
open_message_dialog - open a non blocking dialog window, lines in message chould be separated by the character "|" choices for the SELECTION_BOX should be separated as well with the character "|". message and/or choices could be NULL when not needed. To fetch the response of a dialog, connect to the dialog_callback supported "styles" been
INFO_BOX - a message dialog display a info text
WARNING_BOX - a message dialog display a warning
ERROR_BOX - a message dialog display a error message
QUESTION_BOX - a no/yes dialog message
SELECTION_BOX - a dialog to select between multiple options
ENTRY_BOX - a dialog to get text input
Returns
Widget_t* - pointer to the Widget_t struct
Definition at line 386 of file xmessage-dialog.c.
{
    MessageDialog *mb = (MessageDialog*)malloc(sizeof(MessageDialog));
    mb->response = 0;
    mb->message_type = 0;
    mb->lin = 0;
    mb->width = 330;
    mb->height = 200;
    mb->message = NULL;
    mb->sel = 0;
    mb->choices = NULL;
    check_for_message(mb, message);
    check_for_choices(mb, choices);
    check_for_style(mb, style);
    Widget_t *wid = create_window(w->app, os_get_root_window(w->app, IS_WINDOW), 0, 0, mb->width, mb->height);
    wid->label = message;
    wid->flags |= HAS_MEM;
    wid->scale.gravity = CENTER;
    wid->parent_struct = mb;
    wid->parent = w;
    wid->func.mem_free_callback = mg_mem_free;
    wid->func.expose_callback = draw_message_window;
    check_for_hyperlinks(wid);
    char *alternate_title = NULL;
    char *button_title = (char*)_("OK");
    Widget_t *no;
    switch (style) {
        case INFO_BOX:
            widget_get_png(wid, LDVAR(info_png));
            alternate_title = (char*)_("INFO");
            mb->message_type = INFO_BOX;
            widget_set_icon_from_surface(wid, wid->image);
        break;
        case WARNING_BOX:
            widget_get_png(wid, LDVAR(warning_png));
            alternate_title = (char*)_("WARNING");
            mb->message_type = WARNING_BOX;
            widget_set_icon_from_surface(wid, wid->image);
        break;
        case ERROR_BOX:
            widget_get_png(wid, LDVAR(error_png));
            alternate_title = (char*)_("ERROR");
            mb->message_type = ERROR_BOX;
            widget_set_icon_from_surface(wid, wid->image);
        break;
        case QUESTION_BOX:
            widget_get_png(wid, LDVAR(question_png));
            alternate_title = (char*)_("QUESTION");
            no = add_button(wid, _("NO"), 10, mb->height-40, 60, 30);
            no->scale.gravity = CENTER;
            no->func.value_changed_callback = message_no_callback;
            mb->message_type = QUESTION_BOX;
            button_title = (char*)_("YES");
            widget_set_icon_from_surface(wid, wid->image);
        break;
        case SELECTION_BOX:
            widget_get_png(wid, LDVAR(choice_png));
            alternate_title = (char*)_("SELECTION");
            mb->message_type = SELECTION_BOX;
            create_checkboxes(wid);
            widget_set_icon_from_surface(wid, wid->image);
        break;
        case ENTRY_BOX:
            widget_get_png(wid, LDVAR(message_png));
            alternate_title = (char*)_("TEXT ENTRY");
            mb->message_type = ENTRY_BOX;
            create_entry_box(wid);
            widget_set_icon_from_surface(wid, wid->image);
        break;
    }
    widget_set_title(wid, (title)? title : alternate_title);
    Widget_t *okay = add_button(wid, button_title, mb->width-70, mb->height-40, 60, 30);
    okay->scale.gravity = CENTER;
    okay->func.value_changed_callback = message_okay_callback;
    widget_show_all(wid);
    return wid;
}
References add_button(), Widget_t::app, CENTER, MessageDialog::choices, create_window(), ENTRY_BOX, ERROR_BOX, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, MessageDialog::height, Widget_t::image, INFO_BOX, IS_WINDOW, Widget_t::label, MessageDialog::lin, Func_t::mem_free_callback, MessageDialog::message, MessageDialog::message_type, os_get_root_window(), Widget_t::parent, Widget_t::parent_struct, QUESTION_BOX, MessageDialog::response, Widget_t::scale, MessageDialog::sel, SELECTION_BOX, Func_t::value_changed_callback, WARNING_BOX, widget_get_png(), widget_set_icon_from_surface(), widget_set_title(), widget_show_all(), and MessageDialog::width.
Referenced by hyperlink_pressed().
radio_box_set_active()
void radio_box_set_active (Widget_t * w)
Definition at line 235 of file xmessage-dialog.c.
{
    Widget_t * p = (Widget_t*)w->parent;
    MessageDialog *mb = (MessageDialog *)p->parent_struct;
    int response = 0;
    int i = 0;
    for(;i<p->childlist->elem;i++) {
        Widget_t *wid = p->childlist->childs[i];
        if (wid->adj && wid->flags & IS_RADIO) {
            ++response;
            if (wid != w) adj_set_value(wid->adj_y, 0.0);
            else if (wid == w) mb->response = response;
        }
    }
}
References Widget_t::adj, adj_set_value(), Widget_t::adj_y, Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_RADIO, Widget_t::parent, Widget_t::parent_struct, and MessageDialog::response.