libxputty: xputty/dialogs/xmessage-dialog.c File Reference
xmessage-dialog.c File Reference
Functions
void hyperlink_pressed (void *w_, void *button_, void *user_data)
void draw_hyperlink (void *w_, void *user_data)
Widget_t * create_hyperlink (Widget_t *w, char *label, int x, int y, int width, int height)
void radio_box_set_active (Widget_t *w)
Widget_t * open_message_dialog (Widget_t *w, int style, const char *title, const char *message, const char *choices)
open_message_dialog - open a non blocking dialog window, lines in message chould be separated by the character "|" choices for the SELECTION_BOX should be separated as well with the character "|". message and/or choices could be NULL when not needed. To fetch the response of a dialog, connect to the dialog_callback supported "styles" been
INFO_BOX - a message dialog display a info text
WARNING_BOX - a message dialog display a warning
ERROR_BOX - a message dialog display a error message
QUESTION_BOX - a no/yes dialog message
SELECTION_BOX - a dialog to select between multiple options
ENTRY_BOX - a dialog to get text input
Function Documentation
create_hyperlink()
Widget_t * create_hyperlink (Widget_t * w, char * label, int x, int y, int width, int height)
Definition at line 57 of file xmessage-dialog.c.
{
    Widget_t *wid = create_widget(w->app, w, x, y, width, height);
    wid->label = label;
    wid->scale.gravity = ASPECT;
#ifdef __linux__
    Cursor c = XCreateFontCursor(wid->app->dpy, XC_hand2);
    XDefineCursor (wid->app->dpy, wid->widget, c);
    XFreeCursor(wid->app->dpy, c);
#endif
    wid->func.enter_callback = transparent_draw;
    wid->func.leave_callback = transparent_draw;
    wid->func.expose_callback = draw_hyperlink;
    wid->func.button_press_callback = hyperlink_pressed;
    return wid;
}
References Widget_t::app, ASPECT, Func_t::button_press_callback, create_widget(), Xputty::dpy, draw_hyperlink(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, hyperlink_pressed(), Widget_t::label, Func_t::leave_callback, Widget_t::scale, transparent_draw(), and Widget_t::widget.
draw_hyperlink()
void draw_hyperlink (void * w_, void * user_data)
Definition at line 40 of file xmessage-dialog.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    cairo_text_extents_t extents;
    use_fg_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    cairo_text_extents(w->crb,w->label , &extents);
    cairo_move_to (w->crb, (width*0.5)-(extents.width/2), height-(extents.height/4));
    cairo_show_text(w->crb, w->label);
    cairo_new_path (w->crb);
}
References Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::label, Xputty::normal_font, os_get_window_metrics(), Widget_t::scale, use_fg_color_scheme(), and Metrics_t::width.
Referenced by create_hyperlink().
hyperlink_pressed()
void hyperlink_pressed (void * w_, void * button_, void * user_data)
Definition at line 23 of file xmessage-dialog.c.
{
    Widget_t *w = (Widget_t*)w_;
    XButtonEvent *xbutton = (XButtonEvent*)button_;
    if (xbutton->button == Button1) {
        char *command;
        asprintf(&command, "xdg-open '%s'",w->label);
        if (system(NULL)) {
            int ret = system(command);
            if (ret) {
                open_message_dialog(w, ERROR_BOX, "",
                    "Fail to open link", NULL);
            }
        }
        free(command);
    }
}
References asprintf(), XEvent::button, ERROR_BOX, Widget_t::label, and open_message_dialog().
Referenced by create_hyperlink().
open_message_dialog()
Widget_t * open_message_dialog (Widget_t * w, int style, const char * title, const char * message, const char * choices)
open_message_dialog - open a non blocking dialog window, lines in message chould be separated by the character "|" choices for the SELECTION_BOX should be separated as well with the character "|". message and/or choices could be NULL when not needed. To fetch the response of a dialog, connect to the dialog_callback supported "styles" been
INFO_BOX - a message dialog display a info text
WARNING_BOX - a message dialog display a warning
ERROR_BOX - a message dialog display a error message
QUESTION_BOX - a no/yes dialog message
SELECTION_BOX - a dialog to select between multiple options
ENTRY_BOX - a dialog to get text input
Returns
Widget_t* - pointer to the Widget_t struct
Definition at line 386 of file xmessage-dialog.c.
{
    MessageDialog *mb = (MessageDialog*)malloc(sizeof(MessageDialog));
    mb->response = 0;
    mb->message_type = 0;
    mb->lin = 0;
    mb->width = 330;
    mb->height = 200;
    mb->message = NULL;
    mb->sel = 0;
    mb->choices = NULL;
    check_for_message(mb, message);
    check_for_choices(mb, choices);
    check_for_style(mb, style);
    Widget_t *wid = create_window(w->app, os_get_root_window(w->app, IS_WINDOW), 0, 0, mb->width, mb->height);
    wid->label = message;
    wid->flags |= HAS_MEM;
    wid->scale.gravity = CENTER;
    wid->parent_struct = mb;
    wid->parent = w;
    wid->func.mem_free_callback = mg_mem_free;
    wid->func.expose_callback = draw_message_window;
    check_for_hyperlinks(wid);
    char *alternate_title = NULL;
    char *button_title = (char*)_("OK");
    Widget_t *no;
    switch (style) {
        case INFO_BOX:
            widget_get_png(wid, LDVAR(info_png));
            alternate_title = (char*)_("INFO");
            mb->message_type = INFO_BOX;
            widget_set_icon_from_surface(wid, wid->image);
        break;
        case WARNING_BOX:
            widget_get_png(wid, LDVAR(warning_png));
            alternate_title = (char*)_("WARNING");
            mb->message_type = WARNING_BOX;
            widget_set_icon_from_surface(wid, wid->image);
        break;
        case ERROR_BOX:
            widget_get_png(wid, LDVAR(error_png));
            alternate_title = (char*)_("ERROR");
            mb->message_type = ERROR_BOX;
            widget_set_icon_from_surface(wid, wid->image);
        break;
        case QUESTION_BOX:
            widget_get_png(wid, LDVAR(question_png));
            alternate_title = (char*)_("QUESTION");
            no = add_button(wid, _("NO"), 10, mb->height-40, 60, 30);
            no->scale.gravity = CENTER;
            no->func.value_changed_callback = message_no_callback;
            mb->message_type = QUESTION_BOX;
            button_title = (char*)_("YES");
            widget_set_icon_from_surface(wid, wid->image);
        break;
        case SELECTION_BOX:
            widget_get_png(wid, LDVAR(choice_png));
            alternate_title = (char*)_("SELECTION");
            mb->message_type = SELECTION_BOX;
            create_checkboxes(wid);
            widget_set_icon_from_surface(wid, wid->image);
        break;
        case ENTRY_BOX:
            widget_get_png(wid, LDVAR(message_png));
            alternate_title = (char*)_("TEXT ENTRY");
            mb->message_type = ENTRY_BOX;
            create_entry_box(wid);
            widget_set_icon_from_surface(wid, wid->image);
        break;
    }
    widget_set_title(wid, (title)? title : alternate_title);
    Widget_t *okay = add_button(wid, button_title, mb->width-70, mb->height-40, 60, 30);
    okay->scale.gravity = CENTER;
    okay->func.value_changed_callback = message_okay_callback;
    widget_show_all(wid);
    return wid;
}
References add_button(), Widget_t::app, CENTER, MessageDialog::choices, create_window(), ENTRY_BOX, ERROR_BOX, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, MessageDialog::height, Widget_t::image, INFO_BOX, IS_WINDOW, Widget_t::label, MessageDialog::lin, Func_t::mem_free_callback, MessageDialog::message, MessageDialog::message_type, os_get_root_window(), Widget_t::parent, Widget_t::parent_struct, QUESTION_BOX, MessageDialog::response, Widget_t::scale, MessageDialog::sel, SELECTION_BOX, Func_t::value_changed_callback, WARNING_BOX, widget_get_png(), widget_set_icon_from_surface(), widget_set_title(), widget_show_all(), and MessageDialog::width.
Referenced by hyperlink_pressed().
radio_box_set_active()
void radio_box_set_active (Widget_t * w)
Definition at line 235 of file xmessage-dialog.c.
{
    Widget_t * p = (Widget_t*)w->parent;
    MessageDialog *mb = (MessageDialog *)p->parent_struct;
    int response = 0;
    int i = 0;
    for(;i<p->childlist->elem;i++) {
        Widget_t *wid = p->childlist->childs[i];
        if (wid->adj && wid->flags & IS_RADIO) {
            ++response;
            if (wid != w) adj_set_value(wid->adj_y, 0.0);
            else if (wid == w) mb->response = response;
        }
    }
}
References Widget_t::adj, adj_set_value(), Widget_t::adj_y, Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_RADIO, Widget_t::parent, Widget_t::parent_struct, and MessageDialog::response.