libxputty: xputty/dialogs/xmidi_keyboard.c File Reference
xmidi_keyboard.c File Reference
Functions
void mk_keysym_azerty_to_midi_key (long inkey, float *midi_key)
void mk_keysym_qwertz_to_midi_key (long inkey, float *midi_key)
void mk_keysym_qwerty_to_midi_key (unsigned int inkey, float *midi_key)
bool mk_is_key_in_matrix (unsigned long *key_matrix, int key)
bool mk_have_key_in_matrix (unsigned long *key_matrix)
void mk_clear_key_matrix (unsigned long *key_matrix)
void mk_draw_knob (void *w_, void *user_data)
Widget_t * add_keyboard_knob (Widget_t *parent, const char *label, int x, int y, int width, int height)
Widget_t * mk_open_midi_keyboard (Widget_t *w)
Function Documentation
add_keyboard_knob()
Widget_t * add_keyboard_knob (Widget_t * parent, const char * label, int x, int y, int width, int height)
Definition at line 789 of file xmidi_keyboard.c.
{
    Widget_t *wid = add_knob(parent,label, x, y, width, height);
    wid->flags |= NO_AUTOREPEAT;
    set_adjustment(wid->adj,64.0, 64.0, 0.0, 127.0, 1.0, CL_CONTINUOS);
    wid->func.expose_callback = mk_draw_knob;
    wid->func.key_press_callback = wheel_key_press;
    wid->func.key_release_callback = wheel_key_release;
    return wid;
}
References add_knob(), Widget_t::adj, CL_CONTINUOS, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Func_t::key_press_callback, Func_t::key_release_callback, mk_draw_knob(), NO_AUTOREPEAT, and set_adjustment().
Referenced by mk_open_midi_keyboard().
mk_clear_key_matrix()
void mk_clear_key_matrix (unsigned long * key_matrix)
Definition at line 221 of file xmidi_keyboard.c.
{
    int i = 0;
    int j = 0;
    for(;j<4;j++) {
        for(;i<32;i++) {
            key_matrix[j] &= (~(1 << i));
        }
        i = 0;
    }
}
mk_draw_knob()
void mk_draw_knob (void * w_, void * user_data)
get values for the knob
create a rotating pointer on the kob
show value on the kob
show label below the knob
Definition at line 231 of file xmidi_keyboard.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    const double scale_zero = 20 * (M_PI/180); // defines "dead zone" for knobs
    int arc_offset = 2;
    int knob_x = 0;
    int knob_y = 0;
    int grow = (width > height) ? height:width;
    knob_x = grow-1;
    knob_y = grow-1;
    int knobx = (width - knob_x) * 0.5;
    int knobx1 = width* 0.5;
    int knoby = (height - knob_y) * 0.5;
    int knoby1 = height * 0.5;
    double knobstate = adj_get_state(w->adj_y);
    double angle = scale_zero + knobstate * 2 * (M_PI - scale_zero);
    double pointer_off =knob_x/3.5;
    double radius = min(knob_x-pointer_off, knob_y-pointer_off) / 2;
    double lengh_x = (knobx+radius+pointer_off/2) - radius * sin(angle);
    double lengh_y = (knoby+radius+pointer_off/2) + radius * cos(angle);
    double radius_x = (knobx+radius+pointer_off/2) - radius/ 1.18 * sin(angle);
    double radius_y = (knoby+radius+pointer_off/2) + radius/ 1.18 * cos(angle);
    cairo_pattern_t* pat;
    cairo_new_path (w->crb);
    pat = cairo_pattern_create_linear (0, 0, 0, knob_y);
    cairo_pattern_add_color_stop_rgba (pat, 1,  0.3, 0.3, 0.3, 1.0);
    cairo_pattern_add_color_stop_rgba (pat, 0.75,  0.2, 0.2, 0.2, 1.0);
    cairo_pattern_add_color_stop_rgba (pat, 0.5,  0.15, 0.15, 0.15, 1.0);
    cairo_pattern_add_color_stop_rgba (pat, 0.25,  0.1, 0.1, 0.1, 1.0);
    cairo_pattern_add_color_stop_rgba (pat, 0,  0.05, 0.05, 0.05, 1.0);
    cairo_scale (w->crb, 0.95, 1.05);
    cairo_arc(w->crb,knobx1+arc_offset/2, knoby1-arc_offset, knob_x/2.2, 0, 2 * M_PI );
    cairo_set_source (w->crb, pat);
    cairo_fill_preserve (w->crb);
     cairo_set_source_rgb (w->crb, 0.1, 0.1, 0.1);
    cairo_set_line_width(w->crb,1);
    cairo_stroke(w->crb);
    cairo_scale (w->crb, 1.05, 0.95);
    cairo_new_path (w->crb);
    cairo_pattern_destroy (pat);
    pat = NULL;
    pat = cairo_pattern_create_linear (0, 0, 0, knob_y);
    cairo_pattern_add_color_stop_rgba (pat, 0,  0.3, 0.3, 0.3, 1.0);
    cairo_pattern_add_color_stop_rgba (pat, 0.25,  0.2, 0.2, 0.2, 1.0);
    cairo_pattern_add_color_stop_rgba (pat, 0.5,  0.15, 0.15, 0.15, 1.0);
    cairo_pattern_add_color_stop_rgba (pat, 0.75,  0.1, 0.1, 0.1, 1.0);
    cairo_pattern_add_color_stop_rgba (pat, 1,  0.05, 0.05, 0.05, 1.0);
    cairo_arc(w->crb,knobx1, knoby1, knob_x/2.6, 0, 2 * M_PI );
    cairo_set_source (w->crb, pat);
    cairo_fill_preserve (w->crb);
     cairo_set_source_rgb (w->crb, 0.1, 0.1, 0.1);
    cairo_set_line_width(w->crb,1);
    cairo_stroke(w->crb);
    cairo_new_path (w->crb);
    cairo_pattern_destroy (pat);
    cairo_set_line_cap(w->crb, CAIRO_LINE_CAP_ROUND);
    cairo_set_line_join(w->crb, CAIRO_LINE_JOIN_BEVEL);
    cairo_move_to(w->crb, radius_x, radius_y);
    cairo_line_to(w->crb,lengh_x,lengh_y);
    cairo_set_line_width(w->crb,3);
    cairo_set_source_rgb (w->crb,0.63,0.63,0.63);
    cairo_stroke(w->crb);
    cairo_new_path (w->crb);
    cairo_text_extents_t extents;
    if (w->state) {
        char s[64];
        snprintf(s, 63,"%d",  (int) w->adj_y->value);
        cairo_set_source_rgb (w->crb, 0.6, 0.6, 0.6);
        cairo_set_font_size (w->crb, knobx1/3);
        cairo_text_extents(w->crb, s, &extents);
        cairo_move_to (w->crb, knobx1-extents.width/2, knoby1+extents.height/2);
        cairo_show_text(w->crb, s);
        cairo_new_path (w->crb);
    }
    use_text_color_scheme(w, get_color_state(w));
    float font_size = ((height/2.2 < (width*0.5)/3) ? height/2.2 : (width*0.5)/3);
    cairo_set_font_size (w->crb, font_size);
    cairo_text_extents(w->crb,w->label , &extents);
    cairo_move_to (w->crb, knobx1-extents.width/2, height );
    cairo_show_text(w->crb, w->label);
    cairo_new_path (w->crb);
}
References adj_get_state(), Widget_t::adj_y, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::label, os_get_window_metrics(), Widget_t::state, use_text_color_scheme(), Adjustment_t::value, Metrics_t::visible, and Metrics_t::width.
Referenced by add_keyboard_knob().
mk_have_key_in_matrix()
bool mk_have_key_in_matrix (unsigned long * key_matrix)
Definition at line 204 of file xmidi_keyboard.c.
{
    bool ret = false;
    int i = 0;
    int j = 0;
    for(;j<4;j++) {
        for(;i<32;i++) {
            if(key_matrix[j] & (1<<i)) {
                ret = true;
                break;
            }
        }
        i = 0;
    }
    return ret;
}
mk_is_key_in_matrix()
bool mk_is_key_in_matrix (unsigned long * key_matrix, int key)
Definition at line 183 of file xmidi_keyboard.c.
{
    unsigned long *use_matrix = &key_matrix[0];
    if(key>94) {
        use_matrix = &key_matrix[3];
        key -=94;
    } else if(key>62) {
        use_matrix = &key_matrix[2];
        key -=62;
    } else if(key>31) {
        use_matrix = &key_matrix[1];
        key -= 31;
    }
    bool ret = false;
    if((*use_matrix) & (1<<key)) {
        ret = true;
    }
    return ret;
}
mk_keysym_azerty_to_midi_key()
void mk_keysym_azerty_to_midi_key (long inkey, float * midi_key)
Definition at line 24 of file xmidi_keyboard.c.
{
    switch(inkey) {
        case(XK_w) : (*midi_key) = 12.0; /* w = C0 */
        break;
        case(XK_s) : (*midi_key) = 13.0; /* s */
        break;
        case(XK_x) : (*midi_key) = 14.0; /* x */
        break;
        case(XK_d) : (*midi_key) = 15.0; /* d */
        break;
        case(XK_c) : (*midi_key) = 16.0; /* c */
        break;
        case(XK_v) : (*midi_key) = 17.0; /* v */
        break;
        case(XK_g) : (*midi_key) = 18.0; /* g */
        break;
        case(XK_b) : (*midi_key) = 19.0; /* b */
        break;
        case(XK_h) : (*midi_key) = 20.0; /* h */
        break;
        case(XK_n) : (*midi_key) = 21.0; /* n */
        break;
        case(XK_j) : (*midi_key) = 22.0; /* j */
        break;
        case(XK_comma) : (*midi_key) = 23.0; /* , */
        break;
        case(XK_a) : (*midi_key) = 24.0; /* a */
        break;
        case(XK_eacute) : (*midi_key) = 25.0; /* eacute */
        break;
        case(XK_z) : (*midi_key) = 26.0; /* z */
        break;
        case(XK_quotedbl) : (*midi_key) = 27.0; /* quotedbl */
        break;
        case(XK_e) : (*midi_key) = 28.0; /* e */
        break;
        case(XK_r) : (*midi_key) = 29.0; /* r */
        break;
        case(XK_parenleft) : (*midi_key) = 30.0; /* parenleft */
        break;
        case(XK_t) : (*midi_key) = 31.0; /* t */
        break;
        case(XK_minus) : (*midi_key) = 32.0; /* minus */
        break;
        case(XK_y) : (*midi_key) = 33.0; /* y */
        break;
        case(XK_egrave) : (*midi_key) = 34.0; /* egrave */
        break;
        case(XK_u) : (*midi_key) = 35.0; /* u */
        break;
        case(XK_i) : (*midi_key) = 36.0; /* i */
        break;
        case(XK_ccedilla) : (*midi_key) = 37.0; /* ccedilla */
        break;
        case(XK_o) : (*midi_key) = 38.0; /* o */
        break;
        case(XK_agrave) : (*midi_key) = 39.0; /* agrave */
        break;
        case(XK_p) : (*midi_key) = 40.0; /* p */
        break;
        case(XK_dead_diaeresis) :
        case(XK_dead_circumflex) : (*midi_key) = 41.0; /* dead circumflex */
        break;
    }
}
mk_keysym_qwerty_to_midi_key()
void mk_keysym_qwerty_to_midi_key (unsigned int inkey, float * midi_key)
Definition at line 157 of file xmidi_keyboard.c.
{
    mk_keysym_qwertz_to_midi_key(inkey,midi_key);
    if ((*midi_key) == 12) (*midi_key) = 33;
    else if ((*midi_key) == 33) (*midi_key) = 12;
}
References mk_keysym_qwertz_to_midi_key().
mk_keysym_qwertz_to_midi_key()
void mk_keysym_qwertz_to_midi_key (long inkey, float * midi_key)
Definition at line 90 of file xmidi_keyboard.c.
{
    switch(inkey) {
        case(XK_y) : (*midi_key) = 12.0; /* y = C0 */
        break;
        case(XK_s) : (*midi_key) = 13.0; /* s */
        break;
        case(XK_x) : (*midi_key) = 14.0; /* x */
        break;
        case(XK_d) : (*midi_key) = 15.0; /* d */
        break;
        case(XK_c) : (*midi_key) = 16.0; /* c */
        break;
        case(XK_v) : (*midi_key) = 17.0; /* v */
        break;
        case(XK_g) : (*midi_key) = 18.0; /* g */
        break;
        case(XK_b) : (*midi_key) = 19.0; /* b */
        break;
        case(XK_h) : (*midi_key) = 20.0; /* h */
        break;
        case(XK_n) : (*midi_key) = 21.0; /* n */
        break;
        case(XK_j) : (*midi_key) = 22.0; /* j */
        break;
        case(XK_m) : (*midi_key) = 23.0; /* m */
        break;
        case(XK_q) : (*midi_key) = 24.0; /* q */
        break;
        case(XK_2) : (*midi_key) = 25.0; /* 2 */
        break;
        case(XK_w) : (*midi_key) = 26.0; /* w */
        break;
        case(XK_3) : (*midi_key) = 27.0; /* 3 */
        break;
        case(XK_e) : (*midi_key) = 28.0; /* e */
        break;
        case(XK_r) : (*midi_key) = 29.0; /* r */
        break;
        case(XK_5) : (*midi_key) = 30.0; /* 5 */
        break;
        case(XK_t) : (*midi_key) = 31.0; /* t */
        break;
        case(XK_6) : (*midi_key) = 32.0; /* 6 */
        break;
        case(XK_z) : (*midi_key) = 33.0; /* z */
        break;
        case(XK_7) : (*midi_key) = 34.0; /* 7 */
        break;
        case(XK_u) : (*midi_key) = 35.0; /* u */
        break;
        case(XK_i) : (*midi_key) = 36.0; /* i */
        break;
        case(XK_9) : (*midi_key) = 37.0; /* 9 */
        break;
        case(XK_o) : (*midi_key) = 38.0; /* o */
        break;
        case(XK_0) : (*midi_key) = 39.0; /* 0 */
        break;
        case(XK_p) : (*midi_key) = 40.0; /* p */
        break;
        case(XK_udiaeresis) : (*midi_key) = 41.0; /*  */
        break;
        case(XK_plus) : (*midi_key) = 42.0; /* + */
        break;
    }
}
Referenced by mk_keysym_qwerty_to_midi_key().
mk_open_midi_keyboard()
Widget_t * mk_open_midi_keyboard (Widget_t * w)
Definition at line 800 of file xmidi_keyboard.c.
{
    Widget_t *wid = create_window(w->app, os_get_root_window(w->app, IS_WINDOW), 0, 0, 700, 200);
    os_set_input_mask(wid);
    MidiKeyboard_mk *keys = (MidiKeyboard_mk*)malloc(sizeof(MidiKeyboard_mk));
    wid->parent_struct = keys;
    wid->parent = w;
    wid->flags |= HAS_MEM | NO_AUTOREPEAT;
    keys->prelight_key = -1;
    keys->active_key = -1;
    keys->send_key = -1;
    keys->octave = 12*2;
    keys->layout = 0;
    int j = 0;
    for(;j<4;j++) {
        keys->key_matrix[j] = 0;
    }
    wid->func.expose_callback = draw_keyboard;
    wid->func.motion_callback = keyboard_motion;
    wid->func.leave_callback = leave_keyboard;
    wid->func.button_press_callback = button_pressed_keyboard;
    wid->func.button_release_callback = button_released_keyboard;
    wid->func.key_press_callback = key_press;
    wid->func.key_release_callback = key_release;
    wid->func.mem_free_callback = keyboard_mem_free;
    wid->func.map_notify_callback = map_keyboard;
    widget_set_icon_from_png(wid, LDVAR(midikeyboard_png));
    widget_set_title(wid, "Midi Keyboard");
    keys->mk_send_note = key_dummy;
    keys->mk_send_pitch = wheel_dummy;
    keys->mk_send_pitchsensity = wheel_dummy;
    keys->mk_send_mod = wheel_dummy;
    keys->mk_send_detune = wheel_dummy;
    keys->mk_send_attack = wheel_dummy;
    keys->mk_send_sustain = wheel_dummy;
    keys->mk_send_release = wheel_dummy;
    keys->mk_send_volume = wheel_dummy;
    keys->mk_send_velocity = wheel_dummy;
    keys->mk_send_all_sound_off = wheel_dummy;
    Widget_t *p = add_keyboard_knob(wid, "PitchBend", 5, 0, 60, 75);
    p->func.value_changed_callback = pitchwheel_callback;
    keys->pitchwheel = (int)adj_get_value(p->adj);
    Widget_t *s = add_keyboard_knob(wid, "P.Sensity", 65, 0, 60, 75);
    s->func.value_changed_callback = pitchsensity_callback;
    keys->pitchsensity = (int)adj_get_value(s->adj);
    Widget_t *m = add_keyboard_knob(wid, "ModWheel", 125, 0, 60, 75);
    m->func.value_changed_callback = modwheel_callback;
    keys->modwheel = (int)adj_get_value(m->adj);
    Widget_t *de = add_keyboard_knob(wid, "Detune", 185, 0, 60, 75);
    de->func.value_changed_callback = detune_callback;
    keys->detune = (int)adj_get_value(de->adj);
    Widget_t *at = add_keyboard_knob(wid, "Attack", 245, 0, 60, 75);
    at->func.value_changed_callback = attack_callback;
    keys->attack = (int)adj_get_value(at->adj);
    Widget_t *su = add_keyboard_knob(wid, "Sustain", 305, 0, 60, 75);
    su->func.value_changed_callback = sustain_callback;
    keys->sustain = (int)adj_get_value(su->adj);
    Widget_t *re = add_keyboard_knob(wid, "Release", 365, 0, 60, 75);
    re->func.value_changed_callback = release_callback;
    keys->release = (int)adj_get_value(re->adj);
    Widget_t *v = add_keyboard_knob(wid, "Volume", 425, 0, 60, 75);
    v->func.value_changed_callback = volume_callback;
    keys->volume = (int)adj_get_value(v->adj);
    Widget_t *ve = add_keyboard_knob(wid, "Velocity", 485, 0, 60, 75);
    set_adjustment(ve->adj,127.0, 127.0, 0.0, 127.0, 1.0, CL_CONTINUOS);
    ve->func.value_changed_callback = velocity_callback;
    keys->velocity = (int)adj_get_value(ve->adj);
    Widget_t *b = add_hslider(wid, "Keyboard mapping", 540, 40, 160, 35);
    b->flags |= NO_AUTOREPEAT;
    set_adjustment(b->adj,2.0, 2.0, 0.0, 4.0, 1.0, CL_CONTINUOS);
    adj_set_scale(b->adj, 0.05);
    b->func.value_changed_callback = octave_callback;
    Widget_t *layout = add_combobox(wid, "", 550, 2, 130, 30);
    layout->flags |= NO_AUTOREPEAT;
    layout->scale.gravity = ASPECT;
    combobox_add_entry(layout,"qwertz");
    combobox_add_entry(layout,"qwerty");
    combobox_add_entry(layout,"azerty");
    combobox_set_active_entry(layout, 0);
    set_adjustment(layout->adj,0.0, 0.0, 0.0, 2.0, 1.0, CL_ENUM);
    layout->func.value_changed_callback = layout_callback;
 return wid;
}
References MidiKeyboard_mk::active_key, add_combobox(), add_hslider(), add_keyboard_knob(), Widget_t::adj, adj_get_value(), adj_set_scale(), Widget_t::app, ASPECT, MidiKeyboard_mk::attack, Func_t::button_press_callback, Func_t::button_release_callback, CL_CONTINUOS, CL_ENUM, combobox_add_entry(), combobox_set_active_entry(), create_window(), MidiKeyboard_mk::detune, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, IS_WINDOW, MidiKeyboard_mk::key_matrix, Func_t::key_press_callback, Func_t::key_release_callback, MidiKeyboard_mk::layout, Func_t::leave_callback, Func_t::map_notify_callback, Func_t::mem_free_callback, MidiKeyboard_mk::mk_send_all_sound_off, MidiKeyboard_mk::mk_send_attack, MidiKeyboard_mk::mk_send_detune, MidiKeyboard_mk::mk_send_mod, MidiKeyboard_mk::mk_send_note, MidiKeyboard_mk::mk_send_pitch, MidiKeyboard_mk::mk_send_pitchsensity, MidiKeyboard_mk::mk_send_release, MidiKeyboard_mk::mk_send_sustain, MidiKeyboard_mk::mk_send_velocity, MidiKeyboard_mk::mk_send_volume, MidiKeyboard_mk::modwheel, Func_t::motion_callback, NO_AUTOREPEAT, MidiKeyboard_mk::octave, os_get_root_window(), os_set_input_mask(), Widget_t::parent, Widget_t::parent_struct, MidiKeyboard_mk::pitchsensity, MidiKeyboard_mk::pitchwheel, MidiKeyboard_mk::prelight_key, MidiKeyboard_mk::release, Widget_t::scale, MidiKeyboard_mk::send_key, set_adjustment(), MidiKeyboard_mk::sustain, Func_t::value_changed_callback, MidiKeyboard_mk::velocity, MidiKeyboard_mk::volume, widget_set_icon_from_png(), and widget_set_title().