libxputty: xputty/header/dialogs/xmidi_keyboard.h File Reference
xmidi_keyboard.h File Reference
Data Structures
struct MidiKeyboard_mk
Typedefs
typedef void(* mk_midikeyfunc) (Widget_t *w, int *key, bool on_off)
typedef void(* mk_midiwheelfunc) (Widget_t *w, int *value)
Functions
void mk_keysym_azerty_to_midi_key (long inkey, float *midi_key)
void mk_keysym_qwertz_to_midi_key (long inkey, float *midi_key)
void mk_keysym_qwerty_to_midi_key (unsigned int inkey, float *midi_key)
bool mk_is_key_in_matrix (unsigned long *key_matrix, int key)
bool mk_have_key_in_matrix (unsigned long *key_matrix)
void mk_clear_key_matrix (unsigned long *key_matrix)
Widget_t * mk_open_midi_keyboard (Widget_t *w)
Typedef Documentation
mk_midikeyfunc
typedef void(* mk_midikeyfunc) (Widget_t *w, int *key, bool on_off)
Definition at line 32 of file xmidi_keyboard.h.
mk_midiwheelfunc
typedef void(* mk_midiwheelfunc) (Widget_t *w, int *value)
Definition at line 33 of file xmidi_keyboard.h.
Function Documentation
mk_clear_key_matrix()
void mk_clear_key_matrix (unsigned long * key_matrix)
Definition at line 221 of file xmidi_keyboard.c.
{
    int i = 0;
    int j = 0;
    for(;j<4;j++) {
        for(;i<32;i++) {
            key_matrix[j] &= (~(1 << i));
        }
        i = 0;
    }
}
mk_have_key_in_matrix()
bool mk_have_key_in_matrix (unsigned long * key_matrix)
Definition at line 204 of file xmidi_keyboard.c.
{
    bool ret = false;
    int i = 0;
    int j = 0;
    for(;j<4;j++) {
        for(;i<32;i++) {
            if(key_matrix[j] & (1<<i)) {
                ret = true;
                break;
            }
        }
        i = 0;
    }
    return ret;
}
mk_is_key_in_matrix()
bool mk_is_key_in_matrix (unsigned long * key_matrix, int key)
Definition at line 183 of file xmidi_keyboard.c.
{
    unsigned long *use_matrix = &key_matrix[0];
    if(key>94) {
        use_matrix = &key_matrix[3];
        key -=94;
    } else if(key>62) {
        use_matrix = &key_matrix[2];
        key -=62;
    } else if(key>31) {
        use_matrix = &key_matrix[1];
        key -= 31;
    }
    bool ret = false;
    if((*use_matrix) & (1<<key)) {
        ret = true;
    }
    return ret;
}
mk_keysym_azerty_to_midi_key()
void mk_keysym_azerty_to_midi_key (long inkey, float * midi_key)
Definition at line 24 of file xmidi_keyboard.c.
{
    switch(inkey) {
        case(XK_w) : (*midi_key) = 12.0; /* w = C0 */
        break;
        case(XK_s) : (*midi_key) = 13.0; /* s */
        break;
        case(XK_x) : (*midi_key) = 14.0; /* x */
        break;
        case(XK_d) : (*midi_key) = 15.0; /* d */
        break;
        case(XK_c) : (*midi_key) = 16.0; /* c */
        break;
        case(XK_v) : (*midi_key) = 17.0; /* v */
        break;
        case(XK_g) : (*midi_key) = 18.0; /* g */
        break;
        case(XK_b) : (*midi_key) = 19.0; /* b */
        break;
        case(XK_h) : (*midi_key) = 20.0; /* h */
        break;
        case(XK_n) : (*midi_key) = 21.0; /* n */
        break;
        case(XK_j) : (*midi_key) = 22.0; /* j */
        break;
        case(XK_comma) : (*midi_key) = 23.0; /* , */
        break;
        case(XK_a) : (*midi_key) = 24.0; /* a */
        break;
        case(XK_eacute) : (*midi_key) = 25.0; /* eacute */
        break;
        case(XK_z) : (*midi_key) = 26.0; /* z */
        break;
        case(XK_quotedbl) : (*midi_key) = 27.0; /* quotedbl */
        break;
        case(XK_e) : (*midi_key) = 28.0; /* e */
        break;
        case(XK_r) : (*midi_key) = 29.0; /* r */
        break;
        case(XK_parenleft) : (*midi_key) = 30.0; /* parenleft */
        break;
        case(XK_t) : (*midi_key) = 31.0; /* t */
        break;
        case(XK_minus) : (*midi_key) = 32.0; /* minus */
        break;
        case(XK_y) : (*midi_key) = 33.0; /* y */
        break;
        case(XK_egrave) : (*midi_key) = 34.0; /* egrave */
        break;
        case(XK_u) : (*midi_key) = 35.0; /* u */
        break;
        case(XK_i) : (*midi_key) = 36.0; /* i */
        break;
        case(XK_ccedilla) : (*midi_key) = 37.0; /* ccedilla */
        break;
        case(XK_o) : (*midi_key) = 38.0; /* o */
        break;
        case(XK_agrave) : (*midi_key) = 39.0; /* agrave */
        break;
        case(XK_p) : (*midi_key) = 40.0; /* p */
        break;
        case(XK_dead_diaeresis) :
        case(XK_dead_circumflex) : (*midi_key) = 41.0; /* dead circumflex */
        break;
    }
}
mk_keysym_qwerty_to_midi_key()
void mk_keysym_qwerty_to_midi_key (unsigned int inkey, float * midi_key)
Definition at line 157 of file xmidi_keyboard.c.
{
    mk_keysym_qwertz_to_midi_key(inkey,midi_key);
    if ((*midi_key) == 12) (*midi_key) = 33;
    else if ((*midi_key) == 33) (*midi_key) = 12;
}
References mk_keysym_qwertz_to_midi_key().
mk_keysym_qwertz_to_midi_key()
void mk_keysym_qwertz_to_midi_key (long inkey, float * midi_key)
Definition at line 90 of file xmidi_keyboard.c.
{
    switch(inkey) {
        case(XK_y) : (*midi_key) = 12.0; /* y = C0 */
        break;
        case(XK_s) : (*midi_key) = 13.0; /* s */
        break;
        case(XK_x) : (*midi_key) = 14.0; /* x */
        break;
        case(XK_d) : (*midi_key) = 15.0; /* d */
        break;
        case(XK_c) : (*midi_key) = 16.0; /* c */
        break;
        case(XK_v) : (*midi_key) = 17.0; /* v */
        break;
        case(XK_g) : (*midi_key) = 18.0; /* g */
        break;
        case(XK_b) : (*midi_key) = 19.0; /* b */
        break;
        case(XK_h) : (*midi_key) = 20.0; /* h */
        break;
        case(XK_n) : (*midi_key) = 21.0; /* n */
        break;
        case(XK_j) : (*midi_key) = 22.0; /* j */
        break;
        case(XK_m) : (*midi_key) = 23.0; /* m */
        break;
        case(XK_q) : (*midi_key) = 24.0; /* q */
        break;
        case(XK_2) : (*midi_key) = 25.0; /* 2 */
        break;
        case(XK_w) : (*midi_key) = 26.0; /* w */
        break;
        case(XK_3) : (*midi_key) = 27.0; /* 3 */
        break;
        case(XK_e) : (*midi_key) = 28.0; /* e */
        break;
        case(XK_r) : (*midi_key) = 29.0; /* r */
        break;
        case(XK_5) : (*midi_key) = 30.0; /* 5 */
        break;
        case(XK_t) : (*midi_key) = 31.0; /* t */
        break;
        case(XK_6) : (*midi_key) = 32.0; /* 6 */
        break;
        case(XK_z) : (*midi_key) = 33.0; /* z */
        break;
        case(XK_7) : (*midi_key) = 34.0; /* 7 */
        break;
        case(XK_u) : (*midi_key) = 35.0; /* u */
        break;
        case(XK_i) : (*midi_key) = 36.0; /* i */
        break;
        case(XK_9) : (*midi_key) = 37.0; /* 9 */
        break;
        case(XK_o) : (*midi_key) = 38.0; /* o */
        break;
        case(XK_0) : (*midi_key) = 39.0; /* 0 */
        break;
        case(XK_p) : (*midi_key) = 40.0; /* p */
        break;
        case(XK_udiaeresis) : (*midi_key) = 41.0; /* ü */
        break;
        case(XK_plus) : (*midi_key) = 42.0; /* + */
        break;
    }
}
Referenced by mk_keysym_qwerty_to_midi_key().
mk_open_midi_keyboard()
Widget_t * mk_open_midi_keyboard (Widget_t * w)
Definition at line 800 of file xmidi_keyboard.c.
{
    Widget_t *wid = create_window(w->app, os_get_root_window(w->app, IS_WINDOW), 0, 0, 700, 200);
    os_set_input_mask(wid);
    MidiKeyboard_mk *keys = (MidiKeyboard_mk*)malloc(sizeof(MidiKeyboard_mk));
    wid->parent_struct = keys;
    wid->parent = w;
    wid->flags |= HAS_MEM | NO_AUTOREPEAT;
    keys->prelight_key = -1;
    keys->active_key = -1;
    keys->send_key = -1;
    keys->octave = 12*2;
    keys->layout = 0;
    int j = 0;
    for(;j<4;j++) {
        keys->key_matrix[j] = 0;
    }
    wid->func.expose_callback = draw_keyboard;
    wid->func.motion_callback = keyboard_motion;
    wid->func.leave_callback = leave_keyboard;
    wid->func.button_press_callback = button_pressed_keyboard;
    wid->func.button_release_callback = button_released_keyboard;
    wid->func.key_press_callback = key_press;
    wid->func.key_release_callback = key_release;
    wid->func.mem_free_callback = keyboard_mem_free;
    wid->func.map_notify_callback = map_keyboard;
    widget_set_icon_from_png(wid, LDVAR(midikeyboard_png));
    widget_set_title(wid, "Midi Keyboard");
    keys->mk_send_note = key_dummy;
    keys->mk_send_pitch = wheel_dummy;
    keys->mk_send_pitchsensity = wheel_dummy;
    keys->mk_send_mod = wheel_dummy;
    keys->mk_send_detune = wheel_dummy;
    keys->mk_send_attack = wheel_dummy;
    keys->mk_send_sustain = wheel_dummy;
    keys->mk_send_release = wheel_dummy;
    keys->mk_send_volume = wheel_dummy;
    keys->mk_send_velocity = wheel_dummy;
    keys->mk_send_all_sound_off = wheel_dummy;
    Widget_t *p = add_keyboard_knob(wid, "PitchBend", 5, 0, 60, 75);
    p->func.value_changed_callback = pitchwheel_callback;
    keys->pitchwheel = (int)adj_get_value(p->adj);
    Widget_t *s = add_keyboard_knob(wid, "P.Sensity", 65, 0, 60, 75);
    s->func.value_changed_callback = pitchsensity_callback;
    keys->pitchsensity = (int)adj_get_value(s->adj);
    Widget_t *m = add_keyboard_knob(wid, "ModWheel", 125, 0, 60, 75);
    m->func.value_changed_callback = modwheel_callback;
    keys->modwheel = (int)adj_get_value(m->adj);
    Widget_t *de = add_keyboard_knob(wid, "Detune", 185, 0, 60, 75);
    de->func.value_changed_callback = detune_callback;
    keys->detune = (int)adj_get_value(de->adj);
    Widget_t *at = add_keyboard_knob(wid, "Attack", 245, 0, 60, 75);
    at->func.value_changed_callback = attack_callback;
    keys->attack = (int)adj_get_value(at->adj);
    Widget_t *su = add_keyboard_knob(wid, "Sustain", 305, 0, 60, 75);
    su->func.value_changed_callback = sustain_callback;
    keys->sustain = (int)adj_get_value(su->adj);
    Widget_t *re = add_keyboard_knob(wid, "Release", 365, 0, 60, 75);
    re->func.value_changed_callback = release_callback;
    keys->release = (int)adj_get_value(re->adj);
    Widget_t *v = add_keyboard_knob(wid, "Volume", 425, 0, 60, 75);
    v->func.value_changed_callback = volume_callback;
    keys->volume = (int)adj_get_value(v->adj);
    Widget_t *ve = add_keyboard_knob(wid, "Velocity", 485, 0, 60, 75);
    set_adjustment(ve->adj,127.0, 127.0, 0.0, 127.0, 1.0, CL_CONTINUOS);
    ve->func.value_changed_callback = velocity_callback;
    keys->velocity = (int)adj_get_value(ve->adj);
    Widget_t *b = add_hslider(wid, "Keyboard mapping", 540, 40, 160, 35);
    b->flags |= NO_AUTOREPEAT;
    set_adjustment(b->adj,2.0, 2.0, 0.0, 4.0, 1.0, CL_CONTINUOS);
    adj_set_scale(b->adj, 0.05);
    b->func.value_changed_callback = octave_callback;
    Widget_t *layout = add_combobox(wid, "", 550, 2, 130, 30);
    layout->flags |= NO_AUTOREPEAT;
    layout->scale.gravity = ASPECT;
    combobox_add_entry(layout,"qwertz");
    combobox_add_entry(layout,"qwerty");
    combobox_add_entry(layout,"azerty");
    combobox_set_active_entry(layout, 0);
    set_adjustment(layout->adj,0.0, 0.0, 0.0, 2.0, 1.0, CL_ENUM);
    layout->func.value_changed_callback = layout_callback;
 return wid;
}
References MidiKeyboard_mk::active_key, add_combobox(), add_hslider(), add_keyboard_knob(), Widget_t::adj, adj_get_value(), adj_set_scale(), Widget_t::app, ASPECT, MidiKeyboard_mk::attack, Func_t::button_press_callback, Func_t::button_release_callback, CL_CONTINUOS, CL_ENUM, combobox_add_entry(), combobox_set_active_entry(), create_window(), MidiKeyboard_mk::detune, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, IS_WINDOW, MidiKeyboard_mk::key_matrix, Func_t::key_press_callback, Func_t::key_release_callback, MidiKeyboard_mk::layout, Func_t::leave_callback, Func_t::map_notify_callback, Func_t::mem_free_callback, MidiKeyboard_mk::mk_send_all_sound_off, MidiKeyboard_mk::mk_send_attack, MidiKeyboard_mk::mk_send_detune, MidiKeyboard_mk::mk_send_mod, MidiKeyboard_mk::mk_send_note, MidiKeyboard_mk::mk_send_pitch, MidiKeyboard_mk::mk_send_pitchsensity, MidiKeyboard_mk::mk_send_release, MidiKeyboard_mk::mk_send_sustain, MidiKeyboard_mk::mk_send_velocity, MidiKeyboard_mk::mk_send_volume, MidiKeyboard_mk::modwheel, Func_t::motion_callback, NO_AUTOREPEAT, MidiKeyboard_mk::octave, os_get_root_window(), os_set_input_mask(), Widget_t::parent, Widget_t::parent_struct, MidiKeyboard_mk::pitchsensity, MidiKeyboard_mk::pitchwheel, MidiKeyboard_mk::prelight_key, MidiKeyboard_mk::release, Widget_t::scale, MidiKeyboard_mk::send_key, set_adjustment(), MidiKeyboard_mk::sustain, Func_t::value_changed_callback, MidiKeyboard_mk::velocity, MidiKeyboard_mk::volume, widget_set_icon_from_png(), and widget_set_title().