libxputty: xputty/xpngloader.c File Reference
xpngloader.c File Reference
Functions
cairo_status_t png_stream_reader (void *_stream, unsigned char *data, unsigned int length)
cairo_surface_t * cairo_image_surface_create_from_stream (const unsigned char *name)
cairo_image_surface_create_from_stream - read binary data into cairo surface from stream
void _copy_surface_to_widget (Widget_t *w, cairo_surface_t *getpng)
void _copy_scaled_surface_to_widget (Widget_t *w, cairo_surface_t *getpng)
void widget_get_png (Widget_t *w, const unsigned char *name)
widget_get_png - read png into Widget_t xlib surface
void widget_get_scaled_png (Widget_t *w, const unsigned char *name)
widget_get_scaled_png - read scaled png into Widget_t xlib surface
void widget_get_png_from_file (Widget_t *w, const char *filename)
widget_get_png_from_file - read png from file into Widget_t xlib surface
void widget_get_scaled_png_from_file (Widget_t *w, const char *filename)
widget_get_scaled_png_from_file - read scaled png into Widget_t xlib surface
void widget_get_surface_ptr (Widget_t *w, Widget_t *wid)
widget_get_surface_ptr - set pointer to a 2. Widget_t xlib surface
cairo_surface_t * surface_get_png (Widget_t *w, cairo_surface_t *sf, const unsigned char *name)
surface_get_png - read png into Widget_t xlib surface
void widget_set_icon_from_surface (Widget_t *w, cairo_surface_t *image)
widget_set_icon_from_surface - set icon image from cairo surface for Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
void widget_set_icon_from_png (Widget_t *w, const unsigned char *name)
widget_set_icon_from_png - set icon image from png binary to Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
Function Documentation
_copy_scaled_surface_to_widget()
void _copy_scaled_surface_to_widget (Widget_t * w, cairo_surface_t * getpng)
Definition at line 56 of file xpngloader.c.
{
    int width = cairo_image_surface_get_width(getpng);
    int height = cairo_image_surface_get_height(getpng);
    int width_t = w->scale.init_width;
    int height_t = w->scale.init_height;
    double x = (double)width_t/(double)width;
    double y = (double)height_t/(double)height;
    cairo_surface_destroy(w->image);
    w->image = NULL;
    w->image = cairo_surface_create_similar (w->surface,
                        CAIRO_CONTENT_COLOR_ALPHA, width_t, height_t);
    cairo_t *cri = cairo_create (w->image);
    cairo_scale(cri, x,y);
    cairo_set_source_surface (cri, getpng,0,0);
    cairo_paint (cri);
    cairo_destroy(cri);
}
References Widget_t::image, Resize_t::init_height, Resize_t::init_width, Widget_t::scale, and Widget_t::surface.
Referenced by widget_get_scaled_png(), and widget_get_scaled_png_from_file().
_copy_surface_to_widget()
void _copy_surface_to_widget (Widget_t * w, cairo_surface_t * getpng)
Definition at line 42 of file xpngloader.c.
{
    int width = cairo_image_surface_get_width(getpng);
    int height = cairo_image_surface_get_height(getpng);
    cairo_surface_destroy(w->image);
    w->image = NULL;
    w->image = cairo_surface_create_similar (w->surface,
                        CAIRO_CONTENT_COLOR_ALPHA, width, height);
    cairo_t *cri = cairo_create (w->image);
    cairo_set_source_surface (cri, getpng,0,0);
    cairo_paint (cri);
    cairo_destroy(cri);
}
References Widget_t::image, and Widget_t::surface.
Referenced by widget_get_png(), and widget_get_png_from_file().
cairo_image_surface_create_from_stream()
cairo_surface_t * cairo_image_surface_create_from_stream (const unsigned char * name)
cairo_image_surface_create_from_stream - read binary data into cairo surface from stream
Parameters
*name - pointer to the binary image data LDVAR(name)
Returns
cairo_surface_t - the cairo_image_surface
Definition at line 35 of file xpngloader.c.
{
    binary_stream png_stream;
    png_stream.data = name;
    png_stream.position = 0;
    return cairo_image_surface_create_from_png_stream(&png_stream_reader, (void *)&png_stream);
}
References binary_stream::data, png_stream_reader(), and binary_stream::position.
Referenced by surface_get_png(), widget_get_png(), widget_get_scaled_png(), and widget_set_icon_from_png().
png_stream_reader()
cairo_status_t png_stream_reader (void * _stream, unsigned char * data, unsigned int length)
Definition at line 28 of file xpngloader.c.
{
    binary_stream * stream = (binary_stream *) _stream;
    memcpy(data, &stream->data[stream->position],length);
    stream->position += length;
    return CAIRO_STATUS_SUCCESS;
}
References binary_stream::data, and binary_stream::position.
Referenced by cairo_image_surface_create_from_stream().
surface_get_png()
cairo_surface_t * surface_get_png (Widget_t * w, cairo_surface_t * sf, const unsigned char * name)
surface_get_png - read png into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the png
*sf - pointer to the cairo_surface_t which should hold the png
*name - pointer to the binary image data LDVAR(name)
Returns
cairo_surface_t - the cairo_xlib_surface, you need to free it by yourself
Definition at line 104 of file xpngloader.c.
{
    cairo_surface_t *getpng = cairo_image_surface_create_from_stream (name);
    int width = cairo_image_surface_get_width(getpng);
    int height = cairo_image_surface_get_height(getpng);
    sf = cairo_surface_create_similar (w->surface,
                        CAIRO_CONTENT_COLOR_ALPHA, width, height);
    cairo_t *cri = cairo_create (sf);
    cairo_set_source_surface (cri, getpng,0,0);
    cairo_paint (cri);
    cairo_surface_destroy(getpng);
    cairo_destroy(cri);
    return sf;
}
References cairo_image_surface_create_from_stream(), and Widget_t::surface.
Referenced by add_listview(), and add_multi_listview().
widget_get_png()
void widget_get_png (Widget_t * w, const unsigned char * name)
widget_get_png - read png into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the png
*name - pointer to the binary image data LDVAR(name)
Definition at line 75 of file xpngloader.c.
{
    cairo_surface_t *getpng = cairo_image_surface_create_from_stream (name);
    _copy_surface_to_widget(w, getpng);
    cairo_surface_destroy(getpng);
}
References _copy_surface_to_widget(), and cairo_image_surface_create_from_stream().
Referenced by add_directory_button(), add_file_button(), add_save_file_button(), and open_message_dialog().
widget_get_png_from_file()
void widget_get_png_from_file (Widget_t * w, const char * filename)
widget_get_png_from_file - read png from file into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the png
*filename - pointer to the image path/file
Definition at line 87 of file xpngloader.c.
{
    cairo_surface_t *getpng = cairo_image_surface_create_from_png (filename);
    _copy_surface_to_widget(w, getpng);
    cairo_surface_destroy(getpng);
}
References _copy_surface_to_widget().
widget_get_scaled_png()
void widget_get_scaled_png (Widget_t * w, const unsigned char * name)
widget_get_scaled_png - read scaled png into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the png
*name - pointer to the binary image data LDVAR(name)
Definition at line 81 of file xpngloader.c.
{
    cairo_surface_t *getpng = cairo_image_surface_create_from_stream (name);
    _copy_scaled_surface_to_widget(w, getpng);
    cairo_surface_destroy(getpng);
}
References _copy_scaled_surface_to_widget(), and cairo_image_surface_create_from_stream().
widget_get_scaled_png_from_file()
void widget_get_scaled_png_from_file (Widget_t * w, const char * filename)
widget_get_scaled_png_from_file - read scaled png into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the png
*filename - pointer to the image path/file
Definition at line 93 of file xpngloader.c.
{
    cairo_surface_t *getpng = cairo_image_surface_create_from_png (filename);
    _copy_scaled_surface_to_widget(w, getpng);
    cairo_surface_destroy(getpng);
}
References _copy_scaled_surface_to_widget().
widget_get_surface_ptr()
void widget_get_surface_ptr (Widget_t * w, Widget_t * wid)
widget_get_surface_ptr - set pointer to a 2. Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the surface
*wid - pointer to the Widget_t which hold the surface
Definition at line 99 of file xpngloader.c.
{
    w->image = wid->image;
    w->flags |= REUSE_IMAGE;
}
References Widget_t::flags, Widget_t::image, and REUSE_IMAGE.
widget_set_icon_from_png()
void widget_set_icon_from_png (Widget_t * w, const unsigned char * name)
widget_set_icon_from_png - set icon image from png binary to Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
Parameters
*w - pointer to the Widget_t which should use the icon
*name - pointer to the binary image data LDVAR(name)
Definition at line 159 of file xpngloader.c.
{
#ifdef _WIN32 //PixmapIcon
    return; // TODO
#else
    cairo_surface_t *image = cairo_image_surface_create_from_stream (name);
    int width_t = cairo_image_surface_get_width(image);
    int height_t = cairo_image_surface_get_height(image);
    int stride = cairo_image_surface_get_stride (image);
    unsigned long* icon_data = malloc(16+width_t*height_t * sizeof(unsigned long));
    memset(icon_data, 0, 16+width_t*height_t * sizeof(unsigned long));
    const unsigned char *data = cairo_image_surface_get_data(image);
    icon_data[0] = width_t;
    icon_data[1] = height_t;
    int x = 0;
    int y = 0;
    unsigned long* output_pixel = icon_data;
    output_pixel += 2;
    for (y = 0; y < height_t; y++) {
        uint32_t *row = (uint32_t*) (data + y * stride);
        for (x = 0; x < width_t; x++) {
            output_pixel[0] |= row[x];
            output_pixel ++;
        }
    }
    Atom net_wm_icon = XInternAtom(w->app->dpy, "_NET_WM_ICON", False);
    Atom cardinal = XInternAtom(w->app->dpy, "CARDINAL", False);
    XChangeProperty(w->app->dpy, w->widget, net_wm_icon, cardinal, 32, PropModeReplace,
                                    (const unsigned char*) icon_data, 2+width_t*height_t);
    cairo_surface_destroy(image);
    free(icon_data);
#endif
}
References Widget_t::app, cairo_image_surface_create_from_stream(), Xputty::dpy, and Widget_t::widget.
Referenced by mk_open_midi_keyboard(), open_directory_dialog(), open_file_dialog(), and save_file_dialog().
widget_set_icon_from_surface()
void widget_set_icon_from_surface (Widget_t * w, cairo_surface_t * image)
widget_set_icon_from_surface - set icon image from cairo surface for Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
Parameters
*w - pointer to the Widget_t which should use the icon
*image - pointer to the cairo_surface_t to use for the icon
Definition at line 119 of file xpngloader.c.
{
#ifdef _WIN32 //PixmapIcon
    return; // TODO
#else
    int width_t = cairo_xlib_surface_get_width(image);
    int height_t = cairo_xlib_surface_get_height(image);
    cairo_surface_t *icon = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, width_t, height_t);
    cairo_t *cri = cairo_create (icon);
    cairo_set_source_surface (cri, image,0,0);
    cairo_paint (cri);
    int stride = cairo_image_surface_get_stride (icon);
    unsigned long* icon_data = malloc(2+width_t*height_t * sizeof(unsigned long));
    memset(icon_data, 0, 2+width_t*height_t * sizeof(unsigned long));
    const unsigned char *data = cairo_image_surface_get_data(icon);
    icon_data[0] = width_t;
    icon_data[1] = height_t;
    int x = 0;
    int y = 0;
    unsigned long* output_pixel = icon_data;
    output_pixel += 2;
    for (y = 0; y < height_t; y++) {
        uint32_t *row = (uint32_t*) (data + y * stride);
        for (x = 0; x < width_t; x++) {
            output_pixel[0] |= row[x];
            output_pixel ++;
        }
    }
    Atom net_wm_icon = XInternAtom(w->app->dpy, "_NET_WM_ICON", False);
    Atom cardinal = XInternAtom(w->app->dpy, "CARDINAL", False);
    XChangeProperty(w->app->dpy, w->widget, net_wm_icon, cardinal, 32, PropModeReplace,
                                    (const unsigned char*) icon_data, 2+width_t*height_t);
    cairo_surface_destroy(icon);
    cairo_destroy(cri);
    free(icon_data);
#endif
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by open_message_dialog().