libxputty: xputty/dialogs/xsavefile-dialoge.c File Reference
xsavefile-dialoge.c File Reference
Functions
Widget_t * save_file_dialog (Widget_t *w, const char *path, const char *filter)
save_file_dialog - open a non blocking dialog window, to select a file. The path to open the file-selector could be NULL It will open then in $HOME. The filter to use could be NULL, then the file-selector will show all files.
Widget_t * add_save_file_button (Widget_t *parent, int x, int y, int width, int height, const char *path, const char *filter)
add_save_file_button - add a pre-defined button which will pop-up a file dialog when pressed. path and filter will e hand over to the file selector.
Function Documentation
add_save_file_button()
Widget_t * add_save_file_button (Widget_t * parent, int x, int y, int width, int height, const char * path, const char * filter)
add_save_file_button - add a pre-defined button which will pop-up a file dialog when pressed. path and filter will e hand over to the file selector.
Returns
Widget_t* - pointer to the Widget_t struct
Definition at line 731 of file xsavefile-dialoge.c.
{
    FileButton *filebutton = (FileButton*)malloc(sizeof(FileButton));
    filebutton->path = path;
    filebutton->filter = filter;
    filebutton->last_path = NULL;
    filebutton->w = NULL;
    filebutton->is_active = false;
    Widget_t *fbutton = add_image_toggle_button(parent, "", x, y, width, height);
    fbutton->parent_struct = filebutton;
    fbutton->flags |= HAS_MEM;
    widget_get_png(fbutton, LDVAR(directory_open_png));
    fbutton->scale.gravity = CENTER;
    fbutton->func.mem_free_callback = fbutton_mem_free;
    fbutton->func.value_changed_callback = fbutton_callback;
    fbutton->func.dialog_callback = fdialog_response;
    return fbutton;
}
References add_image_toggle_button(), CENTER, Func_t::dialog_callback, FileButton::filter, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, FileButton::is_active, FileButton::last_path, Func_t::mem_free_callback, Widget_t::parent_struct, FileButton::path, Widget_t::scale, Func_t::value_changed_callback, FileButton::w, and widget_get_png().
save_file_dialog()
Widget_t * save_file_dialog (Widget_t * w, const char * path, const char * filter)
save_file_dialog - open a non blocking dialog window, to select a file. The path to open the file-selector could be NULL It will open then in $HOME. The filter to use could be NULL, then the file-selector will show all files.
Returns
Widget_t* - pointer to the Widget_t struct
Definition at line 544 of file xsavefile-dialoge.c.
{
    FileDialog *file_dialog = (FileDialog*)malloc(sizeof(FileDialog));
    file_dialog->xdg_user_dirs = NULL;
    file_dialog->xdg_dir_counter = 0;
    file_dialog->fp = (FilePicker*)malloc(sizeof(FilePicker));
#ifdef __linux__
    parse_xdg_dirs(file_dialog);
    struct stat sb;
    if (stat(path, &sb) == 0 && S_ISDIR(sb.st_mode)) {
        fp_init(file_dialog->fp, path);
    } else if (stat(file_dialog->home_dir, &sb) == 0 && S_ISDIR(sb.st_mode)) {
        fp_init(file_dialog->fp, file_dialog->home_dir);
    } else {
        fp_init(file_dialog->fp, "/");
    }
#else
    DWORD attr = GetFileAttributes(path);
    if (attr&FILE_ATTRIBUTE_DIRECTORY) {
        fp_init(file_dialog->fp, path);
    } else {
        fp_init(file_dialog->fp, "c:\\");
    }
#endif
    file_dialog->parent = w;
    file_dialog->send_clear_func = true;
    file_dialog->w = create_window(w->app, os_get_root_window(w->app, IS_WINDOW), 0, 0, 660, 420);
#ifdef __linux__
    XSizeHints* win_size_hints;
    win_size_hints = XAllocSizeHints();
    win_size_hints->flags =  PMinSize|PBaseSize|PMaxSize|PWinGravity;
    win_size_hints->min_width = 660;
    win_size_hints->min_height = 420;
    win_size_hints->base_width = 660;
    win_size_hints->base_height = 420;
    win_size_hints->max_width = 660;
    win_size_hints->max_height = 840;
    win_size_hints->win_gravity = CenterGravity;
    XSetWMNormalHints(file_dialog->w->app->dpy, file_dialog->w->widget, win_size_hints);
    XFree(win_size_hints);
#endif
    file_dialog->w->flags |= HAS_MEM;
    file_dialog->w->parent_struct = file_dialog;
    widget_set_title(file_dialog->w, _("File Save"));
    file_dialog->w->func.expose_callback = draw_window;
    file_dialog->w->func.key_press_callback = forward_key_press;
    file_dialog->w->func.mem_free_callback = fd_mem_free;
    widget_set_icon_from_png(file_dialog->w,LDVAR(directory_png));
    file_dialog->ct = add_combobox(file_dialog->w, "", 20, 40, 550, 30);
    file_dialog->ct->parent_struct = file_dialog;
    file_dialog->ct->scale.gravity = NORTHEAST;
    file_dialog->ct->func.value_changed_callback = combo_response;
    file_dialog->ct->func.key_press_callback = forward_key_press;
    file_dialog->sel_dir = add_button(file_dialog->w, _("Open"), 580, 40, 60, 30);
    file_dialog->sel_dir->parent_struct = file_dialog;
    file_dialog->sel_dir->scale.gravity = WESTNORTH;
    add_tooltip(file_dialog->sel_dir,_("Open sub-directory's"));
    file_dialog->sel_dir->func.value_changed_callback = open_dir_callback;
    file_dialog->sel_dir->func.key_press_callback = forward_key_press;
    file_dialog->ft = add_listview(file_dialog->w, "", 130, 90, 510, 225);
    file_dialog->ft->parent_struct = file_dialog;
    file_dialog->ft->scale.gravity = NORTHWEST;
    listview_set_check_dir(file_dialog->ft, 1);
    file_dialog->ft->func.key_press_callback = forward_key_press;
    int ds = fp_get_files(file_dialog->fp,file_dialog->fp->path, 1, 1);
    int set_f = set_files(file_dialog);
    set_dirs(file_dialog);
    combobox_set_active_entry(file_dialog->ct, ds);
    if (set_f != -1) {
        listview_set_active_entry(file_dialog->ft, set_f);
    } else {
        listview_unset_active_entry(file_dialog->ft);
    }
    file_dialog->ft->func.value_changed_callback = file_released_callback;
#ifdef __linux__
    add_xdg_dirs(file_dialog);
#endif
    file_dialog->text_entry = create_widget(file_dialog->w->app, file_dialog->w, 130, 320, 200, 30);
    memset(file_dialog->text_entry->input_label, 0, 32 * (sizeof file_dialog->text_entry->input_label[0]) );
    file_dialog->text_entry->func.expose_callback = entry_add_text;
    file_dialog->text_entry->func.key_press_callback = entry_get_text;
    file_dialog->text_entry->flags &= ~USE_TRANSPARENCY;
    file_dialog->text_entry->scale.gravity = EASTWEST;
    file_dialog->text_entry->parent_struct = file_dialog;
#ifdef __linux__
    Cursor c = XCreateFontCursor(file_dialog->w->app->dpy, XC_xterm);
    XDefineCursor (file_dialog->w->app->dpy, file_dialog->text_entry->widget, c);
    XFreeCursor(file_dialog->w->app->dpy, c);
#endif
    file_dialog->w_quit = add_button(file_dialog->w, _("Cancel"), 580, 350, 60, 60);
    file_dialog->w_quit->parent_struct = file_dialog;
    file_dialog->w_quit->scale.gravity = SOUTHWEST;
    add_tooltip(file_dialog->w_quit,_("Exit File Saver"));
    file_dialog->w_quit->func.value_changed_callback = button_quit_callback;
    file_dialog->w_quit->func.key_press_callback = forward_key_press;
    file_dialog->w_okay = add_button(file_dialog->w, _("Save"), 490, 350, 80, 60);
    file_dialog->w_okay->parent_struct = file_dialog;
    file_dialog->w_okay->scale.gravity = SOUTHWEST;
    add_tooltip(file_dialog->w_okay,_("Save as selected file"));
    file_dialog->w_okay->func.value_changed_callback = button_ok_callback;
    file_dialog->w_okay->func.key_press_callback = forward_key_press;
    file_dialog->set_filter = add_combobox(file_dialog->w, "", 340, 355, 120, 30);
    file_dialog->set_filter->parent_struct = file_dialog;
    file_dialog->set_filter->scale.gravity = SOUTHWEST;
    combobox_add_entry(file_dialog->set_filter,_("all"));
    combobox_add_entry(file_dialog->set_filter,_("application"));
    combobox_add_entry(file_dialog->set_filter,_("audio"));
    combobox_add_entry(file_dialog->set_filter,_("font"));
    combobox_add_entry(file_dialog->set_filter,_("image"));
    combobox_add_entry(file_dialog->set_filter,_("text"));
    combobox_add_entry(file_dialog->set_filter,_("video"));
    combobox_add_entry(file_dialog->set_filter,_("x-content"));
    if(filter !=NULL && strlen(filter))
        combobox_add_entry(file_dialog->set_filter,filter);
    combobox_set_active_entry(file_dialog->set_filter, 0);
    file_dialog->set_filter->func.key_press_callback = forward_key_press;
    file_dialog->set_filter->func.value_changed_callback = set_filter_callback;
    if(filter !=NULL && strlen(filter))
        combobox_set_active_entry(file_dialog->set_filter, 8);
    add_tooltip(file_dialog->set_filter->childlist->childs[0], _("File filter type"));
    file_dialog->w_hidden = add_check_button(file_dialog->w, "", 20, 365, 20, 20);
    file_dialog->w_hidden->parent_struct = file_dialog;
    file_dialog->w_hidden->scale.gravity = EASTWEST;
    add_tooltip(file_dialog->w_hidden,_("Show hidden files and folders"));
    file_dialog->w_hidden->func.key_press_callback = forward_key_press;
    file_dialog->w_hidden->func.value_changed_callback = button_hidden_callback;
    widget_show_all(file_dialog->w);
    return file_dialog->w;
}
References add_button(), add_check_button(), add_combobox(), add_listview(), add_tooltip(), Widget_t::app, Widget_t::childlist, Childlist_t::childs, combobox_add_entry(), combobox_set_active_entry(), create_widget(), create_window(), FileDialog::ct, Xputty::dpy, EASTWEST, Func_t::expose_callback, Widget_t::flags, FileDialog::fp, fp_get_files(), fp_init(), FileDialog::ft, Widget_t::func, Resize_t::gravity, HAS_MEM, FileDialog::home_dir, Widget_t::input_label, IS_WINDOW, Func_t::key_press_callback, listview_set_active_entry(), listview_set_check_dir(), listview_unset_active_entry(), Func_t::mem_free_callback, NORTHEAST, NORTHWEST, os_get_root_window(), FileDialog::parent, Widget_t::parent_struct, FilePicker::path, Widget_t::scale, FileDialog::sel_dir, FileDialog::send_clear_func, FileDialog::set_filter, SOUTHWEST, FileDialog::text_entry, Func_t::value_changed_callback, FileDialog::w, FileDialog::w_hidden, FileDialog::w_okay, FileDialog::w_quit, WESTNORTH, Widget_t::widget, widget_set_icon_from_png(), widget_set_title(), widget_show_all(), FileDialog::xdg_dir_counter, and FileDialog::xdg_user_dirs.