libxputty: xputty/header/xsvgloader.h File Reference
xsvgloader.h File Reference
Functions
void widget_get_svg (Widget_t *w, const char *name)
widget_get_svg - read svg into Widget_t xlib surface
void widget_get_scaled_svg (Widget_t *w, const char *name)
widget_get_scaled_svg - read svg scaled into Widget_t xlib surface
void widget_get_svg_from_file (Widget_t *w, const char *filename)
widget_get_svg_from_file - read svg into Widget_t xlib surface
void widget_get_scaled_svg_from_file (Widget_t *w, const char *filename, int width_t, int height_t)
widget_get_scaled_svg_from_file - read svg into Widget_t xlib surface
cairo_surface_t * cairo_image_surface_create_from_svg (const char *name)
Function Documentation
cairo_image_surface_create_from_svg()
cairo_surface_t * cairo_image_surface_create_from_svg (const char * name)
Definition at line 336 of file xsvgloader.c.
{
    struct NSVGimage* const image = nsvgParseFromFile(filename, "px", 96);
    if (!image) return NULL;
    int width_t = image->width;
    int height_t = image->height;
    cairo_surface_t *getsvg = cairo_image_surface_create ( CAIRO_FORMAT_ARGB32, width_t, height_t);
    cairo_t *cri = cairo_create (getsvg);
    draw_svg_image(cri, image, width_t, height_t);
    nsvgDelete(image);
    return getsvg;
}
References NSVGimage::height, nsvgDelete(), nsvgParseFromFile(), and NSVGimage::width.
widget_get_scaled_svg()
void widget_get_scaled_svg (Widget_t * w, const char * name)
widget_get_scaled_svg - read svg scaled into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the svg
*name - pointer to the base64 image data
Returns
void
Definition at line 269 of file xsvgloader.c.
{
    char* b64dst;
    b64dst = (char*)malloc((strlen(name)+1) * sizeof(char));
    b64_decode((char*)name, b64dst);
    struct NSVGimage* const image = nsvgParse(b64dst, "px", 96);
    if (!image) return;
    int width = image->width;
    int height = image->height;
    int width_t = w->scale.init_width;
    int height_t = w->scale.init_height;
    double x = (double)width_t/(double)width;
    double y = (double)height_t/(double)height;
    cairo_surface_t *getsvg = cairo_image_surface_create ( CAIRO_FORMAT_ARGB32, width, height);
    cairo_t *cris = cairo_create (getsvg);
    draw_svg_image(cris, image, width, height);
    cairo_surface_destroy(w->image);
    w->image = NULL;
    w->image = cairo_surface_create_similar (w->surface,
                        CAIRO_CONTENT_COLOR_ALPHA, width_t, height_t);
    cairo_t *cri = cairo_create (w->image);
    cairo_scale(cri, x,y);
    cairo_set_source_surface (cri, getsvg,0,0);
    cairo_paint (cri);
    cairo_destroy(cris);
    cairo_surface_destroy(getsvg);
    nsvgDelete(image);
    free(b64dst);
    cairo_destroy(cri);
}
References b64_decode(), NSVGimage::height, Widget_t::image, Resize_t::init_height, Resize_t::init_width, nsvgDelete(), nsvgParse(), Widget_t::scale, Widget_t::surface, and NSVGimage::width.
widget_get_scaled_svg_from_file()
void widget_get_scaled_svg_from_file (Widget_t * w, const char * filename, int width_t, int height_t)
widget_get_scaled_svg_from_file - read svg into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the svg
*filename - pointer to the image data file
width_t - the requested width
height_t - the requested height
Returns
void
Definition at line 321 of file xsvgloader.c.
{
    struct NSVGimage* const image = nsvgParseFromFile(filename, "px", 96);
    if (!image) return;
    cairo_surface_destroy(w->image);
    w->image = NULL;
    w->image = cairo_surface_create_similar (w->surface,
                        CAIRO_CONTENT_COLOR_ALPHA, width_t, height_t);
    cairo_t *cri = cairo_create (w->image);
    draw_svg_image(cri, image, width_t, height_t);
    nsvgDelete(image);
    cairo_destroy(cri);
}
References Widget_t::image, nsvgDelete(), nsvgParseFromFile(), and Widget_t::surface.
widget_get_svg()
void widget_get_svg (Widget_t * w, const char * name)
widget_get_svg - read svg into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the svg
*name - pointer to the base64 image data
Returns
void
Definition at line 248 of file xsvgloader.c.
{
    char* b64dst;
    b64dst = (char*)malloc((strlen(name)+1) * sizeof(char));
    b64_decode((char*)name, b64dst);
    struct NSVGimage* const image = nsvgParse(b64dst, "px", 96);
    if (!image) return;
    int width_t = image->width;
    int height_t = image->height;
    cairo_surface_destroy(w->image);
    w->image = NULL;
    w->image = cairo_surface_create_similar (w->surface,
                        CAIRO_CONTENT_COLOR_ALPHA, width_t, height_t);
    cairo_t *cri = cairo_create (w->image);
    draw_svg_image(cri, image, width_t, height_t);
    nsvgDelete(image);
    free(b64dst);
    cairo_destroy(cri);
}
References b64_decode(), NSVGimage::height, Widget_t::image, nsvgDelete(), nsvgParse(), Widget_t::surface, and NSVGimage::width.
widget_get_svg_from_file()
void widget_get_svg_from_file (Widget_t * w, const char * filename)
widget_get_svg_from_file - read svg into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the svg
*filename - pointer to the image data file
Returns
void
Definition at line 304 of file xsvgloader.c.
{
    struct NSVGimage* const image = nsvgParseFromFile(filename, "px", 96);
    if (!image) return;
    int width_t = w->scale.init_width;
    int height_t = w->scale.init_height;
    cairo_surface_destroy(w->image);
    w->image = NULL;
    w->image = cairo_surface_create_similar (w->surface,
                        CAIRO_CONTENT_COLOR_ALPHA, width_t, height_t);
    cairo_t *cri = cairo_create (w->image);
    draw_svg_image(cri, image, width_t, height_t);
    nsvgDelete(image);
    cairo_destroy(cri);
}
References Widget_t::image, Resize_t::init_height, Resize_t::init_width, nsvgDelete(), nsvgParseFromFile(), Widget_t::scale, and Widget_t::surface.