libxputty: xputty/widgets/xtabbox.c File Reference
xtabbox.c File Reference
Functions
Widget_t * tabbox_add_tab (Widget_t *tabbox, const char *label)
tabbox_add_tab - add a tab to a tabbox Widget_t
Widget_t * add_tabbox (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_tabbox - add a tabbox to a Widget_t
void tabbox_remove_tab (Widget_t *tabbox, int tab)
tabbox_remove_tab - remove a tab from a tabbox Widget_t
Function Documentation
add_tabbox()
Widget_t * add_tabbox (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_tabbox - add a tabbox to a Widget_t
Parameters
*parent - pointer to the Widget_t request the tabbox
*label - the label of the tabbox
x,y,width,height - the position/geometry to create the tabbox
Returns
Widget_t* - pointer to the Widget_t tabbox struct
Definition at line 42 of file xtabbox.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->scale.gravity = CENTER;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_NONE);
    wid->adj = wid->adj_y;
    wid->func.expose_callback = _draw_tabbox;
    //wid->func.button_press_callback = _tab_button_pressed;
    wid->func.button_release_callback = _tab_button_released;
    //wid->func.map_notify_callback = _tabbox_mapped_callback;
    return wid;
}
References _draw_tabbox(), _tab_button_released(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, Func_t::button_release_callback, CENTER, CL_NONE, create_widget(), Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, and Widget_t::scale.
tabbox_add_tab()
Widget_t * tabbox_add_tab (Widget_t * tabbox, const char * label)
tabbox_add_tab - add a tab to a tabbox Widget_t
Parameters
*tabbox - pointer to the tabbox Widget_t the tab should added to
*label - the label of the tab
Returns
Widget_t* - pointer to the Widget_t tab struct
Definition at line 26 of file xtabbox.c.
{
    Metrics_t metrics;
    os_get_window_metrics(tabbox, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    Widget_t *wid = create_widget(tabbox->app,tabbox, 4, 20,  width-8, height-24);
    wid->scale.gravity = NORTHWEST;
    wid->label = label;
    wid->func.expose_callback = _draw_tab;
    //wid->func.map_notify_callback = _tab_mapped_callback;
    float max_value = tabbox->adj->max_value+1.0;
    set_adjustment(tabbox->adj,0.0, max_value, 0.0, max_value,1.0, CL_NONE);
    adj_set_value(tabbox->adj,0.0);
    return wid;
}
References _draw_tab(), Widget_t::adj, adj_set_value(), Widget_t::app, CL_NONE, create_widget(), Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Metrics_t::height, Widget_t::label, Adjustment_t::max_value, NORTHWEST, os_get_window_metrics(), Widget_t::scale, set_adjustment(), and Metrics_t::width.
tabbox_remove_tab()
void tabbox_remove_tab (Widget_t * tabbox, int tab)
tabbox_remove_tab - remove a tab from a tabbox Widget_t
Parameters
*tabbox - pointer to the tabbox Widget_t the tab should removed from
tab - the number of the tab
Returns
void
Definition at line 57 of file xtabbox.c.
{
    int elem = tabbox->childlist->elem;
    if (tab > elem) return;
    Widget_t *wid = tabbox->childlist->childs[tab];
    destroy_widget(wid, tabbox->app);
    float max_value = tabbox->adj->max_value-1.0;
    set_adjustment(tabbox->adj,0.0, max_value, 0.0, max_value,1.0, CL_NONE);
}
References Widget_t::adj, Widget_t::app, Widget_t::childlist, Childlist_t::childs, CL_NONE, destroy_widget(), Childlist_t::elem, Adjustment_t::max_value, and set_adjustment().