libxputty: xputty/header/widgets/xtabbox_private.h File Reference
xtabbox_private.h File Reference
Functions
void _draw_tabbox (void *w_, void *user_data)
_draw_tabbox - draw the tabbox on expose call
void _draw_tab (void *w_, void *user_data)
_draw_tab - draw a single tab on expose call
void _tab_button_released (void *w_, void *button_, void *user_data)
_tab_button_released - select the tab to show (hide all other)
Function Documentation
_draw_tab()
void _draw_tab (void * w_, void * user_data)
_draw_tab - draw a single tab on expose call
Parameters
*w_ - the tab to draw
*user_data - attached user_data
Definition at line 92 of file xtabbox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t *p = (Widget_t*)w->parent;
    _draw_tabbox(p, NULL);
}
References _draw_tabbox(), and Widget_t::parent.
Referenced by tabbox_add_tab().
_draw_tabbox()
void _draw_tabbox (void * w_, void * user_data)
_draw_tabbox - draw the tabbox on expose call
Parameters
*w_ - the tabbox to draw
*user_data - attached user_data
Definition at line 39 of file xtabbox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width_t = metrics.width;
    int height_t = metrics.height;
    if (!metrics.visible) return;
    int tabsize = 1;
    int elem = w->childlist->elem;
    if (elem) tabsize = width_t/elem;
    int v = (int)adj_get_value(w->adj);
    cairo_new_path (w->crb);
    cairo_set_line_width(w->crb,1);
    use_frame_color_scheme(w, NORMAL_);
    _rounded_box(w->crb, 1, 21, width_t-2, height_t-22, (v+1)*tabsize);
    cairo_stroke(w->crb);
    cairo_text_extents_t extents;
    use_text_color_scheme(w, get_color_state(w));
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    int i = 0;
    int t = 0;
    for(;i<elem;i++) {
        Widget_t *wi = w->childlist->childs[i];
        if(v == i) {
            cairo_move_to (w->crb, t+1, 21);
            cairo_line_to(w->crb, t+1, 1);
            cairo_line_to(w->crb, t+tabsize-1, 1);
            cairo_line_to(w->crb, t+tabsize-1, 21);
            use_frame_color_scheme(w, NORMAL_);
            cairo_stroke(w->crb);
            use_text_color_scheme(w, ACTIVE_);
            widget_show_all(wi);
        } else {
            use_bg_color_scheme(w, ACTIVE_);
            cairo_rectangle(w->crb, t+2, 1, tabsize-4, 20);
            cairo_fill_preserve(w->crb);
            use_frame_color_scheme(w, NORMAL_);
            cairo_stroke(w->crb);
            use_text_color_scheme(w, INSENSITIVE_);
            widget_hide(wi);
        }
        cairo_text_extents(w->crb,"Äy" , &extents);
        cairo_move_to (w->crb, 5+t, 2+extents.height);
        cairo_show_text(w->crb, wi->label);
        cairo_new_path (w->crb);
        t += tabsize;
    }
}
References _rounded_box(), ACTIVE_, Widget_t::adj, adj_get_value(), Widget_t::app, Resize_t::ascale, Widget_t::childlist, Childlist_t::childs, Widget_t::crb, Childlist_t::elem, get_color_state(), Metrics_t::height, INSENSITIVE_, Widget_t::label, NORMAL_, Xputty::normal_font, os_get_window_metrics(), Widget_t::scale, use_bg_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), Metrics_t::visible, widget_hide(), widget_show_all(), and Metrics_t::width.
Referenced by _draw_tab(), and add_tabbox().
_tab_button_released()
void _tab_button_released (void * w_, void * button_, void * user_data)
_tab_button_released - select the tab to show (hide all other)
Parameters
*w_ - the Widget_t which is released
*button_ - the xbutton event
*user_data - attached user_data
Definition at line 98 of file xtabbox_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width_t = metrics.width;
    if (w->flags & HAS_POINTER) {
        XButtonEvent *xbutton = (XButtonEvent*)button_;
        if (xbutton->y < 20) {
            int tabsize = width_t;
            int elem = w->childlist->elem;
            if (elem) tabsize = width_t/elem;
            adj_set_value(w->adj,(float)(xbutton->x/tabsize));
            expose_widget(w);
        }
     }
}
References Widget_t::adj, adj_set_value(), Widget_t::childlist, Childlist_t::elem, expose_widget(), Widget_t::flags, HAS_POINTER, os_get_window_metrics(), Metrics_t::width, XEvent::x, and XEvent::y.
Referenced by add_tabbox().