libxputty: xputty/header/widgets/xtooltip.h File Reference
xtooltip.h File Reference
Functions
void tooltip_set_text (Widget_t *w, const char *label)
tooltip_set_text - set a (new) text to a tooltip for Widget_t
void add_tooltip (Widget_t *w, const char *label)
add_tooltip - add a tooltip to Widget_t
Widget_t * create_tooltip (Widget_t *parent, int width, int height)
create_tooltip - create a tooltip for a Widget_t
Function Documentation
add_tooltip()
void add_tooltip (Widget_t * w, const char * label)
add_tooltip - add a tooltip to Widget_t
Parameters
*w - pointer to the Widget_t request the tooltip
*label - the tooltip text
Definition at line 41 of file xtooltip.c.
{
    Widget_t *wid = create_tooltip(w, 25, 25);
    wid->label = label;
    _get_width(wid);
}
References _get_width(), create_tooltip(), and Widget_t::label.
Referenced by open_directory_dialog(), open_file_dialog(), save_file_dialog(), and tooltip_set_text().
create_tooltip()
Widget_t * create_tooltip (Widget_t * parent, int width, int height)
create_tooltip - create a tooltip for a Widget_t
Parameters
*parent - pointer to the Widget_t the tooltip should pop over
width - define the width of the tooltip
height - define the height of the tooltip
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 47 of file xtooltip.c.
{
    int x1, y1;
    os_translate_coords(parent, parent->widget, os_get_root_window(parent->app, IS_WIDGET), 0, 0, &x1, &y1);
    Widget_t *wid = create_window(parent->app, os_get_root_window(parent->app, IS_WIDGET), x1+10, y1+10, width, height);
    os_set_window_attrb(wid);
    os_set_transient_for_hint(parent, wid);
    wid->flags &= ~USE_TRANSPARENCY;
    wid->func.expose_callback = _draw_tooltip;
    wid->flags |= IS_TOOLTIP;
    parent->flags |= HAS_TOOLTIP;
    wid->scale.gravity = NONE;
    childlist_add_child(parent->childlist, wid);
    return wid;
}
References _draw_tooltip(), Widget_t::app, Widget_t::childlist, childlist_add_child(), create_window(), Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_TOOLTIP, IS_TOOLTIP, IS_WIDGET, NONE, os_get_root_window(), os_set_transient_for_hint(), os_set_window_attrb(), os_translate_coords(), Widget_t::scale, and Widget_t::widget.
Referenced by add_tooltip().
tooltip_set_text()
void tooltip_set_text (Widget_t * w, const char * label)
tooltip_set_text - set a (new) text to a tooltip for Widget_t
Parameters
*w - pointer to the Widget_t request the tooltip
*label - the tooltip text
Definition at line 25 of file xtooltip.c.
{
    Widget_t *wid = NULL;
    bool is_tooltip = false;
    int i = 0;
    for(;i<w->childlist->elem;i++) {
        wid = w->childlist->childs[i];
        if (wid->flags & IS_TOOLTIP) {
            wid->label = label;
            _get_width(wid);
            is_tooltip = true;
            break;
        }
    }
    if (!is_tooltip) add_tooltip(w, label);
}
References _get_width(), add_tooltip(), Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_TOOLTIP, and Widget_t::label.
Referenced by _draw_combobox(), _draw_combobox_entrys(), _draw_list(), _draw_listbox_item(), _draw_multi_list(), _update_list_view(), and _update_view().