libxputty: xputty/header/widgets/xtuner.h File Reference
xtuner.h File Reference
Data Structures
struct XTuner
Functions
void tuner_set_temperament (Widget_t *w, float temp)
void tuner_set_ref_freq (Widget_t *w, float ref)
Widget_t * add_tuner (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_tuner - add a tuner widget to a Widget_t
Function Documentation
add_tuner()
Widget_t * add_tuner (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_tuner - add a tuner widget to a Widget_t
Parameters
*parent - pointer to the Widget_t request the tuner
*label - Label to show on the tuner
x,y,width,height - the position/geometry to create the tuner
Returns
Widget_t* - pointer to the Widget_t tuner struct
Definition at line 47 of file xtuner.c.
{
    XTuner *xt = (XTuner*)malloc(sizeof(XTuner));
    xt->ref_freq = 440.0;
    xt->temp_adjust = 3;
    xt->temperament = 0;
    xt->move = 0;
    xt->smove = 0;
    xt->lang = 0;
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->parent_struct = xt;
    wid->label = label;
    wid->adj_y = add_adjustment(wid,20.0, 20.0, 20.0, 20000.0,0.01, CL_CONTINUOS);
    wid->adj = wid->adj_y;
    wid->scale.gravity = CENTER;
    wid->flags &= ~USE_TRANSPARENCY;
    wid->flags |= HAS_MEM;
    wid->func.mem_free_callback = xtuner_mem_free;
    wid->func.expose_callback = _draw_tuner;
    return wid;
}
References _draw_tuner(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, CENTER, CL_CONTINUOS, create_widget(), Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, Widget_t::label, XTuner::lang, Func_t::mem_free_callback, XTuner::move, Widget_t::parent_struct, XTuner::ref_freq, Widget_t::scale, XTuner::smove, XTuner::temp_adjust, and XTuner::temperament.
tuner_set_ref_freq()
void tuner_set_ref_freq (Widget_t * w, float ref)
Definition at line 36 of file xtuner.c.
{
    XTuner *xt = (XTuner *)w->parent_struct;
    xt->ref_freq = ref;
}
References Widget_t::parent_struct, and XTuner::ref_freq.
tuner_set_temperament()
void tuner_set_temperament (Widget_t * w, float temp)
Definition at line 25 of file xtuner.c.
{
    XTuner *xt = (XTuner *)w->parent_struct;
    xt->temperament = temp;
    if((int)temp == 0) xt->temp_adjust = 3;
    else if((int)temp == 1) xt->temp_adjust =  6;
    else if((int)temp == 2) xt->temp_adjust =  7;
    else if((int)temp == 3) xt->temp_adjust =  9;
    else if((int)temp == 4) xt->temp_adjust =  15;
    else xt->temp_adjust = 3;
}
References Widget_t::parent_struct, XTuner::temp_adjust, and XTuner::temperament.