libxputty: xputty/widgets/xtuner_private.c File Reference
xtuner_private.c File Reference
Functions
void _draw_tuner (void *w_, void *user_data)
_draw_tuner - draw the tuner on expose call
Function Documentation
_draw_tuner()
void _draw_tuner (void * w_, void * user_data)
_draw_tuner - draw the tuner on expose call
Parameters
*w_ - The Widget_t contain the tuner
*user_data - attached user_data
Returns
void
Definition at line 85 of file xtuner_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    XTuner *xt = (XTuner *)w->parent_struct;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width;
    int height = metrics.height;
    if (!metrics.visible) return;
    float x0 = width/2;
    float y0 = height/2;
    use_bg_color_scheme(w, NORMAL_);
    cairo_paint (w->crb);
    cairo_pattern_t* pat = cairo_pattern_create_linear (0, 0,x0, 0);
    cairo_pattern_set_extend(pat, CAIRO_EXTEND_REFLECT);
    cairo_pattern_add_color_stop_rgb (pat, 1, 0.1, 0.8, 0.1);
    cairo_pattern_add_color_stop_rgb (pat, 0.7, 0.8, 0.8, 0.1);
    cairo_pattern_add_color_stop_rgb (pat, 0, 1, 0.1, 0.1);
    cairo_set_source_rgb(w->crb,0.2,0.2,0.2);
    int i = 0;
    for (; i < width/20 +1; ++i) {
        cairo_rectangle(w->crb,(width/2)+i*10, 5, 5, 20);
        cairo_fill(w->crb);
    }
    for (; i >0; --i) {
        cairo_rectangle(w->crb,(width/2)-i*10, 5, 5, 20);
        cairo_fill(w->crb);
    }
    cairo_set_source_rgb(w->crb,0.2,0.2,0.2);
    _tuner_triangle(w, width/5.8,y0 , 25/w->scale.ascale, 20/w->scale.ascale);
    _tuner_triangle(w, width/1.2, y0, -25/w->scale.ascale, 20/w->scale.ascale);
    float value = adj_get_value(w->adj);
    float scale = -0.5;
    float fvis = _get_tuner_temperament(w) * (log2f(value/xt->ref_freq) + 4);
    float fvisr = round(fvis);
    int vis = fvisr;
    int indicate_oc = round((fvisr+xt->temp_adjust)/_get_tuner_temperament(w));
    const int octsz = sizeof(octave) / sizeof(octave[0]);
    if (indicate_oc < 0 || indicate_oc >= octsz) {
        // just safety, should not happen with current parameters
        // (pitch tracker output 23 .. 999 Hz)
        indicate_oc = octsz - 1;
    }
    scale = (fvis-vis) / 4;
    float cent = (scale * 10000) / 25;
    vis = vis % _get_tuner_temperament(w);
    if (vis < 0) {
        vis += _get_tuner_temperament(w);
    }
    if (value > 24.0 && value < 999.0) {
        if (scale < 0.004) {
            cairo_set_source_rgb(w->crb,0.80,0.79,0.01);
            _tuner_triangle(w, (width/5.8),y0 , 25/w->scale.ascale, 20/w->scale.ascale);
            _tuner_triangle(w, (width/5.8)-(300*scale)/w->scale.ascale,y0 , 25/w->scale.ascale, 20/w->scale.ascale);
            _tuner_triangle(w, (width/5.8)-(600*scale)/w->scale.ascale,y0 , 25/w->scale.ascale, 20/w->scale.ascale);
        }
        if (scale > -0.004) {
            cairo_set_source_rgb(w->crb,0.80,0.79,0.01);
            _tuner_triangle(w, (width/1.2), y0, -25/w->scale.ascale, 20/w->scale.ascale);
            _tuner_triangle(w, (width/1.2)-(300*scale)/w->scale.ascale, y0, -25/w->scale.ascale, 20/w->scale.ascale);
            _tuner_triangle(w, (width/1.2)-(600*scale)/w->scale.ascale, y0, -25/w->scale.ascale, 20/w->scale.ascale);
        }
    }
    // display note
    cairo_select_font_face (w->crb, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
    cairo_set_source_rgba(w->crb, fabsf(scale)*2, 1-(scale*scale*4), 0.2,max(0,1-(fabsf(scale)*6)));
    cairo_set_font_size(w->crb, (w->app->big_font*2)/w->scale.ascale);
    cairo_text_extents_t extents;
    if (value > 24.0 && value < 999.0) {
        cairo_text_extents(w->crb,_get_note_set(w)[vis] , &extents);
        float c = (extents.width/2)+10.0;
        cairo_move_to(w->crb,x0-c , y0+10 );
        cairo_show_text(w->crb, _get_note_set(w)[vis]);
        cairo_set_font_size(w->crb, (w->app->small_font*2)/w->scale.ascale);
        cairo_move_to(w->crb,x0+c-10.0, y0+10+ extents.height/2 );
        cairo_show_text(w->crb, octave[indicate_oc]);
        char s[64];
        char sc[64];
        snprintf(s, 63, "%.2f Hz", value);
        use_text_color_scheme(w, NORMAL_);
        cairo_set_font_size (w->crb, w->app->big_font/w->scale.ascale);
        cairo_text_extents(w->crb,s , &extents);
        cairo_move_to (w->crb, width/1.1-extents.width, height-extents.height );
        cairo_show_text(w->crb, s);
        snprintf(sc, 63, "%.2f cent", cent);
        cairo_text_extents(w->crb,sc , &extents);
        cairo_move_to (w->crb, width/4.1-extents.width, height-extents.height );
        cairo_show_text(w->crb, sc);
        cairo_set_source(w->crb,pat);
        int m = 1000*scale;
        int n = 100*scale;
        int o = 500*scale;
        int p = 250*scale;
        //if (m==0 && xt->smove !=0) xt->move=width/20;
        xt->smove = m;
        xt->move +=m;
        static int cmove = 0;
        static int omove = 0;
        static int pmove = 0;
        cmove += n;
        omove += o;
        pmove += p;
        if(xt->move<-width/20) xt->move=width/20;
        else if(xt->move>width/20) xt->move=-width/20;
        if(cmove<-width/20) cmove=width/20;
        else if(cmove>width/20) cmove=-width/20;
        if(omove<-width/20) omove=width/20;
        else if(omove>width/20) omove=-width/20;
        if(pmove<-width/20) pmove=width/20;
        else if(pmove>width/20) pmove=-width/20;
        if (m==0) {
            if(xt->move<0) xt->move+=1;
            else if(xt->move>0) xt->move-=1;
        }
        if (n==0) {
            if(cmove<0) cmove+=1;
            else if(cmove>0) cmove-=1;
        }
        if (o==0) {
            if(omove<0) omove+=1;
            else if(omove>0) omove-=1;
        }
        if (p==0) {
            if(pmove<0) pmove+=1;
            else if(pmove>0) pmove-=1;
        }
        for (int i = 0; i < 4; ++i) {
            cairo_rectangle(w->crb,(width/2)-20 + (xt->move+i)*10, 5, 5, 5);
            cairo_rectangle(w->crb,(width/2)-20 + (omove+i)*10, 10, 5, 5);
            cairo_rectangle(w->crb,(width/2)-20 + (pmove+i)*10, 15, 5, 5);
            cairo_rectangle(w->crb,(width/2)-20 + (cmove+i)*10, 20, 5, 5);
            cairo_fill(w->crb);
        }
    } else {
        cairo_set_source_rgb(w->crb,0.2,0.2,0.2);
        cairo_set_font_size (w->crb, w->app->big_font/w->scale.ascale);
        cairo_text_extents(w->crb, "000.00 Hz", &extents);
        cairo_move_to (w->crb, width/1.1-extents.width, height-extents.height );
        cairo_show_text(w->crb, "000.00 Hz");
        cairo_text_extents(w->crb, "0.00 cent", &extents);
        cairo_move_to (w->crb, width/4.1-extents.width, height-extents.height );
        cairo_show_text(w->crb, "0.00 cent");
        cairo_set_font_size(w->crb, (w->app->big_font*2)/w->scale.ascale);
        cairo_text_extents(w->crb,"#" , &extents);
        float c = (extents.width/2)+10.0;
        cairo_move_to(w->crb,x0-c , y0+10 );
        cairo_show_text(w->crb, "#");
        cairo_set_font_size(w->crb, (w->app->small_font*2)/w->scale.ascale);
        cairo_move_to(w->crb,x0+c-10.0, y0+10+ extents.height/2 );
        cairo_show_text(w->crb, "0");
    }
    cairo_pattern_destroy(pat);
}
References Widget_t::adj, adj_get_value(), Widget_t::app, Resize_t::ascale, Xputty::big_font, Widget_t::crb, Metrics_t::height, XTuner::move, NORMAL_, os_get_window_metrics(), Widget_t::parent_struct, XTuner::ref_freq, Widget_t::scale, Xputty::small_font, XTuner::smove, XTuner::temp_adjust, use_bg_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by add_tuner().