libxputty: xputty/header/widgets/xvaluedisplay_private.h File Reference
xvaluedisplay_private.h File Reference
Functions
void _draw_valuedisplay (void *w_, void *user_data)
_draw_valuedisplay - draw a valuedisplay on expose call
void _popup_spinbox (void *w_, void *button, void *user_data)
_popup_spinbox - show a spinbox above a valuedisplay
void _draw_spinbox (void *w_, void *user_data)
_draw_spinbox - draw a spinbox expose call
void _draw_buttons (void *w_, void *user_data)
_draw_buttons - draw the spinbox buttons
void _buttons_released (void *w_, void *button, void *user_data)
_buttons_released - set the spinbox value on button releases
Function Documentation
_buttons_released()
void _buttons_released (void * w_, void * button, void * user_data)
_buttons_released - set the spinbox value on button releases
Parameters
*w_ - The Widget_t contain the button
*button - the XButtonEvent
*user_data - attached user_data
Definition at line 157 of file xvaluedisplay_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t *p = (Widget_t*)w->parent;
    Widget_t *parent = (Widget_t*)p->parent;
    XButtonEvent *xbutton = (XButtonEvent*)button_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int height = metrics.height-2;
    if (!metrics.visible) return;
    if (xbutton->button == Button1) {
        if (xbutton->y > height/2)
            adj_set_value(parent->adj, adj_get_value(parent->adj)-parent->adj->step);
        else
           adj_set_value(parent->adj, adj_get_value(parent->adj)+parent->adj->step);
        expose_widget(p);
    } else if (xbutton->button == Button4) {
        adj_set_value(parent->adj, adj_get_value(parent->adj)+parent->adj->step);
        expose_widget(p);
    } else if (xbutton->button == Button5) {
        adj_set_value(parent->adj, adj_get_value(parent->adj)-parent->adj->step);
        expose_widget(p);
    }
}
References Widget_t::adj, adj_get_value(), adj_set_value(), XEvent::button, expose_widget(), Metrics_t::height, os_get_window_metrics(), Widget_t::parent, Adjustment_t::step, Metrics_t::visible, and XEvent::y.
Referenced by add_popup_spinbox().
_draw_buttons()
void _draw_buttons (void * w_, void * user_data)
_draw_buttons - draw the spinbox buttons
Parameters
*w_ - The Widget_t contain the spinbox
*user_data - attached user_data
Definition at line 133 of file xvaluedisplay_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    cairo_rectangle(w->crb,0.0, 2.0, width, height-2);
    use_bg_color_scheme(w, NORMAL_);
    cairo_fill_preserve(w->crb);
    use_text_color_scheme(w, NORMAL_);
    cairo_stroke(w->crb);
    cairo_rectangle(w->crb,0.0, height/2, width, height-2);
    cairo_stroke(w->crb);
    use_text_color_scheme(w, get_color_state(w));
    float font_size = w->app->big_font/w->scale.ascale;
    cairo_set_font_size (w->crb, font_size);
    cairo_move_to (w->crb, 5,18);
    cairo_show_text(w->crb, "+");
    cairo_move_to (w->crb, 7,38);
    cairo_show_text(w->crb, "-");
}
References Widget_t::app, Resize_t::ascale, Xputty::big_font, Widget_t::crb, get_color_state(), Metrics_t::height, NORMAL_, os_get_window_metrics(), Widget_t::scale, use_bg_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by add_popup_spinbox().
_draw_spinbox()
void _draw_spinbox (void * w_, void * user_data)
_draw_spinbox - draw a spinbox expose call
Parameters
*w_ - The Widget_t contain the spinbox
*user_data - attached user_data
Definition at line 93 of file xvaluedisplay_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t *p = (Widget_t*)w->parent;
    Widget_t *parent = (Widget_t*)p->parent;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    cairo_rectangle(w->crb,2.0, 2.0, width, height);
    use_bg_color_scheme(w, NORMAL_);
    cairo_fill_preserve(w->crb);
    use_text_color_scheme(w, NORMAL_);
    cairo_stroke(w->crb);
    cairo_text_extents_t extents;
    char s[64];
    const char* format[] = {"%.1f", "%.2f", "%.3f"};
    float value = adj_get_value(parent->adj);
    if (fabs(parent->adj->step)>0.99) {
        snprintf(s, 63,"%d",  (int) value);
    } else if (fabs(parent->adj->step)>0.09) {
        snprintf(s, 63, format[1-1], value);
    } else {
        snprintf(s, 63, format[2-1], value);
    }
    use_text_color_scheme(w, get_color_state(w));
    float font_size = w->app->normal_font/w->scale.ascale;
    cairo_set_font_size (w->crb, font_size);
    cairo_text_extents(w->crb,s , &extents);
    cairo_move_to (w->crb, (width-extents.width)*0.5, (height+extents.height)*0.55);
    cairo_show_text(w->crb, s);
    cairo_new_path (w->crb);
}
References Widget_t::adj, adj_get_value(), Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, NORMAL_, Xputty::normal_font, os_get_window_metrics(), Widget_t::parent, Widget_t::scale, Adjustment_t::step, use_bg_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by add_popup_spinbox().
_draw_valuedisplay()
void _draw_valuedisplay (void * w_, void * user_data)
_draw_valuedisplay - draw a valuedisplay on expose call
Parameters
*w_ - The Widget_t contain the valuedisplay
*user_data - attached user_data
Definition at line 25 of file xvaluedisplay_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    if (!w) return;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width = metrics.width-2;
    int height = metrics.height-2;
    if (!metrics.visible) return;
    cairo_rectangle(w->crb,2.0, 2.0, width, height);
    if(w->state==0) {
        cairo_set_line_width(w->crb, 1.0);
        use_shadow_color_scheme(w, NORMAL_);
        cairo_fill_preserve(w->crb);
        use_frame_color_scheme(w, NORMAL_);
    } else if(w->state==1) {
        use_shadow_color_scheme(w, PRELIGHT_);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.5);
        use_frame_color_scheme(w, NORMAL_);
    } else if(w->state==2) {
        use_shadow_color_scheme(w, SELECTED_);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, SELECTED_);
    } else if(w->state==3) {
        use_shadow_color_scheme(w, ACTIVE_);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, ACTIVE_);
    } else if(w->state==4) {
        use_shadow_color_scheme(w, INSENSITIVE_);
        cairo_fill_preserve(w->crb);
        cairo_set_line_width(w->crb, 1.0);
        use_frame_color_scheme(w, INSENSITIVE_);
    }
    cairo_stroke(w->crb);
    cairo_rectangle(w->crb,4.0, 4.0, width, height);
    cairo_stroke(w->crb);
    cairo_rectangle(w->crb,3.0, 3.0, width, height);
    cairo_stroke(w->crb);
    cairo_text_extents_t extents;
    char s[64];
    const char* format[] = {"%.1f", "%.2f", "%.3f"};
    float value = adj_get_value(w->adj);
    if (fabs(w->adj->step)>0.99) {
        snprintf(s, 63,"%d",  (int) value);
    } else if (fabs(w->adj->step)>0.09) {
        snprintf(s, 63, format[1-1], value);
    } else {
        snprintf(s, 63, format[2-1], value);
    }
    use_text_color_scheme(w, get_color_state(w));
    float font_size = w->app->normal_font/w->scale.ascale;
    cairo_set_font_size (w->crb, font_size);
    cairo_text_extents(w->crb,s , &extents);
    cairo_move_to (w->crb, (width-extents.width)*0.5, (height+extents.height)*0.55);
    cairo_show_text(w->crb, s);
    cairo_new_path (w->crb);
}
References ACTIVE_, Widget_t::adj, adj_get_value(), Widget_t::app, Resize_t::ascale, Widget_t::crb, get_color_state(), Metrics_t::height, INSENSITIVE_, NORMAL_, Xputty::normal_font, os_get_window_metrics(), PRELIGHT_, Widget_t::scale, SELECTED_, Widget_t::state, Adjustment_t::step, use_frame_color_scheme(), use_shadow_color_scheme(), use_text_color_scheme(), Metrics_t::visible, and Metrics_t::width.
Referenced by add_valuedisplay().
_popup_spinbox()
void _popup_spinbox (void * w_, void * button, void * user_data)
_popup_spinbox - show a spinbox above a valuedisplay
Parameters
*w_ - The Widget_t contain the valuedisplay
*button - the XButtonEvent
*user_data - attached user_data
Definition at line 182 of file xvaluedisplay_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    Widget_t *spin_box = (Widget_t*)w->childlist->childs[0];
    int x1, y1;
    os_translate_coords(w, w->widget, os_get_root_window(w->app, IS_WIDGET), 0, 0, &x1, &y1);
    os_move_window(spin_box->app->dpy,spin_box,x1-10, y1-10);
    pop_widget_show_all(spin_box);
    int err = os_grab_pointer(w);
    w->app->hold_grab = spin_box;
    if (err) debug_print("Error grap pointer\n");
}
References Widget_t::app, Widget_t::childlist, Childlist_t::childs, Xputty::dpy, Xputty::hold_grab, IS_WIDGET, os_get_root_window(), os_grab_pointer(), os_move_window(), os_translate_coords(), pop_widget_show_all(), and Widget_t::widget.
Referenced by add_valuedisplay().