libxputty: xputty/header/widgets/xvaluedisplay.h File Reference
xvaluedisplay.h File Reference
Functions
Widget_t * add_valuedisplay (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_valuedisplay - add a valuedisplay widget to a Widget_t
Widget_t * add_popup_spinbox (Widget_t *parent, const char *label, int x, int y, int width, int height)
Function Documentation
add_popup_spinbox()
Widget_t * add_popup_spinbox (Widget_t * parent, const char * label, int x, int y, int width, int height)
Definition at line 26 of file xvaluedisplay.c.
{
    int x1, y1;
    os_translate_coords(parent, parent->widget, os_get_root_window(parent->app, IS_WIDGET), 0, 0, &x1, &y1);
    Widget_t *wid = create_window(parent->app, os_get_root_window(parent->app, IS_WIDGET), x1, y1, width +40, height+20);
    os_set_window_attrb(wid);
    os_set_transient_for_hint(parent, wid);
    //wid->func.expose_callback = _draw_spinbox;
    wid->flags |= IS_POPUP;
    wid->scale.gravity = NONE;
    wid->parent = parent;
    childlist_add_child(parent->childlist, wid);
    Widget_t *view_port = create_widget(wid->app, wid, 0 , 0, width+20, height+20);
    view_port->func.expose_callback = _draw_spinbox;
    Widget_t *buttons = create_widget(wid->app, wid, width+20 , 0, 20, height+20);
    buttons->func.expose_callback = _draw_buttons;
    buttons->scale.gravity = NORTHWEST;
    buttons->flags &= ~USE_TRANSPARENCY;
    buttons->flags |= NO_AUTOREPEAT | NO_PROPAGATE;
    buttons->func.button_release_callback = _buttons_released;
    return wid;
}
References _buttons_released(), _draw_buttons(), _draw_spinbox(), Widget_t::app, Func_t::button_release_callback, Widget_t::childlist, childlist_add_child(), create_widget(), create_window(), Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, IS_POPUP, IS_WIDGET, NO_AUTOREPEAT, NO_PROPAGATE, NONE, NORTHWEST, os_get_root_window(), os_set_transient_for_hint(), os_set_window_attrb(), os_translate_coords(), Widget_t::parent, Widget_t::scale, and Widget_t::widget.
Referenced by add_valuedisplay().
add_valuedisplay()
Widget_t * add_valuedisplay (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_valuedisplay - add a valuedisplay widget to a Widget_t
Parameters
*parent - pointer to the Widget_t request the valuedisplay
*label - Label to show on the valuedisplay
x,y,width,height - the position/geometry to create the valuedisplay
Returns
Widget_t* - pointer to the Widget_t valuedisplay struct
Definition at line 50 of file xvaluedisplay.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    add_popup_spinbox(wid, label, x, y, width, height);
    wid->label = label;
    wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0, 0.01, CL_CONTINUOS);
    wid->adj = wid->adj_y;
    wid->scale.gravity = CENTER;
    wid->func.enter_callback = os_transparent_draw;
    wid->func.leave_callback = os_transparent_draw;
    wid->func.double_click_callback = _popup_spinbox;
    wid->func.expose_callback = _draw_valuedisplay;
    return wid;
}
References _draw_valuedisplay(), _popup_spinbox(), add_adjustment(), add_popup_spinbox(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, CENTER, CL_CONTINUOS, create_widget(), Func_t::double_click_callback, Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, os_transparent_draw(), and Widget_t::scale.