libxputty: xputty/header/widgets/xwaveview.h File Reference
xwaveview.h File Reference
Data Structures
struct WaveView_t
Functions
Widget_t * add_waveview (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_waveview - add a waveview to a Widget_t
void update_waveview (Widget_t *waveview, float *wave, int size)
void waveview_mem_free (void *w_, void *user_data)
Function Documentation
add_waveview()
Widget_t * add_waveview (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_waveview - add a waveview to a Widget_t
Parameters
*parent - pointer to the Widget_t request the waveview
*label - Label to show on the waveview
x,y,width,height - the position/geometry to create the waveview
Returns
Widget_t* - pointer to the Widget_t waveview struct
Definition at line 26 of file xwaveview.c.
{
    Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
    wid->label = label;
    wid->flags |= HAS_MEM;
    wid->scale.gravity = CENTER;
    WaveView_t *wave_view;
    wave_view = (WaveView_t*)malloc(sizeof(WaveView_t));
    wave_view->wave = NULL;
    wave_view->size = 0;
    wid->private_struct = wave_view;
    wid->func.expose_callback = _draw_waveview;
    wid->func.mem_free_callback = waveview_mem_free;
    return wid;
}
References _draw_waveview(), Widget_t::app, CENTER, create_widget(), Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, Widget_t::label, Func_t::mem_free_callback, Widget_t::private_struct, Widget_t::scale, WaveView_t::size, WaveView_t::wave, and waveview_mem_free().
update_waveview()
void update_waveview (Widget_t * waveview, float * wave, int size)
Definition at line 43 of file xwaveview.c.
{
    WaveView_t *wave_view = (WaveView_t*)waveview->private_struct;
    if (size !=wave_view->size && size>1) {
        free(wave_view->wave);
        wave_view->wave = NULL;
        wave_view->size = size;
        wave_view->wave = (float*)malloc(size*sizeof(float));
    }
    if (wave_view->size>1) {
        memcpy(wave_view->wave, wave, size*sizeof(float));
        expose_widget(waveview);
    }
}
References expose_widget(), Widget_t::private_struct, WaveView_t::size, and WaveView_t::wave.
waveview_mem_free()
void waveview_mem_free (void * w_, void * user_data)
Definition at line 57 of file xwaveview.c.
{
    Widget_t *w = (Widget_t*)w_;
    WaveView_t *wave_view = (WaveView_t*)w->private_struct;
    free(wave_view->wave);
    free(wave_view);
}
References Widget_t::private_struct, and WaveView_t::wave.
Referenced by add_waveview().