libxputty: xputty/widgets/xwaveview_private.c File Reference
xwaveview_private.c File Reference
Functions
void _rounded_view (cairo_t *cr, float x, float y, float w, float h, float lsize)
void _draw_waveview (void *w_, void *user_data)
Function Documentation
_draw_waveview()
void _draw_waveview (void * w_, void * user_data)
Definition at line 39 of file xwaveview_private.c.
{
    Widget_t *w = (Widget_t*)w_;
    WaveView_t *wave_view = (WaveView_t*)w->private_struct;
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    int width_t = metrics.width;
    int height_t = metrics.height;
    if (!metrics.visible) return;
    int half_height_t = height_t/2;
    cairo_text_extents_t extents;
    cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
    cairo_text_extents(w->crb,w->label , &extents);
    cairo_set_line_width(w->crb,2);
    use_bg_color_scheme(w, NORMAL_);
    _rounded_view(w->crb, 2, 5, width_t-4, height_t-7, extents.width+15);
    cairo_fill_preserve(w->crb);
    use_frame_color_scheme(w, NORMAL_);
    cairo_stroke(w->crb);
    cairo_move_to(w->crb,2,half_height_t);
    cairo_line_to(w->crb, width_t-4, half_height_t);
    cairo_stroke(w->crb);
    use_text_color_scheme(w, get_color_state(w));
    cairo_move_to (w->crb, 30, extents.height);
    cairo_show_text(w->crb, w->label);
    cairo_new_path (w->crb);
    if (wave_view->size<1) return;
    float step = (float)(width_t-10)/(float)wave_view->size+1;
    float lstep = (float)(half_height_t-10.0);
    cairo_set_line_width(w->cr,2);
    use_fg_color_scheme(w, NORMAL_);
    int i = 0;
    for (;i<wave_view->size;i++) {
        cairo_line_to(w->crb, (float)(i+0.5)*step,(float)(half_height_t)+ -wave_view->wave[i]*lstep);
    }
    cairo_line_to(w->crb, width_t, half_height_t);
    cairo_line_to(w->crb, 2, half_height_t);
    cairo_close_path(w->crb);
    use_light_color_scheme(w, NORMAL_);
    cairo_fill_preserve(w->crb);
    use_fg_color_scheme(w, NORMAL_);
    cairo_stroke(w->crb);
    i = 0;
    for (;i<wave_view->size;i++) {
        cairo_line_to(w->crb, (float)(i+0.5)*step,(float)(half_height_t)+ wave_view->wave[i]*lstep);
    }
    cairo_line_to(w->crb, width_t, half_height_t);
    cairo_line_to(w->crb, 2, half_height_t);
    cairo_close_path(w->crb);
    use_light_color_scheme(w, NORMAL_);
    cairo_fill_preserve(w->crb);
    use_fg_color_scheme(w, NORMAL_);
    cairo_stroke(w->crb);
}
References _rounded_view(), Widget_t::app, Resize_t::ascale, Widget_t::cr, Widget_t::crb, get_color_state(), Metrics_t::height, Widget_t::label, NORMAL_, Xputty::normal_font, os_get_window_metrics(), Widget_t::private_struct, Widget_t::scale, WaveView_t::size, use_bg_color_scheme(), use_fg_color_scheme(), use_frame_color_scheme(), use_light_color_scheme(), use_text_color_scheme(), Metrics_t::visible, WaveView_t::wave, and Metrics_t::width.
Referenced by add_waveview().
_rounded_view()
void _rounded_view (cairo_t * cr, float x, float y, float w, float h, float lsize)
Definition at line 25 of file xwaveview_private.c.
{
    cairo_new_path (cr);
    float r = 20.0;
    cairo_move_to(cr, x+lsize+r,y);
    cairo_line_to(cr, x+w-r,y);
    cairo_curve_to(cr, x+w,y,x+w,y,x+w,y+r);
    cairo_line_to(cr, x+w,y+h-r);
    cairo_curve_to(cr, x+w,y+h,x+w,y+h,x+w-r,y+h);
    cairo_line_to(cr, x+r,y+h);
    cairo_curve_to(cr, x,y+h,x,y+h,x,y+h-r);
    cairo_line_to(cr, x,y+r);
    cairo_curve_to(cr, x,y,x,y,x+r,y);
}
Referenced by _draw_waveview().