libxputty: xputty/header/xwidget.h File Reference
xwidget.h File Reference
Data Structures
struct Func_t
Func_t - struct to hold all supported event callbacks.
struct Resize_t
Resize_t - struct used to resize child widgets.
struct Widget_t
Widget_t - struct to hold the basic Widget_t info.
Typedefs
typedef void(* vfunc) (void *widget, void *event, Xputty *main, void *user_data)
*vfunc - function pointer to connect Xevents from the main loop to Widget_t
typedef void(* evfunc) (void *widget, void *event, void *user_data)
*evfunc - function pointer to connect Xevents from a Widget_t to a event handler
typedef void(* xevfunc) (void *widget, void *user_data)
*xevfunc - function pointer to connect XEvents from a Widget_t to a event handler
Enumerations
enum EventType {
EXPOSE = 1 , CONFIGURE , ENTER , LEAVE ,
ADJ_INTERN , VALUE_CHANGED , USER , MEM_FREE_CB ,
CONFIGURE_NOTIFY , MAP_NOTIFY , UNMAP_NOTIFY , DIALOG_RESPONSE ,
BUTTON_PRESS , BUTTON_RELEASE , POINTER_MOTION , KEY_PRESS ,
KEY_RELEASE
}
EventType - enum to hold identifier for all supported event callbacks
Events could be connected to a handler by using this identifier.
enum WidgetType {
WT_NONE , WT_WINDOW , WT_WIDGET , WT_BUTTON ,
WT_ON_OFF_BUTTON , WT_TOGGLE_BUTTON , WT_IMAGE_TOGGLE_BUTTON , WT_SWITCH_IMAGE_TOGGLE_BUTTON ,
WT_CHECK_BUTTON , WT_CHECK_BOX , WT_COMBOBOX , WT_FILE_DIALOG ,
WT_KNOB , WT_IMAGE_KNOB , WT_LABEL , WT_LISTBOX_VIEWPORT ,
WT_LISTBOX , WT_LISTBOX_ENTRY , WT_LISTVIEW_VIEWPORT , WT_LISTVIEW ,
WT_MENU , WT_MENU_VIEWPORT , WT_MENU_ITEM , WT_MENU_CHECK_ITEM ,
WT_MENU_RADIO_ITEM , WT_MESSAGE_DIALOG , WT_VMETER , WT_VMETER_SCALE ,
WT_HMETER , WT_HMETER_SCALE , WT_MIDI_KEYBOARD , WT_PLAYHEAD ,
WT_VSLIDER , WT_HSLIDER , WT_TOOLTIP , WT_TUNER ,
WT_VALUEDISPLAY , WT_TEXT_ENTRY
}
WidgetType - enum describing the kind of the widget (button, menu, ...)
The widget_type member can be used to identify the source widget e.g. in the messageloop.
enum Gravity {
NORTHWEST , NORTHEAST , SOUTHWEST , SOUTHEAST ,
SOUTHCENTER , EASTWEST , EASTNORTH , EASTSOUTH ,
WESTNORTH , WESTSOUTH , CENTER , ASPECT ,
FIXEDSIZE , MENUITEM , NONE
}
Gravity - enum to indicate how to resize a widget.
enum {
IS_WIDGET = 1<<0 , IS_WINDOW = 1<<1 , IS_POPUP = 1<<2 , IS_RADIO = 1<<3 ,
IS_TOOLTIP = 1<<4 , USE_TRANSPARENCY = 1<<5 , HAS_FOCUS = 1<<6 , HAS_POINTER = 1<<7 ,
HAS_TOOLTIP = 1<<8 , HAS_MEM = 1<<9 , NO_AUTOREPEAT = 1<<10 , FAST_REDRAW = 1<<11 ,
HIDE_ON_DELETE = 1<<12 , REUSE_IMAGE = 1<<13 , NO_PROPAGATE = 1<<14 , IS_SUBMENU = 1<<15 ,
DONT_PROPAGATE = 1<<16
}
anonymous enum - flags to set Widget_t propertys
Functions
Widget_t * create_window (Xputty *app, Window win, int x, int y, int width, int height)
*create_window - create a Window
You need to create as least minimun one Window to get started.
The first created Window is the top_level_widget()
A Window could be created on the DefaultRootWindow() or embeded into a other XWindow
Widget_t * create_widget (Xputty *app, Widget_t *win, int x, int y, int width, int height)
*create_widget - create a widget
A Widget_t could only be created as child of a other Widget_t
To create a Widget_t you need to create a Widget_t with create_window() before.
void connect_func (void(**event)(), void(*handler)())
connect_func - connect a event with a handler without type check. For supported events see: Func_t
void widget_set_title (Widget_t *w, const char *title)
widget_set_title - set window title for a Widget_t
void widget_show (Widget_t *w)
widget_show - map/show widget
void pop_widget_show_all (Widget_t *w)
pop_widget_show_all - map/show popup widget with all it's childs
void submenu_widget_show_all (Widget_t *w)
submenu_widget_show_all - map/show submenu Widget_t with all childs
void widget_hide (Widget_t *w)
widget_hide - unmap/hide a Widget_t
void widget_hide_all (Widget_t *w)
widget_hide_all - unmap/hide all Widget_t from app
void widget_show_all (Widget_t *w)
widget_show_all - map/show Widget_t with all childs
void show_tooltip (Widget_t *wid)
show_tooltip - check if a Widget_t have a tooltip, and show it, if a tooltip is available.
void hide_tooltip (Widget_t *wid)
hide_tooltip - check if a Widget_t have a tooltip, and hide it, if a tooltip is mapped.
Widget_t * get_toplevel_widget (Xputty *main)
*get_toplevel_widget - get pointer to the top level Widget_t
void quit (Widget_t *w)
quit - exit the main loop
void quit_widget (Widget_t *w)
quit_widget - remove a widget from the processing loop
void transparent_draw (void *wid, void *user_data)
transparent_draw - copy parent surface to child surface
you usaualy didn't need to call this, it's used automaticaly when a Widget_t have set the flag USE_TRANSPARENCY
this is the default setting for Widget_t
void widget_draw (void *w_, void *user_data)
widget_draw - redraw only the widget,not the child widgets
void resize_childs (Widget_t *wid)
resize_childs - intern check if child widgets needs resizing
void widget_reset_scale (Widget_t *w)
widget_reset_scale - used to reset scaling mode after a image surface is drawn to the Widget_t surface with widget_set_scale()
void widget_set_scale (Widget_t *w)
widget_set_scale - set scaling mode to scale a image surface to the size of the Widget_t surface
void destroy_widget (Widget_t *w, Xputty *main)
destroy_widget - destroy a widget
When a Widget_t receive a destroy_widget() call, it will propagate that to all childs in it's Childlist_t. So all childs get destroyed before the Widget_t itself close.
void widget_event_loop (void *w_, void *event, Xputty *main, void *user_data)
widget_event_loop - the internal widget event loop
void send_configure_event (Widget_t *w, int x, int y, int width, int height)
send_configure_event - send a ConfigureNotify to Widget_t
used to resize a Widget_t
void send_button_press_event (Widget_t *w)
send_button_press_event - send ButtonPress event to Widget_t
simulate a BUTTON_PRESS Event
void send_button_release_event (Widget_t *w)
send_button_release_event - send ButtonRelease event to Widget_t
simulate a BUTTON_RELEASE Event
void send_systray_message (Widget_t *w)
send_systray_message - request a systray icon for Widget_t
currently not working
void expose_widget (Widget_t *w)
expose_widgets - send a expose event (EXPOSE) to a Widget_t
int key_mapping (Display *dpy, XKeyEvent *xkey)
_key_mapping - modifier key's mapped to a integer value
const char * widget_type_name (Widget_t *w)
widget_type_name - textual representation of (Widget_t*)->widget_type
void strdecode (char *target, const char *needle, const char *replacement)
strdecode - replace string in char*
void widget_set_dnd_aware (Widget_t *w)
widget_set_dnd_aware - allow drag and drop for on Widget_t
void widget_set_dnd_unaware (Widget_t *w)
widget_set_dnd_unaware - disable drag and drop for on Widget_t
void handle_drag_data (Widget_t *w, XEvent *event)
handle_drag_data - handle recived drag data
void handle_dnd_enter (Xputty *main, XEvent *event)
handle_drag_enter - handle drag event enter the Widget_t
void send_dnd_finished_event (Widget_t *w, XEvent *event)
send_dnd_finished_event - notify the drag sender that the event is handled
void send_dnd_status_event (Widget_t *w, XEvent *event)
send_dnd_status_event - notify the drag sender that prepared to recive the event
void copy_to_clipboard (Widget_t *w, char *text, int size)
copy_to_clipboard - send textbuffer to clipboard
void send_to_clipboard (Widget_t *w, XEvent *event)
send_to_clipboard - send textbuffer to clipboard on request
int have_paste (Widget_t *w)
have_paste - check if clipboard contain a textbuffer
void request_paste_from_clipboard (Widget_t *w)
request_paste_from_clipboard - request textbuffer from clipboard
void receive_paste_from_clipboard (Widget_t *w, XEvent *event)
receive_paste_from_clipboard - receive textbuffer from clipboard
Typedef Documentation
evfunc
typedef void(* evfunc) (void *widget, void *event, void *user_data)
*evfunc - function pointer to connect Xevents from a Widget_t to a event handler
Parameters
*widget - void pointer to the Widget_t
*event - void pointer to the XEvent
*user_data - void pointer to attached user_data, maybe NULL
Returns
void
Definition at line 62 of file xwidget.h.
vfunc
typedef void(* vfunc) (void *widget, void *event, Xputty *main, void *user_data)
*vfunc - function pointer to connect Xevents from the main loop to Widget_t
Parameters
*widget - void pointer to the Widget_t
*main - pointer to Xputty main struct running the loop
*event - void pointer to the XEvent
*user_data - void pointer to attached user_data, maybe NULL
Returns
void
Definition at line 52 of file xwidget.h.
xevfunc
typedef void(* xevfunc) (void *widget, void *user_data)
*xevfunc - function pointer to connect XEvents from a Widget_t to a event handler
Parameters
*widget - void pointer to the widget
*user_data - void pointer to attached user_data, maybe NULL
Returns
void
Definition at line 72 of file xwidget.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
anonymous enum - flags to set Widget_t propertys
Parameters
IS_WIDGET - Widget_t is a sub widget
IS_WINDOW - Widget_t has no Widget_t parent
IS_POPUP - Widget_t is a pop up widget
IS_RADIO - Widget_t is part of a radio group
USE_TRANSPARENCY - Widget_t need transparent draw (buffer)
HAS_FOCUS - Mouse pointer is above Widget_t
HAS_POINTER - Mouse pointer is pressed on Widget_t
HAS_TOOLTIP - Widget_t have tooltip
HAS_MEM - Widget_t have mem to be released
Enumerator
IS_WIDGET
Widget_t is a sub widget
IS_WINDOW
Widget_t has no Widget_t parent
IS_POPUP
Widget_t is a pop up widget
IS_RADIO
Widget_t is part of a radio group
IS_TOOLTIP
Widget_t is a tooltip widget
USE_TRANSPARENCY
Widget_t need transparent draw (buffer)
HAS_FOCUS
Mouse pointer is above Widget_t
HAS_POINTER
Mouse pointer is pressed on Widget_t
HAS_TOOLTIP
Widget_t have tooltip
HAS_MEM
Widget_t have mem to be released
NO_AUTOREPEAT
Widget_t didn't receive autorepeated keys
FAST_REDRAW
Widget_t need fast redrawing
HIDE_ON_DELETE
Hide Widget_t instead delete on "WM_DELETE_WINDOW"
REUSE_IMAGE
Widget_t reuse a surface from a other Widget_t
NO_PROPAGATE
Widget_t didn't receive redraw events on propagate
IS_SUBMENU
Widget_t is a sub Widget_t from a Popup Widget_t
DONT_PROPAGATE
Widget_t didn't send redraw events to child widgets
Definition at line 382 of file xwidget.h.
     {
    IS_WIDGET         = 1<<0,
    IS_WINDOW         = 1<<1,
    IS_POPUP          = 1<<2,
    IS_RADIO          = 1<<3,
    IS_TOOLTIP        = 1<<4,
    USE_TRANSPARENCY  = 1<<5,
    HAS_FOCUS         = 1<<6,
    HAS_POINTER       = 1<<7,
    HAS_TOOLTIP       = 1<<8,
    HAS_MEM           = 1<<9,
    NO_AUTOREPEAT     = 1<<10,
    FAST_REDRAW       = 1<<11,
    HIDE_ON_DELETE    = 1<<12,
    REUSE_IMAGE       = 1<<13,
    NO_PROPAGATE      = 1<<14,
    IS_SUBMENU        = 1<<15,
    DONT_PROPAGATE    = 1<<16,
};
EventType
enum EventType
EventType - enum to hold identifier for all supported event callbacks
Events could be connected to a handler by using this identifier.
Parameters
EXPOSE - (xevfunc) expose_callback(void * widget, void user_data)
CONFIGURE - (xevfunc) configure_callback(void * widget, void user_data)
ENTER - (xevfunc) enter_callback(void * widget, void user_data)
LEAVE - (xevfunc) leave_callback(void * widget, void user_data)
ADJ_INTERN - (xevfunc) adj_callback(void * widget, void user_data)
VALUE_CHANGED - (xevfunc) value_changed_callback(void * widget, void user_data)
USER - (xevfunc) user_callback(void * widget, void user_data)
MEM_FREE_CB - (xevfunc) mem_free_callback(void * widget, void user_data)
CONFIGURE_NOTIFY - (xevfunc) configure_notify_callback(void * widget, void user_data)
MAP_NOTIFY - (xevfunc) map_notify_callback(void * widget, void user_data)
UNMAP_NOTIFY - (xevfunc) unmap_notify_callback(void * widget, void user_data)
DIALOG_RESPONS - (xevfunc) dialog_callback(void * widget, void user_data)
BUTTON_PRESS - (evfunc) button_press_callback(void * widget, void * event, void user_data)
BUTTON_RELEASE - (evfunc) button_release_callback(void * widget, void * event, void user_data)
POINTER_MOTION - (evfunc) motion_callback(void * widget, void * event, void user_data)
KEY_PRESS - (evfunc) key_press_callback(void * widget, void * event, void user_data)
KEY_RELEASE - (evfunc) key_release_callback(void * widget, void * event, void user_data)
Enumerator
EXPOSE
CONFIGURE
ENTER
LEAVE
ADJ_INTERN
VALUE_CHANGED
USER
MEM_FREE_CB
CONFIGURE_NOTIFY
MAP_NOTIFY
UNMAP_NOTIFY
DIALOG_RESPONSE
BUTTON_PRESS
BUTTON_RELEASE
POINTER_MOTION
KEY_PRESS
KEY_RELEASE
Definition at line 127 of file xwidget.h.
             {
    EXPOSE = 1,
    CONFIGURE,
    ENTER,
    LEAVE,
    ADJ_INTERN,
    VALUE_CHANGED,
    USER,
    MEM_FREE_CB,
    CONFIGURE_NOTIFY,
    MAP_NOTIFY,
    UNMAP_NOTIFY,
    DIALOG_RESPONSE,
    BUTTON_PRESS,
    BUTTON_RELEASE,
    POINTER_MOTION,
    KEY_PRESS,
    KEY_RELEASE,
} EventType;
Gravity
enum Gravity
Gravity - enum to indicate how to resize a widget.
Parameters
NORTHWEST - Widget_t adjust nord/west
NORTHEAST - Widget_t adjust nord/east
SOUTHWEST - Widget_t adjust south/west
SOUTHEAST - Widget_t adjust south/east
CENTER - Widget_t adjust centered
ASPECT - Widget_t adjust in a aspect frame
NONE - Widget_t request no adjustment in frame
Enumerator
NORTHWEST
Widget_t adjust nord/west
NORTHEAST
Widget_t adjust nord/east
SOUTHWEST
Widget_t adjust south/west
SOUTHEAST
Widget_t adjust south/east
SOUTHCENTER
Widget_t adjust south/east
EASTWEST
Widget_t adjust east/west
EASTNORTH
Widget_t adjust east/north
EASTSOUTH
Widget_t adjust east/south
WESTNORTH
Widget_t adjust west/north
WESTSOUTH
Widget_t adjust west/south
CENTER
Widget_t adjust centered
ASPECT
Widget_t adjust in a aspect frame
FIXEDSIZE
Widget_t has fixed size
MENUITEM
Widget_t adjust in a aspect frame
NONE
Widget_t request no adjustment in frame
Definition at line 294 of file xwidget.h.
             {
    NORTHWEST    ,
    NORTHEAST    ,
    SOUTHWEST     ,
    SOUTHEAST     ,
    SOUTHCENTER     ,
    EASTWEST     ,
    EASTNORTH     ,
    EASTSOUTH     ,
    WESTNORTH     ,
    WESTSOUTH     ,
    CENTER        ,
    ASPECT        ,
    FIXEDSIZE        ,
    MENUITEM      ,
    NONE          ,
}Gravity;
WidgetType
enum WidgetType
WidgetType - enum describing the kind of the widget (button, menu, ...)
The widget_type member can be used to identify the source widget e.g. in the messageloop.
Parameters
WT_NONE - (unitialized or error)
WT_WINDOW - create_window()
WT_WIDGET - create_widget()
WT_BUTTON - add_button()
WT_ON_OFF_BUTTON - add_on_off_button()
WT_TOGGLE_BUTTON - add_toggle_button()
WT_IMAGE_TOGGLE_BUTTON - add_image_toggle_button()
WT_SWITCH_IMAGE_TOGGLE_BUTTON - add_switch_image_button()
WT_CHECK_BUTTON - add_check_box()
WT_CHECK_BOX - add_check_box()
WT_COMBOBOX - add_combobox()
WT_FILE_DIALOG - open_file_dialog()
WT_KNOB - add_knob()
WT_IMAGE_KNOB - add_image_knob()
WT_LABEL - add_label()
WT_LISTBOX - add_listbox()
WT_LISTBOX_VIEWPORT - create_listbox_viewport()
WT_LISTBOX_ENTRY - listbox_add_entry()
WT_LISTVIEW - add_listview()
WT_LISTVIEW_VIEWPORT - create_listbox_viewport()
WT_MENU - create_menu(), used by WT_COMBOBOX
WT_MENU_VIEWPORT - create_viewport()
WT_MENU_ITEM - menu_add_item()
WT_MENU_CHECK_ITEM - menu_add_check_item()
WT_MENU_RADIO_ITEM - menu_add_radio_item()
WT_MESSAGE_DIALOG - open_message_dialog()
WT_TEXT_ENTRY - create_entry_box(), used by WT_MESSAGE_DIALOG
WT_VMETER - add_vmeter()
WT_VMETER_SCALE - add_vmeter()
WT_HMETER - add_hmeter()
WT_HMETER_SCALE - add_hmeter()
WT_MIDI_KEYBOARD - open_midi_keyboard()
WT_PLAYHEAD - add_playhead()
WT_VSLIDER - add_vslider()
WT_HSLIDER - add_hslider()
WT_TOOLTIP - add_tooltip()
WT_TUNER - add_tuner()
WT_VALUEDISPLAY - add_valuedisplay()
Enumerator
WT_NONE
WT_WINDOW
WT_WIDGET
WT_BUTTON
WT_ON_OFF_BUTTON
WT_TOGGLE_BUTTON
WT_IMAGE_TOGGLE_BUTTON
WT_SWITCH_IMAGE_TOGGLE_BUTTON
WT_CHECK_BUTTON
WT_CHECK_BOX
WT_COMBOBOX
WT_FILE_DIALOG
WT_KNOB
WT_IMAGE_KNOB
WT_LABEL
WT_LISTBOX_VIEWPORT
WT_LISTBOX
WT_LISTBOX_ENTRY
WT_LISTVIEW_VIEWPORT
WT_LISTVIEW
WT_MENU
WT_MENU_VIEWPORT
WT_MENU_ITEM
WT_MENU_CHECK_ITEM
WT_MENU_RADIO_ITEM
WT_MESSAGE_DIALOG
WT_VMETER
WT_VMETER_SCALE
WT_HMETER
WT_HMETER_SCALE
WT_MIDI_KEYBOARD
WT_PLAYHEAD
WT_VSLIDER
WT_HSLIDER
WT_TOOLTIP
WT_TUNER
WT_VALUEDISPLAY
WT_TEXT_ENTRY
Definition at line 191 of file xwidget.h.
             {
    WT_NONE,
    WT_WINDOW,
    WT_WIDGET,
    WT_BUTTON,
    WT_ON_OFF_BUTTON,
    WT_TOGGLE_BUTTON,
    WT_IMAGE_TOGGLE_BUTTON,
    WT_SWITCH_IMAGE_TOGGLE_BUTTON,
    WT_CHECK_BUTTON,
    WT_CHECK_BOX,
    WT_COMBOBOX,
    WT_FILE_DIALOG,
    WT_KNOB,
    WT_IMAGE_KNOB,
    WT_LABEL,
    WT_LISTBOX_VIEWPORT,
    WT_LISTBOX,
    WT_LISTBOX_ENTRY,
    WT_LISTVIEW_VIEWPORT,
    WT_LISTVIEW,
    WT_MENU,
    WT_MENU_VIEWPORT,
    WT_MENU_ITEM,
    WT_MENU_CHECK_ITEM,
    WT_MENU_RADIO_ITEM,
    WT_MESSAGE_DIALOG,
    WT_VMETER,
    WT_VMETER_SCALE,
    WT_HMETER,
    WT_HMETER_SCALE,
    WT_MIDI_KEYBOARD,
    WT_PLAYHEAD,
    WT_VSLIDER,
    WT_HSLIDER,
    WT_TOOLTIP,
    WT_TUNER,
    WT_VALUEDISPLAY,
    WT_TEXT_ENTRY,
} WidgetType;
Function Documentation
connect_func()
void connect_func (void(**)() event, void(*)() handler)
connect_func - connect a event with a handler without type check. For supported events see: Func_t
Parameters
**event - the event to connect
*handler - the handler to handle the event
Returns
void
Definition at line 352 of file xwidget.c.
{
    debug_print("address of a is: %p\n", (void*)event);
    debug_print("address of b is: %p\n", (void*)handler);
    *event = handler;
    debug_print("address of a is: %p\n", (void*)(*event));
}
copy_to_clipboard()
void copy_to_clipboard (Widget_t * w, char * text, int size)
copy_to_clipboard - send textbuffer to clipboard
Parameters
w - the Widget_t to send the event
text - the text buffer to send to clipboard
size - the size of the buffer to send
Returns
void
Definition at line 586 of file xwidget-linux.c.
{
    XSetSelectionOwner (w->app->dpy, w->app->selection, w->widget, 0);
    if (XGetSelectionOwner (w->app->dpy, w->app->selection) != w->widget) return;
    free(w->app->ctext);
    w->app->ctext = NULL;
    w->app->ctext = (unsigned char*)strndup(text, size);
    w->app->csize = size;
}
References Widget_t::app, Xputty::csize, Xputty::ctext, Xputty::dpy, Xputty::selection, and Widget_t::widget.
create_widget()
Widget_t * create_widget (Xputty * app, Widget_t * win, int x, int y, int width, int height)
*create_widget - create a widget
A Widget_t could only be created as child of a other Widget_t
To create a Widget_t you need to create a Widget_t with create_window() before.
Parameters
*app - pointer to the Xputty *main struct to use
*parent - pointer to the Parrent Widget_t
x,y,width,height - the position/geometry to create the widget
Returns
Widget_t* - pointer to the Widget_t struct
Definition at line 265 of file xwidget.c.
{
    Widget_t *w = (Widget_t*)malloc(sizeof(Widget_t));
    assert(w != NULL);
    debug_print("assert(w)\n");
    memset(w, 0, sizeof(Widget_t));
    w->image = NULL;
    w->flags = IS_WIDGET | USE_TRANSPARENCY;
    w->flags &= ~NO_AUTOREPEAT;
    w->flags &= ~FAST_REDRAW;
    w->flags &= ~HIDE_ON_DELETE;
    w->flags &= ~REUSE_IMAGE;
    w->flags &= ~NO_PROPAGATE;
    w->flags &= ~IS_SUBMENU;
    w->flags &= ~DONT_PROPAGATE;
    w->app = app;
    w->parent = parent;
    w->parent_struct = NULL;
    w->private_struct = NULL;
    w->label = NULL;
    memset(w->input_label, 0, 32 * (sizeof w->input_label[0]));
    w->state = 0;
#ifdef __linux__
    w->double_click = 0;
#endif
    w->data = 0;
    w->x = x;
    w->y = y;
    w->width = width;
    w->height = height;
    w->scale.gravity = CENTER;
    w->scale.init_width = width;
    w->scale.init_height = height;
    w->scale.init_x   = x;
    w->scale.init_y   = y;
    w->scale.scale_x  = 0.0;
    w->scale.scale_y  = 0.0;
    w->scale.cscale_x = 1.0;
    w->scale.cscale_y = 1.0;
    w->scale.rcscale_x = 1.0;
    w->scale.rcscale_y = 1.0;
    w->scale.ascale   = 1.0;
    w->adj_x = NULL;
    w->adj_y = NULL;
    w->adj   = NULL;
    w->color_scheme = (XColor_t*)malloc(sizeof(XColor_t));
    memcpy(w->color_scheme, app->color_scheme, sizeof (struct XColor_t));
    w->childlist = (Childlist_t*)malloc(sizeof(Childlist_t));
    assert(w->childlist != NULL);
    childlist_init(w->childlist);
    childlist_add_child(parent->childlist, w);
    w->event_callback = os_widget_event_loop;
    w->func.expose_callback = _dummy_callback;
    w->func.configure_callback = configure_event;
    w->func.button_press_callback = _dummy1_callback;
    w->func.button_release_callback = _dummy1_callback;
    w->func.double_click_callback = _dummy1_callback;
    w->func.motion_callback = _dummy1_callback;
    w->func.adj_callback = os_adjustment_callback;
    w->func.value_changed_callback = _dummy_callback;
    w->func.key_press_callback = _dummy1_callback;
    w->func.key_release_callback = _dummy1_callback;
    w->func.enter_callback = _dummy_callback;
    w->func.leave_callback = _dummy_callback;
    w->func.user_callback = _dummy_callback;
    w->func.mem_free_callback = _dummy_callback;
    w->func.configure_notify_callback = os_transparent_draw;
    w->func.map_notify_callback = _dummy_callback;
    w->func.unmap_notify_callback = _dummy_callback;
    w->func.visibiliy_change_callback = _dummy_callback;
    w->func.dialog_callback = _dummy_callback;
    w->func.dnd_notify_callback = _dummy_callback;
    w->xpaste_callback = _dummy_callback;
    //XMapWindow(app->dpy, w->widget);
    //debug_print("size of Widget_t = %lld\n", sizeof(struct Widget_t));
    os_create_widget_window_and_surface(w, app, parent, x, y, width, height);
    create_cairo_context_and_buffer(w);
#ifdef __linux__ // childlist already set up
    childlist_add_child(app->childlist,w);
#endif
    return w;
}
References _dummy1_callback(), _dummy_callback(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_x, Widget_t::adj_y, Widget_t::app, Resize_t::ascale, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, Xputty::childlist, Widget_t::childlist, childlist_add_child(), childlist_init(), Xputty::color_scheme, Widget_t::color_scheme, Func_t::configure_callback, configure_event(), Func_t::configure_notify_callback, create_cairo_context_and_buffer(), Resize_t::cscale_x, Resize_t::cscale_y, Widget_t::data, Func_t::dialog_callback, Func_t::dnd_notify_callback, Widget_t::double_click, Func_t::double_click_callback, Func_t::enter_callback, Widget_t::event_callback, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, Widget_t::height, Widget_t::image, Resize_t::init_height, Resize_t::init_width, Resize_t::init_x, Resize_t::init_y, Widget_t::input_label, IS_WIDGET, Func_t::key_press_callback, Func_t::key_release_callback, Widget_t::label, Func_t::leave_callback, Func_t::map_notify_callback, Func_t::mem_free_callback, Func_t::motion_callback, os_adjustment_callback(), os_create_widget_window_and_surface(), os_transparent_draw(), os_widget_event_loop(), Widget_t::parent, Widget_t::parent_struct, Widget_t::private_struct, Resize_t::rcscale_x, Resize_t::rcscale_y, Widget_t::scale, Resize_t::scale_x, Resize_t::scale_y, Widget_t::state, Func_t::unmap_notify_callback, USE_TRANSPARENCY, Func_t::user_callback, Func_t::value_changed_callback, Func_t::visibiliy_change_callback, Widget_t::width, Widget_t::x, Widget_t::xpaste_callback, and Widget_t::y.
Referenced by add_button(), add_check_box(), add_check_button(), add_combobox(), add_frame(), add_hmeter(), add_hslider(), add_image(), add_image_button(), add_image_knob(), add_image_toggle_button(), add_knob(), add_label(), add_listbox(), add_listview(), add_menu(), add_menubar(), add_midi_keyboard(), add_multi_listview(), add_on_off_button(), add_playhead(), add_popup_spinbox(), add_switch_image_button(), add_tabbox(), add_toggle_button(), add_tuner(), add_valuedisplay(), add_vmeter(), add_vslider(), add_waveview(), cmenu_add_submenu(), create_combobox_viewport(), create_hyperlink(), create_listbox_viewport(), create_listview_viewport(), create_multi_listview_viewport(), create_viewport(), listbox_add_entry(), menu_add_item(), menu_add_numeric_items(), menu_add_submenu(), menu_add_value_entry(), save_file_dialog(), and tabbox_add_tab().
create_window()
Widget_t * create_window (Xputty * app, Window win, int x, int y, int width, int height)
*create_window - create a Window
You need to create as least minimun one Window to get started.
The first created Window is the top_level_widget()
A Window could be created on the DefaultRootWindow() or embeded into a other XWindow
Parameters
*app - pointer to the Xputty *main struct to use
win - pointer to the Parrent Window (may be Root)
x,y,width,height - the position/geometry to create the window
Returns
Widget_t * - pointer to the Widget_t struct
Definition at line 163 of file xwidget.c.
{
    Widget_t *w = (Widget_t*)malloc(sizeof(Widget_t));
    assert(w != NULL);
    debug_print("assert(w)\n");
    memset(w, 0, sizeof(Widget_t));
    w->image = NULL;
    w->flags = IS_WINDOW;
    w->flags &= ~NO_AUTOREPEAT;
    w->flags &= ~FAST_REDRAW;
    w->flags &= ~HIDE_ON_DELETE;
    w->flags &= ~REUSE_IMAGE;
    w->flags &= ~NO_PROPAGATE;
    w->flags &= ~IS_SUBMENU;
    w->flags &= ~DONT_PROPAGATE;
    w->app = app;
    w->parent = &win;
    w->parent_struct = NULL;
    w->private_struct = NULL;
    w->label = NULL;
    memset(w->input_label, 0, 32 * (sizeof w->input_label[0]));
    w->state = 0;
#ifdef __linux__
    w->double_click = 0;
#endif
    w->data = 0;
    w->x = x;
    w->y = y;
    w->width = width;
    w->height = height;
    w->scale.init_x = x;
    w->scale.init_y = y;
    w->scale.init_width = width;
    w->scale.init_height = height;
    w->scale.scale_x  = 0.0;
    w->scale.scale_y  = 0.0;
    w->scale.cscale_x = 1.0;
    w->scale.cscale_y = 1.0;
    w->scale.rcscale_x = 1.0;
    w->scale.rcscale_y = 1.0;
    w->scale.ascale   = 1.0;
    w->scale.gravity  = CENTER;
    w->adj_x = NULL;
    w->adj_y = NULL;
    w->adj   = NULL;
    w->color_scheme = (XColor_t*)malloc(sizeof(XColor_t));
    memcpy(w->color_scheme, app->color_scheme, sizeof (struct XColor_t));
    w->childlist = (Childlist_t*)malloc(sizeof(Childlist_t));
    assert(w->childlist != NULL);
    childlist_init(w->childlist);
    w->event_callback = widget_event_loop;
    w->func.expose_callback = _dummy_callback;
    w->func.configure_callback = configure_event;
    w->func.button_press_callback = _dummy1_callback;
    w->func.button_release_callback = _dummy1_callback;
    w->func.double_click_callback = _dummy1_callback;
    w->func.motion_callback = _dummy1_callback;
    w->func.adj_callback = os_adjustment_callback;
    w->func.value_changed_callback = _dummy_callback;
    w->func.key_press_callback = _dummy1_callback;
    w->func.key_release_callback = _dummy1_callback;
    w->func.enter_callback = _dummy_callback;
    w->func.leave_callback = _dummy_callback;
    w->func.user_callback = _dummy_callback;
    w->func.mem_free_callback = _dummy_callback;
    w->func.configure_notify_callback = _dummy_callback;
    w->func.map_notify_callback = _dummy_callback;
    w->func.unmap_notify_callback = _dummy_callback;
    w->func.visibiliy_change_callback = _dummy_callback;
    w->func.dialog_callback = _dummy_callback;
    w->func.dnd_notify_callback = _dummy_callback;
    w->xpaste_callback = _dummy_callback;
    //XMapWindow(app->dpy, w->widget);
    //debug_print("size of Func_t = %llu\n", sizeof(w->func)/sizeof(void*));
    os_create_main_window_and_surface(w, app, win, x, y, width, height);
    create_cairo_context_and_buffer(w);
#ifdef __linux__ // childlist already set up
    childlist_add_child(app->childlist,w);
#endif
    return w;
}
References _dummy1_callback(), _dummy_callback(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_x, Widget_t::adj_y, Widget_t::app, Resize_t::ascale, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, Xputty::childlist, Widget_t::childlist, childlist_add_child(), childlist_init(), Xputty::color_scheme, Widget_t::color_scheme, Func_t::configure_callback, configure_event(), Func_t::configure_notify_callback, create_cairo_context_and_buffer(), Resize_t::cscale_x, Resize_t::cscale_y, Widget_t::data, Func_t::dialog_callback, Func_t::dnd_notify_callback, Widget_t::double_click, Func_t::double_click_callback, Func_t::enter_callback, Widget_t::event_callback, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, Widget_t::height, Widget_t::image, Resize_t::init_height, Resize_t::init_width, Resize_t::init_x, Resize_t::init_y, Widget_t::input_label, IS_WINDOW, Func_t::key_press_callback, Func_t::key_release_callback, Widget_t::label, Func_t::leave_callback, Func_t::map_notify_callback, Func_t::mem_free_callback, Func_t::motion_callback, os_adjustment_callback(), os_create_main_window_and_surface(), Widget_t::parent, Widget_t::parent_struct, Widget_t::private_struct, Resize_t::rcscale_x, Resize_t::rcscale_y, Widget_t::scale, Resize_t::scale_x, Resize_t::scale_y, Widget_t::state, Func_t::unmap_notify_callback, Func_t::user_callback, Func_t::value_changed_callback, Func_t::visibiliy_change_callback, widget_event_loop(), Widget_t::width, Widget_t::x, Widget_t::xpaste_callback, and Widget_t::y.
Referenced by add_popup_spinbox(), create_combobox_menu(), create_menu(), create_tooltip(), mk_open_midi_keyboard(), open_directory_dialog(), open_file_dialog(), open_message_dialog(), open_midi_keyboard(), and save_file_dialog().
destroy_widget()
void destroy_widget (Widget_t * w, Xputty * main)
destroy_widget - destroy a widget
When a Widget_t receive a destroy_widget() call, it will propagate that to all childs in it's Childlist_t. So all childs get destroyed before the Widget_t itself close.
Parameters
*w - pointer to the Widget_t sending the request
*main - pointer to main struct
Returns
void
Definition at line 86 of file xwidget.c.
{
    int count = childlist_find_child(main->childlist, w);
    if (count == 0 && main->run == true) {
        quit(w);
    } else if(childlist_find_child(main->childlist, w)>=0) {
        if(w->flags & REUSE_IMAGE) {
            w->image = NULL;
        }
        if(w->flags & HAS_MEM) {
            w->func.mem_free_callback(w, NULL);
        }
        childlist_remove_child(main->childlist, w);
        int ch = childlist_has_child(w->childlist);
        if (ch) {
            int i = ch;
            for(;i>0;i--) {
                destroy_widget(w->childlist->childs[i-1],main);
            }
            destroy_widget(w,main);
        }
        if(w->flags & IS_WIDGET) {
            Widget_t *p = (Widget_t *) w->parent;
            childlist_remove_child(p->childlist, w);
        }
        delete_adjustment(w->adj_x);
        delete_adjustment(w->adj_y);
        childlist_destroy(w->childlist);
        cairo_surface_destroy(w->image);
        cairo_destroy(w->crb);
        cairo_surface_destroy(w->buffer);
        cairo_destroy(w->cr);
        cairo_surface_destroy(w->surface);
        os_destroy_window(w);
        free(w->color_scheme);
        free(w->childlist);
        free(w);
        w = NULL;
    }
}
References Widget_t::adj_x, Widget_t::adj_y, Widget_t::buffer, Xputty::childlist, Widget_t::childlist, childlist_destroy(), childlist_find_child(), childlist_has_child(), childlist_remove_child(), Childlist_t::childs, Widget_t::color_scheme, Widget_t::cr, Widget_t::crb, delete_adjustment(), destroy_widget(), Widget_t::flags, Widget_t::func, HAS_MEM, Widget_t::image, IS_WIDGET, Func_t::mem_free_callback, os_destroy_window(), Widget_t::parent, quit(), REUSE_IMAGE, Xputty::run, and Widget_t::surface.
Referenced by destroy_widget(), main_quit(), menu_remove_item(), os_main_run(), os_run_embedded(), os_widget_event_loop(), tabbox_remove_tab(), and WndProc().
expose_widget()
void expose_widget (Widget_t * w)
expose_widgets - send a expose event (EXPOSE) to a Widget_t
Parameters
w - the Widget_t to send the event to
Returns
void
Definition at line 445 of file xwidget.c.
{
    os_expose_widget(w);
}
References os_expose_widget().
Referenced by _buttons_released(), _combobox_motion(), _knob_released(), _leave_combobox(), _leave_list(), _leave_multi_list(), _listbox_entry_released(), _propagate_child_expose(), _set_combobox_menu_viewport(), _set_combobox_viewpoint(), _set_listview_viewpoint(), _set_listviewport(), _set_multi_listview_viewpoint(), _set_multi_listviewport(), _slider_released(), _tab_button_released(), _toggle_button_pressed(), _toggle_button_released(), _value_item_released(), multi_listview_set_item_size(), and update_waveview().
get_toplevel_widget()
Widget_t * get_toplevel_widget (Xputty * main)
*get_toplevel_widget - get pointer to the top level Widget_t
Parameters
*main - pointer to the main Xputty struct
Returns
void
Definition at line 441 of file xwidget.c.
{
    return  main->childlist->childs[0];
}
References Xputty::childlist, and Childlist_t::childs.
Referenced by os_quit().
handle_dnd_enter()
void handle_dnd_enter (Xputty * main, XEvent * event)
handle_drag_enter - handle drag event enter the Widget_t
Parameters
main - pointer to the Xputty *main struct running
event - the drag event contain the drop data
Returns
void
Definition at line 481 of file xwidget-linux.c.
{
    main->dnd_source_window = DND_SOURCE_WIN(event);
    main->dnd_version = 0;
    if (DND_STATUS_ACCEPT(event)) {
        main->dnd_version = DND_VERSION(event);
        if (main->dnd_version > 5) return;
        Atom type = 0;
        int format;
        unsigned long count, remaining;
        unsigned char *data = 0;
        XGetWindowProperty (main->dpy, main->dnd_source_window, main->XdndTypeList,
            0, 0x8000000L, False, XA_ATOM, &type, &format, &count, &remaining, &data);
        if (!data || type != XA_ATOM || format != 32) {
            if (data) {
                XFree (data);
            }
            return;
        }
        Atom* types = (Atom*)data;
        for (unsigned long l = 1; l < count; l++) {
            if ((types[l] == main->dnd_type_uri) ||
                (types[l] == main->dnd_type_text) ||
                (types[l] == main->dnd_type_utf8)) {
                main->dnd_type = types[l];
                break;
            }
        }
        if (data) {
            XFree (data);
        }
    } else {
        for (int i = 2; i < 5; ++i) {
            if ((event->xclient.data.l[i] == main->dnd_type_uri) ||
                (event->xclient.data.l[i] == main->dnd_type_text) ||
                (event->xclient.data.l[i] == main->dnd_type_utf8)) {
                main->dnd_type = event->xclient.data.l[i];
                break;
            }
        }
    }
}
References Xputty::dnd_source_window, Xputty::dnd_type, Xputty::dnd_type_text, Xputty::dnd_type_uri, Xputty::dnd_type_utf8, Xputty::dnd_version, Xputty::dpy, and Xputty::XdndTypeList.
Referenced by os_widget_event_loop().
handle_drag_data()
void handle_drag_data (Widget_t * w, XEvent * event)
handle_drag_data - handle recived drag data
Parameters
w - the Widget_t recive the event
event - the drag event contain the drop data
Returns
void
Definition at line 455 of file xwidget-linux.c.
{
    if (event->xselection.property != w->app->XdndSelection) return;
    Atom type;
    int format;
    unsigned long  count = 0, remaining;
    unsigned char* data = 0;
    XGetWindowProperty(w->app->dpy,w->widget, event->xselection.property,
                        0, 65536, True, w->app->dnd_type, &type, &format,
                        &count, &remaining, &data);
    send_dnd_finished_event (w, event);
    if (!data || count == 0) {
        return;
    }
    char* dndfile = (char*)data;
    strdecode(dndfile, "%20", " ");
    strremove(dndfile, "file://");
    w->func.dnd_notify_callback(w, (void*)&dndfile);
    w->app->dnd_type = None;
    w->app->dnd_source_window = 0;
    free(data);
}
References Widget_t::app, Func_t::dnd_notify_callback, Xputty::dnd_source_window, Xputty::dnd_type, Xputty::dpy, Widget_t::func, send_dnd_finished_event(), strdecode(), strremove(), Widget_t::widget, and Xputty::XdndSelection.
Referenced by os_widget_event_loop().
have_paste()
int have_paste (Widget_t * w)
have_paste - check if clipboard contain a textbuffer
Parameters
w - the Widget_t to send the request
Returns
void
Definition at line 557 of file xwidget-linux.c.
{
    return XGetSelectionOwner(w->app->dpy,w->app->selection);
}
References Widget_t::app, Xputty::dpy, and Xputty::selection.
hide_tooltip()
void hide_tooltip (Widget_t * wid)
hide_tooltip - check if a Widget_t have a tooltip, and hide it, if a tooltip is mapped.
Parameters
*wid - pointer to the Widget_t receiving the event
Returns
void
Definition at line 430 of file xwidget.c.
{
    int i = 0;
    for(;i<wid->childlist->elem;i++) {
        Widget_t *w = wid->childlist->childs[i];
        if (w->flags & IS_TOOLTIP) {
            widget_hide(w);
            break;
        }
    }
}
References Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_TOOLTIP, and widget_hide().
Referenced by _draw_combobox_entrys(), _draw_list(), _draw_multi_list(), _list_motion(), _multi_list_motion(), _update_list_view(), _update_view(), os_widget_event_loop(), and WndProc().
key_mapping()
int key_mapping (Display * dpy, XKeyEvent * xkey)
_key_mapping - modifier key's mapped to a integer value
Parameters
*dpy - pointer to the Display in use
*xkey - the key to map
Returns
int - value (1-10) or 0 when not mapped
Definition at line 37 of file xwidget.c.
{
    if (xkey->keycode == XKeysymToKeycode(dpy,XK_Tab))
        return (xkey->state & ShiftMask) ? 1 : 2;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Up))
        return 3;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Right))
        return 4;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Down))
        return 5;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Left))
        return 6;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Home))
        return 7;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Insert))
        return 8;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_End))
        return 9;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Return))
        return 10;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_BackSpace))
        return 11;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Delete))
        return 12;
    // keypad
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Subtract))
        return 1;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Add))
        return 2;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Up))
        return 3;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Right))
        return 4;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Down))
        return 5;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Left))
        return 6;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Home))
        return 7;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Insert))
        return 8;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_End))
        return 9;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Enter))
        return 10;
    else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Delete))
        return 12;
    else return 0;
}
References XEvent::keycode, and XEvent::state.
Referenced by _check_keymap(), _combobox_key_pressed(), _list_key_pressed(), and _multi_list_key_pressed().
pop_widget_show_all()
void pop_widget_show_all (Widget_t * w)
pop_widget_show_all - map/show popup widget with all it's childs
Parameters
*w - pointer to the Widget_t to map
Returns
void
Definition at line 400 of file xwidget.c.
{
    if (w->flags & IS_SUBMENU) return;
    w->func.map_notify_callback(w, NULL);
    os_widget_show(w);
    int i=0;
    for(;i<w->childlist->elem;i++) {
            pop_widget_show_all(w->childlist->childs[i]);
    }
}
References Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, Widget_t::func, IS_SUBMENU, Func_t::map_notify_callback, os_widget_show(), and pop_widget_show_all().
Referenced by _popup_spinbox(), pop_combobox_menu_show(), pop_menu_show(), and pop_widget_show_all().
quit()
void quit (Widget_t * w)
quit - exit the main loop
Parameters
*w - pointer to the Widget_t sending the request
Returns
void
Definition at line 526 of file xwidget.c.
                       {
    os_quit(w);
}
References os_quit().
Referenced by destroy_widget().
quit_widget()
void quit_widget (Widget_t * w)
quit_widget - remove a widget from the processing loop
Parameters
*w - pointer to the Widget_t sending the request
Returns
void
Definition at line 530 of file xwidget.c.
{
    os_quit(w);
}
References os_quit().
Referenced by os_widget_event_loop(), and WndProc().
receive_paste_from_clipboard()
void receive_paste_from_clipboard (Widget_t * w, XEvent * event)
receive_paste_from_clipboard - receive textbuffer from clipboard
Parameters
w - the Widget_t which requested the buffer
event - the event contain the request
Returns
void
Definition at line 566 of file xwidget-linux.c.
{
    if(event->xselection.property) {
        Atom target;
        char * data = NULL;
        int format;
        unsigned long N, size;
        XGetWindowProperty(event->xselection.display, event->xselection.requestor,
            event->xselection.property, 0L,(~0L), 0, AnyPropertyType, &target,
            &format, &size, &N,(unsigned char**)&data);
        if(target == w->app->UTF8 || target == XA_STRING) {
            free(w->app->ctext);
            w->app->ctext = NULL;
            w->app->ctext = (unsigned char*)strndup(data, size);
            XFree(data);
        }
        XDeleteProperty(event->xselection.display, event->xselection.requestor, event->xselection.property);
        w->xpaste_callback(w, (void*)&w->app->ctext);
    }
}
References Widget_t::app, Xputty::ctext, Xputty::UTF8, and Widget_t::xpaste_callback.
Referenced by os_widget_event_loop().
request_paste_from_clipboard()
void request_paste_from_clipboard (Widget_t * w)
request_paste_from_clipboard - request textbuffer from clipboard
Parameters
w - the Widget_t to send the request
Returns
void
Definition at line 561 of file xwidget-linux.c.
{
    Atom XSEL_DATA = XInternAtom(w->app->dpy, "XSEL_DATA", 0);
    XConvertSelection(w->app->dpy, w->app->selection, w->app->UTF8, XSEL_DATA, w->widget, CurrentTime);
}
References Widget_t::app, Xputty::dpy, Xputty::selection, Xputty::UTF8, and Widget_t::widget.
resize_childs()
void resize_childs (Widget_t * wid)
resize_childs - intern check if child widgets needs resizing
Parameters
*wid - pointer to the Widget_t receive the event
Returns
void
Definition at line 151 of file xwidget.c.
{
    _resize_childs(w);
}
References _resize_childs().
send_button_press_event()
void send_button_press_event (Widget_t * w)
send_button_press_event - send ButtonPress event to Widget_t
simulate a BUTTON_PRESS Event
Parameters
*w - pointer to the Widget_t to send the notify
Returns
void
Definition at line 514 of file xwidget.c.
{
    os_send_button_press_event(w);
}
References os_send_button_press_event().
Referenced by _check_keymap().
send_button_release_event()
void send_button_release_event (Widget_t * w)
send_button_release_event - send ButtonRelease event to Widget_t
simulate a BUTTON_RELEASE Event
Parameters
*w - pointer to the Widget_t to send the notify
Returns
void
Definition at line 518 of file xwidget.c.
{
    os_send_button_release_event(w);
}
References os_send_button_release_event().
Referenced by _check_keymap().
send_configure_event()
void send_configure_event (Widget_t * w, int x, int y, int width, int height)
send_configure_event - send a ConfigureNotify to Widget_t
used to resize a Widget_t
Parameters
*w - pointer to the Widget_t to send the notify
x,y - the new Widget_t position
width,height - the new Widget_t size
Returns
void
Definition at line 510 of file xwidget.c.
{
    os_send_configure_event(w, x, y, width, height);
}
References os_send_configure_event().
send_dnd_finished_event()
void send_dnd_finished_event (Widget_t * w, XEvent * event)
send_dnd_finished_event - notify the drag sender that the event is handled
Parameters
w - the Widget_t handled the event
event - the drag event contain the drop data
Returns
void
Definition at line 540 of file xwidget-linux.c.
{
    if (w->app->dnd_version < 2) {
        return;
    }
    XEvent xev;
    memset (&xev, 0, sizeof (XEvent));
    xev.xany.type            = ClientMessage;
    xev.xany.display         = w->app->dpy;
    xev.xclient.window       = w->app->dnd_source_window;
    xev.xclient.message_type = w->app->XdndFinished;
    xev.xclient.format       = 32;
    xev.xclient.data.l[0]    = event->xany.window;
    xev.xclient.data.l[1]    = 1;
    xev.xclient.data.l[2]    = w->app->XdndActionCopy;
    XSendEvent (w->app->dpy, w->app->dnd_source_window, False, NoEventMask, &xev);
}
References Widget_t::app, Xputty::dnd_source_window, Xputty::dnd_version, Xputty::dpy, XEvent::window, Xputty::XdndActionCopy, and Xputty::XdndFinished.
Referenced by handle_drag_data(), and os_widget_event_loop().
send_dnd_status_event()
void send_dnd_status_event (Widget_t * w, XEvent * event)
send_dnd_status_event - notify the drag sender that prepared to recive the event
Parameters
w - the Widget_t to recive the event
event - the drag event contain the drop data
Returns
void
Definition at line 524 of file xwidget-linux.c.
{
    XEvent xev;
    memset (&xev, 0, sizeof (XEvent));
    xev.xany.type            = ClientMessage;
    xev.xany.display         = w->app->dpy;
    xev.xclient.window       = w->app->dnd_source_window;
    xev.xclient.message_type = w->app->XdndStatus;
    xev.xclient.format       = 32;
    xev.xclient.data.l[0]    = event->xany.window;
    xev.xclient.data.l[1]    = (w->app->dnd_type != None) ? 1 : 0;
    xev.xclient.data.l[2]    = DND_DROP_TIME(event);
    xev.xclient.data.l[3]    = 0;
    xev.xclient.data.l[4]    = w->app->XdndActionCopy;
    XSendEvent (w->app->dpy, w->app->dnd_source_window, False, NoEventMask, &xev);
}
References Widget_t::app, Xputty::dnd_source_window, Xputty::dnd_type, Xputty::dpy, XEvent::window, Xputty::XdndActionCopy, and Xputty::XdndStatus.
Referenced by os_widget_event_loop().
send_systray_message()
void send_systray_message (Widget_t * w)
send_systray_message - request a systray icon for Widget_t
currently not working
Parameters
*w - pointer to the Widget_t to send the notify
Returns
void
Definition at line 522 of file xwidget.c.
{
    os_send_systray_message(w);
}
References os_send_systray_message().
send_to_clipboard()
void send_to_clipboard (Widget_t * w, XEvent * event)
send_to_clipboard - send textbuffer to clipboard on request
Parameters
w - the Widget_t to send the event
event - the event contain the request
Returns
void
Definition at line 595 of file xwidget-linux.c.
{
    XSelectionRequestEvent * xsr = &event->xselectionrequest;
    XSelectionEvent xev;
    memset (&xev, 0, sizeof (XSelectionEvent));
    int R = 0;
    xev.type = SelectionNotify;
    xev.display = xsr->display;
    xev.requestor = xsr->requestor;
    xev.selection = xsr->selection;
    xev.time = xsr->time;
    xev.target = xsr->target;
    xev.property = xsr->property;
    if (xev.target == w->app->targets_atom) {
        R = XChangeProperty (xev.display, xev.requestor, xev.property, XA_ATOM, 32,
            PropModeReplace, (unsigned char*)&w->app->UTF8, 1);
    } else if (xev.target == XA_STRING || xev.target == w->app->text_atom) {
        R = XChangeProperty(xev.display, xev.requestor, xev.property, XA_STRING, 8,
            PropModeReplace, w->app->ctext, w->app->csize);
    } else if (xev.target == w->app->UTF8) {
        R = XChangeProperty(xev.display, xev.requestor, xev.property, w->app->UTF8, 8,
            PropModeReplace, w->app->ctext, w->app->csize);
    } else {
        xev.property = None;
    }
    if ((R & 2) == 0) XSendEvent (w->app->dpy, xev.requestor, 0, 0, (XEvent *)&xev);
    debug_print("send to clipboard %s\n", w->app->ctext);
}
References Widget_t::app, Xputty::csize, Xputty::ctext, Xputty::dpy, Xputty::targets_atom, Xputty::text_atom, and Xputty::UTF8.
Referenced by os_widget_event_loop().
show_tooltip()
void show_tooltip (Widget_t * wid)
show_tooltip - check if a Widget_t have a tooltip, and show it, if a tooltip is available.
Parameters
*wid - pointer to the Widget_t receiving the event
Returns
void
Definition at line 419 of file xwidget.c.
{
    int i = 0;
    for(;i<wid->childlist->elem;i++) {
        Widget_t *w = wid->childlist->childs[i];
        if (w->flags & IS_TOOLTIP) {
            os_show_tooltip(wid, w);
            break;
        }
    }
}
References Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_TOOLTIP, and os_show_tooltip().
Referenced by _draw_combobox_entrys(), _draw_list(), _draw_multi_list(), _update_list_view(), _update_view(), os_widget_event_loop(), and WndProc().
strdecode()
void strdecode (char * target, const char * needle, const char * replacement)
strdecode - replace string in char*
Parameters
*target - the string to modify
*needle - the string to replace
*replacement - the replacement for the needle
Returns
void
Definition at line 432 of file xwidget-linux.c.
{
    char buffer[1024] = { 0 };
    char *insert_point = &buffer[0];
    const char *tmp = target;
    size_t needle_len = strlen(needle);
    size_t repl_len = strlen(replacement);
    while (1) {
        const char *p = strstr(tmp, needle);
        if (p == NULL) {
            strcpy(insert_point, tmp);
            break;
        }
        memcpy(insert_point, tmp, p - tmp);
        insert_point += p - tmp;
        memcpy(insert_point, replacement, repl_len);
        insert_point += repl_len;
        tmp = p + needle_len;
    }
    strcpy(target, buffer);
}
Referenced by handle_drag_data().
submenu_widget_show_all()
void submenu_widget_show_all (Widget_t * w)
submenu_widget_show_all - map/show submenu Widget_t with all childs
Parameters
*w - pointer to the Widget_t to map
Returns
void
Definition at line 410 of file xwidget.c.
{
    w->func.map_notify_callback(w, NULL);
    os_widget_show(w);
    int i=0;
    for(;i<w->childlist->elem;i++) {
            submenu_widget_show_all(w->childlist->childs[i]);
    }
}
References Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::func, Func_t::map_notify_callback, os_widget_show(), and submenu_widget_show_all().
Referenced by pop_submenu_show(), and submenu_widget_show_all().
transparent_draw()
void transparent_draw (void * wid, void * user_data)
transparent_draw - copy parent surface to child surface
you usaualy didn't need to call this, it's used automaticaly when a Widget_t have set the flag USE_TRANSPARENCY
this is the default setting for Widget_t
Parameters
*wid - pointer to the Widget_t receiving the event
*user_data - void pointer to attached user_data
Returns
void
Definition at line 449 of file xwidget.c.
{
    Widget_t *wid = (Widget_t*)w_;
    Metrics_t m;
    os_get_window_metrics(wid, &m);
    if (!m.visible) return;
    cairo_push_group (wid->cr);
    if (wid->flags & USE_TRANSPARENCY) {
        Widget_t *parent = (Widget_t*)wid->parent;
        debug_print("Widget_t _transparency \n");
        cairo_set_source_surface (wid->crb, parent->buffer, -m.x, -m.y);
        cairo_paint (wid->crb);
    }
    cairo_push_group (wid->crb);
    wid->func.expose_callback(wid, user_data);
    cairo_pop_group_to_source (wid->crb);
    cairo_paint (wid->crb);
    cairo_set_source_surface (wid->cr, wid->buffer,0,0);
    cairo_paint (wid->cr);
    cairo_pop_group_to_source (wid->cr);
    cairo_paint (wid->cr);
    if ( wid->flags & DONT_PROPAGATE) return;
    _propagate_child_expose(wid);
}
References _propagate_child_expose(), Widget_t::buffer, Widget_t::cr, Widget_t::crb, DONT_PROPAGATE, Func_t::expose_callback, Widget_t::flags, Widget_t::func, os_get_window_metrics(), Widget_t::parent, USE_TRANSPARENCY, Metrics_t::visible, Metrics_t::x, and Metrics_t::y.
Referenced by _propagate_child_expose(), create_hyperlink(), onPaint(), os_adjustment_callback(), os_transparent_draw(), and os_widget_event_loop().
widget_draw()
void widget_draw (void * w_, void * user_data)
widget_draw - redraw only the widget,not the child widgets
Parameters
*wid - pointer to the Widget_t receiving the event
*user_data - void pointer to attached user_data
Returns
void
Definition at line 479 of file xwidget.c.
{
    Widget_t *wid = (Widget_t*)w_;
    cairo_push_group (wid->cr);
    if (wid->flags & USE_TRANSPARENCY) {
        Widget_t *parent = (Widget_t*)wid->parent;
        Metrics_t m;
        os_get_window_metrics(wid, &m);
        debug_print("Widget_t draw widget \n");
        cairo_set_source_surface (wid->crb, parent->buffer, -m.x, -m.y);
        cairo_paint (wid->crb);
    }
    cairo_push_group (wid->crb);
    wid->func.expose_callback(wid, user_data);
    cairo_pop_group_to_source (wid->crb);
    cairo_paint (wid->crb);
    cairo_set_source_surface (wid->cr, wid->buffer,0,0);
    cairo_paint (wid->cr);
    cairo_pop_group_to_source (wid->cr);
    cairo_paint (wid->cr);
}
References Widget_t::buffer, Widget_t::cr, Widget_t::crb, Func_t::expose_callback, Widget_t::flags, Widget_t::func, os_get_window_metrics(), Widget_t::parent, USE_TRANSPARENCY, Metrics_t::x, and Metrics_t::y.
widget_event_loop()
void widget_event_loop (void * w_, void * event, Xputty * main, void * user_data)
widget_event_loop - the internal widget event loop
Parameters
*w - void pointer to the Widget_t receiving the event
*event - void pointer to the XEvent
*main - void pointer to the Xputty *main struct running the event loop
*user_data - void pointer to attached user_data
Returns
void
Definition at line 506 of file xwidget.c.
{
    os_widget_event_loop(w_, event, main, user_data);
}
References os_widget_event_loop().
Referenced by create_window().
widget_hide()
void widget_hide (Widget_t * w)
widget_hide - unmap/hide a Widget_t
Parameters
*w - pointer to the Widget_t to unmap
Returns
void
Definition at line 368 of file xwidget.c.
{
    int i=0;
    for(;i<w->childlist->elem;i++) {
        widget_hide(w->childlist->childs[i]);
    }
    w->func.unmap_notify_callback(w, NULL);
    os_widget_hide(w);
}
References Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::func, os_widget_hide(), Func_t::unmap_notify_callback, and widget_hide().
Referenced by _check_grab(), _check_menu_state(), _check_submenu(), _draw_tabbox(), _enter_submenu(), _hide_all_tooltips(), _leave_submenu(), hide_tooltip(), os_main_run(), os_run_embedded(), pop_menu_show(), widget_hide(), widget_hide_all(), and WndProc().
widget_hide_all()
void widget_hide_all (Widget_t * w)
widget_hide_all - unmap/hide all Widget_t from app
Parameters
*w - pointer to the Widget_t which send the unmap request
Returns
void
Definition at line 377 of file xwidget.c.
{
    int i=0;
    for(;i<w->app->childlist->elem;i++) {
        widget_hide(w->app->childlist->childs[i]);
    }
    w->func.unmap_notify_callback(w, NULL);
    os_widget_hide(w);
}
References Widget_t::app, Xputty::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::func, os_widget_hide(), Func_t::unmap_notify_callback, and widget_hide().
widget_reset_scale()
void widget_reset_scale (Widget_t * w)
widget_reset_scale - used to reset scaling mode after a image surface is drawn to the Widget_t surface with widget_set_scale()
Parameters
*w - pointer to the Widget_t sending the request
Returns
void
Definition at line 155 of file xwidget.c.
{
    cairo_scale(w->crb, w->scale.cscale_x,w->scale.cscale_y);
}
References Widget_t::crb, Resize_t::cscale_x, Resize_t::cscale_y, and Widget_t::scale.
Referenced by _draw_playhead().
widget_set_dnd_aware()
void widget_set_dnd_aware (Widget_t * w)
widget_set_dnd_aware - allow drag and drop for on Widget_t
Parameters
w - the Widget_t to send the event to
Returns
void
Definition at line 409 of file xwidget-linux.c.
{
    Atom dnd_version = 5;
    XChangeProperty (w->app->dpy, w->widget, w->app->XdndAware, XA_ATOM,
                    32, PropModeReplace, (unsigned char*)&dnd_version, 1);
}
References Widget_t::app, Xputty::dpy, Widget_t::widget, and Xputty::XdndAware.
widget_set_dnd_unaware()
void widget_set_dnd_unaware (Widget_t * w)
widget_set_dnd_unaware - disable drag and drop for on Widget_t
Parameters
w - the Widget_t to send the event to
Returns
void
Definition at line 415 of file xwidget-linux.c.
{
    XDeleteProperty(w->app->dpy, w->widget, w->app->XdndAware);
}
References Widget_t::app, Xputty::dpy, Widget_t::widget, and Xputty::XdndAware.
widget_set_scale()
void widget_set_scale (Widget_t * w)
widget_set_scale - set scaling mode to scale a image surface to the size of the Widget_t surface
Parameters
*w - pointer to the Widget_t sending the request
Returns
void
Definition at line 159 of file xwidget.c.
{
    cairo_scale(w->crb, w->scale.rcscale_x,w->scale.rcscale_y);
}
References Widget_t::crb, Resize_t::rcscale_x, Resize_t::rcscale_y, and Widget_t::scale.
Referenced by _draw_playhead().
widget_set_title()
void widget_set_title (Widget_t * w, const char * title)
widget_set_title - set window title for a Widget_t
Parameters
*w - pointer to the Widget_t to set the title
*title - the title to store
Returns
void
Definition at line 359 of file xwidget.c.
{
    os_set_title(w, title);
}
References os_set_title().
Referenced by mk_open_midi_keyboard(), open_directory_dialog(), open_file_dialog(), open_message_dialog(), and save_file_dialog().
widget_show()
void widget_show (Widget_t * w)
widget_show - map/show widget
Parameters
*w - pointer to the Widget_t to map
Returns
void
Definition at line 363 of file xwidget.c.
{
    w->func.map_notify_callback(w, NULL);
    os_widget_show(w);
}
References Widget_t::func, Func_t::map_notify_callback, and os_widget_show().
widget_show_all()
void widget_show_all (Widget_t * w)
widget_show_all - map/show Widget_t with all childs
Parameters
*w - pointer to the Widget_t to map
Returns
void
Definition at line 386 of file xwidget.c.
{
    if (w->flags & IS_POPUP || w->flags & IS_TOOLTIP ||
        w->flags & IS_SUBMENU) {
        return;
    } else {
        w->func.map_notify_callback(w, NULL);
        os_widget_show(w);
        int i=0;
        for(;i<w->childlist->elem;i++) {
            widget_show_all(w->childlist->childs[i]);
        }
    }
}
References Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, Widget_t::func, IS_POPUP, IS_SUBMENU, IS_TOOLTIP, Func_t::map_notify_callback, os_widget_show(), and widget_show_all().
Referenced by _draw_tabbox(), open_directory_dialog(), open_file_dialog(), open_message_dialog(), save_file_dialog(), and widget_show_all().
widget_type_name()
const char * widget_type_name (Widget_t * w)
widget_type_name - textual representation of (Widget_t*)->widget_type
Parameters
w - the Widget_t* to query (NULL is allowed)
Returns
const char* - zero terminated string; must not be free()d
Definition at line 27 of file xwidget.c.
{
  if (!w)
    return widget_type_names[0]; // "WT_NONE"
  else if (w->widget_type >= XPUTTY_WIDGET_NAME_COUNT)
    return widget_type_names[XPUTTY_WIDGET_NAME_COUNT]; // "UNKNOWN"
  else
    return widget_type_names[w->widget_type];
}
References Widget_t::widget_type.