libxputty: xputty/xwidget-mswin.c File Reference
xwidget-mswin.c File Reference
Functions
void SetClientSize (HWND hwnd, int clientWidth, int clientHeight)
BOOL SetMouseTracking (HWND hwnd, BOOL enable)
LRESULT CALLBACK WndProc (HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
LRESULT onPaint (HWND hwnd, WPARAM wParam, LPARAM lParam)
void debug_lasterror (const char *prefix, const char *prefix2)
char * convert_cp (DWORD cp_from, DWORD cp_to, char *s_from)
char * utf8_from_locale (char *localestr)
utf8_from_locale - convert active codepage to utf8 must be freed by the caller
char * locale_from_utf8 (char *utf8str)
locale_from_utf8 - convert utf8 to active codepage must be freed by the caller
Display * os_open_display (char *display_name)
os_open_display - Connect to the display to use
void os_close_display (Display *dpy)
os_close_display - Close connection to the used display
void os_destroy_window (Widget_t *w)
os_destroy_window - destroy a widget (close and remove from processing)
Window os_get_root_window (Xputty *main, int flag)
os_get_root_window - get a pointer to the root window (desktop)
void os_translate_coords (Widget_t *w, Window from_window, Window to_window, int from_x, int from_y, int *to_x, int *to_y)
os_translate_coords - get x,y related to destination Window
void os_get_window_metrics (Widget_t *w_, Metrics_t *metrics)
os_get_window_metrics - Get the Merics_t struct related to a Widget_t
void os_set_window_min_size (Widget_t *w, int min_width, int min_height, int base_width, int base_height)
os_set_window_min_size - Set the min and base size of a Widget_t
void os_move_window (Display *dpy, Widget_t *w, int x, int y)
os_move_window - Move a Widget_t
void os_resize_window (Display *dpy, Widget_t *w, int x, int y)
os_resize_window - Resize a Widget_t
void os_get_surface_size (cairo_surface_t *surface, int *width, int *height)
os_get_surface_size - get the size of the cairo surface
void os_set_widget_surface_size (Widget_t *w, int width, int height)
os_set_widget_surface_size - set the size of a Widget_t cairo surface
void os_create_main_window_and_surface (Widget_t *w, Xputty *app, Window win, int x, int y, int width, int height)
os_create_main_window_and_surface - create a Widget_t with a acairo surface this function is used mainly internal on create_window()
void os_create_widget_window_and_surface (Widget_t *w, Xputty *app, Widget_t *parent, int x, int y, int width, int height)
os_create_main_widget_and_surface - create a Widget_t with a acairo surface this function is used mainly internal on create_widget()
void os_set_title (Widget_t *w, const char *title)
os_set_title - Set the title of a Widget_t
void os_widget_show (Widget_t *w)
os_widget_show - Show a Widget_t
void os_widget_hide (Widget_t *w)
os_widget_hide - Hide a Widget_t
void os_show_tooltip (Widget_t *wid, Widget_t *w)
os_show_tooltip - Show a tooltip of a Widget_t
void os_expose_widget (Widget_t *w)
os_expose_widget - Draw the the back buffer to the Widget_t surface
void os_widget_event_loop (void *w_, void *event, Xputty *main, void *user_data)
os_widget_event_loop - the Widget_t event loop on windows all messges goes into WndProc, so stub here
void os_send_configure_event (Widget_t *w, int x, int y, int width, int height)
os_send_configure_event - Send a configure event to a Widget_t
void os_send_button_press_event (Widget_t *w)
os_send_button_press_event - Send a button press event to a Widget_t see XButtonEvent
void os_send_button_release_event (Widget_t *w)
os_send_button_release_event - Send a button release event to a Widget_t see XButtonEvent
void os_send_systray_message (Widget_t *w)
os_send_send_systray_message - Send a systray event to a Widget_t only working on Linux for now
int os_grab_pointer (Widget_t *w)
os_grab_pointer - grab the mouse pointer. Works only on linux
void os_set_input_mask (Widget_t *w)
os_set_input_mask - set the Event mask to a Widget_t only work on linux, stub on Windows
void os_set_window_attrb (Widget_t *w)
os_set_window_attrb - set the attribute mask to a Widget_t only work on linux, stub on Windows
void os_set_transient_for_hint (Widget_t *parent, Widget_t *w)
os_set_ transient_for_hint - set a Widget_t transient to a other Widget_t only work on linux, stub on Windows
int os_get_screen_height (Widget_t *w)
os_get_screen_height - Get the height of the used Display
int os_get_screen_width (Widget_t *w)
os_get_screen_width - Get the width of the used Display
char * os_get_home_dir ()
os_get_home_dir - get the users home directory
bool os_is_directory (const char *filename)
os_is directory - check if a given path is a directory or a file
void os_transparent_draw (void *w_, void *user_data)
os_transparent_draw - Draw the Widget_t to the back buffer
void os_adjustment_callback (void *w_, void *user_data)
os_adjustment_callback - called when a adjustment value have changed used internal for redraw the Widget_t
bool os_get_keyboard_input (Widget_t *w, XKeyEvent *key, char *buf, size_t bufsize)
os_ get_keyboard_input - Get the Keyboard input and convert it to utf8
void os_free_pixmap (Widget_t *w, Pixmap pixmap)
os_free_pixmap - Free the memory used by a Pixmap only Linux, stub otherwise
void os_quit (Widget_t *w)
os_quit - quit the main loop and free all used memory
void os_quit_widget (Widget_t *w)
os_quit_widget - remove a Widget_t from the main loop and free it's used memory
Atom os_register_wm_delete_window (Widget_t *wid)
os_register_wm_delete_window - Get the needed Atom to send a widget delete message
Atom os_register_widget_destroy (Widget_t *wid)
os_register_widget_destroy - Get the needed Atom to send a widget destroy message
void os_main_run (Xputty *main)
os_main_run - start the event loop
void os_run_embedded (Xputty *main)
os_run_embedded - the event handling when run embedded on windows all messges goes into WndProc, so stub here
void os_init_dnd (Xputty *main)
os_init_dnd - register a Widget_t for handling drag and drop events only implemented on linux
void build_xkey_event (XKeyEvent *ev, UINT msg, WPARAM wParam, LPARAM lParam)
Variables
TCHAR szMainUIClassName [] = TEXT("xputtyMainUI____0123456789ABCDEF")
TCHAR szWidgetUIClassName [] = TEXT("xputtyWidgetUI__0123456789ABCDEF")
Function Documentation
build_xkey_event()
void build_xkey_event (XKeyEvent * ev, UINT msg, WPARAM wParam, LPARAM lParam)
Definition at line 487 of file xwidget-mswin.c.
{
    UINT uVirtKey = (UINT)wParam;
    UINT uScanCode = (UINT)(HIWORD(lParam) & 0x1FF);
    BYTE lpKeyState[256];
    if (GetKeyboardState(lpKeyState)) {
        //https://stackoverflow.com/questions/42667205/maximum-number-of-characters-output-from-win32-tounicode-toascii
        // required size for the return buffer isn't exactly clear, maybe 255, so 1K should be a safe guess
        WCHAR lpChar[1024];
        UINT uFlags = 0x04; // 1=menu is active, 4=dont change anything
        if (msg == WM_CHAR) {
            ev->vk = uVirtKey;
            ev->vk_is_final_char = 1;
        } else {
            ToUnicode(uVirtKey, uScanCode, lpKeyState, lpChar, 2, uFlags);
            ev->vk = lpChar[0];
            ev->vk_is_final_char = 0;
        }
    }
    // handle special characters (only in KEYUP/DOWN?)
    switch (uScanCode) {
        case 0x0029: ev->keycode = XK_dead_circumflex;  break;
        case 0x000e: ev->keycode = XK_BackSpace;        break;
        case 0x000f: ev->keycode = XK_Tab;              break;
        case 0x001c: ev->keycode = XK_Return;           break;
        case 0x0147: ev->keycode = XK_Home;             break;
        case 0x014b: ev->keycode = XK_Left;             break;
        case 0x0148: ev->keycode = XK_Up;               break;
        case 0x014d: ev->keycode = XK_Right;            break;
        case 0x0150: ev->keycode = XK_Down;             break;
        case 0x014f: ev->keycode = XK_End;              break;
        case 0x0152: ev->keycode = XK_Insert;           break;
        case 0x011c: ev->keycode = XK_KP_Enter;         break;
        case 0x0047: ev->keycode = XK_KP_Home;          break;
        case 0x004b: ev->keycode = XK_KP_Left;          break;
        case 0x0048: ev->keycode = XK_KP_Up;            break;
        case 0x004d: ev->keycode = XK_KP_Right;         break;
        case 0x0050: ev->keycode = XK_KP_Down;          break;
        case 0x004f: ev->keycode = XK_KP_End;           break;
        case 0x0052: ev->keycode = XK_KP_Insert;        break;
        case 0x004e: ev->keycode = XK_KP_Add;           break;
        case 0x004a: ev->keycode = XK_KP_Subtract;      break;
        default:
            if (ev->vk == 0xfc) //''
                ev->keycode = XK_udiaeresis;
            else if (ev->vk == 0xdc) //''
                ev->keycode = XK_dead_diaeresis;
            else
                ev->keycode = ev->vk;
    }
}
References XEvent::keycode, XEvent::vk, and XEvent::vk_is_final_char.
Referenced by WndProc().
convert_cp()
char * convert_cp (DWORD cp_from, DWORD cp_to, char * s_from)
Definition at line 71 of file xwidget-mswin.c.
{
    char *s_to = NULL;
    int flags = MB_PRECOMPOSED; // | MB_ERR_INVALID_CHARS;
    // prepare conversion to WideChar (using cp_from) - get required space
    size_t size = MultiByteToWideChar(cp_from, flags, s_from, -1, NULL, 0);
    if (size) {
        // convert Ansi to WideChar (pwc)
        wchar_t *pwc= (wchar_t*)malloc(size*2);
        size_t size_wc = MultiByteToWideChar(cp_from, flags, s_from, -1, pwc, size);
        if (size_wc) {
            // prepare conversion to cp_to - get required space
            flags = 0;
            size = WideCharToMultiByte(cp_to, flags, pwc, size_wc, NULL, 0, NULL, NULL);
            if (size) {
                // convert WideChar (pwc) to Ansi using cp_to
                s_to = (char*)malloc(size+1);
                memset(s_to, 0 , size+1);
                size = WideCharToMultiByte(cp_to, flags, pwc, size_wc, s_to, size, NULL, NULL);
            }
        }
        free(pwc);
    }
    // needs to be free()d by caller
    return s_to;
}
Referenced by locale_from_utf8(), and utf8_from_locale().
debug_lasterror()
void debug_lasterror (const char * prefix, const char * prefix2)
Definition at line 49 of file xwidget-mswin.c.
{
    LPSTR msg = NULL;
    DWORD err = GetLastError();
    size_t size = FormatMessageA(FORMAT_MESSAGE_ALLOCATE_BUFFER
                |FORMAT_MESSAGE_FROM_SYSTEM|FORMAT_MESSAGE_IGNORE_INSERTS,
                NULL, err, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
                (LPSTR)&msg, 0, NULL);
    if (size) {
        debug_print("%s%s:ERR=%8.8lx (%ld): %s\n",prefix?prefix:"",prefix2?prefix2:"",err,err,msg);
        LocalFree(msg);
    } else {
        DWORD fmt_err = GetLastError();
        debug_print("%s%s:ERROR:FormatMessage for ERR=%8.8lx (%ld) returned %8.8lx (%ld)\n",
                (prefix ? prefix : ""), (prefix2 ? prefix2 : ""), err, err, fmt_err, fmt_err);
    }
}
Referenced by os_quit().
locale_from_utf8()
char * locale_from_utf8 (char * utf8str)
locale_from_utf8 - convert utf8 to active codepage must be freed by the caller
Parameters
*utf8str - Pointer to char to convert
Returns
*char - the converted char in locale format
Definition at line 109 of file xwidget-mswin.c.
{
    return (convert_cp(CP_UTF8, GetACP(), utf8str));
}
References asprintf(), and convert_cp().
onPaint()
LRESULT onPaint (HWND hwnd, WPARAM wParam, LPARAM lParam)
Definition at line 933 of file xwidget-mswin.c.
{
    PAINTSTRUCT ps ;
    Widget_t *w = (Widget_t *)GetWindowLongPtr(hwnd, GWLP_USERDATA);
    // The cairo_win32_surface should only exist between BeginPaint()/EndPaint(),
    // otherwise it becomes unusable once the HDC of the owner window changes
    // (what can happen anytime, e.g. on resize).
    // Therefore, w->surface is created as a simple cairo_image_surface,
    // that can exist throughout the plugins lifetime (exception: see resize_event())
    // and is copied to a win32_surface in the onPaint() event (see WM_PAINT).
    // draw onto the image surface first
    transparent_draw(w, NULL);
    // prepare to update window
    HDC hdc = BeginPaint(hwnd, &ps );
    // create the cairo surface and context
    cairo_surface_t *surface = cairo_win32_surface_create (hdc);
    cairo_t *cr = cairo_create (surface);
    // copy contents of the (permanent) image_surface to the win32_surface
    cairo_set_source_surface(cr, w->surface, 0.0, 0.0);
    cairo_paint(cr);
    // cleanup
    cairo_destroy (cr);
    cairo_surface_destroy (surface);
    EndPaint( hwnd, &ps );
    return 0 ;
}
References Widget_t::surface, and transparent_draw().
Referenced by WndProc().
os_adjustment_callback()
void os_adjustment_callback (void * w_, void * user_data)
os_adjustment_callback - called when a adjustment value have changed used internal for redraw the Widget_t
Parameters
*w - Pointer to the widget
*user_data - additional user data or NULL
Definition at line 398 of file xwidget-mswin.c.
{
    Widget_t *w = (Widget_t *)w_;
   // transparent_draw(w, user_data);
    RedrawWindow(w->widget, NULL, NULL, RDW_NOERASE | RDW_INVALIDATE | RDW_UPDATENOW | RDW_ALLCHILDREN);
}
References transparent_draw(), and Widget_t::widget.
Referenced by create_widget(), and create_window().
os_close_display()
void os_close_display (Display * dpy)
os_close_display - Close connection to the used display
Parameters
*dpy - Display to close
Definition at line 118 of file xwidget-mswin.c.
{
    // nothing to do on MSWin
}
Referenced by main_quit().
os_create_main_window_and_surface()
void os_create_main_window_and_surface (Widget_t * w, Xputty * app, Window win, int x, int y, int width, int height)
os_create_main_window_and_surface - create a Widget_t with a acairo surface this function is used mainly internal on create_window()
Parameters
*w - the Widget_t to create
*app - the Xputty struct the Widget_t belongs to
*win - the Parent Window were the Widget_t belongs to
x,y - the position related to the Parent Window
*width,*height - the Widget_t size
Definition at line 195 of file xwidget-mswin.c.
{
    // Event callbacks already start during CreateWindow(),
    // so prepare childlist before that call on MSWin
    // (on Linux, adding to childlist starts message events)
    childlist_add_child(app->childlist,w);
    // prepare window class
    WNDCLASS wndclass = {0};
    HINSTANCE hInstance = NULL;
    snprintf(szMainUIClassName+16, 16, "%p", WndProc);
    snprintf(szWidgetUIClassName+16, 16, "%p", WndProc);
    // create a permanent surface for drawing (see onPaint() event)
    w->surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, width, height);
    wndclass.style         = CS_DBLCLKS | CS_HREDRAW | CS_VREDRAW;
    wndclass.lpfnWndProc   = WndProc;
    wndclass.hInstance     = hInstance;
    wndclass.hCursor       = LoadCursor(NULL, IDC_ARROW);
    wndclass.hbrBackground = NULL;
    wndclass.lpszClassName = szMainUIClassName;
    wndclass.cbWndExtra    = sizeof(w); // reserve space for SetWindowLongPtr
    RegisterClass(&wndclass);
    // TODO: pass window style (mainwindow,childwidget,popup,...) to create_window()
    // _WIN32 doesnt allow changing the style afterwards, as it is done in xmenu.cpp
    // (this also removes duplicate code for window/widget creation).
    // For the current situation it is sufficient to set popup style if parent is HWND_DESKTOP.
    DWORD dwStyle = 0;
    DWORD dwExStyle = 0;
    // dwExStyle:
    //   WS_EX_APPWINDOW - force(!) taskbar icon
    //   WS_EX_CONTROLPARENT - contains children, uses tab+cursor nav.
    //   WS_EX_NOPARENTNOTIFY - no PARENTNOTIFY on create/destroy
    //   WS_EX_TOOLWINDOW - no taskbar icon
    //   WS_EX_TOPMOST - above all others
    if (win == (HWND)-1) {
        // Dialogs with border
        dwStyle = WS_OVERLAPPEDWINDOW;
        dwExStyle = WS_EX_CONTROLPARENT;
        win = HWND_DESKTOP;
        // include border widths
        RECT Rect = {0};
        BOOL bMenu = false;
        Rect.right = width;
        Rect.bottom = height;
        if (AdjustWindowRectEx(&Rect, dwStyle, bMenu, dwExStyle)) {
            width = Rect.right - Rect.left;
            height = Rect.bottom - Rect.top;
        }
    } else {
        if (win == HWND_DESKTOP) {
            // Floating without border (popup, tooltip)
            dwStyle = WS_POPUP;
            dwExStyle = WS_EX_TOPMOST | WS_EX_CONTROLPARENT | WS_EX_TOOLWINDOW;
        } else {
            // Embedded widget
            dwStyle = WS_CHILD;
            dwExStyle = WS_EX_CONTROLPARENT | WS_EX_TOOLWINDOW;
        }
    }
    // create the window
    w->widget = CreateWindowEx(dwExStyle, szMainUIClassName,
                            TEXT("Draw Surface"), // lpWindowName
                            dwStyle, // dwStyle
                            CW_USEDEFAULT, CW_USEDEFAULT, // X, Y
                            width, height, // nWidth, nHeight
                            win, // hWndParent (no embeddeding takes place yet)
                            NULL, hInstance, (LPVOID)w); // hMenu, hInstance, lpParam
    SetParent(w->widget, win); // embed into parentWindow
    SetMouseTracking(w->widget, true); // for receiving WM_MOUSELEAVE
    os_set_window_min_size(w, width/2, height/2, width, height);
}
References Xputty::childlist, childlist_add_child(), Xputty::dpy, os_set_window_min_size(), SetMouseTracking(), Widget_t::surface, szMainUIClassName, szWidgetUIClassName, Widget_t::widget, WndProc(), Widget_t::xic, and Widget_t::xim.
Referenced by create_window().
os_create_widget_window_and_surface()
void os_create_widget_window_and_surface (Widget_t * w, Xputty * app, Widget_t * parent, int x, int y, int width, int height)
os_create_main_widget_and_surface - create a Widget_t with a acairo surface this function is used mainly internal on create_widget()
Parameters
*w - the Widget_t to create
*app - the Xputty struct the Widget_t belongs to
*parent - the Parent Widget_t were the Widget_t belongs to
x,y - the position related to the Parent Widget_t
*width,*height - the Widget_t size
Definition at line 270 of file xwidget-mswin.c.
{
    // Event callbacks already start during CreateWindow(),
    // so prepare childlist before that call on MSWin
    // (on Linux, adding to childlist starts message events)
    childlist_add_child(app->childlist,w);
    // prepare window class
    WNDCLASS wndclass = {0};
    HINSTANCE hInstance = NULL;
    // create a permanent surface for drawing (see onPaint() event)
    w->surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, width, height);
    wndclass.style         = CS_DBLCLKS;
    wndclass.lpfnWndProc   = WndProc;
    wndclass.hInstance     = hInstance;
    wndclass.hCursor       = LoadCursor(NULL, IDC_ARROW);
    wndclass.hbrBackground = NULL;
    wndclass.lpszClassName = szWidgetUIClassName;
    wndclass.cbWndExtra    = sizeof(w); // reserve space for SetWindowLongPtr
    RegisterClass(&wndclass);
    // create the window
    DWORD dwExStyle = WS_EX_CONTROLPARENT;
    w->widget = CreateWindowEx(dwExStyle, szWidgetUIClassName,
                            TEXT("Draw Surface"), // lpWindowName
                            WS_CHILD, // dwStyle
                            x, y, // X, Y
                            width, height, // nWidth, nHeight
                            parent->widget, // hWndParent (no embeddeding takes place yet)
                            NULL, hInstance, (LPVOID)w); // hMenu, hInstance, lpParam
    SetParent(w->widget, parent->widget); // embed into parentWindow
    SetMouseTracking(w->widget, true); // for receiving WM_MOUSELEAVE
}
References Xputty::childlist, childlist_add_child(), Xputty::dpy, SetMouseTracking(), Widget_t::surface, szWidgetUIClassName, Widget_t::widget, WndProc(), Widget_t::xic, and Widget_t::xim.
Referenced by create_widget().
os_destroy_window()
void os_destroy_window (Widget_t * w)
os_destroy_window - destroy a widget (close and remove from processing)
Parameters
*w - widget to destroy
Definition at line 122 of file xwidget-mswin.c.
{
    // mswin automatically sends WM_DESTROY to all child windows
    // floating windows need to be handled manually
    if (w && (IsWindow(w->widget))) {
        //debug_print("os_destroy_window:DestroyWindow:hwnd=%p\n",(w)?w->widget:NULL);
        DestroyWindow(w->widget);
    } else {
        debug_print("os_destroy_window:DestroyWindow:NOTFOUND:hwnd=%p\n",(w)?w->widget:NULL);
    }
}
References Widget_t::app, Xputty::dpy, Widget_t::widget, Widget_t::xic, and Widget_t::xim.
Referenced by destroy_widget().
os_expose_widget()
void os_expose_widget (Widget_t * w)
os_expose_widget - Draw the the back buffer to the Widget_t surface
Parameters
*w - Pointer to the widget
Definition at line 327 of file xwidget-mswin.c.
{
    RedrawWindow(w->widget, NULL, NULL, RDW_NOERASE | RDW_INVALIDATE | RDW_UPDATENOW);
}
References Widget_t::app, Xputty::dpy, Widget_t::widget, and XEvent::window.
Referenced by _update_view(), and expose_widget().
os_free_pixmap()
void os_free_pixmap (Widget_t * w, Pixmap pixmap)
os_free_pixmap - Free the memory used by a Pixmap only Linux, stub otherwise
Parameters
*w - Pointer to the widget
pixmap - the pixmap to be freed
Definition at line 416 of file xwidget-mswin.c.
{
    // Pixmap stuff not implemented at all
}
References Widget_t::app, and Xputty::dpy.
os_get_home_dir()
char * os_get_home_dir ()
os_get_home_dir - get the users home directory
Returns
*char - return the users home directory must be freed by the caller
Definition at line 376 of file xwidget-mswin.c.
{
    char *pPath = NULL;
    asprintf(&pPath, "%s%s", getenv("HOMEDRIVE"), getenv("HOMEPATH"));
    assert(pPath != NULL);
    fprintf(stderr, "%s\n", pPath);
    return pPath;
}
References asprintf().
os_get_keyboard_input()
bool os_get_keyboard_input (Widget_t * w, XKeyEvent * key, char * buf, size_t bufsize)
os_ get_keyboard_input - Get the Keyboard input and convert it to utf8
Parameters
*w - Pointer to the widget
*key - the XKeyEvent
*buf - the buffer to write the key in utf8 format
bufsize - the max buffer size to write to
Returns
bool - retrun true when the char is written to the buffer false on error
Definition at line 404 of file xwidget-mswin.c.
{
    char ansibuf[2];
    ansibuf[0] = (char)key->vk;
    ansibuf[1] = 0;
    char *utf8 = utf8_from_locale(ansibuf);
    int l=min(bufsize, strlen(utf8));
    strncpy(buf, utf8, l);
    buf[l] = 0;
    free(utf8);
    return key->vk_is_final_char; // for only feeding readily processed chars into input widgets
}
References utf8_from_locale(), XEvent::vk, XEvent::vk_is_final_char, and Widget_t::xic.
os_get_root_window()
Window os_get_root_window (Xputty * main, int flag)
os_get_root_window - get a pointer to the root window (desktop)
Parameters
*main - pointer to the Xputty struct
flag - Could be IS_WIDGET for NO decorated windows (popup etc.)
or IS_WINDOW for decorated TopLevel Windows (Dialogs, MainWindow, etc)
Returns
WINDOW - return pointer to the parent Window to use
Definition at line 133 of file xwidget-mswin.c.
{
    if (flag & IS_WIDGET) return HWND_DESKTOP; // no decorated
    else return (HWND)-1; // decorated
}
References Xputty::dpy, and IS_WIDGET.
Referenced by _configure_combobox_menu(), _configure_menu(), _popup_spinbox(), add_popup_spinbox(), create_combobox_menu(), create_menu(), create_tooltip(), mk_open_midi_keyboard(), open_directory_dialog(), open_file_dialog(), open_message_dialog(), open_midi_keyboard(), and save_file_dialog().
os_get_screen_height()
int os_get_screen_height (Widget_t * w)
os_get_screen_height - Get the height of the used Display
Parameters
*w - Pointer to the widget
Returns
int - the height of the Display
Definition at line 368 of file xwidget-mswin.c.
{
    return GetSystemMetrics(SM_CYSCREEN);
}
References Widget_t::app, and Xputty::dpy.
Referenced by _configure_combobox_menu(), and _configure_menu().
os_get_screen_width()
int os_get_screen_width (Widget_t * w)
os_get_screen_width - Get the width of the used Display
Parameters
*w - Pointer to the widget
Returns
int - the width of the Display
Definition at line 372 of file xwidget-mswin.c.
{
    return GetSystemMetrics(SM_CXSCREEN);
}
References Widget_t::app, and Xputty::dpy.
os_get_surface_size()
void os_get_surface_size (cairo_surface_t * surface, int * width, int * height)
os_get_surface_size - get the size of the cairo surface
Parameters
*surface - the cairo surface
*width,*height - (Pointer) to get the size
Definition at line 182 of file xwidget-mswin.c.
{
    *width = cairo_image_surface_get_width(surface);
    *height = cairo_image_surface_get_height(surface);
}
Referenced by _draw_frame(), _draw_h_meter(), _draw_image(), _draw_image_button(), _draw_image_button_with_label(), _draw_image_knob(), _draw_image_slider(), _draw_playhead(), and _draw_v_meter().
os_get_window_metrics()
void os_get_window_metrics (Widget_t * w_, Metrics_t * metrics)
os_get_window_metrics - Get the Merics_t struct related to a Widget_t
Parameters
*w - Pointer to the widget
*metrics - Pointer to the Metrics_t struct to hold the info for widget
Definition at line 146 of file xwidget-mswin.c.
{
    RECT WindowRect;
    RECT ClientRect;
    POINT Point;
    Widget_t *parent = (Widget_t *)w_->parent;
    if (GetWindowRect(w_->widget, &WindowRect) \
     && GetClientRect(w_->widget, &ClientRect)) {
        Point.x = WindowRect.left; // WindowRect has correct coords, but wrong width/height
        Point.y = WindowRect.top;  // ClientRect has correct width/height, but top/left == 0
        ScreenToClient(parent->widget, &Point); // "parent" is intentional (coords are relative to owner widget)
        metrics->x = Point.x;
        metrics->y = Point.y;
        metrics->width = ClientRect.right - ClientRect.left;
        metrics->height = ClientRect.bottom - ClientRect.top;
    }
    metrics->visible = IsWindowVisible(w_->widget);
}
References Widget_t::app, Xputty::dpy, Metrics_t::height, Widget_t::parent, Metrics_t::visible, Widget_t::widget, Metrics_t::width, Metrics_t::x, and Metrics_t::y.
Referenced by _buttons_released(), _combobox_entry_released(), _combobox_key_pressed(), _combobox_motion(), _configure_listbox(), _configure_listview(), _configure_menu(), _draw_accel_check_item(), _draw_accel_item(), _draw_base_button(), _draw_button(), _draw_buttons(), _draw_check_box(), _draw_check_button(), _draw_check_item(), _draw_combobox(), _draw_combobox_button(), _draw_combobox_entrys(), _draw_combobox_menu_slider(), _draw_frame(), _draw_h_meter(), _draw_hmeter_scale(), _draw_hslider(), _draw_image(), _draw_item(), _draw_knob(), _draw_label(), _draw_list(), _draw_listbox_item(), _draw_listbox_viewslider(), _draw_listviewslider(), _draw_menu_label(), _draw_menu_slider(), _draw_multi_list(), _draw_multi_listviewslider(), _draw_on_off_button(), _draw_spinbox(), _draw_submenu(), _draw_switch_image_button(), _draw_tabbox(), _draw_ti_button(), _draw_tooltip(), _draw_tuner(), _draw_v_meter(), _draw_value_item(), _draw_valuedisplay(), _draw_vmeter_scale(), _draw_vslider(), _draw_waveview(), _enter_submenu(), _has_pointer(), _list_entry_double_clicked(), _list_entry_released(), _list_key_pressed(), _list_motion(), _multi_list_entry_double_clicked(), _multi_list_entry_released(), _multi_list_key_pressed(), _reconfigure_combobox_viewport(), _reconfigure_listbox_viewport(), _reconfigure_listview_viewport(), _reconfigure_multi_listview_viewport(), _set_listbox_viewpoint(), _set_viewpoint(), _tab_button_released(), _update_list_view(), _update_view(), cmenu_add_submenu(), configure_event(), draw_hyperlink(), listview_remove_list(), menu_add_item(), menu_add_numeric_items(), menu_add_submenu(), menu_add_value_entry(), menubar_add_menu(), mk_draw_knob(), multi_listview_remove_list(), set_pattern(), tabbox_add_tab(), transparent_draw(), and widget_draw().
os_grab_pointer()
int os_grab_pointer (Widget_t * w)
os_grab_pointer - grab the mouse pointer. Works only on linux
Parameters
*w - Pointer to the widget which will grab the mouse
Returns
int - Return 0 on error
Definition at line 351 of file xwidget-mswin.c.
{
    // STUB
    return 0;
}
References Widget_t::app, and Xputty::dpy.
Referenced by _popup_spinbox(), pop_combobox_menu_show(), and pop_menu_show().
os_init_dnd()
void os_init_dnd (Xputty * main)
os_init_dnd - register a Widget_t for handling drag and drop events only implemented on linux
Parameters
*main - pointer to the Xputty struct
Definition at line 475 of file xwidget-mswin.c.
{
    // DND not implemented for win32
}
References Xputty::dnd_source_window, Xputty::dnd_type, Xputty::dnd_type_text, Xputty::dnd_type_uri, Xputty::dnd_type_utf8, Xputty::dnd_version, Xputty::dpy, Xputty::selection, Xputty::targets_atom, Xputty::text_atom, Xputty::UTF8, Xputty::XdndActionCopy, Xputty::XdndAware, Xputty::XdndDrop, Xputty::XdndEnter, Xputty::XdndFinished, Xputty::XdndLeave, Xputty::XdndPosition, Xputty::XdndSelection, Xputty::XdndStatus, and Xputty::XdndTypeList.
Referenced by main_init().
os_is_directory()
bool os_is_directory (const char * filename)
os_is directory - check if a given path is a directory or a file
Parameters
*filename - the Path to check
Returns
bool - return true if path is directory, otrherwise false
Definition at line 384 of file xwidget-mswin.c.
{
    DWORD attribs = GetFileAttributes(filename);
    return ((attribs != INVALID_FILE_ATTRIBUTES) &&     // check if a valid file
    ((attribs & FILE_ATTRIBUTE_DIRECTORY) != 0) &&  // file is a directory
    ((attribs & FILE_ATTRIBUTE_HIDDEN) == 0) &&     // file is not hidden
    ((attribs & FILE_ATTRIBUTE_SYSTEM) == 0));     // file is not system
}
Referenced by _draw_list(), and _draw_multi_list().
os_main_run()
void os_main_run (Xputty * main)
os_main_run - start the event loop
Parameters
*main - pointer to the Xputty struct
Definition at line 458 of file xwidget-mswin.c.
{
    MSG msg;
    BOOL bRet;
    while( main->run && (bRet = GetMessage(&msg, NULL, 0, 0)) > 0) {
        if (bRet == -1) {
          return; // error
        } else {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }
    }
}
References Func_t::button_press_callback, Func_t::button_release_callback, Xputty::childlist, Widget_t::childlist, childlist_find_widget(), childlist_has_child(), Childlist_t::childs, destroy_widget(), Xputty::dpy, Childlist_t::elem, Widget_t::event_callback, Widget_t::flags, Widget_t::func, HIDE_ON_DELETE, Xputty::hold_grab, IS_POPUP, Func_t::key_press_callback, Func_t::key_release_callback, Xputty::key_snooper, Xputty::run, Xputty::submenu, Widget_t::widget, widget_hide(), and XEvent::window.
Referenced by main_run().
os_move_window()
void os_move_window (Display * dpy, Widget_t * w, int x, int y)
os_move_window - Move a Widget_t
Parameters
*dpy - Pointer to the Display the widget belongs to
*w - Pointer to the widget
x,y - the point to move to
Definition at line 172 of file xwidget-mswin.c.
{
    SetWindowPos(w->widget, NULL, //hWnd, hWndInsertAfter
      x, y, 0, 0, SWP_NOSIZE|SWP_NOZORDER); //X, Y, width, height, uFlags
}
References Widget_t::widget.
Referenced by _configure_combobox_menu(), _configure_menu(), _popup_spinbox(), _resize_childs(), _set_listbox_viewpoint(), _set_viewpoint(), and menu_remove_item().
os_open_display()
Display * os_open_display (char * display_name)
os_open_display - Connect to the display to use
Parameters
*display_name - Display name could be 0 for default
Returns
Display - return pointer to the Display struct
Definition at line 113 of file xwidget-mswin.c.
{
    // nothing to do on MSWin
    return (Display *)1;
}
Referenced by main_init().
os_quit()
void os_quit (Widget_t * w)
os_quit - quit the main loop and free all used memory
Parameters
*w - Pointer to the widget request the quit call
Definition at line 420 of file xwidget-mswin.c.
{
    if (w) {
        WPARAM wParam = (WPARAM)get_toplevel_widget(w->app)->widget;
        DWORD msg = os_register_wm_delete_window(w);
        SendMessage(w->widget, msg, wParam, 0); // WM_DELETE_WINDOW
    }
    // UnregisterClass silently fails, if there are still more windows of this class
    if (UnregisterClass(szMainUIClassName, NULL)) {
        debug_print("UnregisterMainClass:%s:OK\n", szMainUIClassName);
    } else
        debug_lasterror("UnregisterMainClass:", szMainUIClassName);
    if (UnregisterClass(szWidgetUIClassName, NULL)) {
        debug_print("UnregisterWidgetClass:%s:OK\n", szWidgetUIClassName);
    } else
        debug_lasterror("UnregisterWidgetClass" ,szWidgetUIClassName);
}
References Widget_t::app, debug_lasterror(), Xputty::dpy, get_toplevel_widget(), os_register_wm_delete_window(), szMainUIClassName, szWidgetUIClassName, and Widget_t::widget.
Referenced by quit(), and quit_widget().
os_quit_widget()
void os_quit_widget (Widget_t * w)
os_quit_widget - remove a Widget_t from the main loop and free it's used memory
Parameters
*w - Pointer to the widget request the quit call
Definition at line 439 of file xwidget-mswin.c.
{
    // who invokes this?
    WPARAM wParam = (WPARAM)w->widget;
    DWORD msg = os_register_widget_destroy(w);
    SendMessage(w->widget, msg, wParam, 0); // WIDGET_DESTROY
}
References Widget_t::app, Xputty::dpy, os_register_widget_destroy(), and Widget_t::widget.
os_register_widget_destroy()
Atom os_register_widget_destroy (Widget_t * wid)
os_register_widget_destroy - Get the needed Atom to send a widget destroy message
Parameters
*wid - Pointer to the widget request the quit call
Returns
ATOM - ATOM on linux, DWORD on windows
Definition at line 452 of file xwidget-mswin.c.
{
    Atom msg = WM_USER + 02 ;
    //Atom msg = RegisterWindowMessage("XPUTTY_WIDGET_DESTROY");
    return msg;
}
References Widget_t::app, and Xputty::dpy.
Referenced by os_quit_widget().
os_register_wm_delete_window()
Atom os_register_wm_delete_window (Widget_t * wid)
os_register_wm_delete_window - Get the needed Atom to send a widget delete message
Parameters
*wid - Pointer to the widget request the quit call
Returns
ATOM - ATOM on linux, DWORD on windows
Definition at line 446 of file xwidget-mswin.c.
{
    Atom msg = WM_USER + 01;
    //Atom msg = RegisterWindowMessage("XPUTTY_WM_DELETE_WINDOW");
    return msg;
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by childlist_add_child(), and os_quit().
os_resize_window()
void os_resize_window (Display * dpy, Widget_t * w, int x, int y)
os_resize_window - Resize a Widget_t
Parameters
*dpy - Pointer to the Display the widget belongs to
*w - Pointer to the widget
x,y - the new size
Definition at line 177 of file xwidget-mswin.c.
{
    SetWindowPos(w->widget, NULL, //hWnd, hWndInsertAfter
      0, 0, x, y, SWP_NOMOVE|SWP_NOZORDER); //X, Y, width, height, uFlags
}
References Widget_t::widget.
Referenced by _configure_combobox_menu(), _configure_listbox(), _configure_listview(), _configure_menu(), _get_width(), and _resize_childs().
os_run_embedded()
void os_run_embedded (Xputty * main)
os_run_embedded - the event handling when run embedded on windows all messges goes into WndProc, so stub here
Parameters
*main - pointer to the Xputty struct
Definition at line 471 of file xwidget-mswin.c.
{
    // messageloop already polled by plugin host
}
References Func_t::button_press_callback, Func_t::button_release_callback, Xputty::childlist, Widget_t::childlist, childlist_find_widget(), childlist_has_child(), Childlist_t::childs, destroy_widget(), Xputty::dpy, Childlist_t::elem, Widget_t::event_callback, Widget_t::flags, Widget_t::func, HIDE_ON_DELETE, Xputty::hold_grab, IS_POPUP, Func_t::key_press_callback, Func_t::key_release_callback, Xputty::key_snooper, Xputty::submenu, Widget_t::widget, widget_hide(), and XEvent::window.
Referenced by run_embedded().
os_send_button_press_event()
void os_send_button_press_event (Widget_t * w)
os_send_button_press_event - Send a button press event to a Widget_t see XButtonEvent
Parameters
*w - Pointer to the widget
Definition at line 339 of file xwidget-mswin.c.
{
    // STUB
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by send_button_press_event().
os_send_button_release_event()
void os_send_button_release_event (Widget_t * w)
os_send_button_release_event - Send a button release event to a Widget_t see XButtonEvent
Parameters
*w - Pointer to the widget
Definition at line 343 of file xwidget-mswin.c.
{
    // STUB
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by send_button_release_event().
os_send_configure_event()
void os_send_configure_event (Widget_t * w, int x, int y, int width, int height)
os_send_configure_event - Send a configure event to a Widget_t
Parameters
*w - Pointer to the widget
x,y - the position to set
width,height - the size to set
Definition at line 335 of file xwidget-mswin.c.
{
    // STUB
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by send_configure_event().
os_send_systray_message()
void os_send_systray_message (Widget_t * w)
os_send_send_systray_message - Send a systray event to a Widget_t only working on Linux for now
Parameters
*w - Pointer to the widget
Definition at line 347 of file xwidget-mswin.c.
{
    // STUB
}
References Widget_t::app, default_error_handler, Xputty::dpy, intern_error_handler(), set_systray_color(), and Widget_t::widget.
Referenced by send_systray_message().
os_set_input_mask()
void os_set_input_mask (Widget_t * w)
os_set_input_mask - set the Event mask to a Widget_t only work on linux, stub on Windows
Parameters
*w - Pointer to the widget which will grab the mouse
Definition at line 356 of file xwidget-mswin.c.
{
    // STUB
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by add_midi_keyboard(), create_combobox_viewport(), create_listview_viewport(), create_multi_listview_viewport(), mk_open_midi_keyboard(), and open_midi_keyboard().
os_set_title()
void os_set_title (Widget_t * w, const char * title)
os_set_title - Set the title of a Widget_t
Parameters
*w - Pointer to the widget
title - the title to set
Definition at line 305 of file xwidget-mswin.c.
{
    if (title)
        SetWindowText(w->widget, title);
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by widget_set_title().
os_set_transient_for_hint()
void os_set_transient_for_hint (Widget_t * parent, Widget_t * w)
os_set_ transient_for_hint - set a Widget_t transient to a other Widget_t only work on linux, stub on Windows
Parameters
*parent - Pointer to the parent widget
*w - Pointer to the widget
Definition at line 364 of file xwidget-mswin.c.
{
    // STUB
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by add_popup_spinbox(), create_combobox_menu(), create_menu(), and create_tooltip().
os_set_widget_surface_size()
void os_set_widget_surface_size (Widget_t * w, int width, int height)
os_set_widget_surface_size - set the size of a Widget_t cairo surface
Parameters
*surface - the cairo surface
*width,*height - the size to set
Definition at line 187 of file xwidget-mswin.c.
{
    // image_surface cant be resized (only xlib_surface can)
    cairo_destroy(w->cr);
    cairo_surface_destroy(w->surface);
    w->surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, width, height);
    w->cr = cairo_create(w->surface);
}
References Widget_t::cr, and Widget_t::surface.
Referenced by _resize_surface().
os_set_window_attrb()
void os_set_window_attrb (Widget_t * w)
os_set_window_attrb - set the attribute mask to a Widget_t only work on linux, stub on Windows
Parameters
*w - Pointer to the widget which will grab the mouse
Definition at line 360 of file xwidget-mswin.c.
{
    // STUB
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by add_popup_spinbox(), create_combobox_menu(), create_menu(), and create_tooltip().
os_set_window_min_size()
void os_set_window_min_size (Widget_t * w, int min_width, int min_height, int base_width, int base_height)
os_set_window_min_size - Set the min and base size of a Widget_t
Parameters
*w - Pointer to the widget
min_width,min_height - the min size to set
base_width,base_height - the base size to set
Definition at line 166 of file xwidget-mswin.c.
{
    w->metrics_min.width = min_width;
    w->metrics_min.height = min_height;
}
References Widget_t::app, Xputty::dpy, Metrics_t::height, Widget_t::metrics_min, Widget_t::widget, and Metrics_t::width.
Referenced by os_create_main_window_and_surface().
os_show_tooltip()
void os_show_tooltip (Widget_t * wid, Widget_t * w)
os_show_tooltip - Show a tooltip of a Widget_t
Parameters
*wid - Pointer to the widget the tooltip belongs to
*w - the tooltip Widget_t
Definition at line 318 of file xwidget-mswin.c.
{
    POINT pt;
    if (GetCursorPos(&pt)) {
        SetWindowPos(w->widget, NULL, //hWnd, hWndInsertAfter
          pt.x+10, pt.y-10, 0, 0,
          SWP_NOACTIVATE|SWP_NOSIZE|SWP_NOZORDER|SWP_NOOWNERZORDER|SWP_SHOWWINDOW); //X, Y, width, height, uFlags
    }
}
References Widget_t::app, Xputty::dpy, IS_WIDGET, os_get_root_window(), os_translate_coords(), and Widget_t::widget.
Referenced by show_tooltip().
os_translate_coords()
void os_translate_coords (Widget_t * w, Window from_window, Window to_window, int from_x, int from_y, int * to_x, int * to_y)
os_translate_coords - get x,y related to destination Window
Parameters
*w - Widget_t pointer
from_window - source Window
to_window - destination Window
x,y - point from the source Window
*to_x,*to_y - (Pointer) point in the destination Window
Definition at line 138 of file xwidget-mswin.c.
{
    POINT Point = {from_x, from_y};
    MapWindowPoints(from_window, to_window, &Point, 1);
    *to_x = Point.x;
    *to_y = Point.y;
}
References Widget_t::app, and Xputty::dpy.
Referenced by _configure_combobox_menu(), _configure_menu(), _popup_spinbox(), add_popup_spinbox(), create_combobox_menu(), create_menu(), and create_tooltip().
os_transparent_draw()
void os_transparent_draw (void * w_, void * user_data)
os_transparent_draw - Draw the Widget_t to the back buffer
Parameters
*w - Pointer to the widget
*user_data - additional user data or NULL
Definition at line 392 of file xwidget-mswin.c.
{
    Widget_t *w = (Widget_t *)w_;
   // transparent_draw(w, user_data);
    RedrawWindow(w->widget, NULL, NULL, RDW_NOERASE | RDW_INVALIDATE | RDW_UPDATENOW | RDW_ALLCHILDREN);
}
References transparent_draw(), and Widget_t::widget.
Referenced by _check_menu_state(), _enter_submenu(), _leave_submenu(), _set_entry(), add_button(), add_check_box(), add_check_button(), add_combobox(), add_hslider(), add_image_button(), add_image_knob(), add_image_toggle_button(), add_knob(), add_menu(), add_on_off_button(), add_switch_image_button(), add_toggle_button(), add_valuedisplay(), add_vslider(), create_widget(), listbox_add_entry(), menu_add_item(), menu_add_numeric_items(), and menu_add_value_entry().
os_widget_event_loop()
void os_widget_event_loop (void * w_, void * event, Xputty * main, void * user_data)
os_widget_event_loop - the Widget_t event loop on windows all messges goes into WndProc, so stub here
Parameters
*w - Pointer to the widget
*event - the event to handle
*main - pointer to the Xputty struct
*user_data - additional user data could be NULL
Definition at line 331 of file xwidget-mswin.c.
{
    // nothing to do
}
References _button_press(), _check_enum(), _check_grab(), _check_keymap(), _check_submenu(), _has_pointer(), _hide_all_tooltips(), adj_set_motion_state(), Widget_t::app, XEvent::button, Func_t::button_release_callback, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Func_t::configure_callback, destroy_widget(), Xputty::dnd_source_window, Xputty::dnd_type, Xputty::dnd_version, Widget_t::double_click, Func_t::double_click_callback, Xputty::dpy, Func_t::enter_callback, FAST_REDRAW, Widget_t::flags, Widget_t::func, handle_dnd_enter(), handle_drag_data(), HAS_FOCUS, HAS_POINTER, HAS_TOOLTIP, hide_tooltip(), IS_POPUP, Func_t::key_press_callback, Func_t::key_release_callback, XEvent::keycode, Func_t::leave_callback, Func_t::motion_callback, NO_AUTOREPEAT, quit_widget(), receive_paste_from_clipboard(), Xputty::selection, send_dnd_finished_event(), send_dnd_status_event(), send_to_clipboard(), show_tooltip(), XEvent::state, Widget_t::state, transparent_draw(), Func_t::visibiliy_change_callback, Widget_t::widget, XEvent::x, Xputty::XdndDrop, Xputty::XdndEnter, Xputty::XdndLeave, Xputty::XdndPosition, Xputty::XdndSelection, Widget_t::xpaste_callback, and XEvent::y.
Referenced by create_widget(), and widget_event_loop().
os_widget_hide()
void os_widget_hide (Widget_t * w)
os_widget_hide - Hide a Widget_t
Parameters
*w - Pointer to the widget to hide
Definition at line 314 of file xwidget-mswin.c.
{
    ShowWindow(w->widget, SW_HIDE);
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by widget_hide(), and widget_hide_all().
os_widget_show()
void os_widget_show (Widget_t * w)
os_widget_show - Show a Widget_t
Parameters
*w - Pointer to the widget to show
Definition at line 310 of file xwidget-mswin.c.
{
    ShowWindow(w->widget, SW_SHOW);
}
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
Referenced by pop_widget_show_all(), submenu_widget_show_all(), widget_show(), and widget_show_all().
SetClientSize()
void SetClientSize (HWND hwnd, int clientWidth, int clientHeight)
Definition at line 968 of file xwidget-mswin.c.
{
    if (IsWindow(hwnd)) {
        DWORD dwStyle = GetWindowLongPtr(hwnd, GWL_STYLE) ;
        DWORD dwExStyle = GetWindowLongPtr(hwnd, GWL_EXSTYLE) ;
        HMENU menu = GetMenu(hwnd) ;
        RECT rc = {0, 0, clientWidth, clientHeight} ;
        AdjustWindowRectEx(&rc, dwStyle, menu ? TRUE : FALSE, dwExStyle);
        SetWindowPos(hwnd, NULL, 0, 0, rc.right - rc.left, rc.bottom - rc.top,
                     SWP_NOZORDER | SWP_NOMOVE) ;
    }
}
Referenced by WndProc().
SetMouseTracking()
BOOL SetMouseTracking (HWND hwnd, BOOL enable)
Definition at line 981 of file xwidget-mswin.c.
{
    TRACKMOUSEEVENT tme;
    tme.cbSize = sizeof(tme);
    tme.dwFlags = TME_LEAVE;
    if (!enable)
        tme.dwFlags |= TME_CANCEL;
    tme.hwndTrack = hwnd;
    tme.dwHoverTime = HOVER_DEFAULT;
    return TrackMouseEvent(&tme);
}
Referenced by os_create_main_window_and_surface(), os_create_widget_window_and_surface(), and WndProc().
utf8_from_locale()
char * utf8_from_locale (char * localestr)
utf8_from_locale - convert active codepage to utf8 must be freed by the caller
Parameters
*localestr - Pointer to char to convert
Returns
*char - the converted char in utf8 format
Definition at line 104 of file xwidget-mswin.c.
{
    return (convert_cp(GetACP(), CP_UTF8, localestr));
}
References asprintf(), and convert_cp().
Referenced by _draw_multi_list(), and os_get_keyboard_input().
WndProc()
LRESULT CALLBACK WndProc (HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
Definition at line 538 of file xwidget-mswin.c.
{
    POINT pt;
    XButtonEvent xbutton;
    XMotionEvent xmotion;
    XKeyEvent xkey;
    void *user_data = NULL;
    // be aware: "wid" can be NULL during window creation (esp. if there is a debugger attached)
    Widget_t *wid = (Widget_t *)GetWindowLongPtr(hwnd, GWLP_USERDATA);
    Xputty *main = wid ? wid-> app : NULL;
    xbutton.window = hwnd;
    xbutton.x = GET_X_LPARAM(lParam);
    xbutton.y = GET_Y_LPARAM(lParam);
    xmotion.window = hwnd;
    xmotion.x = GET_X_LPARAM(lParam);
    xmotion.y = GET_Y_LPARAM(lParam);
    switch (msg) {
        case WM_CREATE:
            debug_print("WM:WM_CREATE:hwnd=%p:wid=%p",hwnd,wid);
            {
                CREATESTRUCT *pCreate = (CREATESTRUCT *)lParam;
                wid = (Widget_t *)pCreate->lpCreateParams;
                // CreateWindowEx() hasnt returned yet, so wid->widget is not set
                wid->widget = hwnd;
                // make "wid" available in messageloop events via GetWindowLongPtr()
                SetWindowLongPtr(hwnd, GWLP_USERDATA, (LONG_PTR)wid);
            }
            return 0;
        // MSWin only: React to close requests
        case WM_CLOSE:
            // standalone
            if (hwnd == main->childlist->childs[0]->widget) {
                // is main window: end application
                PostQuitMessage(0); // end messageloop (continuing to main_quit())
            } else // is sub window (menu, dialog, ...): close
                DestroyWindow(hwnd);
            return 0;
        case WM_DESTROY:
            if (!wid) return DefWindowProc(hwnd, msg, wParam, lParam);
            return 0;
        // X11:ConfigureNotify
        case WM_SIZE:
            if (!wid) return DefWindowProc(hwnd, msg, wParam, lParam);
            else {
                if(wid->app->hold_grab && wid != wid->app->hold_grab) {
                    widget_hide(wid->app->hold_grab);
                    wid->app->hold_grab = NULL;
                }
                // Limit window size:
                // The plugin doesnt receive WM_MINMAXINFO or WM_SIZING.
                // SWP_NOSIZE in WM_WINDOWPOSCHANGING cant handle width/height separately.
                // Setting the client size afterwards turned out to be the best working option so far.
                // Plugin: Limits the "zoom" (as the hosts window can always become smaller)
                // Standalone: Limits the window size
                int width = LOWORD(lParam);
                int height = HIWORD(lParam);
                if ((width < wid->metrics_min.width)
                    || (height < wid->metrics_min.height)) {
                    SetClientSize(hwnd, max(width, wid->metrics_min.width),
                            max(height, wid->metrics_min.height));
                    return 0;
                }
                // Resize handler
                if (!wid->func.configure_callback) return 0;
                wid->func.configure_callback(wid, user_data);
                // widgets recive the call to os_transparent_draw via the configure_notify_callback
                // windows have the CS_HREDRAW | CS_VREDRAW flags set so that they be redrawn by the system
                return 0;
            }
        case WM_MOVE:
            if (!wid) return DefWindowProc(hwnd, msg, wParam, lParam);
            if(wid->app->hold_grab && wid != wid->app->hold_grab) {
                widget_hide(wid->app->hold_grab);
                wid->app->hold_grab = NULL;
            }
        // X11:Expose
        case WM_PAINT:
            if (!wid) return DefWindowProc(hwnd, msg, wParam, lParam);
            if (!(wid->crb)) {
                debug_print("WM_PAINT:BAILOUT:wid->crb==NULL\n");
                return 0;
            }
            return onPaint(hwnd, wParam, lParam); // not possible on mswin: (only fetch the last expose event)
        // MSWin only: Allow keyboard input
        case WM_ACTIVATE:
            SetFocus(hwnd);
            return 0;
        case WM_MOUSEACTIVATE:
            SetFocus(hwnd);
            return MA_ACTIVATE;
        // X11:ButtonPress
        case WM_LBUTTONDOWN:
        case WM_RBUTTONDOWN:
            if (!wid) return DefWindowProc(hwnd, msg, wParam, lParam);
            SetCapture(hwnd); // also receive WM_MOUSEMOVE from outside this window
            if (msg == WM_LBUTTONDOWN)
                xbutton.button = Button1;
            else
                xbutton.button = Button3;
            if (wid->state == 4) break;
            if (wid->flags & HAS_TOOLTIP) hide_tooltip(wid);
            _button_press(wid, &xbutton, user_data);
            debug_print("Widget_t  ButtonPress %i\n", xbutton.button);
            return 0;
        case WM_MOUSEWHEEL:
            if (!wid) return DefWindowProc(hwnd, msg, wParam, lParam);
            // opposed to X11, WM_MOUSEWHEEL doesnt contain mouse coordinates
            {
                DWORD pos = GetMessagePos();
                pt.x = GET_X_LPARAM(pos);
                pt.y = GET_Y_LPARAM(pos);
                if (ScreenToClient(hwnd, &pt)) {
                    wid->pos_x = pt.x;
                    wid->pos_y = pt.y;
                }
            }
            if (GET_WHEEL_DELTA_WPARAM(wParam) <= 0) {
                xbutton.button = Button5;
                _button_press(wid, &xbutton, user_data);
            } else {
                xbutton.button = Button4;
                _button_press(wid, &xbutton, user_data);
            }
            // forward WM_MOUSEWHEEL from menuitem to viewport (with slider)
            // (viewport lies below menuitem, so doesnt receive WM_MOUSEWHEEL)
            if(wid->app->hold_grab) {
                Widget_t *view_port = wid->app->hold_grab->childlist->childs[0];
                if (hwnd != view_port->widget)
                    SendMessage(view_port->widget, msg, wParam, lParam);
                RedrawWindow(view_port->widget, NULL, NULL, RDW_NOERASE | RDW_INVALIDATE | RDW_UPDATENOW);
            }
            return 0;
        // X11:ButtonRelease
        case WM_LBUTTONDBLCLK:
            if (!wid) return DefWindowProc(hwnd, msg, wParam, lParam);
            xbutton.button = Button1;
            wid->func.double_click_callback(wid, &xbutton, user_data);
            return 0;
        case WM_LBUTTONUP:
        case WM_RBUTTONUP:
            ReleaseCapture();
            if (msg == WM_LBUTTONUP)
                xbutton.button = Button1;
            else
                xbutton.button = Button3;
            _check_grab(wid, &xbutton, wid->app);
            _check_submenu(wid, &xbutton, main);
            if (wid->state == 4) break;
            _has_pointer(wid, &xbutton);
            if(wid->flags & HAS_POINTER) wid->state = 1;
            else wid->state = 0;
            _check_enum(wid, &xbutton);
            wid->func.button_release_callback((void*)wid, &xbutton, user_data);
            debug_print("Widget_t  ButtonRelease %i\n", xbutton.button);
            return 0;
        // X11:KeyPress and X11:KeyRelease
        // The resulting character (e.g. from dead-key combinations) cannot be
        // determined from WM_KEYUP or WM_KEYDOWN: WM_CHAR has to be used instead.
        // To workaround that, WM_CHAR fires key_press- and key_release_event()
        // after another, with the flag "->vk_is_final_char" set, so the client
        // code can differentiate between real KEYUP/DOWN and fake CHAR events.
        case WM_CHAR:
        case WM_KEYDOWN:
        case WM_KEYUP:
            build_xkey_event(&xkey, msg, wParam, lParam);
            // X11:KeyPress
            if (msg != WM_KEYUP) { // WM_KEYDOWN and WM_CHAR: key_press_callback()
                if (!wid) return DefWindowProc(hwnd, msg, wParam, lParam);
                if (wid->state == 4) return 0;
                // on Linux, retrigger check happens in KeyRelease (WM_KEYUP)
                unsigned short is_retriggered = 0;
                if(wid->flags & NO_AUTOREPEAT) {
                    if ((HIWORD(lParam) & KF_REPEAT) == KF_REPEAT)
                        is_retriggered = 1;
                }
                if (!is_retriggered) {
                    _check_keymap(wid, xkey);
                    wid->func.key_press_callback((void *)wid, &xkey, user_data);
                    debug_print("Widget_t KeyPress %x\n", xkey.keycode);
                }
            }
            //X11:KeyRelease
            if (msg != WM_KEYDOWN) { // WM_KEYUP and WM_CHAR: key_release_callback()
                if (wid->state == 4) return 0;
                // On MSWin, the REPEAT flag is always set for WM_KEYUP,
                // so the retrigger check has to take place in WM_KEYDOWN instead
                wid->func.key_release_callback((void *)wid, &xkey, user_data);
                debug_print("Widget_t KeyRelease %x\n", xkey.keycode);
            }
            return 0;
        // X11:LeaveNotify (X11:EnterNotify: see WM_MOUSEMOVE)
        case WM_MOUSELEAVE:
            if (!wid) return DefWindowProc(hwnd, msg, wParam, lParam);
            // xputty -> xwidget: handled by "ButtonPress" event on Linux
                bool is_item = false;
                GetCursorPos(&pt);
                Window win_cur = WindowFromPoint(pt);
                if(wid->app->submenu != NULL) {
                     if (childlist_has_child(wid->app->submenu->childlist)) {
                        Widget_t *slider = wid->app->submenu->childlist->childs[1];
                        if (win_cur == slider->widget) {
                            return 0;
                        }
                        Widget_t *view_port = wid->app->submenu->childlist->childs[0];
                        int i = view_port->childlist->elem-1;
                        for(;i>-1;i--) {
                            Widget_t *w = view_port->childlist->childs[i];
                            if (win_cur == w->widget) {
                                is_item = True;
                                break;
                            }
                        }
                    }
                }
                if(wid->app->hold_grab != NULL && wid->app->hold_grab->flags & IS_POPUP) {
                    if (childlist_has_child(wid->app->hold_grab->childlist)) {
                        Widget_t *slider = wid->app->hold_grab->childlist->childs[1];
                        if (win_cur == slider->widget) {
                            return 0;
                        }
                        Widget_t *view_port = wid->app->hold_grab->childlist->childs[0];
                        int i = view_port->childlist->elem-1;
                        for(;i>-1;i--) {
                            Widget_t *w = view_port->childlist->childs[i];
                            if (win_cur == w->widget) {
                                is_item = True;
                                break;
                            }
                        }
                        if (win_cur == view_port->widget) is_item = True;
                    }
                    if (!is_item && (wParam & MK_LBUTTON || wParam & MK_RBUTTON)) {
                        ReleaseCapture();
                        widget_hide(wid->app->hold_grab);
                        wid->app->hold_grab = NULL;
                    }
                } else if(wid->app->hold_grab != NULL && ((wid->app->hold_grab->flags & IS_POPUP) == 0)) {
                    wid->app->hold_grab->func.button_press_callback(wid->app->hold_grab, &xbutton, NULL);
                }
/*
            // close popup menu if cursor moves out of widget
            if(wid->app->hold_grab != NULL) {
                GetCursorPos(&pt);
                Window win_cur = WindowFromPoint(pt);
                bool is_item = false;
                // still inside viewport? (finds menu entries in popup window)
                Widget_t *view_port = wid->app->hold_grab->childlist->childs[0];
                if (view_port) { // should never be NULL, but who knows :)
                    int i = view_port->childlist->elem-1;
                    for(;i>-1;i--) {
                        Widget_t *w = view_port->childlist->childs[i];
                        if (win_cur == w->widget) {
                            is_item = true;
                            break;
                        }
                    }
                    if (view_port && win_cur == view_port->widget) is_item = true; // inside slider area?
                }
                // still inside combobox? (finds combobox-button)
                Widget_t *menu = NULL;
                menu = (Widget_t *)wid->app->hold_grab->parent_struct;
                if (menu) { // can be NULL if not contained in combobox
                    int i = menu->childlist->elem-1;
                    for(;i>-1;i--) {
                        Widget_t *w = menu->childlist->childs[i];
                        if (win_cur == w->widget) {
                            is_item = true;
                            break;
                        }
                    }
                    if (menu && win_cur == menu->widget) is_item = true; // inside combobox textarea?
                }
                if (!is_item) {
                    ReleaseCapture();
                    widget_hide(wid->app->hold_grab);
                    wid->app->hold_grab = NULL;
                }
            }
*/
            // for emulating X11:EnterNotify
            wid->mouse_inside = false;
            if (wid->state == 4) break;
            //if(!(xev->xcrossing.state & Button1Mask)) {
            if (!(GetAsyncKeyState(VK_LBUTTON) & 0x8000)) {
                wid->state = 0;
                wid->flags &= ~HAS_FOCUS;
                wid->func.leave_callback((void*)wid, user_data);
               // if (!(wid->flags & IS_WINDOW))
               //     RedrawWindow(hwnd, NULL, NULL, RDW_NOERASE | RDW_INVALIDATE | RDW_UPDATENOW);
            }
            if (wid->flags & HAS_TOOLTIP) hide_tooltip(wid);
            debug_print("Widget_t LeaveNotify:hwnd=%p",hwnd);
            return 0;
        // X11:MotionNotify
        case WM_MOUSEMOVE:
            if (!wid) return DefWindowProc(hwnd, msg, wParam, lParam);
            if (!wid->mouse_inside) {
                // emulate X11:EnterNotify
                int ch = childlist_has_child(main->childlist);
                if (ch) {
                    int i = ch;
                    for(;i>0;i--) {
                        if (main->childlist->childs[i-1] != wid) {
                            if (main->childlist->childs[i-1]->mouse_inside) {
                                main->childlist->childs[i-1]->mouse_inside = false;
                                if (main->childlist->childs[i-1]->state != 4) {
                                    main->childlist->childs[i-1]->state = 0;
                                    //RedrawWindow(main->childlist->childs[i-1]->widget, NULL, NULL, RDW_NOERASE | RDW_INVALIDATE | RDW_UPDATENOW);
                                }
                            }
                        }
                    }
                }
                wid->mouse_inside = true;
                wid->flags |= HAS_FOCUS;
                if (wid->state == 4) break;
                //if(!(xev->xcrossing.state & Button1Mask)) {
                if (!(wParam & MK_LBUTTON)) {
                    wid->state = 1;
                    wid->func.enter_callback((void*)wid, user_data);
                   // if (!(wid->flags & IS_WINDOW))
                   //     RedrawWindow(hwnd, NULL, NULL, RDW_NOERASE | RDW_INVALIDATE | RDW_UPDATENOW);
                    if (wid->flags & HAS_TOOLTIP) show_tooltip(wid);
                    else _hide_all_tooltips(wid);
                }
                debug_print("Widget_t EnterNotify:hwnd=%p",hwnd);
                SetMouseTracking(hwnd, true); // for receiving (next) WM_MOUSELEAVE
            }
            // hovering, etc.
            if (wid->state == 4) return 0;
            if (wParam & MK_LBUTTON) // TODO: why is this if() required here, but not on linux?
                adj_set_motion_state(wid, xmotion.x, xmotion.y);
            wid->func.motion_callback((void*)wid, &xmotion, user_data);
            debug_print("Widget_t MotionNotify x = %li Y = %li hwnd=%p\n",pt.x,pt.y,hwnd );
            return 0;
        // X11:ClientMessage: not implemented (could be done with WM_USER / RegisterWindowMessage())
        case WM_USER + 01: // WM_DELETE_WINDOW
            // xwidget -> xputty (main_run())
            if (wid) {
                if (hwnd == main->childlist->childs[0]->widget) { // main window (this is not invoked for any other window?)
                    main->run = false;
                    destroy_widget(wid, main);
                } else {
                    int i = childlist_find_widget(main->childlist, (Window)wParam);
                    if(i<1) return 0;
                    Widget_t *w = main->childlist->childs[i];
                    if(w->flags & HIDE_ON_DELETE) widget_hide(w);
                    else { destroy_widget(main->childlist->childs[i],main);
                    }
                }
            }
            return 1;
        // X11:ClientMessage:WIDGET_DESTROY
        case WM_USER + 02: // WIDGET_DESTROY
            //os_widget_event_loop()
            if (wid) {
                int ch = childlist_has_child(wid->childlist);
                if (ch) {
                    int i = ch;
                    for(;i>0;i--) {
                        quit_widget(wid->childlist->childs[i-1]);
                    }
                    quit_widget(wid);
                } else {
                    destroy_widget(wid,wid->app);
                }
                return 0;
            }
            return 2;
        default:
            return DefWindowProc(hwnd, msg, wParam, lParam);
    }
    return 0;
}
References _button_press(), _check_enum(), _check_grab(), _check_keymap(), _check_submenu(), _has_pointer(), _hide_all_tooltips(), adj_set_motion_state(), Widget_t::app, build_xkey_event(), XEvent::button, Func_t::button_release_callback, Xputty::childlist, Widget_t::childlist, childlist_find_widget(), childlist_has_child(), Childlist_t::childs, Func_t::configure_callback, Widget_t::crb, destroy_widget(), Func_t::double_click_callback, Childlist_t::elem, Widget_t::flags, Widget_t::func, HAS_FOCUS, HAS_POINTER, HAS_TOOLTIP, Metrics_t::height, HIDE_ON_DELETE, hide_tooltip(), Xputty::hold_grab, IS_POPUP, XEvent::keycode, Widget_t::metrics_min, Widget_t::mouse_inside, NO_AUTOREPEAT, onPaint(), Widget_t::pos_x, Widget_t::pos_y, quit_widget(), Xputty::run, SetClientSize(), SetMouseTracking(), show_tooltip(), Widget_t::state, Xputty::submenu, Widget_t::widget, widget_hide(), Metrics_t::width, XEvent::window, XEvent::x, and XEvent::y.
Referenced by os_create_main_window_and_surface(), and os_create_widget_window_and_surface().
Variable Documentation
szMainUIClassName
TCHAR szMainUIClassName[] = TEXT("xputtyMainUI____0123456789ABCDEF")
Definition at line 34 of file xwidget-mswin.c.
Referenced by os_create_main_window_and_surface(), and os_quit().
szWidgetUIClassName
TCHAR szWidgetUIClassName[] = TEXT("xputtyWidgetUI__0123456789ABCDEF")
Definition at line 35 of file xwidget-mswin.c.
Referenced by os_create_main_window_and_surface(), os_create_widget_window_and_surface(), and os_quit().