libxputty: xputty/xwidget_private.c File Reference
xwidget_private.c File Reference
Functions
void _scroll_event (Widget_t *wid, int direction)
_scroll_event - internal check which Adjustment_t change it's value on a motion event (POINTER_MOTION)
void _toggle_event (Widget_t *wid)
_toggle_event - internal check which Adjustment_t change it's value on a Button press event (BUTTON_PRESS)
void _check_enum (Widget_t *wid, XButtonEvent *xbutton)
_check_enum - internal check if Adjustment_t is of type CL_ENUM and handle events acordingly
void _button_press (Widget_t *wid, XButtonEvent *xbutton, void *user_data)
_button_press - internal check which button is pressed (BUTTON_PRESS)
void _check_grab (Widget_t *wid, XButtonEvent *xbutton, Xputty *main)
_check_grab - internal check if a Widgt_t holds a grab when a BUTTON_PRESS event occur. If so, check if the button is pressed inside the grab Widget_t. If yes, handle the event. In any case destroy the grab
void _check_submenu (Widget_t *wid, XButtonEvent *xbutton, Xputty *main)
_check_submenu - internal check if a Widgt_t is a submenu when a BUTTON_PRESS event occur. If so, check if the button is pressed inside the submenu Widget_t. If yes, handle the event. In any case destroy the submenu
void _propagate_child_expose (Widget_t *wid)
_propagate_child_expose - send expose to any child Widget_t
void _check_keymap (void *w_, XKeyEvent xkey)
_check_keymap - check if key is in map, send requests if so
void _hide_all_tooltips (Widget_t *wid)
_hide_all_tooltips - hide all active tooltips
void _has_pointer (Widget_t *w, XButtonEvent *button)
_has_pointer - check if the widget has the pointer
void _set_adj_value (void *w_, bool x, int direction)
_set_adj_value - set value to adjustment from key event
void _dummy1_callback (void *w_, void *_data, void *user_data)
_dummy1_callback - default debuging callback for evfunc's
void _dummy_callback (void *w_, void *user_data)
_dummy1_callback - default debuging callback for xevfunc's
void _resize_surface (Widget_t *wid, int width, int height)
_resize_surface - intern check if a Widget_t surfaces needs resizing
void _resize_childs (Widget_t *wid)
_resize_childs - intern check if child widgets needs resizing
Function Documentation
_button_press()
void _button_press (Widget_t * wid, XButtonEvent * xbutton, void * user_data)
_button_press - internal check which button is pressed (BUTTON_PRESS)
Parameters
*wid - pointer to the Widget_t receiving a event
*xbutton - pointer to the XButtonEvent
*user_data - void pointer to attached user_data
Returns
void
Definition at line 85 of file xwidget_private.c.
{
    if(wid->app->hold_grab != NULL) {
        int ch = childlist_has_child(wid->childlist);
        if (ch>1 && wid->app->key_snooper == NULL) {
            if (xbutton->window == wid->app->hold_grab->childlist->childs[1]->widget) {
                wid->app->is_grab = true;
            } else {
                wid->app->is_grab = false;
            }
        }
    }
    switch(xbutton->button) {
        case Button1:
            wid->state = 2;
            _has_pointer(wid, xbutton);
            wid->pos_x = xbutton->x;
            wid->pos_y = xbutton->y;
            _toggle_event(wid);
            wid->func.button_press_callback(wid, xbutton, user_data);
        break;
        case Button2:
            debug_print("Button2 \n");
            _has_pointer(wid, xbutton);
            wid->func.button_press_callback(wid, xbutton, user_data);
        break;
        case Button3:
            debug_print("Button3 \n");
            _has_pointer(wid, xbutton);
            wid->func.button_press_callback(wid, xbutton, user_data);
        break;
        case  Button4:
            _scroll_event(wid, 1);
        break;
        case Button5:
            _scroll_event(wid, -1);
        break;
        default:
        break;
    }
}
References _has_pointer(), _scroll_event(), _toggle_event(), Widget_t::app, XEvent::button, Func_t::button_press_callback, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Widget_t::func, Xputty::hold_grab, Xputty::is_grab, Xputty::key_snooper, Widget_t::pos_x, Widget_t::pos_y, Widget_t::state, Widget_t::widget, XEvent::window, XEvent::x, and XEvent::y.
Referenced by os_widget_event_loop(), and WndProc().
_check_enum()
void _check_enum (Widget_t * wid, XButtonEvent * xbutton)
_check_enum - internal check if Adjustment_t is of type CL_ENUM and handle events acordingly
Parameters
*wid - pointer to the Widget_t receiving a event
*xbutton - pointer to the XButtonEvent
Returns
void
Definition at line 68 of file xwidget_private.c.
{
    if (wid->flags & HAS_POINTER && xbutton->button == Button1) {
        Adjustment_t *adj = NULL;
        if (wid->adj_y) {
            adj = wid->adj_y;
        } else if(wid->adj_x) {
            adj = wid->adj_x;
        }
        if (adj && adj->type == CL_ENUM) {
            float value = adj->value;
            value = adj->value + 1.0;
            if (value>adj->max_value) value = adj->min_value;
            check_value_changed(adj, &value);
        }
    }
}
References Widget_t::adj_x, Widget_t::adj_y, XEvent::button, check_value_changed(), CL_ENUM, Widget_t::flags, HAS_POINTER, Adjustment_t::max_value, Adjustment_t::min_value, Adjustment_t::type, and Adjustment_t::value.
Referenced by os_widget_event_loop(), and WndProc().
_check_grab()
void _check_grab (Widget_t * wid, XButtonEvent * xbutton, Xputty * main)
_check_grab - internal check if a Widgt_t holds a grab when a BUTTON_PRESS event occur. If so, check if the button is pressed inside the grab Widget_t. If yes, handle the event. In any case destroy the grab
Parameters
*wid - pointer to the Widget_t receiving a event
*xbutton - pointer to the XButtonEvent
*main - pointer to main struct
Returns
void
Definition at line 127 of file xwidget_private.c.
{
    if(main->hold_grab != NULL && main->hold_grab->flags & IS_POPUP) {
        if (main->is_grab) {
            main->is_grab = false;
            return;
        }
        if (childlist_has_child(main->hold_grab->childlist)) {
            Widget_t *slider = main->hold_grab->childlist->childs[1];
            if (xbutton->window == slider->widget) {
                return;
            }
        }
        Widget_t *view_port = main->hold_grab->childlist->childs[0];
        if(xbutton->button == Button1) {
            //if (xbutton->window == view_port->widget) return;
#ifdef _WIN32 //SetCaptureDisabled//XUngrabPointer
            //ReleaseCapture(); // SetCapture() is currently disabled in pop_menu_show()
#else
            XUngrabPointer(main->dpy,CurrentTime);
#endif
            int i = view_port->childlist->elem-1;
            for(;i>-1;i--) {
                Widget_t *w = view_port->childlist->childs[i];
                if (xbutton->window == w->widget) {
                    const char *l = view_port->childlist->childs[i]->label;
                    main->hold_grab->func.button_release_callback
                        (main->hold_grab, &i, &l);
                    break;
                }
            }
            widget_hide(main->hold_grab);
            main->hold_grab = NULL;
        } /*else if(xbutton->button == Button4) {
            _scroll_event(view_port, 1);
        } else if(xbutton->button == Button5) {
            _scroll_event(view_port, -1);
        }*/ // done in  _button_press() anyway
    } else if(main->hold_grab != NULL) {
        main->hold_grab->func.button_release_callback(main->hold_grab, xbutton, NULL);
    }
}
References XEvent::button, Func_t::button_release_callback, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Xputty::dpy, Childlist_t::elem, Widget_t::flags, Widget_t::func, Xputty::hold_grab, Xputty::is_grab, IS_POPUP, Widget_t::label, Widget_t::widget, widget_hide(), and XEvent::window.
Referenced by os_widget_event_loop(), and WndProc().
_check_keymap()
void _check_keymap (void * w_, XKeyEvent xkey)
_check_keymap - check if key is in map, send requests if so
Parameters
*w - pointer to the Widget_t receiving the event
xkey - the XKeyEvent to check
Returns
void
Definition at line 216 of file xwidget_private.c.
{
    Widget_t *wid = (Widget_t*)w_;
    int n = 1;
    int i = 0;
    for(;i<wid->childlist->elem;i++) {
        Widget_t *w = wid->childlist->childs[i];
        if(w->flags & HAS_FOCUS && w->state != 4) {
             wid=w;
            break;
        }
    }
    if(wid->app->hold_grab != NULL) {
        wid = wid->app->hold_grab->childlist->childs[0];
        n = -1;
    }
    int nk = key_mapping(wid->app->dpy, &xkey);
    if (nk) {
        switch (nk) {
            case 3: _set_adj_value(wid, false, 1*n);
            break;
            case 4: _set_adj_value(wid, true, 1*n);
            break;
            case 5: _set_adj_value(wid, false, -1*n);
            break;
            case 6: _set_adj_value(wid, true, -1*n);
            break;
            case 10:
            {
                int i = 0;
                for(;i<wid->childlist->elem;i++) {
                    Widget_t *w = wid->childlist->childs[i];
                    if(w->flags & HAS_FOCUS && w->state != 4) {
                         wid=w;
                        break;
                    }
                }
                send_button_press_event(wid);
                send_button_release_event(wid);
            }
            break;
            default:
            break;
        }
    }
}
References _set_adj_value(), Widget_t::app, Widget_t::childlist, Childlist_t::childs, Xputty::dpy, Childlist_t::elem, Widget_t::flags, HAS_FOCUS, Xputty::hold_grab, key_mapping(), send_button_press_event(), send_button_release_event(), and Widget_t::state.
Referenced by os_widget_event_loop(), and WndProc().
_check_submenu()
void _check_submenu (Widget_t * wid, XButtonEvent * xbutton, Xputty * main)
_check_submenu - internal check if a Widgt_t is a submenu when a BUTTON_PRESS event occur. If so, check if the button is pressed inside the submenu Widget_t. If yes, handle the event. In any case destroy the submenu
Parameters
*wid - pointer to the Widget_t receiving a event
*xbutton - pointer to the XButtonEvent
*main - pointer to main struct
Returns
void
Definition at line 170 of file xwidget_private.c.
{
    if(main->submenu != NULL) {
        Widget_t *view_port = main->submenu->childlist->childs[0];
        if(xbutton->button == Button1) {
            //if (xbutton->window == view_port->widget) return;
            int i = view_port->childlist->elem-1;
            for(;i>-1;i--) {
                Widget_t *w = view_port->childlist->childs[i];
                if (xbutton->window == w->widget) {
                    const char *l = view_port->childlist->childs[i]->label;
                    main->submenu->func.button_release_callback
                        (main->submenu, &i, &l);
                    break;
                }
            }
            widget_hide(main->submenu);
            main->submenu = NULL;
        } else if(xbutton->button == Button4) {
            _scroll_event(view_port, 1);
        } else if(xbutton->button == Button5) {
            _scroll_event(view_port, -1);
        }
    }
}
References _scroll_event(), XEvent::button, Func_t::button_release_callback, Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::func, Widget_t::label, Xputty::submenu, Widget_t::widget, widget_hide(), and XEvent::window.
Referenced by os_widget_event_loop(), and WndProc().
_dummy1_callback()
void _dummy1_callback (void * w_, void * _data, void * user_data)
_dummy1_callback - default debuging callback for evfunc's
Parameters
*w - pointer to the Widget_t receive the event
user_data - void pointer to attached user_data
Returns
void
Definition at line 309 of file xwidget_private.c.
{
    debug_print("Widget_t _dummy callback\n");
}
Referenced by create_widget(), and create_window().
_dummy_callback()
void _dummy_callback (void * w_, void * user_data)
_dummy1_callback - default debuging callback for xevfunc's
Parameters
*w - pointer to the Widget_t receive the event
user_data - void pointer to attached user_data
Returns
void
Definition at line 313 of file xwidget_private.c.
{
    debug_print("Widget_t _dummy callback\n");
}
Referenced by create_widget(), and create_window().
_has_pointer()
void _has_pointer (Widget_t * w, XButtonEvent * button)
_has_pointer - check if the widget has the pointer
Parameters
*w - pointer to the Widget_t sending the request
*button - pointer to the XButtonEvent sending the notify
Returns
void
Definition at line 272 of file xwidget_private.c.
{
    Metrics_t metrics;
    os_get_window_metrics(w, &metrics);
    if ((button->x<metrics.width && button->y<metrics.height) &&
                                (button->x>0 && button->y>0)){
        w->flags |= HAS_POINTER;
    } else {
        w->flags &= ~HAS_POINTER;
    }
}
References Widget_t::flags, HAS_POINTER, Metrics_t::height, os_get_window_metrics(), Metrics_t::width, XEvent::x, and XEvent::y.
Referenced by _button_press(), os_widget_event_loop(), and WndProc().
_hide_all_tooltips()
void _hide_all_tooltips (Widget_t * wid)
_hide_all_tooltips - hide all active tooltips
Parameters
*wid - pointer to the Widget_t receiving the event
Returns
void
Definition at line 262 of file xwidget_private.c.
{
    int i = 0;
    for(;i<wid->app->childlist->elem;i++) {
        Widget_t *w = wid->app->childlist->childs[i];
        if (w->flags & IS_TOOLTIP) {
            widget_hide(w);
        }
    }
}
References Widget_t::app, Xputty::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_TOOLTIP, and widget_hide().
Referenced by os_widget_event_loop(), and WndProc().
_propagate_child_expose()
void _propagate_child_expose (Widget_t * wid)
_propagate_child_expose - send expose to any child Widget_t
Parameters
*wid - pointer to the Widget_t send the event
Returns
void
Definition at line 196 of file xwidget_private.c.
{
    if (childlist_has_child(wid->childlist)) {
        int i = 0;
        for(;i<wid->childlist->elem;i++) {
            Widget_t *w = wid->childlist->childs[i];
            if ( w->flags & NO_PROPAGATE) continue;
            if (w->flags & USE_TRANSPARENCY) {
                if(w->flags & FAST_REDRAW)
#ifdef __linux__ //ForceRedraw
                    transparent_draw(w, NULL);
#else
                    expose_widget(w);
#endif
                else expose_widget(w);
            }
        }
    }
}
References Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Childlist_t::elem, expose_widget(), FAST_REDRAW, Widget_t::flags, NO_PROPAGATE, transparent_draw(), and USE_TRANSPARENCY.
Referenced by transparent_draw().
_resize_childs()
void _resize_childs (Widget_t * wid)
_resize_childs - intern check if child widgets needs resizing
Parameters
*wid - pointer to the Widget_t receive the event
Returns
void
Definition at line 331 of file xwidget_private.c.
{
    if(!childlist_has_child(wid->childlist)) return;
    int i = 0;
    for(;i<wid->childlist->elem;i++) {
        Widget_t *w = wid->childlist->childs[i];
        switch(w->scale.gravity) {
            case(NORTHWEST):
                os_resize_window (wid->app->dpy, w, max(1,
                    w->scale.init_width - (wid->scale.scale_x)),
                    max(1,w->scale.init_height - (wid->scale.scale_y)));
            break;
            case(NORTHEAST):
                os_resize_window (wid->app->dpy, w, max(1,
                    w->scale.init_width - (wid->scale.scale_x)), w->height);
            break;
            case(SOUTHWEST):
                os_move_window(wid->app->dpy,w,w->scale.init_x-wid->scale.scale_x,
                                        w->scale.init_y-wid->scale.scale_y);
            break;
            case(SOUTHEAST):
                os_move_window(wid->app->dpy,w,w->scale.init_x,
                                            w->scale.init_y-wid->scale.scale_y);
            break;
            case(SOUTHCENTER):
                os_move_window(wid->app->dpy,w,w->scale.init_x,
                                            w->scale.init_y / wid->scale.cscale_y);
                os_resize_window (wid->app->dpy, w, max(1,
                    w->scale.init_width - (wid->scale.scale_x)),
                    max(1,w->scale.init_height / (wid->scale.cscale_y)));
            break;
            case(EASTWEST):
                os_move_window(wid->app->dpy,w,w->scale.init_x,
                                w->scale.init_y-wid->scale.scale_y);
            break;
            case(EASTNORTH):
                os_resize_window (wid->app->dpy, w, w->scale.init_width,
                    max(1,w->scale.init_height - (wid->scale.scale_y)));
            break;
            case(EASTSOUTH):
                os_move_window(wid->app->dpy,w,w->scale.init_x,
                                            w->scale.init_y-wid->scale.scale_y);
                os_resize_window (wid->app->dpy, w, max(1,
                    w->scale.init_width - (wid->scale.scale_x)), w->height);
            break;
            case(WESTNORTH):
                os_move_window(wid->app->dpy,w,w->scale.init_x-wid->scale.scale_x,
                                                                    w->scale.init_y);
            break;
            case(WESTSOUTH):
                os_move_window(wid->app->dpy,w,w->scale.init_x-wid->scale.scale_x,
                                                                    w->scale.init_y);
                os_resize_window (wid->app->dpy, w, w->scale.init_width,
                    max(1,w->scale.init_height - (wid->scale.scale_y)));
            break;
            case(CENTER):
                os_move_window(wid->app->dpy,w,w->scale.init_x /
                    wid->scale.cscale_x,w->scale.init_y / wid->scale.cscale_y);
                os_resize_window (wid->app->dpy, w, max(1,
                    w->scale.init_width / (wid->scale.cscale_x)),
                    max(1,w->scale.init_height / (wid->scale.cscale_y)));
            break;
            case(ASPECT):
                os_move_window(wid->app->dpy,w,(
                    (w->scale.init_x + w->scale.init_width*0.5) /
                    wid->scale.cscale_x) - w->width*0.5,
                    ((w->scale.init_y + w->scale.init_height*0.5) /
                    wid->scale.cscale_y)- w->height*0.5) ;
                os_resize_window (wid->app->dpy, w, max(1,
                    w->scale.init_width / (wid->scale.ascale)),
                    max(1,w->scale.init_height / (wid->scale.ascale)));
            break;
            case(FIXEDSIZE):
                os_move_window(wid->app->dpy,w,(
                    (w->scale.init_x + w->scale.init_width*0.5) /
                    wid->scale.cscale_x) - w->width*0.5,
                    ((w->scale.init_y + w->scale.init_height*0.5) /
                    wid->scale.cscale_y)- w->height*0.5) ;
            break;
            case(MENUITEM):
                os_resize_window (wid->app->dpy, w, max(1,
                    w->scale.init_width - (wid->scale.scale_x)-5), w->scale.init_height);
            break;
            case(NONE):
            break;
            default:
            break;
        }
        w->func.configure_notify_callback(w,NULL);
    }
}
References Widget_t::app, Resize_t::ascale, ASPECT, CENTER, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Func_t::configure_notify_callback, Resize_t::cscale_x, Resize_t::cscale_y, Xputty::dpy, EASTNORTH, EASTSOUTH, EASTWEST, Childlist_t::elem, FIXEDSIZE, Widget_t::func, Resize_t::gravity, Widget_t::height, Resize_t::init_height, Resize_t::init_width, Resize_t::init_x, Resize_t::init_y, MENUITEM, NONE, NORTHEAST, NORTHWEST, os_move_window(), os_resize_window(), Widget_t::scale, Resize_t::scale_x, Resize_t::scale_y, SOUTHCENTER, SOUTHEAST, SOUTHWEST, WESTNORTH, WESTSOUTH, and Widget_t::width.
Referenced by configure_event(), and resize_childs().
_resize_surface()
void _resize_surface (Widget_t * wid, int width, int height)
_resize_surface - intern check if a Widget_t surfaces needs resizing
Parameters
*wid - pointer to the Widget_t receive the event
width - the new width
height - the new height
Returns
void
Definition at line 317 of file xwidget_private.c.
{
    wid->width = width;
    wid->height = height;
    os_set_widget_surface_size(wid, wid->width, wid->height);
    cairo_font_face_t *ff = cairo_get_font_face(wid->crb);
    cairo_destroy(wid->crb);
    cairo_surface_destroy(wid->buffer);
    wid->buffer = cairo_surface_create_similar (wid->surface,
                        CAIRO_CONTENT_COLOR_ALPHA, width, height);
    assert(cairo_surface_status(wid->buffer) == CAIRO_STATUS_SUCCESS);
    wid->crb = cairo_create (wid->buffer);
    cairo_set_font_face(wid->crb, ff);
}
References Widget_t::buffer, Widget_t::crb, Widget_t::height, os_set_widget_surface_size(), Widget_t::surface, and Widget_t::width.
Referenced by configure_event().
_scroll_event()
void _scroll_event (Widget_t * wid, int direction)
_scroll_event - internal check which Adjustment_t change it's value on a motion event (POINTER_MOTION)
Parameters
*wid - pointer to the Widget_t receiving a event
direction - up/down scroll diretion
Returns
void
Definition at line 24 of file xwidget_private.c.
{
    Adjustment_t *adj = NULL;
    if (wid->adj_y) {
        adj = wid->adj_y;
    } else if(wid->adj_x) {
        adj = wid->adj_x;
    }
    if (adj) {
        float value = adj->value;
        switch(adj->type) {
            case (CL_LOGSCALE):
            case (CL_LOGARITHMIC):
            case (CL_CONTINUOS):
                value = min(adj->max_value,max(adj->min_value,
                                adj->value + (adj->step * direction)));
            break;
            case (CL_VIEWPORT):
            case (CL_VIEWPORTSLIDER):
            case (CL_ENUM):
                value = min(adj->max_value,max(adj->min_value,
                                adj->value + (adj->step * -direction)));
            break;
            case (CL_TOGGLE):
               // value = adj->value ? 1.0 : 0.0;
            break;
            default:
            break;
        }
        check_value_changed(adj, &value);
    }
}
References Widget_t::adj_x, Widget_t::adj_y, check_value_changed(), CL_CONTINUOS, CL_ENUM, CL_LOGARITHMIC, CL_LOGSCALE, CL_TOGGLE, CL_VIEWPORT, CL_VIEWPORTSLIDER, Adjustment_t::max_value, Adjustment_t::min_value, Adjustment_t::step, Adjustment_t::type, and Adjustment_t::value.
Referenced by _button_press(), and _check_submenu().
_set_adj_value()
void _set_adj_value (void * w_, bool x, int direction)
_set_adj_value - set value to adjustment from key event
Parameters
*w - pointer to the Widget_t receiving the event
x - use x or y-axis
Returns
void
Definition at line 284 of file xwidget_private.c.
{
    Widget_t *wid = (Widget_t*)w_;
    Adjustment_t *adj = NULL;
    if (x && wid->adj_x) {
        adj = wid->adj_x;
    } else if (!x && wid->adj_y) {
        adj = wid->adj_y;
    }
    if (adj) {
        float value = adj->value;
        switch(adj->type) {
            case (CL_VIEWPORT):
            case (CL_VIEWPORTSLIDER):
                value = min(adj->max_value,max(adj->min_value,
                    adj->value + (adj->step * -direction)));
            break;
            default:
                value = min(adj->max_value,max(adj->min_value,
                    adj->value + (adj->step * direction)));
            break;
        }
        check_value_changed(adj, &value);
    }
}
References Widget_t::adj_x, Widget_t::adj_y, check_value_changed(), CL_VIEWPORT, CL_VIEWPORTSLIDER, Adjustment_t::max_value, Adjustment_t::min_value, Adjustment_t::step, Adjustment_t::type, and Adjustment_t::value.
Referenced by _check_keymap().
_toggle_event()
void _toggle_event (Widget_t * wid)
_toggle_event - internal check which Adjustment_t change it's value on a Button press event (BUTTON_PRESS)
Parameters
*wid - pointer to the Widget_t receiving a event
Returns
void
Definition at line 56 of file xwidget_private.c.
{
    Adjustment_t *adj = NULL;
    if (wid->adj_y) {
        adj = wid->adj_y;
    } else if(wid->adj_x) {
        adj = wid->adj_x;
    }
    if (adj && adj->type != CL_TOGGLE) {
        adj_set_start_value(wid);
    }
}
References adj_set_start_value(), Widget_t::adj_x, Widget_t::adj_y, CL_TOGGLE, and Adjustment_t::type.
Referenced by _button_press().